// GENERATED FILE — do not edit by hand.
//
// Written by `pnpm gen constants` (tools/gen-sdk-constants.ts) from conformance/parity/
// copy.en.json, checked against errors.json and enums.json (licenseStatus, activationResult).
// `pnpm gen constants --check` fails the green gate on any difference. To change a string,
// edit copy.en.json and regenerate.
// The core copy (core.copy): a title and message per error code, gate status (licenseStatus) and activation result (activationResult). A code missing from COPY_CODES shows COPY_FALLBACK with {code} filled in, never the raw body.

@file:Suppress("unused")

package im.plrs.key.core

/** One piece of core copy. */
public data class CopyEntry(public val title: String, public val message: String)

public const val COPY_VERSION: Int = 1
public const val COPY_LOCALE: String = "en"

/** The only placeholders a copy string may hold, each written `{name}`. */
public val COPY_PLACEHOLDERS: List<String> = listOf("code", "detail", "limit", "deviceCount", "retryAfterSeconds", "product")

/** Shown for a code this table does not know, with {code} filled in. */
public val COPY_FALLBACK: CopyEntry = CopyEntry("Something went wrong", "Something went wrong ({code}). Try again.")

/** Per error code (errors.json order). */
public val COPY_CODES: Map<String, CopyEntry> = mapOf(
    "unauthorized" to CopyEntry("Not signed in", "This device isn't signed in, or its license is no longer valid. Sign in or activate again."),
    "not_found" to CopyEntry("Not found", "That wasn't found. It may have been removed."),
    "bad_request" to CopyEntry("Request refused", "The request wasn't valid. Update the app, then try again."),
    "forbidden" to CopyEntry("Not allowed", "You don't have permission to do that."),
    "attestation_required" to CopyEntry("Device check needed", "This needs a verified device. Let the app check this device, then try again."),
    "attestation_rejected" to CopyEntry("Device check failed", "This device couldn't be verified. Try again."),
    "attestation_unavailable" to CopyEntry("Device check unavailable", "Device verification isn't available for this app right now. Try again in a few minutes."),
    "rate_limited" to CopyEntry("Too many attempts", "Too many attempts. Wait a moment and try again."),
    "body_too_large" to CopyEntry("Too large", "That is too large to send."),
    "method_not_allowed" to CopyEntry("Request refused", "The request wasn't valid. Update the app, then try again."),
    "misconfigured" to CopyEntry("Service not set up", "This service isn't set up correctly. Contact the developer."),
    "registration_closed" to CopyEntry("Registration closed", "New devices can't register right now. Activate with a license key or sign in."),
    "value_not_representable" to CopyEntry("Value not accepted", "A value couldn't be saved. Change it and try again."),
    "document_not_representable" to CopyEntry("Service problem", "The service couldn't prepare your settings. Contact the developer."),
    "device_limit" to CopyEntry("Device limit reached", "This license is already on all its devices. Replace a device to use it here."),
    "key_entry_limit" to CopyEntry("No key entries left", "This key has no entries left. Add it to your account and sign in instead."),
    "license_disabled" to CopyEntry("License disabled", "This license has been disabled. Contact the developer."),
    "license_expired" to CopyEntry("License expired", "This license has expired. Renew it to continue."),
    "not_entitled" to CopyEntry("Not included", "Your license doesn't include this."),
    "version_blocked" to CopyEntry("Update required", "This version can't be used with your license. Update the app to continue."),
    "channel_not_allowed" to CopyEntry("Channel not included", "Your license doesn't include this release channel."),
    "hardware_mismatch" to CopyEntry("Device changed", "This device's hardware changed. Activate again to use your license here."),
    "fingerprint_required" to CopyEntry("Device check failed", "This license needs a hardware fingerprint, which couldn't be read on this device."),
    "enroll_disabled" to CopyEntry("No free license", "This app doesn't offer a free license. Enter a license key or sign in."),
    "enroll_claimed" to CopyEntry("Sign in to continue", "This device's free license belongs to an account now. Sign in to use it."),
    "enroll_failed" to CopyEntry("Couldn't get a free license", "A free license couldn't be issued. Try again in a few minutes."),
    "managed_by_admin" to CopyEntry("Set by your organization", "This setting is managed by your organization and can't be changed here."),
    "catalog_unavailable" to CopyEntry("Settings unavailable", "Settings can't be loaded right now. Try again in a few minutes."),
    "license_unusable" to CopyEntry("License no longer valid", "Your license is no longer valid, so settings can't be loaded. Sign in or activate again."),
    "disabled" to CopyEntry("Sign-in unavailable", "Sign-in isn't turned on for this app."),
    "oidc_error" to CopyEntry("Sign-in failed", "Sign-in didn't finish. Try again."),
    "unavailable" to CopyEntry("Sign-in unavailable", "Sign-in isn't available right now. Try again in a few minutes."),
    "identity_disabled" to CopyEntry("Sign-in unavailable", "Sign-in through this app is turned off. Your installs and licenses keep working."),
    "auth_method_disabled" to CopyEntry("Sign-in method unavailable", "That sign-in method is turned off. Choose another one."),
    "email_unavailable" to CopyEntry("Email sign-in unavailable", "Email sign-in isn't available right now. Choose another sign-in method."),
    "turnstile_failed" to CopyEntry("Check didn't pass", "The security check didn't pass. Reload the page and try again."),
    "signin_expired" to CopyEntry("Sign-in expired", "This sign-in has expired. Start again."),
    "invalid_code" to CopyEntry("Wrong code", "That code isn't right. Check the email and try again."),
    "email_in_use" to CopyEntry("Email already in use", "Another Polaris Key account already uses this email. Join this sign-in to that account, or use a different email."),
    "terms_required" to CopyEntry("Terms not accepted", "Agree to the terms to continue."),
    "license_owned" to CopyEntry("License in another account", "This {product} license is already in another Polaris Key account. A license never moves by its key."),
    "license_email_bound" to CopyEntry("Email not verified", "This license belongs to an email address your Polaris Key account hasn't verified. Verify that email in your account, then try again."),
    "account_required" to CopyEntry("Sign-in needed", "Sign in to your Polaris Key account on this device, then try again."),
    "email_mismatch" to CopyEntry("Email not verified", "This license belongs to an email address your account hasn't verified. Add and verify that email, then try again."),
    "link_conflict" to CopyEntry("Already linked", "That sign-in method belongs to another Polaris Key account. Sign in to that account, or join the two accounts."),
    "last_link" to CopyEntry("Can't remove", "This is your account's only sign-in method. Add another one before removing it."),
    "step_up_required" to CopyEntry("Confirm it's you", "For your security, sign in again to continue."),
    "not_eligible" to CopyEntry("Offer unavailable", "This offer isn't available to your account anymore. Refresh and try again."),
    "not_removable" to CopyEntry("Can't remove", "This license can't be added back with a key, so it stays in your library."),
    "download_auth_required" to CopyEntry("Sign in to download", "Sign in or activate a license to download this."),
    "delivery_gate_missing" to CopyEntry("Download unavailable", "This download isn't set up yet. Contact the developer."),
    "upstream_rate_limited" to CopyEntry("Download busy", "Downloads are busy right now. Try again in a few minutes."),
    "server_misconfigured" to CopyEntry("Service not set up", "This service isn't set up correctly. Contact the developer."),
    "internal_error" to CopyEntry("Download failed", "The download server had a problem. Try again in a few minutes."),
    "release_record_rejected" to CopyEntry("Release refused", "The release wasn't published because a check failed. The publish log names the check."),
    "release_tag_is_pack_release" to CopyEntry("Release skipped", "A release was skipped because its tag matches a content pack release. Rename the tag."),
    "asset_unreachable" to CopyEntry("Image not updated", "An image could not be fetched from its source. The previous copy is still shown, and it will be retried automatically."),
    "feed_not_composable" to CopyEntry("Update check unavailable", "Updates can't be checked right now. Try again in a few minutes."),
    "service-unavailable" to CopyEntry("Not available", "This app doesn't use this service."),
    "service-disabled" to CopyEntry("Not available", "This service is turned off for this app."),
    "local-only" to CopyEntry("Offline mode", "This app is running offline, so it didn't connect."),
    "insecure-base-url" to CopyEntry("Insecure connection", "The app refused an insecure connection. Contact the developer."),
    "bundle-jws-rejected" to CopyEntry("Activation file not valid", "The activation file's signature isn't valid."),
    "bundle-claims-rejected" to CopyEntry("Activation file not valid", "The activation file is for another product or device, or it has expired."),
    "bundle-trust-rejected" to CopyEntry("Activation file not trusted", "The activation file is signed by a key this app doesn't trust."),
    "inner-doc-rejected" to CopyEntry("Activation file not valid", "The license inside the activation file isn't valid."),
    "bundle" to CopyEntry("Activation file not valid", "The activation file couldn't be read."),
    "transport" to CopyEntry("Connection problem", "Check your connection and try again."),
    "network" to CopyEntry("Can't connect", "Can't reach Polaris Key. Check your connection and try again."),
    "refresh-failed" to CopyEntry("Couldn't refresh", "Your license and settings couldn't be refreshed. Check your connection and try again."),
    "sync-failed" to CopyEntry("Couldn't check your license", "Your license couldn't be checked, so the app can't start. Check your connection and try again."),
    "fetch-failed" to CopyEntry("Content missing", "Required content couldn't be downloaded, so the app can't start. Check your connection and try again."),
    "bridge-missing" to CopyEntry("App problem", "The app's licensing bridge is missing. Reinstall the app or contact the developer."),
    "unknown" to CopyEntry("Something went wrong", "Something went wrong. Try again."),
    "release-refused" to CopyEntry("Not included", "Your license doesn't include this release."),
    "bundle-rejected" to CopyEntry("Activation file not valid", "The activation file was refused."),
    "bundle-import-unsupported" to CopyEntry("Not available here", "Offline activation isn't available here."),
    "report-unsupported" to CopyEntry("Not available here", "Device reports aren't available here."),
    "device-management-unsupported" to CopyEntry("Not available here", "Devices can't be managed from here. Manage them in your account."),
    "device_list_failed" to CopyEntry("Couldn't load devices", "Your devices couldn't be loaded. Check your connection and try again."),
    "device_rename_failed" to CopyEntry("Couldn't rename", "The device couldn't be renamed. Try again."),
    "device_deauthorize_failed" to CopyEntry("Couldn't remove device", "The device couldn't be removed. Try again."),
    "key-entry-unsupported" to CopyEntry("Not available here", "License keys can't be entered here. Sign in instead."),
    "sign-in-failed" to CopyEntry("Sign-in failed", "Sign-in didn't finish. Try again."),
    "sign-out-failed" to CopyEntry("Sign-out failed", "Sign-out didn't finish. Try again."),
    "bad_response" to CopyEntry("Unexpected answer", "The service sent an answer the app couldn't use. Try again."),
    "network-error" to CopyEntry("Can't connect", "Can't reach Polaris Key. Check your connection and try again."),
    "server-error" to CopyEntry("Service problem", "The service had a problem. Try again in a few minutes."),
    "cancelled" to CopyEntry("Sign-in cancelled", "Sign-in was cancelled."),
    "sign-in-expired" to CopyEntry("Code expired", "The code expired before sign-in finished. Start again."),
    "sign-in-denied" to CopyEntry("Sign-in declined", "Sign-in was declined. Start again."),
    "sign-in-unavailable" to CopyEntry("Sign-in unavailable", "Sign-in isn't available right now. Try again in a few minutes."),
    "invalid-options" to CopyEntry("App not set up", "The app's licensing isn't set up correctly. Contact the developer."),
    "not-configured" to CopyEntry("App not set up", "The app's licensing isn't set up yet. Contact the developer."),
    "unsupported" to CopyEntry("Not available here", "This isn't available here."),
    "timeout" to CopyEntry("Timed out", "The service took too long to answer. Check your connection and try again."),
    "response-too-large" to CopyEntry("Unexpected answer", "The service sent an answer the app couldn't use. Try again."),
    "too-many-redirects" to CopyEntry("Connection problem", "The connection was redirected too many times. Try again."),
    "insecure-redirect" to CopyEntry("Insecure connection", "The app refused an insecure redirect."),
    "http-error" to CopyEntry("Service problem", "The service answered with an error. Try again."),
    "invalid-response" to CopyEntry("Unexpected answer", "The service sent an answer the app couldn't use. Try again."),
    "store-failed" to CopyEntry("Storage problem", "The app couldn't read or save its license on this device. Check that the app can write its data folder."),
    "platform-error" to CopyEntry("Platform problem", "The platform reported an error. Try again."),
    "no-token" to CopyEntry("Not activated", "This device isn't activated yet. Activate it or sign in."),
    "mint-unavailable" to CopyEntry("Not available", "This isn't available for this app."),
    "feed-rejected" to CopyEntry("Update check failed", "The update information couldn't be verified, so nothing was installed."),
    "feed-rollback" to CopyEntry("Update check failed", "The update information was older than what this device already has, so it was refused."),
    "record-rejected" to CopyEntry("Update not verified", "The update couldn't be verified, so it wasn't installed."),
    "record-mismatch" to CopyEntry("Update not verified", "The update didn't match what was published, so it wasn't installed."),
    "payload-mismatch" to CopyEntry("Download corrupted", "The update didn't download correctly, so it wasn't installed. Try again."),
    "swap-refused" to CopyEntry("Can't update here", "This installation can't update itself. Update it the way you installed it."),
    "swap-failed" to CopyEntry("Update not finished", "The update couldn't be applied. It will be tried again next launch."),
    "files-index-invalid" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "files-unsafe-path" to CopyEntry("Content refused", "Some content was refused because it contains an unsafe file path."),
    "files-duplicate-path" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "files-case-collision" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "files-path-conflict" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "files-layout-mismatch" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "content-stamp-invalid" to CopyEntry("App build problem", "This build's content information isn't valid. Reinstall the app or contact the developer."),
    "full-corrupt" to CopyEntry("Download corrupted", "Some content couldn't be installed. It will be downloaded again next time."),
    "delta-artifact-mismatch" to CopyEntry("Download corrupted", "Some content couldn't be installed. It will be downloaded again next time."),
    "delta-base-mismatch" to CopyEntry("Content changed", "Installed content changed on this device, so a full download is needed."),
    "delta-apply-failed" to CopyEntry("Update not applied", "Some content couldn't be installed. It will be downloaded again next time."),
    "file-corrupt" to CopyEntry("Download corrupted", "Some content couldn't be installed. It will be downloaded again next time."),
    "file-source-missing" to CopyEntry("Content missing", "Some content couldn't be installed. It will be downloaded again next time."),
    "payload-hash-mismatch" to CopyEntry("Download corrupted", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-ref-mismatch" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-bad-length" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-bad-magic" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-unsupported-version" to CopyEntry("Content not supported", "This content needs a newer version of the app. Update the app."),
    "chunks-bad-record-size" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-bad-flags" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-reserved-nonzero" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-zero-length" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-bad-clen" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-bad-bundle-ref" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-bad-bundle-range" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-size-mismatch" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-payload-mismatch" to CopyEntry("Content not valid", "Some content couldn't be installed. It will be downloaded again next time."),
    "chunk-bundle-truncated" to CopyEntry("Download interrupted", "A download was cut short. Check your connection and try again."),
    "chunk-corrupt" to CopyEntry("Download corrupted", "Some content couldn't be installed. It will be downloaded again next time."),
    "plan-transport-unsupported" to CopyEntry("Can't download here", "This content can't be downloaded on this platform."),
    "plan-insufficient-disk" to CopyEntry("Not enough space", "There isn't enough free space for this content. Free up some space and try again."),
    "plan-no-strategy" to CopyEntry("Can't install content", "This content can't be installed on this device."),
    "pack-no-variant" to CopyEntry("Content not available", "This content isn't available for this device."),
    "pack-type-unsupported" to CopyEntry("Content not supported", "This content needs a newer version of the app. Update the app."),
    "pack-type-check-failed" to CopyEntry("Content not valid", "Some content failed its check and wasn't installed."),
    "pack-not-pinned" to CopyEntry("Content not available", "This content isn't part of this version of the app."),
    "pack-not-entitled" to CopyEntry("Not included", "Your license doesn't include this content."),
    "pack-state-unreadable" to CopyEntry("Storage problem", "Installed content couldn't be read, so nothing new was installed. Restart the app."),
    "pck-directory-refused" to CopyEntry("Content refused", "Some content was refused because it contains files a content pack may not hold."),
    "pck-engine-mismatch" to CopyEntry("Content not supported", "This content needs a different version of the game. Update the game."),
    "pack-rolled-back" to CopyEntry("Content restored", "The last content update didn't start, so the previous version was restored."),
    "pack-revoked" to CopyEntry("Content withdrawn", "This content was withdrawn by its developer and can't be used."),
    "pack-not-data-only" to CopyEntry("Content refused", "Some content was refused because it contains files a data pack may not hold."),
    "marker-rejected" to CopyEntry("App build problem", "This build's built-in content isn't valid. Reinstall the app or contact the developer."),
    "license_required" to CopyEntry("License needed", "Activate the app, then try again."),
    "license_invalid" to CopyEntry("License not accepted", "Your license couldn't be verified. Reconnect the app, then try again."),
    "license_stale" to CopyEntry("License needs refreshing", "Connect to the internet so the app can refresh your license, then try again."),
    "sign_in_required" to CopyEntry("Sign-in needed", "Sign in to your Polaris Key account in the app, then try again."),
)

/** Per licenseStatus. */
public val COPY_GATE: Map<String, CopyEntry> = mapOf(
    "ok" to CopyEntry("License active", "Your license is active."),
    "grace" to CopyEntry("Offline grace", "The licensing service can't be reached. You can keep using the app until the grace period ends."),
    "expired" to CopyEntry("License expired", "Your license has expired. Connect to the internet or renew it to continue."),
    "revoked" to CopyEntry("Signed out", "This device was signed out. Sign in or activate again to continue."),
    "needs-activation" to CopyEntry("Activate", "Enter a license key or sign in to continue."),
    "version-too-old" to CopyEntry("Update required", "This version is no longer supported. Update the app to continue."),
    "version-too-new" to CopyEntry("Not available on this license", "This build is newer than your license allows."),
    "channel-not-entitled" to CopyEntry("Channel not included", "Your license doesn't include this release channel."),
    "not-applicable" to CopyEntry("No license needed", "This app doesn't need a license."),
)

/** Per activationResult. */
public val COPY_ACTIVATION: Map<String, CopyEntry> = mapOf(
    "ok" to CopyEntry("Activated", "Your license is active on this device."),
    "device-limit" to CopyEntry("Device limit reached", "This license is already on all its devices. Replace a device to use it here."),
    "fingerprint-required" to CopyEntry("Device check failed", "This license needs a hardware fingerprint, which couldn't be read on this device."),
    "hardware-mismatch" to CopyEntry("Device changed", "This device's hardware changed. Activate again to use your license here."),
    "enroll-claimed" to CopyEntry("Sign in to continue", "This device's free license belongs to an account now. Sign in to use it."),
    "license-disabled" to CopyEntry("License disabled", "This license has been disabled. Contact the developer."),
    "license-expired" to CopyEntry("License expired", "This license has expired. Renew it to continue."),
    "attestation-required" to CopyEntry("Device check needed", "This license needs a verified device. Let the app check this device, then try again."),
    "rate-limited" to CopyEntry("Too many attempts", "Too many attempts. Wait a moment and try again."),
    "unauthorized" to CopyEntry("Key not accepted", "That license key wasn't accepted. Check it and try again."),
    "enroll-disabled" to CopyEntry("No free license", "This app doesn't offer a free license. Enter a license key or sign in."),
    "key-entry-limit" to CopyEntry("No key entries left", "This key has no entries left. Add it to your account and sign in instead."),
    "refused" to CopyEntry("Activation refused", "Activation was refused ({code})."),
    "error" to CopyEntry("Activation failed", "Activation didn't finish. Check your connection and try again."),
)
