/**
 * Writes the CLI's copy of the CI plane (A-18h; notes/S-15 §6.1: one declaration, read by the
 * Worker and the CLI): `packages/cli/src/storefronts/ciPlane.generated.ts`, a straight serialise
 * of `src/core/storefront/ciPlane.ts` (every store's command allow-list, never-list and outlet
 * kinds) and of the CI-plane storefront adapters' operations (`stores/itch.ts`, `stores/snap.ts`).
 *
 *   pnpm gen:storefront-ci              # rewrite the file
 *   pnpm gen:storefront-ci -- --check   # exit 1 if it is stale
 *
 * The file is committed (the CLI and the Action bundle build without running this), and
 * `test/storefront/ciPlaneGenerated.test.ts` fails the worker suite when it is stale, so a change
 * to an allow-list that forgets to regenerate fails CI instead of shipping a CLI that runs a
 * different list from the one the Worker re-checks.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as prettier from "prettier";
import { CI_PLANE } from "../src/core/storefront/ciPlane.js";
import {
  STOREFRONT_ADAPTERS,
  STOREFRONT_OPS,
} from "../src/core/storefront/adapter.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
export const GENERATED_PATH =
  "packages/cli/src/storefronts/ciPlane.generated.ts";

/** The declaration the CLI reads (`packages/cli/src/storefronts/types.ts`). */
export function ciPlaneDeclaration() {
  return {
    stores: CI_PLANE.map((s) => ({
      store: s.store,
      label: s.label,
      outletKinds: s.outletKinds,
      list: s.list,
      never: s.never,
      neverTokens: s.neverTokens,
    })),
    adapters: STOREFRONT_ADAPTERS.filter((a) => a.ci !== null).map((a) => ({
      id: a.id,
      label: a.label,
      outletKinds: a.outletKinds,
      ciOps: Object.fromEntries(
        STOREFRONT_OPS.flatMap((op) => {
          const s = a.capabilities.ops[op];
          return s.mode === "ci" ? [[op, s.commands]] : [];
        }),
      ),
    })),
  };
}

export async function renderCiPlane(): Promise<string> {
  const source = [
    "// GENERATED by packages/worker/scripts/gen-storefront-ci.ts from",
    "// packages/worker/src/core/storefront/ciPlane.ts and the CI-plane storefront adapters. DO NOT EDIT.",
    "// Regenerate: pnpm gen:storefront-ci",
    "// Freshness: pnpm gen:storefront-ci -- --check (and the worker suite's ciPlaneGenerated test)",
    "",
    'import type { CiPlaneDeclaration } from "./types.js";',
    "",
    `export const CI_PLANE: CiPlaneDeclaration = ${JSON.stringify(ciPlaneDeclaration(), null, 2)};`,
    "",
  ].join("\n");
  const target = join(ROOT, GENERATED_PATH);
  const options = (await prettier.resolveConfig(target)) ?? {};
  return prettier.format(source, { ...options, parser: "typescript" });
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const target = join(ROOT, GENERATED_PATH);
  const content = await renderCiPlane();
  let current: string | undefined;
  try {
    current = readFileSync(target, "utf8");
  } catch {
    current = undefined;
  }
  if (current === content) {
    console.log(`up to date: ${GENERATED_PATH}`);
    return;
  }
  if (check) {
    console.error(`stale: ${GENERATED_PATH} — run \`pnpm gen:storefront-ci\``);
    process.exit(1);
  }
  writeFileSync(target, content);
  console.log(`wrote ${GENERATED_PATH}`);
}

const invokedDirectly =
  process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url) === process.argv[1];
if (invokedDirectly) await main();
