# GENERATED by `pkey sdk --lang godot --write` from
# https://key.plrs.im/acme/.well-known/polaris.json. Do not edit: run the command again to refresh.
# The trust pins came from discovery; compare each fingerprint with the console before
# you ship (pkey sdk prints them). Release keys match release.releaseKeyFingerprints.
extends RefCounted
## Polaris Key configuration for acme. Keep it outside addons/:
##
##     const PolarisConfig := preload("res://polaris_key_config.gd")
##     PolarisKey.configure(PolarisConfig.options())

const PRODUCT := "acme"
const BASE_URL := "https://key.plrs.im"
const PINNED_TRUST_KEYS := {
	"pkey-test-prod-2026": "kDJF6Deuexo91hFZ9TAPr2SmjUEuTXdia67UogTEpkI",
}
const PINNED_RELEASE_KEYS := {
	"acme-release-2026": "Z6FCkd1K7Om4lxUk4og_J0m73saH4BrrLk8igXzwcJM",
}
const EXPECTED_SERVICES := ["license", "config", "release", "update"]


## Writes the product facts into [param opts] and returns it; every other field is left alone.
static func apply(opts: PKeyOptions) -> PKeyOptions:
	opts.product = PRODUCT
	opts.base_url = BASE_URL
	opts.pinned_trust_keys = PINNED_TRUST_KEYS.duplicate()
	opts.pinned_release_keys = PINNED_RELEASE_KEYS.duplicate()
	opts.expected_services = PackedStringArray(EXPECTED_SERVICES)
	return opts


## A new [PKeyOptions] carrying the product facts.
static func options() -> PKeyOptions:
	return apply(PKeyOptions.new())
