class_name PKeyUiTheme
extends RefCounted
## The UI kit's Theme, built from the Polaris Key design system (`PKeyBrand`, generated by
## `pnpm gen:brand`): the dark and light semantic palettes, the platform violet as the accent,
## Rubik (Regular for body, Bold for titles and codes) and a 2 px violet focus ring with a 2 px
## gap on every interactive control, so a gamepad or TV player always sees where focus is.
##
## The committed themes are `pkey_theme.tres` (dark, the default, which every scene file uses)
## and `pkey_theme_light.tres`, both written from `build()` by tools/gen_theme.gd; the `brand`
## suite fails when either drifts from `build()`.
##
## Integrators restyle the kit in one of four ways, from lightest to heaviest:
##
##   PKeyUiTheme.scheme = "light"                    # the kit's light theme for every scene
##   PKeyUiTheme.override = PKeyUiTheme.build(true, Color("#39d075"))   # your accent
##   PKeyUiTheme.override = preload("res://my_theme.tres")              # your whole Theme
##   $PKeySettingsPanel.theme = my_theme             # one scene (or style its type variations)
##
## Set `scheme` or `override` before a scene enters the tree: a scene whose theme is the kit's
## stock theme takes `current()` in `_ready`. A scene given any other theme keeps it, and
## PKeyBoot's `theme` option (a Theme a mounted pack provides) still applies after MOUNT.
##
## Fonts: Rubik ships with the addon under the SIL Open Font License 1.1 (ui/theme/fonts/OFL.txt;
## keep that file with your game's credits or licences). To use your own face, pass it to
## `build()` (`PKeyUiTheme.build(true, Color(), my_font, my_bold_font)`) or set `default_font` on
## your own Theme. Passing `null` fonts to `build_with()` gives the engine's default font.

const DARK_PATH := "res://addons/polaris_key/ui/theme/pkey_theme.tres"
const LIGHT_PATH := "res://addons/polaris_key/ui/theme/pkey_theme_light.tres"
const REGULAR_PATH := "res://addons/polaris_key/ui/theme/fonts/rubik_regular.tres"
const BOLD_PATH := "res://addons/polaris_key/ui/theme/fonts/rubik_bold.tres"

## Corner radii (BRAND.md §4.6): controls `md`, cards `lg`, chips `full`.
const RADIUS_CONTROL := 6
const RADIUS_CARD := 10
const RADIUS_FULL := 999
## The focus ring (BRAND.md §7.4): 2 px of `focus`, drawn 2 px outside the control.
const RING_WIDTH := 2
const RING_OFFSET := 2

## The type variations every scene uses; a replacement Theme should style them.
const VARIATIONS := {
	"PKeyCard": "PanelContainer",
	"PKeyBanner": "PanelContainer",
	"PKeyTitle": "Label",
	"PKeyMuted": "Label",
	"PKeyCode": "Label",
	"PKeyError": "Label",
	"PKeyBadge": "Label",
	"PKeyPrimary": "Button",
}

## "dark" (the default) or "light": which committed kit theme `current()` answers.
static var scheme := "dark"
## A Theme that replaces the kit's in every scene still on the stock theme; null for none.
static var override: Theme = null


## The theme a kit scene should use now: `override`, else the committed theme for `scheme`.
static func current() -> Theme:
	if override != null:
		return override
	return load(LIGHT_PATH if scheme == "light" else DARK_PATH) as Theme


## True when `t` is one of the kit's committed themes (a scene still on the stock look).
static func is_stock(t: Theme) -> bool:
	return t != null and (t.resource_path == DARK_PATH or t.resource_path == LIGHT_PATH)


## The kit theme with the bundled Rubik. `accent` (alpha 0: the platform violet) colours the
## primary button, the chips and the hover border; give it a colour with at least 3:1 against
## the theme's surfaces. `regular` / `bold` replace Rubik.
static func build(dark := true, accent := Color(0, 0, 0, 0), regular: Font = null, bold: Font = null) -> Theme:
	return build_with(dark, accent, regular if regular != null else load(REGULAR_PATH) as Font, bold if bold != null else load(BOLD_PATH) as Font)


## `build()` with exactly these fonts: null keeps the engine's default font for that role.
static func build_with(dark: bool, accent: Color, regular: Font, bold: Font) -> Theme:
	var p := palette(dark)
	if accent.a > 0.0:
		p["accent"] = accent
		p["accent_hover"] = accent.lightened(0.15) if dark else accent.darkened(0.15)
		p["accent_pressed"] = accent.darkened(0.2) if dark else accent.darkened(0.3)
		p["on_accent"] = _on(accent)
	var t := Theme.new()
	t.default_font_size = 18
	if regular != null:
		t.default_font = regular

	# Surfaces: the page ground, raised cards and banners.
	t.set_stylebox("panel", "PanelContainer", _box(p.page, p.page, 0, RADIUS_CARD, 24))
	for v in VARIATIONS:
		t.set_type_variation(v, VARIATIONS[v])
	t.set_stylebox("panel", "PKeyCard", _box(p.raised, p.border, 1, RADIUS_CARD, 24))
	t.set_stylebox("panel", "PKeyBanner", _box(p.raised, p.border, 1, RADIUS_CARD, 10))

	# Text.
	t.set_color("font_color", "Label", p.text)
	t.set_font_size("font_size", "PKeyTitle", 28)
	t.set_color("font_color", "PKeyTitle", p.strong)
	t.set_color("font_color", "PKeyMuted", p.muted)
	t.set_font_size("font_size", "PKeyMuted", 16)
	t.set_font_size("font_size", "PKeyCode", 40)
	t.set_color("font_color", "PKeyCode", p.strong)
	t.set_color("font_color", "PKeyError", p.danger)
	if bold != null:
		t.set_font("font", "PKeyTitle", bold)
		t.set_font("font", "PKeyCode", bold)
	# The entitlement chip: the accent's text on its tint, never gold (BRAND.md §1.2).
	t.set_color("font_color", "PKeyBadge", p.accent_fg)
	t.set_font_size("font_size", "PKeyBadge", 14)
	t.set_stylebox("normal", "PKeyBadge", _box(p.accent_subtle, p.accent, 1, RADIUS_FULL, 4))

	# Controls.
	var focus := _ring(p.focus)
	for type in ["Button", "CheckButton", "CheckBox", "OptionButton", "LineEdit", "TextEdit"]:
		t.set_stylebox("focus", type, focus)
	for type in ["Button", "OptionButton"]:
		t.set_stylebox("normal", type, _box(p.overlay, p.border_strong, 1, RADIUS_CONTROL, 10))
		t.set_stylebox("hover", type, _box(p.overlay, p.accent, 1, RADIUS_CONTROL, 10))
		t.set_stylebox("pressed", type, _box(p.sunken, p.accent, 1, RADIUS_CONTROL, 10))
		t.set_stylebox("disabled", type, _box(p.raised, p.border, 1, RADIUS_CONTROL, 10))
		t.set_color("font_color", type, p.text)
		t.set_color("font_hover_color", type, p.strong)
		t.set_color("font_focus_color", type, p.strong)
		t.set_color("font_pressed_color", type, p.strong)
		t.set_color("font_disabled_color", type, p.subtle)
	t.set_stylebox("normal", "PKeyPrimary", _box(p.accent, p.accent, 1, RADIUS_CONTROL, 10))
	t.set_stylebox("hover", "PKeyPrimary", _box(p.accent_hover, p.accent_hover, 1, RADIUS_CONTROL, 10))
	t.set_stylebox("pressed", "PKeyPrimary", _box(p.accent_pressed, p.accent_pressed, 1, RADIUS_CONTROL, 10))
	for c in ["font_color", "font_hover_color", "font_focus_color", "font_pressed_color"]:
		t.set_color(c, "PKeyPrimary", p.on_accent)
	for type in ["LineEdit", "TextEdit"]:
		t.set_stylebox("normal", type, _box(p.sunken, p.border_strong, 1, RADIUS_CONTROL, 10))
		t.set_stylebox("read_only", type, _box(p.raised, p.border, 1, RADIUS_CONTROL, 10))
		t.set_color("font_color", type, p.text)
		t.set_color("font_placeholder_color", type, p.subtle)
		t.set_color("caret_color", type, p.focus)
		t.set_color("selection_color", type, p.accent_subtle)
	for type in ["CheckButton", "CheckBox"]:
		t.set_color("font_color", type, p.text)
		t.set_color("font_hover_color", type, p.strong)
		t.set_color("font_focus_color", type, p.strong)
		t.set_color("font_pressed_color", type, p.text)
		t.set_color("font_disabled_color", type, p.subtle)
	# OptionButton's list.
	t.set_stylebox("panel", "PopupMenu", _box(p.overlay, p.border_strong, 1, RADIUS_CONTROL, 6))
	t.set_stylebox("hover", "PopupMenu", _box(p.accent_subtle, p.accent_subtle, 0, RADIUS_CONTROL, 4))
	t.set_color("font_color", "PopupMenu", p.text)
	t.set_color("font_hover_color", "PopupMenu", p.strong)
	t.set_color("font_disabled_color", "PopupMenu", p.subtle)
	# Progress: neutral, never the mark (BRAND.md §7.5).
	t.set_stylebox("background", "ProgressBar", _box(p.sunken, p.border, 1, RADIUS_FULL, 0))
	t.set_stylebox("fill", "ProgressBar", _box(p.subtle, p.subtle, 0, RADIUS_FULL, 0))
	t.set_color("font_color", "ProgressBar", p.text)
	# A QR code stays black on white whatever the theme: scanners need the contrast.
	t.set_color("dark", "PKeyQrRect", Color.BLACK)
	t.set_color("light", "PKeyQrRect", Color.WHITE)
	return t


## The semantic colours the kit uses, for one theme, from PKeyBrand.
static func palette(dark: bool) -> Dictionary:
	if dark:
		return {
			"page": PKeyBrand.Dark.SURFACE_PAGE, "raised": PKeyBrand.Dark.SURFACE_RAISED,
			"overlay": PKeyBrand.Dark.SURFACE_OVERLAY, "sunken": PKeyBrand.Dark.SURFACE_SUNKEN,
			"strong": PKeyBrand.Dark.TEXT_STRONG, "text": PKeyBrand.Dark.TEXT_DEFAULT,
			"muted": PKeyBrand.Dark.TEXT_MUTED, "subtle": PKeyBrand.Dark.TEXT_SUBTLE,
			"border": PKeyBrand.Dark.BORDER_SUBTLE, "border_strong": PKeyBrand.Dark.BORDER_STRONG,
			"focus": PKeyBrand.Dark.FOCUS, "danger": PKeyBrand.Dark.DANGER,
			"accent": PKeyBrand.Dark.SERVICE_CORE, "accent_fg": PKeyBrand.Dark.SERVICE_CORE_FG,
			"accent_subtle": PKeyBrand.Dark.SERVICE_CORE_SUBTLE, "on_accent": PKeyBrand.Dark.SERVICE_CORE_ON,
			"accent_hover": PKeyBrand.Dark.SERVICE_CORE.lightened(0.15),
			"accent_pressed": PKeyBrand.Dark.SERVICE_CORE.darkened(0.2),
		}
	return {
		"page": PKeyBrand.Light.SURFACE_PAGE, "raised": PKeyBrand.Light.SURFACE_RAISED,
		"overlay": PKeyBrand.Light.SURFACE_OVERLAY, "sunken": PKeyBrand.Light.SURFACE_SUNKEN,
		"strong": PKeyBrand.Light.TEXT_STRONG, "text": PKeyBrand.Light.TEXT_DEFAULT,
		"muted": PKeyBrand.Light.TEXT_MUTED, "subtle": PKeyBrand.Light.TEXT_SUBTLE,
		"border": PKeyBrand.Light.BORDER_SUBTLE, "border_strong": PKeyBrand.Light.BORDER_STRONG,
		"focus": PKeyBrand.Light.FOCUS, "danger": PKeyBrand.Light.DANGER,
		"accent": PKeyBrand.Light.SERVICE_CORE, "accent_fg": PKeyBrand.Light.SERVICE_CORE_FG,
		"accent_subtle": PKeyBrand.Light.SERVICE_CORE_SUBTLE, "on_accent": PKeyBrand.Light.SERVICE_CORE_ON,
		"accent_hover": PKeyBrand.Light.SERVICE_CORE.darkened(0.15),
		"accent_pressed": PKeyBrand.Light.SERVICE_CORE.darkened(0.3),
	}


## The size a "Powered by Polaris Key" badge is shown at: `requested`, raised to the kit minimum
## for its layout ("compact" for app UI, "horizontal" for credits, "stacked" for square spots),
## keeping the badge's proportions. Never crop the badge or show it smaller (BRAND.md §1.5).
static func powered_by_size(layout: String, requested := Vector2.ZERO) -> Vector2:
	var minimum: Vector2 = {
		"horizontal": Vector2(PKeyBrand.BADGE_MIN_HORIZONTAL),
		"stacked": Vector2(PKeyBrand.BADGE_MIN_STACKED),
	}.get(layout, Vector2(PKeyBrand.BADGE_MIN_COMPACT))
	var k := maxf(1.0, maxf(requested.x / minimum.x, requested.y / minimum.y))
	return minimum * k


## The text colour for an integrator's accent fill: the page ink or white, whichever contrasts more.
static func _on(fill: Color) -> Color:
	var a: Color = PKeyBrand.Dark.TEXT_ON_ACCENT
	var b: Color = PKeyBrand.Light.TEXT_ON_ACCENT
	return a if _contrast(fill, a) >= _contrast(fill, b) else b


static func _contrast(x: Color, y: Color) -> float:
	var lx := x.srgb_to_linear().get_luminance()
	var ly := y.srgb_to_linear().get_luminance()
	return (maxf(lx, ly) + 0.05) / (minf(lx, ly) + 0.05)


static func _box(bg: Color, border: Color, width: int, radius: int, pad: int) -> StyleBoxFlat:
	var s := StyleBoxFlat.new()
	s.bg_color = bg
	s.border_color = border
	s.set_border_width_all(width)
	s.set_corner_radius_all(radius)
	s.set_content_margin_all(pad)
	return s


## The focus ring: no fill, `RING_WIDTH` px of `color`, `RING_OFFSET` px outside the control so
## the gap shows the surface behind it and the ring never hides the control's own border.
static func _ring(color: Color) -> StyleBoxFlat:
	var s := StyleBoxFlat.new()
	s.draw_center = false
	s.border_color = color
	s.set_border_width_all(RING_WIDTH)
	s.set_corner_radius_all(RADIUS_CONTROL + RING_OFFSET + RING_WIDTH)
	s.set_expand_margin_all(RING_OFFSET + RING_WIDTH)
	return s
