class_name PKeyUiTheme
extends RefCounted
## The UI kit's look. Two families:
##
## - **Polaris Key (the default).** The design system (`PKeyBrand`, generated by `pnpm gen:brand`):
##   the kit's dark or light palette, Rubik (bundled under the SIL OFL 1.1), your product's accent
##   (derived from its icon, else ink; never the platform violet by default) and a 3 px focus ring
##   with a gap. The product leads every screen; the kit's own mark appears on none.
## - **Neutral (`ui_branding = "none"`).** No Polaris Key branding. The scenes take the game's own
##   theme and font, as the scene's place in the tree resolves them (a Theme on an ancestor, else
##   the project's `gui/theme/custom` and `gui/theme/custom_font`, else the engine's), and add only
##   what the kit needs on top: a type hierarchy (title, muted, code and chip sizes derived from
##   the project's font size), padded cards, a bold title face derived from the project's font, an
##   ink primary action and a focus ring that reads on the game's ground.
##
## Choose with PKeyOptions (`configure()` applies them) or directly, before a scene enters the
## tree:
##
##   options.ui_branding = "none"               # the game's own look; "polaris-key" is the default
##   options.ui_brand_scheme = "light"          # the brand's light theme
##   options.ui_accent = Color("#39d075")       # your accent in the brand theme
##   options.ui_theme = preload("res://my_theme.tres")   # your whole Theme, whatever branding
##   options.ui_powered_by = true               # the "Powered by Polaris Key" badge (off by default)
##
## A scene given a Theme of its own (in the inspector or in code) keeps it; only a scene still on
## the kit's stock theme follows these settings. PKeyBoot's `theme` option (a Theme a mounted pack
## provides) still applies after MOUNT. `ui_theme` is layered: the game's Theme wins wherever it
## sets an item, over the neutral layer derived from it (`layered()`), so a game's own theme keeps
## the kit's type hierarchy, spacing and container gaps where it does not set them itself.
##
## **Spacing and type (both looks).** One spacing scale on a 4 px base (`SPACE`), and the roles the
## scenes use (`DENSITIES`, `MEASURES`), in every stock theme as constants of the type
## `PKeyLayout` (`get_theme_constant("card_padding", "PKeyLayout")`), and as the container type
## variations the scenes are built from: `PKeyStack` (a column of related items), `PKeyTight` (a
## title over its line, a label over its control), `PKeySections` (a card's sections),
## `PKeyRow` and `PKeyActions` (buttons in a row, wrapping), `PKeyColumns` (the two columns of a
## landscape layout). The type scale is `PKeyTitle`, `PKeySection`, the body (Label, Button and the
## inputs), `PKeyMuted` (captions), `PKeyCode` (the user code, mono) and `PKeyMono` (ids). The
## numbers are at scale 1 (a 1280×720 screen) in the spacious density, the Godot default
## (UI-KITS.md §3.1); `variant()` makes a stock theme for another screen scale or density, which
## PKeyUiView picks as the screen changes. The brand theme's roles are these numbers; the neutral
## one scales them by the game's font size against the brand's body size (18).
##
## Committed resources (tools/gen_theme.gd writes them; the `brand` suite fails on drift):
## pkey_theme.tres (neutral, the one every scene file references, as built over the engine's
## default theme), pkey_brand_dark.tres and pkey_brand_light.tres.

const NEUTRAL_PATH := "res://addons/polaris_key/ui/theme/pkey_theme.tres"
const DARK_PATH := "res://addons/polaris_key/ui/theme/pkey_brand_dark.tres"
const LIGHT_PATH := "res://addons/polaris_key/ui/theme/pkey_brand_light.tres"
const REGULAR_PATH := "res://addons/polaris_key/ui/theme/fonts/rubik_regular.tres"
const BOLD_PATH := "res://addons/polaris_key/ui/theme/fonts/rubik_bold.tres"
const MONO_PATH := "res://addons/polaris_key/ui/theme/fonts/system_mono.tres"

## The bundled fonts' licence texts (SIL OFL 1.1 requires them to travel with the fonts), keyed by
## the font resources' path prefix under `fonts/`. They are `.txt` files, which an export preset
## leaves out unless its include filter names them, so PKeyExportPlugin adds each one to any
## export that carries a matching font resource (`font_licences`).
const FONT_LICENCES := {
	"res://addons/polaris_key/ui/theme/fonts/rubik_": [
		"res://addons/polaris_key/ui/theme/fonts/OFL.txt",
		"res://addons/polaris_key/ui/theme/fonts/FONT-NOTICE.txt",
	],
	"res://addons/polaris_key/ui/theme/fonts/jetbrains_mono_": [
		"res://addons/polaris_key/ui/theme/fonts/OFL-JetBrainsMono.txt",
	],
}


## The licence files that must ship beside the resource at `path`: empty unless it is one of the
## bundled fonts.
static func font_licences(path: String) -> Array:
	for prefix in FONT_LICENCES:
		if path.begins_with(prefix):
			return FONT_LICENCES[prefix]
	return []


## True when `path` is one of the bundled fonts' licence files.
static func is_font_licence(path: String) -> bool:
	for files in FONT_LICENCES.values():
		if files.has(path):
			return true
	return false

## `branding`: no Polaris Key branding; the game's theme and font (the default).
const BRANDING_NONE := "none"
## `branding`: the Polaris Key design system.
const BRANDING_POLARIS_KEY := "polaris-key"

## Meta on every theme this class builds, so a scene can tell the stock look from the game's own.
const STOCK_META := &"pkey_stock"

## Corner radii: the Godot kit's control and panel radii (PKeyKitTokens.RADIUS_CONTROL and
## RADIUS_PANEL, UI-KITS.md §2.1), chips `full`.
const RADIUS_CONTROL := int(PKeyKitTokens.RADIUS_CONTROL)
const RADIUS_CARD := int(PKeyKitTokens.RADIUS_PANEL)
const RADIUS_FULL := 999
## The focus ring (BRAND.md §7.4): 2 px of `focus`, drawn 2 px outside the control.
const RING_WIDTH := int(PKeyKitTokens.FOCUS_WIDTH)
const RING_OFFSET := int(PKeyKitTokens.FOCUS_OFFSET)
## The neutral error colour on a dark ground (light text): 5.7:1 on black.
const NEUTRAL_ERROR := Color("#e5534b")
## The neutral error colour on a light ground (dark text): 5.6:1 on white (#e5534b is ~3.7:1).
const NEUTRAL_ERROR_ON_LIGHT := Color("#c62828")

## The type variations every scene uses; a replacement Theme should style them.
const VARIATIONS := {
	"PKeyCard": "PanelContainer",
	"PKeyBanner": "PanelContainer",
	"PKeyTitle": "Label",
	"PKeySection": "Label",
	"PKeyMuted": "Label",
	"PKeyCode": "Label",
	"PKeyMono": "Label",
	"PKeyStrong": "Label",
	"PKeyError": "Label",
	"PKeyBadge": "Label",
	"PKeyPrimary": "Button",
	"PKeyWarning": "Label",
	"PKeyAvatar": "PanelContainer",
	"PKeyActionRow": "BoxContainer",
	"PKeyLink": "Button",
	"PKeyFieldError": "LineEdit",
	"PKeyQrTile": "PanelContainer",
	"PKeyScrim": "PanelContainer",
	"PKeySeatOn": "PanelContainer",
	"PKeySeatOff": "PanelContainer",
	"PKeyRail": "PanelContainer",
	"PKeyStack": "VBoxContainer",
	"PKeyTight": "VBoxContainer",
	"PKeySections": "VBoxContainer",
	"PKeyRow": "HBoxContainer",
	"PKeyColumns": "BoxContainer",
	"PKeyActions": "HFlowContainer",
	"PKeyGrid": "GridContainer",
}

# ── Spacing and type ─────────────────────────────────────────────────────────────────────

## The spacing scale: a 4 px base, in logical pixels at scale 1. Every margin, padding and gap in
## the kit is one of these (through the roles below); in every stock theme as the PKeyLayout
## constants space_1 … space_16 (the step is the multiple of 4).
const SPACE := [4, 8, 12, 16, 20, 24, 32, 40, 48, 64]
## The theme type that carries the layout roles and the scale as constants.
const LAYOUT_TYPE := &"PKeyLayout"
## The layout roles in each density (UI-KITS.md §3.1 `density`; Godot defaults to spacious), at
## scale 1. Translated from the mockup kit's rhythm (its card inset 24, section gap 32, stack 16,
## label to control 8, buttons 8 apart, controls 36 high, at a 14 px body) to the Godot kit's
## 18 px body at TV distance:
##   page_margin      the least space between the screen's (safe) edge and a card
##   card_padding     inside a card or dialog
##   section_gap      between a card's sections: its heading, its body, its actions
##   stack_gap        between related items in a section (fields, stacked buttons)
##   tight_gap        a title to its one line, a label to its control, a value to its caption
##   inline_gap       buttons and chips in a row
##   column_gap       between the two columns of a landscape layout
##   control_height   every button and input
##   control_padding  a button's sides
##   banner_padding   a strip's top and bottom
const DENSITIES := {
	# Spacious is the Godot kit tokens (PKeyKitTokens: CARD_PAD, CONTROL_HEIGHT; 16 between paired
	# gamepad buttons, UI-KITS.md §1.5 rule 5); the others step down on the 4 px grid.
	"spacious": {"page_margin": 32, "card_padding": int(PKeyKitTokens.CARD_PAD), "section_gap": 32, "stack_gap": 16, "tight_gap": 8, "inline_gap": 16, "column_gap": 48, "control_height": int(PKeyKitTokens.CONTROL_HEIGHT), "control_padding": 24, "banner_padding": 16},
	"comfortable": {"page_margin": 24, "card_padding": 36, "section_gap": 24, "stack_gap": 12, "tight_gap": 8, "inline_gap": 12, "column_gap": 40, "control_height": 52, "control_padding": 20, "banner_padding": 12},
	"compact": {"page_margin": 16, "card_padding": 28, "section_gap": 16, "stack_gap": 8, "tight_gap": 4, "inline_gap": 8, "column_gap": 24, "control_height": 44, "control_padding": 16, "banner_padding": 8},
}
## The density a stock theme is built in when nobody asks for another.
const DEFAULT_DENSITY := "spacious"
## Widths and sizes that do not change with density, at scale 1:
##   card_width       a one-column card
##   card_width_wide  a two-column (landscape) card
##   content_width    a list (settings)
##   qr_size          a QR code a phone scans (never under PKeyUiView.QR_MIN_PHYSICAL on screen)
##   icon_size        the product's icon heading a focused step (32)
##   icon_size_card   the product's icon on an update or settings card (56)
##   hero_icon_size   the product's icon leading a screen (the gate, the boot)
const MEASURES := {"card_width": 520, "card_width_wide": 960, "content_width": 680, "qr_size": 232, "icon_size": 32, "icon_size_card": 56, "hero_icon_size": 64}
## Which role sets each container variation's gap.
const CONTAINER_GAPS := {
	"PKeyStack": "stack_gap",
	"PKeyTight": "tight_gap",
	"PKeySections": "section_gap",
	"PKeyRow": "inline_gap",
	"PKeyColumns": "column_gap",
	"PKeyActions": "inline_gap",
	"PKeyActionRow": "inline_gap",
}
## The type scale at scale 1 (the generated Godot kit tokens, PKeyKitTokens: title, body, meta and
## code; the section step sits between body and title).
const TYPE_TITLE := 32
const TYPE_SECTION := 24
const TYPE_BODY := 18
const TYPE_CAPTION := 16
const TYPE_CHIP := 16
## The type floor: captions, chips and meta text never render under this at any scale, and under
## TYPE_FLOOR_AT_SCALE_1 at scale 1 or more (limited to the body size where that is smaller).
const TYPE_FLOOR := 14
const TYPE_FLOOR_AT_SCALE_1 := 16
const FLOOR_TYPES := ["PKeyMuted", "PKeyBadge"]
const TYPE_CODE := 52
## The neutral look's steps, as multiples of the game's font size.
const NEUTRAL_RATIOS := {"PKeyTitle": 1.5, "PKeySection": 1.25, "PKeyCode": 2.25, "PKeyMono": 1.0, "PKeyMuted": 0.875, "PKeyBadge": 0.8}
## Meta on a stock theme: its density, the multiplier its layout roles were built with (1 for the
## brand theme, the game's font size over TYPE_BODY for the neutral one), and whether it is the
## brand theme (which also sizes the built-in controls' padding).
const DENSITY_META := &"pkey_density"
const UNIT_META := &"pkey_unit"
const BRAND_META := &"pkey_brand"
## Meta on a `layered()` theme: the game's Theme it was built over.
const LAYERED_META := &"pkey_layered_over"
## Meta on a stock theme: the colours `kit_icons()` draws its switch, check and chevron icons in.
const ICON_PALETTE_META := &"pkey_icon_palette"
## Meta on a neutral theme: the game's font size it was built for. On a `variant()`: the stock
## theme it was made from (`base_of()`).
const BASE_SIZE_META := &"pkey_base_size"
const VARIANT_OF_META := &"pkey_variant_of"
## The engine control types a scaled neutral theme sizes (the neutral theme itself leaves them to
## the game).
const BODY_TYPES := ["Label", "Button", "CheckButton", "CheckBox", "OptionButton", "LineEdit", "TextEdit", "PopupMenu", "TooltipLabel", "ProgressBar"]
## Engine icons a scaled theme resizes with the text.
const SCALED_ICON_TYPES := ["CheckButton", "CheckBox", "OptionButton"]

static var _variants := {}
static var _layered := {}
static var _icons := {}

## BRANDING_NONE (the default) or BRANDING_POLARIS_KEY.
static var branding := BRANDING_POLARIS_KEY:
	set(value):
		branding = value
		_cache = null
## The brand theme's scheme: "dark" (the default) or "light". Ignored without branding.
static var scheme := "dark":
	set(value):
		scheme = value
		_cache = null
## The brand theme's accent; alpha 0 (the default) resolves in this order (UI-KITS.md §1.2, never
## the platform violet by default): `presentation_accent`, the accent derived from the product's
## icon, then ink (a text_strong primary with a page-colour label).
static var accent := Color(0, 0, 0, 0):
	set(value):
		accent = value
		_cache = null
## A Theme that replaces the kit's in every scene still on the stock theme; null for none.
static var override: Theme = null
## Show the "Powered by Polaris Key" badge where the scenes offer it (gate, boot, settings).
static var powered_by := false
## The density the scenes use where the screen has room for it (UI-KITS.md §3.1): "spacious" (the
## Godot default), "comfortable" or "compact". A screen too small for it steps down on its own.
static var density := DEFAULT_DENSITY
## The product the screens name (UI-KITS.md §1.2 ProductIdentity, until the SDK's presentation
## accessor feeds it): empty / null fall back to the project's application/config/name and icon.
static var product_name := ""
static var product_icon: Texture2D = null:
	set(value):
		product_icon = value
		_cache = null
## The product's registered presentation accent ("#rrggbb"), the seam HA-14's SDK accessor feeds;
## "" until then. Nothing is fetched here.
static var presentation_accent := "":
	set(value):
		presentation_accent = value
		_cache = null
static var _derived := {}

static var _cache: Theme = null
static var _textures := {}
static var _neutral_cache := {}


## Apply the UI options of a PKeyOptions (called by `PolarisKey.configure()`). An unknown
## `ui_branding` is neutral (the game-theme look).
static func apply_options(opts: Resource) -> void:
	if opts == null:
		return
	branding = BRANDING_POLARIS_KEY if str(opts.get("ui_branding")) == BRANDING_POLARIS_KEY else BRANDING_NONE
	scheme = "light" if str(opts.get("ui_brand_scheme")) == "light" else "dark"
	accent = opts.get("ui_accent") if opts.get("ui_accent") is Color else Color(0, 0, 0, 0)
	override = opts.get("ui_theme") as Theme
	powered_by = opts.get("ui_powered_by") == true
	var d = opts.get("ui_density")
	density = d if d is String and DENSITIES.has(d) else DEFAULT_DENSITY
	var pn = opts.get("ui_product_name")
	product_name = pn if pn is String else ""
	product_icon = opts.get("ui_product_icon") as Texture2D
	refresh_views()


## Re-render every kit view in the tree (deferred), so options applied after a scene was mounted
## take effect: PolarisKey.boot() shows its view before configuring from polaris_key.tres.
static func refresh_views() -> void:
	var tree := Engine.get_main_loop() as SceneTree
	if tree != null:
		tree.call_group_flags(SceneTree.GROUP_CALL_DEFERRED, &"pkey_ui_views", &"refresh_view")


## Back to the defaults: the Polaris Key look (dark), no override, no badge.
static func reset() -> void:
	branding = BRANDING_POLARIS_KEY
	scheme = "dark"
	accent = Color(0, 0, 0, 0)
	override = null
	powered_by = false
	density = DEFAULT_DENSITY
	product_name = ""
	product_icon = null
	presentation_accent = ""


## The product's identity for the kit's headers: {"name": String, "icon": Texture2D or null}, from
## `product_name` / `product_icon`, else the project's `application/config/name` and
## `application/config/icon` (UI-KITS.md §1.2: the integrator first, the bundle last; never a
## Polaris Key mark).
static func product_identity() -> Dictionary:
	var n := product_name
	if n == "":
		n = str(ProjectSettings.get_setting("application/config/name", ""))
	var icon := product_icon
	if icon == null:
		var path := str(ProjectSettings.get_setting("application/config/icon", ""))
		if path != "" and ResourceLoader.exists(path):
			icon = load(path) as Texture2D
	return {"name": n, "icon": icon}


## True when the Polaris Key brand is on (and no override Theme replaces it).
static func branded() -> bool:
	return override == null and branding == BRANDING_POLARIS_KEY


## The theme a kit scene should use now: `override` (layered over the kit's neutral structure),
## else the brand theme when branded, else the neutral theme built over the game's project theme.
static func current() -> Theme:
	if override != null:
		return layered(override)
	if _cache != null:
		return _cache
	if branding == BRANDING_POLARIS_KEY:
		var dark := scheme != "light"
		var hex := accent_hex()
		if hex == "":
			# Ink: the committed theme.
			_cache = load(LIGHT_PATH if not dark else DARK_PATH) as Theme
		else:
			_cache = build(dark, Color(hex))
		kit_icons(_cache, 1.0)
		cjk_fallback(_cache)
	else:
		_cache = neutral()
		kit_icons(_cache, 1.0)
	return _cache


## The brand accent as "#rrggbb", or "" for ink: `accent` (ui_accent), else `presentation_accent`,
## else the accent derived from the product's icon, cached per icon; ink for a missing or
## greyscale icon.
static func accent_hex() -> String:
	if accent.a > 0.0:
		return "#" + accent.to_html(false)
	if presentation_accent != "":
		var n := PKeyAccent.normalize(presentation_accent)
		if n != "":
			return n
	var icon: Texture2D = product_identity()["icon"]
	if icon == null:
		return ""
	var id := icon.get_instance_id()
	if not _derived.has(id):
		var hex := ""
		var img := icon.get_image()
		if img != null and not img.is_empty():
			img = img.duplicate() as Image
			if img.is_compressed():
				img.decompress()
			img.convert(Image.FORMAT_RGBA8)
			# A small copy is enough for a dominant hue, and keeps the pass fast.
			var longest := maxi(img.get_width(), img.get_height())
			if longest > 64:
				var k := 64.0 / longest
				img.resize(maxi(1, roundi(img.get_width() * k)), maxi(1, roundi(img.get_height() * k)), Image.INTERPOLATE_BILINEAR)
			hex = PKeyAccent.derive(img.get_data())
		_derived[id] = hex
	return _derived[id]


## The theme for one scene: `current()`, except that the neutral theme is derived from what the
## scene's place in the tree resolves (an ancestor's Theme, else the project's), so a kit scene
## inside a game's own themed menu matches that menu. The game's styles are read from the nearest
## ancestor that is not itself on a kit theme, never from the view (whose own local overrides and
## stock theme are not the game's).
static func for_view(view: Control) -> Theme:
	if override != null or branding == BRANDING_POLARIS_KEY or view == null:
		return current()
	var src := _game_source(view)
	if src == null:
		return current()
	var size := src.get_theme_default_font_size()
	var font := src.get_theme_default_font()
	var text := src.get_theme_color("font_color", "Label")
	var game := {
		"panel": src.get_theme_stylebox("panel", "PanelContainer"),
		"normal": src.get_theme_stylebox("normal", "Button"),
		"hover": src.get_theme_stylebox("hover", "Button"),
		"pressed": src.get_theme_stylebox("pressed", "Button"),
		"disabled": src.get_theme_stylebox("disabled", "Button"),
		"focus": src.get_theme_stylebox("focus", "Button"),
		"field": src.get_theme_stylebox("normal", "LineEdit"),
		"field_focus": src.get_theme_stylebox("focus", "LineEdit"),
	}
	var key := "%d|%d|%s" % [size, font.get_instance_id() if font != null else 0, text.to_html()]
	for k in game:
		key += "|%d" % (game[k].get_instance_id() if game[k] != null else 0)
	if not _neutral_cache.has(key):
		var bold: Font = null
		if font != null:
			var v := FontVariation.new()
			v.base_font = font
			v.variation_embolden = 0.6
			bold = v
		var t := neutral_with(size, text, bold, game["panel"], game["normal"], game)
		kit_icons(t, 1.0)
		_neutral_cache[key] = t
	return _neutral_cache[key]


## The nearest ancestor Control of `view` that is not on a kit theme: the node whose theme lookups
## are the game's. Null when there is none (the project theme is the game's).
static func _game_source(view: Control) -> Control:
	var n := view.get_parent_control()
	while n != null:
		if not is_stock(n.theme) and not n.has_theme_stylebox_override("panel"):
			return n
		n = n.get_parent_control()
	return null


## True when `t` is one of the kit's stock themes (a scene still on the default look).
static func is_stock(t: Theme) -> bool:
	return t != null and t.has_meta(STOCK_META)


## Whether the look is on a dark ground (picks the dark or light mark and badge files): the brand
## scheme when branded, else whether `view`'s text (or the project's) is light.
static func is_dark(view: Control = null) -> bool:
	if branded():
		return scheme != "light"
	var text := view.get_theme_color("font_color", "Label") if view != null else _project_color("font_color", "Label")
	return text.get_luminance() > 0.5


# ── Neutral ──────────────────────────────────────────────────────────────────────────────

## The neutral theme over the game's project theme: its font size, text colour, panel and font.
static func neutral() -> Theme:
	var project := ThemeDB.get_project_theme()
	var base := ThemeDB.fallback_font_size
	if project != null and project.has_default_font_size():
		base = project.default_font_size
	var font: Font = ThemeDB.fallback_font
	if project != null and project.has_default_font():
		font = project.default_font
	var bold := FontVariation.new()
	bold.base_font = font
	bold.variation_embolden = 0.6
	var game := {
		"panel": _project_stylebox("panel", "PanelContainer"),
		"normal": _project_stylebox("normal", "Button"),
		"hover": _project_stylebox("hover", "Button"),
		"pressed": _project_stylebox("pressed", "Button"),
		"disabled": _project_stylebox("disabled", "Button"),
		"focus": _project_stylebox("focus", "Button"),
		"field": _project_stylebox("normal", "LineEdit"),
		"field_focus": _project_stylebox("focus", "LineEdit"),
	}
	return neutral_with(base, _project_color("font_color", "Label"), bold, game["panel"], game["normal"], game)


## The neutral theme from explicit inputs (`bold` null: titles keep the body face). `button` is the
## game's normal Button style and `game` its other styles (keys panel, normal, hover, pressed,
## disabled, focus, field, field_focus; any may be missing): the primary action's ink style and the
## controls' widened margins, hairlines and focus rings are built on them.
static func neutral_with(base_size: int, text: Color, bold: Font, panel: StyleBox, button: StyleBox = null, game: Dictionary = {}) -> Theme:
	var t := Theme.new()
	t.set_meta(STOCK_META, true)
	for v in VARIATIONS:
		t.set_type_variation(v, VARIATIONS[v])
	var light_text := text.get_luminance() > 0.5
	var ground := _ground(panel, button, text)
	var card := _raised(panel, text, ground)
	var card_fill: Color = (card as StyleBoxFlat).bg_color if card is StyleBoxFlat else ground
	t.set_stylebox("panel", "PKeyCard", card)
	t.set_stylebox("panel", "PKeyBanner", card.duplicate() as StyleBox)
	var floor_px := mini(TYPE_FLOOR_AT_SCALE_1, maxi(TYPE_FLOOR, base_size))
	for v in NEUTRAL_RATIOS:
		var px := roundi(base_size * NEUTRAL_RATIOS[v])
		t.set_font_size("font_size", v, maxi(px, floor_px) if v in FLOOR_TYPES else px)
	_apply_layout(t, float(base_size) / TYPE_BODY, DEFAULT_DENSITY, false)
	var muted := text
	muted.a *= 0.72
	t.set_color("font_color", "PKeyMuted", muted)
	# Dark text means a light ground, which needs the darker red for 4.5:1.
	var danger := NEUTRAL_ERROR if light_text else NEUTRAL_ERROR_ON_LIGHT
	t.set_color("font_color", "PKeyError", danger)
	t.set_color("font_color", "PKeyBadge", text)
	t.set_color("font_color", "PKeyWarning", Color("#e0a030") if light_text else Color("#8a5a00"))
	t.set_stylebox("panel", "PKeyAvatar", _box(Color(text, 0.14), Color(text, 0.14), 0, RADIUS_FULL, 0))
	var tint := text
	tint.a = 0.1
	var edge := text
	edge.a = 0.35
	var chip := _box(tint, edge, 1, RADIUS_FULL, 3)
	chip.content_margin_left = roundi(base_size * 0.6)
	chip.content_margin_right = roundi(base_size * 0.6)
	t.set_stylebox("normal", "PKeyBadge", chip)
	if bold != null:
		t.set_font("font", "PKeyTitle", bold)
		t.set_font("font", "PKeySection", bold)
		t.set_font("font", "PKeyCode", bold)
		t.set_font("font", "PKeyPrimary", bold)
	t.set_color("dark", "PKeyQrRect", Color.BLACK)
	t.set_color("light", "PKeyQrRect", Color.WHITE)
	var tile := _box(Color.WHITE, Color(0, 0, 0, 0.12) if not light_text else Color.WHITE, 1, RADIUS_CONTROL, 6)
	t.set_stylebox("panel", "PKeyQrTile", tile)

	# Controls: the game's own boxes, never narrower than a control's padding, with a hairline
	# where the game draws none and its fill all but vanishes into the card; the game's ring only
	# when it reads at TV distance, else the kit's.
	var pad := float(DENSITIES[DEFAULT_DENSITY]["control_padding"]) * float(base_size) / TYPE_BODY
	var normal: StyleBox = game.get("normal", button)
	var accent_edge := _accent_of(normal, ground, text)
	var ring := _tv_ring(game.get("focus"), normal, ground, text, accent_edge)
	var secondary_hairline := normal is StyleBoxFlat and _no_border(normal as StyleBoxFlat) and _contrast((normal as StyleBoxFlat).bg_color, card_fill) < 1.2
	for item in ["normal", "hover", "pressed", "disabled"]:
		var src: StyleBox = game.get(item, normal if item != "normal" else button)
		if src == null:
			src = normal
		if src == null:
			continue
		var b := _widen(src, pad)
		if secondary_hairline and b is StyleBoxFlat:
			(b as StyleBoxFlat).border_color = edge
			for side in [SIDE_LEFT, SIDE_TOP, SIDE_RIGHT, SIDE_BOTTOM]:
				(b as StyleBoxFlat).set_border_width(side, 1)
		t.set_stylebox(item, "Button", b)
	t.set_stylebox("focus", "Button", ring)
	t.set_stylebox("focus", "OptionButton", ring)
	var field: StyleBox = game.get("field")
	if field != null:
		t.set_stylebox("normal", "LineEdit", _widen(field, pad))
		t.set_stylebox("normal", "TextEdit", _widen(field, pad))
		var err := _widen(field, pad).duplicate() as StyleBox
		if err is StyleBoxFlat:
			(err as StyleBoxFlat).border_color = danger
			for side in [SIDE_LEFT, SIDE_TOP, SIDE_RIGHT, SIDE_BOTTOM]:
				(err as StyleBoxFlat).set_border_width(side, maxi(2, (err as StyleBoxFlat).get_border_width(side)))
		t.set_stylebox("normal", "PKeyFieldError", err)
	t.set_stylebox("focus", "LineEdit", ring)
	t.set_stylebox("focus", "TextEdit", ring)
	# A switch or a check box is its label and its drawn control, never a framed button.
	for type in ["CheckButton", "CheckBox"]:
		for item in ["normal", "hover", "pressed", "hover_pressed", "disabled"]:
			var e := StyleBoxEmpty.new()
			e.content_margin_top = 4
			e.content_margin_bottom = 4
			t.set_stylebox(item, type, e)
		t.set_stylebox("focus", type, ring)
	# The one primary action: the ink style on the game's button shape (the game's hairline-free
	# normal box widened like the rest).
	_ink_primary(t, text, ground, t.get_stylebox("normal", "Button"))
	# A quiet link (the tertiary action): the text colour, underlined by its ring when focused.
	var none := StyleBoxEmpty.new()
	none.content_margin_left = 8
	none.content_margin_right = 8
	for item in ["normal", "hover", "pressed", "disabled"]:
		t.set_stylebox(item, "PKeyLink", none)
	for c in ["font_color", "font_hover_color", "font_focus_color", "font_pressed_color"]:
		t.set_color(c, "PKeyLink", text)
	var scrim := Color(0, 0, 0, PKeyKitTokens.SCRIM_DARK_OPACITY) if light_text else Color(0, 0, 0, PKeyKitTokens.SCRIM_LIGHT_OPACITY)
	t.set_stylebox("panel", "PKeyScrim", _box(scrim, scrim, 0, 0, 0))
	var page_px := roundf(float(DENSITIES[DEFAULT_DENSITY]["page_margin"]) * float(base_size) / TYPE_BODY)
	_pad(t, "panel", "PKeyScrim", page_px, page_px)
	t.set_stylebox("panel", "PKeySeatOn", _box(Color(text, 0.8), Color(text, 0.8), 0, RADIUS_FULL, 0))
	t.set_stylebox("panel", "PKeySeatOff", _box(Color(text, 0.1), Color(text, 0.1), 0, RADIUS_FULL, 0))
	t.set_stylebox("panel", "PKeyRail", _box(Color(text, 0.06), Color(text, 0.06), 0, RADIUS_CONTROL, 0))
	t.set_meta(UNIT_META, float(base_size) / TYPE_BODY)
	t.set_meta(BASE_SIZE_META, base_size)
	# The kit's switch, check box and chevron icons in the game's text colour (`kit_icons`).
	var off := ground.lerp(text, 0.35)
	t.set_meta(ICON_PALETTE_META, {"on": text, "knob": ground, "off": off, "ink": text, "muted": ground.lerp(Color(text, 1.0), 0.72)})
	return t


## The page colour a theme sits on, opaque: the game's panel fill, else its button fill, else a
## dark or light ground chosen by the text colour.
static func _ground(panel: StyleBox, button: StyleBox, text: Color) -> Color:
	for b in [panel, button]:
		if b is StyleBoxFlat and (b as StyleBoxFlat).bg_color.a >= 0.5 and (b as StyleBoxFlat).draw_center:
			return Color((b as StyleBoxFlat).bg_color, 1.0)
	return Color("#161a22") if text.get_luminance() > 0.5 else Color("#f6f7f9")


## A card raised off the game's panel, so it shows on a page of the same panel: the panel's own
## style with its ground lifted a little toward the text colour (toward white on a light theme), a
## hairline and at least a 12 px radius. A missing, empty or see-through panel gets a card of the
## `ground` instead, never none; a textured panel is kept as it is.
static func _raised(panel: StyleBox, text: Color, ground: Color) -> StyleBox:
	var light_text := text.get_luminance() > 0.5
	if panel != null and not (panel is StyleBoxFlat) and not (panel is StyleBoxEmpty):
		return panel.duplicate() as StyleBox
	var f := StyleBoxFlat.new()
	var solid := panel is StyleBoxFlat and (panel as StyleBoxFlat).bg_color.a >= 0.5 and (panel as StyleBoxFlat).draw_center
	if solid:
		f = panel.duplicate() as StyleBoxFlat
	f.draw_center = true
	f.bg_color = Color(ground.lerp(text, 0.06) if light_text else ground.lerp(Color.WHITE, 0.7), 0.96)
	f.border_color = Color(text, 0.14)
	for side in [SIDE_LEFT, SIDE_TOP, SIDE_RIGHT, SIDE_BOTTOM]:
		f.set_border_width(side, maxi(1, f.get_border_width(side)))
	for corner in [CORNER_TOP_LEFT, CORNER_TOP_RIGHT, CORNER_BOTTOM_RIGHT, CORNER_BOTTOM_LEFT]:
		f.set_corner_radius(corner, maxi(12, f.get_corner_radius(corner)))
	return f


static func _no_border(b: StyleBoxFlat) -> bool:
	return b.border_width_left + b.border_width_top + b.border_width_right + b.border_width_bottom == 0


## A copy of `b` whose left and right content margins are at least `pad` (the game's value when
## larger).
static func _widen(b: StyleBox, pad: float) -> StyleBox:
	var c := b.duplicate() as StyleBox
	c.content_margin_left = maxf(b.get_margin(SIDE_LEFT), pad)
	c.content_margin_right = maxf(b.get_margin(SIDE_RIGHT), pad)
	return c


## The game's own accent: its button's border colour when that reads (3:1) on the ground, else its
## text colour.
static func _accent_of(normal: StyleBox, ground: Color, text: Color) -> Color:
	if normal is StyleBoxFlat and not _no_border(normal as StyleBoxFlat):
		var c := (normal as StyleBoxFlat).border_color
		if c.a > 0.5 and _contrast(Color(c, 1.0), ground) >= 3.0:
			return Color(c, 1.0)
	return Color(text, 1.0)


## The focus ring a neutral look draws: the game's own when it is a flat box at least 3 px wide
## (FOCUS_WIDTH) that reads 3:1 on the ground, else the kit's ring (3 px, 2 px off) in `colour`.
static func _tv_ring(game_focus: StyleBox, normal: StyleBox, ground: Color, text: Color, colour: Color) -> StyleBox:
	if game_focus is StyleBoxFlat:
		var f := game_focus as StyleBoxFlat
		if f.border_width_left >= RING_WIDTH and _contrast(Color(f.border_color, 1.0), ground) >= 3.0:
			return game_focus
	return _ring(colour)


## The one primary action in the game's own look: the ink primary of UI-KITS.md §1.2 (filled with
## the text colour, labelled in the page's ground), on the game's button shape.
static func _ink_primary(t: Theme, text: Color, ground: Color, button: StyleBox) -> void:
	var ink := Color(text, 1.0)
	for pair in [["normal", 0.0], ["hover", 0.12], ["pressed", 0.24]]:
		var b: StyleBoxFlat = button.duplicate() as StyleBoxFlat if button is StyleBoxFlat else StyleBoxFlat.new()
		b.draw_center = true
		b.bg_color = ink.lerp(ground, pair[1])
		b.border_color = b.bg_color
		if b.get_corner_radius(CORNER_TOP_LEFT) == 0:
			b.set_corner_radius_all(6)
		t.set_stylebox(pair[0], "PKeyPrimary", b)
	for c in ["font_color", "font_hover_color", "font_focus_color", "font_pressed_color"]:
		t.set_color(c, "PKeyPrimary", ground)


## The committed neutral theme: built over the engine's default theme, without a derived bold
## face (a FontVariation of the engine's built-in font cannot be saved).
static func neutral_default() -> Theme:
	var d := ThemeDB.get_default_theme()
	var game := {
		"panel": d.get_stylebox("panel", "PanelContainer"), "normal": d.get_stylebox("normal", "Button"),
		"hover": d.get_stylebox("hover", "Button"), "pressed": d.get_stylebox("pressed", "Button"),
		"disabled": d.get_stylebox("disabled", "Button"), "focus": d.get_stylebox("focus", "Button"),
		"field": d.get_stylebox("normal", "LineEdit"), "field_focus": d.get_stylebox("focus", "LineEdit"),
	}
	return neutral_with(ThemeDB.fallback_font_size, d.get_color("font_color", "Label"), null, game["panel"], game["normal"], game)


static func _project_color(item: StringName, type: StringName) -> Color:
	var project := ThemeDB.get_project_theme()
	if project != null and project.has_color(item, type):
		return project.get_color(item, type)
	return ThemeDB.get_default_theme().get_color(item, type)


static func _project_stylebox(item: StringName, type: StringName) -> StyleBox:
	var project := ThemeDB.get_project_theme()
	if project != null and project.has_stylebox(item, type):
		return project.get_stylebox(item, type)
	return ThemeDB.get_default_theme().get_stylebox(item, type)


# ── Polaris Key ──────────────────────────────────────────────────────────────────────────

## The brand theme with the bundled Rubik. `p_accent` (alpha 0: the platform
## violet) colours the primary button, the chips and the hover border; give it a colour with at
## least 3:1 against the theme's surfaces. `regular` / `bold` replace Rubik.
static func build(dark := true, p_accent := Color(0, 0, 0, 0), regular: Font = null, bold: Font = null) -> Theme:
	return build_with(dark, p_accent, regular if regular != null else load(REGULAR_PATH) as Font, bold if bold != null else load(BOLD_PATH) as Font, system_mono())


## The platform's monospace face for ids (SF Mono or Menlo, Consolas, DejaVu Sans Mono…;
## fonts/system_mono.tres). The bundled JetBrains Mono variable font draws E, 8 and 0 as solid
## boxes in Godot 4.7, so the kit does not use it until it is fixed (UK-11).
static func system_mono() -> Font:
	return load(MONO_PATH) as Font


## `build()` with exactly these fonts: null keeps the engine's default font for that role.
static func build_with(dark: bool, p_accent: Color, regular: Font, bold: Font, mono: Font = null) -> Theme:
	var p := palette(dark)
	_resolve_accent(p, dark, p_accent)
	var t := Theme.new()
	t.set_meta(STOCK_META, true)
	t.set_meta(BRAND_META, true)
	t.set_meta(UNIT_META, 1.0)
	t.default_font_size = TYPE_BODY
	if regular != null:
		t.default_font = regular

	# Surfaces: the page ground, raised cards and banners (their padding: _apply_layout below).
	t.set_stylebox("panel", "PanelContainer", _box(p.page, p.page, 0, 0, 0))
	for v in VARIATIONS:
		t.set_type_variation(v, VARIATIONS[v])
	t.set_stylebox("panel", "PKeyCard", _box(p.raised, p.border, 1, RADIUS_CARD, 0))
	t.set_stylebox("panel", "PKeyBanner", _box(p.raised, p.border, 1, RADIUS_CARD, 0))

	# Text: the type scale, every step sized explicitly (so a scaled variant scales them all), with
	# the line heights of the Godot kit tokens (body 18/26, caption 16/22, section 24/32, title 32/40).
	for type in ["Label", "Button", "CheckButton", "CheckBox", "OptionButton", "LineEdit", "TextEdit", "PopupMenu", "TooltipLabel", "ProgressBar"]:
		t.set_font_size("font_size", type, TYPE_BODY)
	t.set_color("font_color", "Label", p.text)
	t.set_constant("line_spacing", "Label", 4)
	t.set_font_size("font_size", "PKeyTitle", TYPE_TITLE)
	t.set_color("font_color", "PKeyTitle", p.strong)
	t.set_constant("line_spacing", "PKeyTitle", 2)
	t.set_font_size("font_size", "PKeySection", TYPE_SECTION)
	t.set_color("font_color", "PKeySection", p.strong)
	t.set_constant("line_spacing", "PKeySection", 4)
	t.set_color("font_color", "PKeyMuted", p.muted)
	t.set_font_size("font_size", "PKeyMuted", TYPE_CAPTION)
	t.set_constant("line_spacing", "PKeyMuted", 3)
	t.set_font_size("font_size", "PKeyCode", TYPE_CODE)
	t.set_color("font_color", "PKeyCode", p.strong)
	t.set_font_size("font_size", "PKeyMono", TYPE_BODY)
	t.set_color("font_color", "PKeyMono", p.strong)
	t.set_color("font_color", "PKeyStrong", p.strong)
	t.set_color("font_color", "PKeyError", p.danger)
	t.set_color("font_color", "PKeyWarning", PKeyBrand.Dark.WARNING if dark else PKeyBrand.Light.WARNING)
	t.set_stylebox("panel", "PKeyAvatar", _box(p.sunken, p.border, 1, RADIUS_FULL, 0))
	if bold != null:
		t.set_font("font", "PKeyTitle", bold)
		t.set_font("font", "PKeySection", bold)
	# The user code in Rubik Bold (the display face); ids in the platform's monospace.
	if bold != null:
		t.set_font("font", "PKeyCode", bold)
	if mono != null:
		t.set_font("font", "PKeyMono", mono)
	# The entitlement chip: the accent's text on its tint, never gold (BRAND.md §1.2).
	t.set_color("font_color", "PKeyBadge", p.accent_fg)
	t.set_font_size("font_size", "PKeyBadge", TYPE_CHIP)
	var chip := _box(p.accent_subtle, p.accent_edge, 1, RADIUS_FULL, 4)
	chip.content_margin_left = 12
	chip.content_margin_right = 12
	t.set_stylebox("normal", "PKeyBadge", chip)

	# Controls (their padding and height: _apply_layout below).
	var focus := _ring(p.focus)
	for type in ["Button", "CheckButton", "CheckBox", "OptionButton", "LineEdit", "TextEdit"]:
		t.set_stylebox("focus", type, focus)
	for type in ["Button", "OptionButton"]:
		t.set_stylebox("normal", type, _box(p.overlay, p.border_strong, 1, RADIUS_CONTROL, 0))
		t.set_stylebox("hover", type, _box(p.overlay, p.accent, 1, RADIUS_CONTROL, 0))
		t.set_stylebox("pressed", type, _box(p.sunken, p.accent, 1, RADIUS_CONTROL, 0))
		t.set_stylebox("disabled", type, _box(p.raised, p.border, 1, RADIUS_CONTROL, 0))
		t.set_color("font_color", type, p.text)
		t.set_color("font_hover_color", type, p.strong)
		t.set_color("font_focus_color", type, p.strong)
		t.set_color("font_pressed_color", type, p.strong)
		t.set_color("font_disabled_color", type, p.subtle)
	t.set_stylebox("normal", "PKeyPrimary", _box(p.accent, p.accent, 1, RADIUS_CONTROL, 0))
	t.set_stylebox("hover", "PKeyPrimary", _box(p.accent_hover, p.accent_hover, 1, RADIUS_CONTROL, 0))
	t.set_stylebox("pressed", "PKeyPrimary", _box(p.accent_pressed, p.accent_pressed, 1, RADIUS_CONTROL, 0))
	for c in ["font_color", "font_hover_color", "font_focus_color", "font_pressed_color"]:
		t.set_color(c, "PKeyPrimary", p.on_accent)
	if bold != null:
		t.set_font("font", "PKeyPrimary", bold)
	for type in ["LineEdit", "TextEdit"]:
		t.set_stylebox("normal", type, _box(p.sunken, p.border_strong, 1, RADIUS_CONTROL, 0))
		t.set_stylebox("read_only", type, _box(p.raised, p.border, 1, RADIUS_CONTROL, 0))
		t.set_color("font_color", type, p.text)
		t.set_color("font_placeholder_color", type, p.subtle)
		t.set_color("caret_color", type, p.focus)
		t.set_color("selection_color", type, p.accent_subtle)
	for type in ["CheckButton", "CheckBox"]:
		# A check control is its label and its switch or box, never a framed button.
		for item in ["normal", "hover", "pressed", "hover_pressed", "disabled"]:
			var e := StyleBoxEmpty.new()
			e.content_margin_top = 4
			e.content_margin_bottom = 4
			t.set_stylebox(item, type, e)
		t.set_constant("h_separation", type, 12)
		t.set_color("font_color", type, p.text)
		t.set_color("font_hover_color", type, p.strong)
		t.set_color("font_focus_color", type, p.strong)
		t.set_color("font_pressed_color", type, p.text)
		t.set_color("font_disabled_color", type, p.subtle)
	# OptionButton's list.
	t.set_stylebox("panel", "PopupMenu", _box(p.overlay, p.border_strong, 1, RADIUS_CONTROL, 6))
	t.set_stylebox("hover", "PopupMenu", _box(p.accent_subtle, p.accent_subtle, 0, RADIUS_CONTROL, 4))
	t.set_color("font_color", "PopupMenu", p.text)
	t.set_color("font_hover_color", "PopupMenu", p.strong)
	t.set_color("font_disabled_color", "PopupMenu", p.subtle)
	# Progress: neutral, never the mark (BRAND.md §7.5).
	t.set_stylebox("background", "ProgressBar", _box(p.sunken, p.border, 1, RADIUS_FULL, 0))
	t.set_stylebox("fill", "ProgressBar", _box(p.subtle, p.subtle, 0, RADIUS_FULL, 0))
	t.set_color("font_color", "ProgressBar", p.text)
	# A QR code stays black on white whatever the theme: scanners need the contrast.
	t.set_color("dark", "PKeyQrRect", Color.BLACK)
	t.set_color("light", "PKeyQrRect", Color.WHITE)
	# Its tile: white, rounded, a little padding beyond the code's own quiet zone.
	t.set_stylebox("panel", "PKeyQrTile", _box(Color.WHITE, Color.WHITE, 0, RADIUS_CONTROL, 6))
	# The tertiary action: a link, no box, in the accent's text colour.
	var none := StyleBoxEmpty.new()
	none.content_margin_left = 8
	none.content_margin_right = 8
	for item in ["normal", "hover", "pressed", "disabled"]:
		t.set_stylebox(item, "PKeyLink", none)
	for c in ["font_color", "font_hover_color", "font_focus_color", "font_pressed_color"]:
		t.set_color(c, "PKeyLink", p.accent_fg)
	# A field that holds a rejected value.
	t.set_stylebox("normal", "PKeyFieldError", _box(p.sunken, p.danger, 2, RADIUS_CONTROL, 0))
	# The page of a dialog opened over a running game: the scrim token, not an opaque ground.
	var scrim: Color = PKeyKitTokens.SCRIM_DARK if dark else PKeyKitTokens.SCRIM_LIGHT
	t.set_stylebox("panel", "PKeyScrim", _box(scrim, scrim, 0, 0, 0))
	# The seat meter's segments (text_strong at 80 % filled, 10 % empty) and a section rail.
	t.set_stylebox("panel", "PKeySeatOn", _box(Color(p.strong, 0.8), Color(p.strong, 0.8), 0, RADIUS_FULL, 0))
	t.set_stylebox("panel", "PKeySeatOff", _box(Color(p.strong, 0.1), Color(p.strong, 0.1), 0, RADIUS_FULL, 0))
	t.set_stylebox("panel", "PKeyRail", _box(p.sunken, p.sunken, 0, RADIUS_CONTROL, 0))
	# Icons: the accent track with a white knob when on (UI-KITS.md §1.5 rule 6).
	t.set_meta(ICON_PALETTE_META, {"on": p.accent, "knob": Color.WHITE, "off": p.border_strong, "ink": p.text, "muted": p.muted, "on_ink": p.on_accent})
	_apply_layout(t, 1.0, DEFAULT_DENSITY, true)
	return t


## Put the resolved accent (PKeyAccent.resolve: solid, on, fg, subtle, focus) into palette `p`;
## alpha 0, or a colour the resolver rejects, is ink: a text_strong fill with a page-colour label.
## Nothing in the brand theme reads the platform violet directly.
static func _resolve_accent(p: Dictionary, dark: bool, input: Color) -> void:
	var r: Dictionary = {}
	if input.a > 0.0:
		r = PKeyAccent.resolve("#" + input.to_html(false), dark)
	if r.is_empty():
		p["accent"] = p.strong
		p["accent_fg"] = p.strong
		p["accent_subtle"] = p.sunken
		p["accent_edge"] = p.border_strong
		p["on_accent"] = p.page
		p["focus"] = p.strong
		p["accent_hover"] = p.strong.darkened(0.12) if dark else p.strong.lightened(0.18)
		p["accent_pressed"] = p.strong.darkened(0.24) if dark else p.strong.lightened(0.32)
		return
	var solid := Color(r["solid"])
	p["accent"] = solid
	p["accent_edge"] = solid
	p["accent_fg"] = Color(r["fg"])
	p["accent_subtle"] = Color(r["subtle"])
	p["on_accent"] = Color(r["on"])
	p["focus"] = Color(r["focus"])
	p["accent_hover"] = solid.lightened(0.12) if dark else solid.darkened(0.12)
	p["accent_pressed"] = solid.darkened(0.2) if dark else solid.darkened(0.28)


## The semantic colours the brand theme uses, for one theme, from PKeyBrand (the accent keys are
## filled by `_resolve_accent`, never from here).
static func palette(dark: bool) -> Dictionary:
	if dark:
		return {
			"page": PKeyBrand.Dark.SURFACE_PAGE, "raised": PKeyBrand.Dark.SURFACE_RAISED,
			"overlay": PKeyBrand.Dark.SURFACE_OVERLAY, "sunken": PKeyBrand.Dark.SURFACE_SUNKEN,
			"strong": PKeyBrand.Dark.TEXT_STRONG, "text": PKeyBrand.Dark.TEXT_DEFAULT,
			"muted": PKeyBrand.Dark.TEXT_MUTED, "subtle": PKeyBrand.Dark.TEXT_SUBTLE,
			"border": PKeyBrand.Dark.BORDER_SUBTLE, "border_strong": PKeyBrand.Dark.BORDER_STRONG,
			"focus": PKeyBrand.Dark.FOCUS, "danger": PKeyBrand.Dark.DANGER,
		}
	return {
		"page": PKeyBrand.Light.SURFACE_PAGE, "raised": PKeyBrand.Light.SURFACE_RAISED,
		"overlay": PKeyBrand.Light.SURFACE_OVERLAY, "sunken": PKeyBrand.Light.SURFACE_SUNKEN,
		"strong": PKeyBrand.Light.TEXT_STRONG, "text": PKeyBrand.Light.TEXT_DEFAULT,
		"muted": PKeyBrand.Light.TEXT_MUTED, "subtle": PKeyBrand.Light.TEXT_SUBTLE,
		"border": PKeyBrand.Light.BORDER_SUBTLE, "border_strong": PKeyBrand.Light.BORDER_STRONG,
		"focus": PKeyBrand.Light.FOCUS, "danger": PKeyBrand.Light.DANGER,
	}


# ── Marks ────────────────────────────────────────────────────────────────────────────────

## The compact "Powered by Polaris Key" badge (the kit's transparent treatment) for a dark or
## light ground, rasterised at 2x its minimum. Show it at powered_by_size("compact") or larger.
static func powered_by_texture(dark: bool) -> Texture2D:
	return _svg("powered-%s" % dark, PKeyBrandMarks.POWERED_BY_COMPACT_DARK if dark else PKeyBrandMarks.POWERED_BY_COMPACT_LIGHT, 2.0 * PKeyBrand.BADGE_MIN_COMPACT.x / PKeyBrandMarks.POWERED_BY_COMPACT_WIDTH)


static func _svg(key: String, svg: String, scale: float) -> Texture2D:
	if _textures.has(key):
		return _textures[key]
	var img := Image.new()
	var tex: Texture2D = null
	if img.load_svg_from_string(svg, scale) == OK:
		tex = ImageTexture.create_from_image(img)
	_textures[key] = tex
	return tex


## The size a "Powered by Polaris Key" badge is shown at: `requested`, raised to the kit minimum
## for its layout ("compact" for app UI, "horizontal" for credits, "stacked" for square spots),
## keeping the badge's proportions. Never crop the badge or show it smaller (BRAND.md §1.5).
static func powered_by_size(layout: String, requested := Vector2.ZERO) -> Vector2:
	var minimum: Vector2 = {
		"horizontal": Vector2(PKeyBrand.BADGE_MIN_HORIZONTAL),
		"stacked": Vector2(PKeyBrand.BADGE_MIN_STACKED),
	}.get(layout, Vector2(PKeyBrand.BADGE_MIN_COMPACT))
	var k := maxf(1.0, maxf(requested.x / minimum.x, requested.y / minimum.y))
	return minimum * k


# ── Layout, scale and density ─────────────────────────────────────────────────────────────

## Write the layout roles of `density`, times `unit` (the screen scale times the theme's own
## multiplier), into `t`: the PKeyLayout constants (the roles, MEASURES and the scale), the gaps of
## the container variations, and the padding of the card and the strip; in the brand theme also of
## the page ground and the controls (a neutral theme leaves those to the game).
static func _apply_layout(t: Theme, unit: float, density: String, brand: bool) -> void:
	var roles: Dictionary = DENSITIES.get(density, DENSITIES[DEFAULT_DENSITY])
	for r in roles:
		t.set_constant(r, LAYOUT_TYPE, roundi(roles[r] * unit))
	for m in MEASURES:
		t.set_constant(m, LAYOUT_TYPE, roundi(MEASURES[m] * unit))
	for s in SPACE:
		t.set_constant("space_%d" % (s / 4), LAYOUT_TYPE, roundi(s * unit))
	t.set_constant("h_separation", "PKeyGrid", roundi(roles["control_padding"] * unit))
	t.set_constant("v_separation", "PKeyGrid", roundi(roles["tight_gap"] * unit))
	for v in CONTAINER_GAPS:
		var gap := roundi(roles[CONTAINER_GAPS[v]] * unit)
		if VARIATIONS[v] == "HFlowContainer":
			t.set_constant("h_separation", v, gap)
			t.set_constant("v_separation", v, gap)
		else:
			t.set_constant("separation", v, gap)
	var card := roundf(roles["card_padding"] * unit)
	_pad(t, "panel", "PKeyCard", card, card)
	_pad(t, "panel", "PKeyBanner", roundf(roles["control_padding"] * unit), roundf(roles["banner_padding"] * unit))
	var page_pad := roundf(roles["page_margin"] * unit)
	_pad(t, "panel", "PKeyScrim", page_pad, page_pad)
	# A sunken surface (a pane, a grouped list) keeps its content off its edge.
	_pad(t, "panel", "PKeyRail", roundf(roles["control_padding"] * unit), roundf(roles["stack_gap"] * unit))
	if brand:
		var page := roundf(roles["page_margin"] * unit)
		_pad(t, "panel", "PanelContainer", page, page)
		var side := roundf(roles["control_padding"] * unit)
		var v := roundf(roles["tight_gap"] * unit)
		for type in ["Button", "OptionButton", "PKeyPrimary"]:
			for item in ["normal", "hover", "pressed", "disabled"]:
				_pad(t, item, type, side, v)
		for type in ["LineEdit", "TextEdit"]:
			for item in ["normal", "read_only"]:
				_pad(t, item, type, roundf(roles["stack_gap"] * unit), v)
		_pad(t, "normal", "PKeyFieldError", roundf(roles["stack_gap"] * unit), v)
	t.set_meta(DENSITY_META, density)


## Replace `t`'s stylebox `item` of `type` (when it has one) with a copy padded `x` a side and `y`
## top and bottom.
static func _pad(t: Theme, item: StringName, type: StringName, x: float, y: float) -> void:
	if not t.has_stylebox(item, type):
		return
	var b := t.get_stylebox(item, type).duplicate() as StyleBox
	b.content_margin_left = x
	b.content_margin_right = x
	b.content_margin_top = y
	b.content_margin_bottom = y
	t.set_stylebox(item, type, b)


## A layout role (or MEASURES entry, or `space_N`) as `t` holds it, else its spacious value at
## scale 1: what a scene reads when its Theme is a game's own without the kit's constants.
static func role(t: Theme, name: StringName) -> int:
	if t != null and t.has_constant(name, LAYOUT_TYPE):
		return t.get_constant(name, LAYOUT_TYPE)
	var roles: Dictionary = DENSITIES[DEFAULT_DENSITY]
	if roles.has(name):
		return roles[name]
	return MEASURES.get(name, 0)


## The density `t` was built in (DEFAULT_DENSITY for a theme the kit did not build).
static func density_of(t: Theme) -> String:
	return String(t.get_meta(DENSITY_META, DEFAULT_DENSITY)) if t != null else DEFAULT_DENSITY


## A stock theme for screen scale `k` and `density`: `base` itself at scale 1 in its own density;
## otherwise a copy with every font size, stylebox (padding, radii, borders, focus ring), constant
## and engine check and arrow icon times `k`, and the layout roles of `density` times `k` (and the
## theme's own multiplier). Cached per theme, scale and density; a theme that is not stock is
## returned as it is.
static func variant(base: Theme, k: float, density: String) -> Theme:
	if base == null or not is_stock(base):
		return base
	if is_equal_approx(k, 1.0) and density == density_of(base):
		return base
	var key := "%d|%.3f|%s" % [base.get_instance_id(), k, density]
	if _variants.has(key):
		return _variants[key]
	var t := base.duplicate() as Theme
	if base.has_default_font_size():
		t.default_font_size = roundi(base.default_font_size * k)
	for type in base.get_font_size_type_list():
		for n in base.get_font_size_list(type):
			t.set_font_size(n, type, maxi(1, roundi(base.get_font_size(n, type) * k)))
	for type in base.get_stylebox_type_list():
		for n in base.get_stylebox_list(type):
			t.set_stylebox(n, type, _scaled_box(base.get_stylebox(n, type), k))
	for type in base.get_constant_type_list():
		for n in base.get_constant_list(type):
			t.set_constant(n, type, roundi(base.get_constant(n, type) * k))
	t.remove_meta(&"pkey_icons")
	kit_icons(t, k)
	if not is_equal_approx(k, 1.0):
		_scale_icons(t, k)
		if not base.has_default_font_size() and base.has_meta(BASE_SIZE_META):
			# The neutral body text follows the game's size; shrunk, it is set here.
			for type in BODY_TYPES:
				if not t.has_font_size("font_size", type):
					t.set_font_size("font_size", type, maxi(1, roundi(int(base.get_meta(BASE_SIZE_META)) * k)))
	# The type floor: captions and chips never under TYPE_FLOOR px, and under TYPE_FLOOR_AT_SCALE_1
	# at scale 1 or more (the body size where that is smaller).
	var body: int = t.get_font_size("font_size", "Label") if t.has_font_size("font_size", "Label") else int(base.get_meta(BASE_SIZE_META, TYPE_BODY)) * 1
	var floor_px := TYPE_FLOOR if k < 1.0 else mini(TYPE_FLOOR_AT_SCALE_1, maxi(TYPE_FLOOR, body))
	for type in FLOOR_TYPES:
		if t.has_font_size("font_size", type):
			t.set_font_size("font_size", type, maxi(floor_px, t.get_font_size("font_size", type)))
	_apply_layout(t, float(base.get_meta(UNIT_META, 1.0)) * k, density, base.has_meta(BRAND_META))
	t.set_meta(VARIANT_OF_META, base)
	_variants[key] = t
	return t


## The body text size (scale 1) of the neutral or layered theme `t`: the game's font size.
static func neutral_body_size(t: Theme) -> int:
	var b := base_of(t)
	return int(b.get_meta(BASE_SIZE_META, TYPE_BODY)) if b != null else TYPE_BODY


## The stock theme `t` was made from by `variant()` (`t` itself when it is not a variant).
static func base_of(t: Theme) -> Theme:
	return t.get_meta(VARIANT_OF_META) as Theme if t != null and t.has_meta(VARIANT_OF_META) else t


## `b` with its padding, corner radii, borders, expand margins and shadow times `k`.
static func _scaled_box(b: StyleBox, k: float) -> StyleBox:
	if b == null or is_equal_approx(k, 1.0):
		return b
	var s := b.duplicate() as StyleBox
	for side in [SIDE_LEFT, SIDE_TOP, SIDE_RIGHT, SIDE_BOTTOM]:
		var m := b.get_content_margin(side)
		if m > 0.0:
			s.set_content_margin(side, roundf(m * k))
	if s is StyleBoxFlat:
		var f := s as StyleBoxFlat
		for side in [SIDE_LEFT, SIDE_TOP, SIDE_RIGHT, SIDE_BOTTOM]:
			var w := f.get_border_width(side)
			if w > 0:
				f.set_border_width(side, maxi(1, roundi(w * k)))
			f.set_expand_margin(side, roundf(f.get_expand_margin(side) * k))
		for corner in [CORNER_TOP_LEFT, CORNER_TOP_RIGHT, CORNER_BOTTOM_RIGHT, CORNER_BOTTOM_LEFT]:
			var r := f.get_corner_radius(corner)
			if r < RADIUS_FULL:
				f.set_corner_radius(corner, roundi(r * k))
		f.shadow_size = roundi(f.shadow_size * k)
		f.shadow_offset = f.shadow_offset * k
	elif s is StyleBoxLine:
		var l := s as StyleBoxLine
		l.thickness = maxi(1, roundi(l.thickness * k))
		l.grow_begin *= k
		l.grow_end *= k
	return s


## The platform's Japanese, Chinese and Korean faces, the fallback the brand theme's Rubik takes
## for the scripts it lacks (the engine's own system fallback misses glyphs).
const CJK_FONTS := ["Hiragino Sans", "Hiragino Kaku Gothic ProN", "Yu Gothic UI", "Yu Gothic", "Meiryo", "Noto Sans CJK JP", "Noto Sans JP", "Source Han Sans JP", "PingFang SC", "Microsoft YaHei", "Noto Sans CJK SC", "Apple SD Gothic Neo", "Malgun Gothic", "Noto Sans CJK KR", "sans-serif"]
static var _cjk: SystemFont = null
static var _cjk_bold: SystemFont = null


## Give the brand theme's fonts the platform's CJK faces as their fallback (at run time; the
## bundled font files are unchanged): the regular face for the body, a 600-weight one for the bold
## faces (titles, sections, the primary action, the code), so Japanese titles do not render at
## body weight.
static func cjk_fallback(t: Theme) -> void:
	if t == null or t.has_meta(&"pkey_cjk"):
		return
	if _cjk == null:
		_cjk = SystemFont.new()
		_cjk.font_names = PackedStringArray(CJK_FONTS)
		_cjk_bold = SystemFont.new()
		_cjk_bold.font_names = PackedStringArray(CJK_FONTS)
		_cjk_bold.font_weight = 600
	var bold_fonts: Array = []
	for type in ["PKeyTitle", "PKeySection", "PKeyPrimary", "PKeyCode", "PKeyStrong"]:
		if t.has_font("font", type):
			bold_fonts.append(t.get_font("font", type))
	for f in bold_fonts:
		_set_fallback(f, _cjk_bold)
	if t.default_font != null and not bold_fonts.has(t.default_font):
		_set_fallback(t.default_font, _cjk)
	t.set_meta(&"pkey_cjk", true)


static func _set_fallback(f: Font, fallback: Font) -> void:
	var base: Font = (f as FontVariation).base_font if f is FontVariation else f
	if base is FontFile and (base as FontFile).fallbacks.is_empty():
		(base as FontFile).fallbacks = [fallback]


## The kit's own switch, check box, radio and drop-down chevron (PKeyKitIcons, the generated
## Godot kit icons), rasterised for screen scale `k` into `t`, in the colours of its
## ICON_PALETTE_META: the brand's accent track and white knob when on (never the dark ink knob,
## UI-KITS.md §1.5 rule 6), a game's text colour on a neutral theme. Done at run time, so the
## committed .tres files carry no bitmaps.
static func kit_icons(t: Theme, k: float) -> void:
	if t == null or not t.has_meta(ICON_PALETTE_META) or (t.has_meta(&"pkey_icons") and is_equal_approx(float(t.get_meta(&"pkey_icons")), k)):
		return
	var pal: Dictionary = t.get_meta(ICON_PALETTE_META)
	var on: Color = pal["on"]
	var knob: Color = pal["knob"]
	var off: Color = pal["off"]
	var ink: Color = pal["ink"]
	var muted: Color = pal["muted"]
	var on_ink: Color = pal.get("on_ink", knob)
	var sets := {
		"CheckButton": {
			"checked": ["toggle_on", knob, on, on], "unchecked": ["toggle_off", ink, off, off],
			"checked_disabled": ["toggle_on", muted, off, off], "unchecked_disabled": ["toggle_off", muted, off, off],
		},
		"CheckBox": {
			"checked": ["checkbox_checked", on_ink, on, on], "unchecked": ["checkbox_unchecked", off, off, off],
			"checked_disabled": ["checkbox_checked", muted, off, off], "unchecked_disabled": ["checkbox_unchecked", muted, muted, muted],
			"radio_checked": ["radio_checked", on_ink, on, on], "radio_unchecked": ["radio_unchecked", off, off, off],
			"radio_checked_disabled": ["radio_checked", muted, off, off], "radio_unchecked_disabled": ["radio_unchecked", muted, muted, muted],
		},
		"OptionButton": {"arrow": ["chevron_down", muted, muted, muted]},
	}
	for type in sets:
		for icon in sets[type]:
			var spec: Array = sets[type][icon]
			var tex := _kit_icon(spec[0], spec[1], spec[2], spec[3], k)
			if tex == null:
				continue
			t.set_icon(icon, type, tex)
			if type == "CheckButton":
				t.set_icon(icon + "_mirrored", type, tex)
	t.set_meta(&"pkey_icons", k)


## A status glyph (PKeyKitIcons: lock, cloud_off, warning) as a texture `px` logical pixels square
## at screen scale `k`, in `colour`.
static func glyph(name: String, colour: Color, px: float, k := 1.0) -> Texture2D:
	return _kit_icon(name, colour, colour, colour, px / 24.0 * k)


static func _kit_icon(name: String, fg: Color, bg: Color, track: Color, k: float) -> Texture2D:
	var key := "kit|%s|%s|%s|%s|%.3f" % [name, fg.to_html(), bg.to_html(), track.to_html(), k]
	if _icons.has(key):
		return _icons[key]
	var img := Image.new()
	var tex: Texture2D = null
	if img.load_svg_from_string(PKeyKitIcons.svg(name, fg, bg, track), k) == OK:
		tex = ImageTexture.create_from_image(img)
	_icons[key] = tex
	return tex


## The engine's check, toggle and arrow icons (the project theme's, else the engine's) at `k`
## times their size, into `t`, unless `t` sets its own.
static func _scale_icons(t: Theme, k: float) -> void:
	var project := ThemeDB.get_project_theme()
	var stock := ThemeDB.get_default_theme()
	for type in SCALED_ICON_TYPES:
		for icon in stock.get_icon_list(type):
			if t.has_icon(icon, type):
				continue
			var src: Texture2D = project.get_icon(icon, type) if project != null and project.has_icon(icon, type) else stock.get_icon(icon, type)
			var key := "%d|%.3f" % [src.get_instance_id() if src != null else 0, k]
			if not _icons.has(key):
				var tex: Texture2D = null
				var img := src.get_image() if src != null else null
				if img != null and not img.is_empty():
					img = img.duplicate() as Image
					if img.is_compressed():
						img.decompress()
					img.resize(maxi(1, roundi(img.get_width() * k)), maxi(1, roundi(img.get_height() * k)), Image.INTERPOLATE_LANCZOS)
					tex = ImageTexture.create_from_image(img)
				_icons[key] = tex
			if _icons[key] != null:
				t.set_icon(icon, type, _icons[key])


## A game's whole Theme (`ui_theme`) over the kit's neutral structure derived from it: the type
## hierarchy, the layout roles, the container gaps and the card padding in the game's own font
## size, text colour and panel, wherever `own` does not set them itself (the game's items win).
## Stock-marked, so the scenes keep following the options. Cached per theme.
static func layered(own: Theme) -> Theme:
	if own == null or is_stock(own):
		return own
	if _layered.has(own):
		return _layered[own]
	var project := ThemeDB.get_project_theme()
	var size := ThemeDB.fallback_font_size
	if own.has_default_font_size():
		size = own.default_font_size
	elif project != null and project.has_default_font_size():
		size = project.default_font_size
	var font: Font = own.default_font if own.has_default_font() else (project.default_font if project != null and project.has_default_font() else ThemeDB.fallback_font)
	var bold: FontVariation = null
	if font != null:
		bold = FontVariation.new()
		bold.base_font = font
		bold.variation_embolden = 0.6
	var text := own.get_color("font_color", "Label") if own.has_color("font_color", "Label") else _project_color("font_color", "Label")
	var panel := own.get_stylebox("panel", "PanelContainer") if own.has_stylebox("panel", "PanelContainer") else _project_stylebox("panel", "PanelContainer")
	var button := own.get_stylebox("normal", "Button") if own.has_stylebox("normal", "Button") else _project_stylebox("normal", "Button")
	var t := neutral_with(size, text, bold, panel, button)
	t.merge_with(own)
	t.set_meta(STOCK_META, true)
	t.set_meta(LAYERED_META, own)
	_layered[own] = t
	return t


# ── Helpers ──────────────────────────────────────────────────────────────────────────────

## The text colour for an integrator's accent fill: the page ink or white, whichever contrasts more.
static func _on(fill: Color) -> Color:
	var a: Color = PKeyBrand.Dark.TEXT_ON_ACCENT
	var b: Color = PKeyBrand.Light.TEXT_ON_ACCENT
	return a if _contrast(fill, a) >= _contrast(fill, b) else b


static func _contrast(x: Color, y: Color) -> float:
	var lx := x.srgb_to_linear().get_luminance()
	var ly := y.srgb_to_linear().get_luminance()
	return (maxf(lx, ly) + 0.05) / (minf(lx, ly) + 0.05)


static func _box(bg: Color, border: Color, width: int, radius: int, pad: int) -> StyleBoxFlat:
	var s := StyleBoxFlat.new()
	s.bg_color = bg
	s.border_color = border
	s.set_border_width_all(width)
	s.set_corner_radius_all(radius)
	s.set_content_margin_all(pad)
	return s


## The focus ring: no fill, `RING_WIDTH` px of `color`, `RING_OFFSET` px outside the control so
## the gap shows the surface behind it and the ring never hides the control's own border.
static func _ring(color: Color) -> StyleBoxFlat:
	var s := StyleBoxFlat.new()
	s.draw_center = false
	s.border_color = color
	s.set_border_width_all(RING_WIDTH)
	s.set_corner_radius_all(RADIUS_CONTROL + RING_OFFSET + RING_WIDTH)
	s.set_expand_margin_all(RING_OFFSET + RING_WIDTH)
	return s
