class_name PKeyUiTheme
extends RefCounted
## The UI kit's look. Two families:
##
## - **Neutral (the default).** No Polaris Key branding. The scenes take the game's own theme and
##   font, as the scene's place in the tree resolves them (a Theme on an ancestor, else the
##   project's `gui/theme/custom` and `gui/theme/custom_font`, else the engine's), and add only
##   what the kit needs on top: a type hierarchy (title, muted, code and chip sizes derived from
##   the project's font size), padded cards and a bold title face derived from the project's font.
## - **Polaris Key (opt-in).** The design system (`PKeyBrand`, generated by `pnpm gen brand`):
##   the kit's dark or light palette, the platform violet (or your accent), Rubik (bundled under
##   the SIL OFL 1.1), a 2 px violet focus ring with a 2 px gap, and the Pinned K above the gate
##   and boot screens.
##
## Choose with PKeyOptions (`configure()` applies them) or directly, before a scene enters the
## tree:
##
##   options.ui_branding = "polaris-key"        # or PKeyUiTheme.branding = BRANDING_POLARIS_KEY
##   options.ui_brand_scheme = "light"          # the brand's light theme
##   options.ui_accent = Color("#39d075")       # your accent in the brand theme
##   options.ui_theme = preload("res://my_theme.tres")   # your whole Theme, whatever branding
##   options.ui_powered_by = true               # the "Powered by Polaris Key" badge (off by default)
##
## A scene given a Theme of its own (in the inspector or in code) keeps it; only a scene still on
## the kit's stock theme follows these settings. PKeyBoot's `theme` option (a Theme a mounted pack
## provides) still applies after MOUNT.
##
## Committed resources (tools/gen_theme.gd writes them; the `brand` suite fails on drift):
## pkey_theme.tres (neutral, the one every scene file references, as built over the engine's
## default theme), pkey_brand_dark.tres and pkey_brand_light.tres.

const NEUTRAL_PATH := "res://addons/polaris_key/ui/theme/pkey_theme.tres"
const DARK_PATH := "res://addons/polaris_key/ui/theme/pkey_brand_dark.tres"
const LIGHT_PATH := "res://addons/polaris_key/ui/theme/pkey_brand_light.tres"
const REGULAR_PATH := "res://addons/polaris_key/ui/theme/fonts/rubik_regular.tres"
const BOLD_PATH := "res://addons/polaris_key/ui/theme/fonts/rubik_bold.tres"

## The bundled fonts' licence texts (SIL OFL 1.1 requires them to travel with the fonts), keyed by
## the font resources' path prefix under `fonts/`. They are `.txt` files, which an export preset
## leaves out unless its include filter names them, so PKeyExportPlugin adds each one to any
## export that carries a matching font resource (`font_licences`).
const FONT_LICENCES := {
	"res://addons/polaris_key/ui/theme/fonts/rubik_": [
		"res://addons/polaris_key/ui/theme/fonts/OFL.txt",
		"res://addons/polaris_key/ui/theme/fonts/FONT-NOTICE.txt",
	],
	"res://addons/polaris_key/ui/theme/fonts/jetbrains_mono_": [
		"res://addons/polaris_key/ui/theme/fonts/OFL-JetBrainsMono.txt",
	],
}


## The licence files that must ship beside the resource at `path`: empty unless it is one of the
## bundled fonts.
static func font_licences(path: String) -> Array:
	for prefix in FONT_LICENCES:
		if path.begins_with(prefix):
			return FONT_LICENCES[prefix]
	return []


## True when `path` is one of the bundled fonts' licence files.
static func is_font_licence(path: String) -> bool:
	for files in FONT_LICENCES.values():
		if files.has(path):
			return true
	return false

## `branding`: no Polaris Key branding; the game's theme and font (the default).
const BRANDING_NONE := "none"
## `branding`: the Polaris Key design system.
const BRANDING_POLARIS_KEY := "polaris-key"

## Meta on every theme this class builds, so a scene can tell the stock look from the game's own.
const STOCK_META := &"pkey_stock"

## Corner radii (BRAND.md §4.6): controls `md`, cards `lg`, chips `full`.
const RADIUS_CONTROL := 6
const RADIUS_CARD := 10
const RADIUS_FULL := 999
## The focus ring (BRAND.md §7.4): 2 px of `focus`, drawn 2 px outside the control.
const RING_WIDTH := 2
const RING_OFFSET := 2
## The Pinned K's displayed size above a card: the display cut, never the bit (BRAND.md §1.3).
const MARK_SIZE := 48
## The neutral error colour on a dark ground (light text): 5.7:1 on black.
const NEUTRAL_ERROR := Color("#e5534b")
## The neutral error colour on a light ground (dark text): 5.6:1 on white (#e5534b is ~3.7:1).
const NEUTRAL_ERROR_ON_LIGHT := Color("#c62828")

## The type variations every scene uses; a replacement Theme should style them.
const VARIATIONS := {
	"PKeyCard": "PanelContainer",
	"PKeyBanner": "PanelContainer",
	"PKeyTitle": "Label",
	"PKeyMuted": "Label",
	"PKeyCode": "Label",
	"PKeyError": "Label",
	"PKeyBadge": "Label",
	"PKeyPrimary": "Button",
}

## BRANDING_NONE (the default) or BRANDING_POLARIS_KEY.
static var branding := BRANDING_NONE:
	set(value):
		branding = value
		_cache = null
## The brand theme's scheme: "dark" (the default) or "light". Ignored without branding.
static var scheme := "dark":
	set(value):
		scheme = value
		_cache = null
## The brand theme's accent; alpha 0 (the default) is the platform violet.
static var accent := Color(0, 0, 0, 0):
	set(value):
		accent = value
		_cache = null
## A Theme that replaces the kit's in every scene still on the stock theme; null for none.
static var override: Theme = null
## Show the "Powered by Polaris Key" badge where the scenes offer it (gate, boot, settings).
static var powered_by := false

static var _cache: Theme = null
static var _textures := {}
static var _neutral_cache := {}


## Apply the UI options of a PKeyOptions (called by `PolarisKey.configure()`). An unknown
## `ui_branding` is neutral.
static func apply_options(opts: Resource) -> void:
	if opts == null:
		return
	branding = BRANDING_POLARIS_KEY if str(opts.get("ui_branding")) == BRANDING_POLARIS_KEY else BRANDING_NONE
	scheme = "light" if str(opts.get("ui_brand_scheme")) == "light" else "dark"
	accent = opts.get("ui_accent") if opts.get("ui_accent") is Color else Color(0, 0, 0, 0)
	override = opts.get("ui_theme") as Theme
	powered_by = opts.get("ui_powered_by") == true
	refresh_views()


## Re-render every kit view in the tree (deferred), so options applied after a scene was mounted
## take effect: PolarisKey.boot() shows its view before configuring from polaris_key.tres.
static func refresh_views() -> void:
	var tree := Engine.get_main_loop() as SceneTree
	if tree != null:
		tree.call_group_flags(SceneTree.GROUP_CALL_DEFERRED, &"pkey_ui_views", &"refresh_view")


## Back to the defaults: neutral, no override, no badge.
static func reset() -> void:
	branding = BRANDING_NONE
	scheme = "dark"
	accent = Color(0, 0, 0, 0)
	override = null
	powered_by = false


## True when the Polaris Key brand is on (and no override Theme replaces it).
static func branded() -> bool:
	return override == null and branding == BRANDING_POLARIS_KEY


## The theme a kit scene should use now: `override`, else the brand theme when branded, else the
## neutral theme built over the game's project theme.
static func current() -> Theme:
	if override != null:
		return override
	if _cache != null:
		return _cache
	if branding == BRANDING_POLARIS_KEY:
		if accent.a > 0.0:
			_cache = build(scheme != "light", accent)
		else:
			_cache = load(LIGHT_PATH if scheme == "light" else DARK_PATH) as Theme
	else:
		_cache = neutral()
	return _cache


## The theme for one scene: `current()`, except that the neutral theme is derived from what the
## scene's place in the tree resolves (an ancestor's Theme, else the project's), so a kit scene
## inside a game's own themed menu matches that menu.
static func for_view(view: Control) -> Theme:
	if override != null or branding == BRANDING_POLARIS_KEY or view == null:
		return current()
	var size := view.get_theme_default_font_size()
	var font := view.get_theme_default_font()
	var text := view.get_theme_color("font_color", "Label")
	var panel := view.get_theme_stylebox("panel", "PanelContainer")
	var key := "%d|%d|%s|%d" % [size, font.get_instance_id() if font != null else 0, text.to_html(), panel.get_instance_id() if panel != null else 0]
	if not _neutral_cache.has(key):
		var bold: Font = null
		if font != null:
			var v := FontVariation.new()
			v.base_font = font
			v.variation_embolden = 0.6
			bold = v
		_neutral_cache[key] = neutral_with(size, text, bold, panel)
	return _neutral_cache[key]


## True when `t` is one of the kit's stock themes (a scene still on the default look).
static func is_stock(t: Theme) -> bool:
	return t != null and t.has_meta(STOCK_META)


## Whether the look is on a dark ground (picks the dark or light mark and badge files): the brand
## scheme when branded, else whether `view`'s text (or the project's) is light.
static func is_dark(view: Control = null) -> bool:
	if branded():
		return scheme != "light"
	var text := view.get_theme_color("font_color", "Label") if view != null else _project_color("font_color", "Label")
	return text.get_luminance() > 0.5


# ── Neutral ──────────────────────────────────────────────────────────────────────────────

## The neutral theme over the game's project theme: its font size, text colour, panel and font.
static func neutral() -> Theme:
	var project := ThemeDB.get_project_theme()
	var base := ThemeDB.fallback_font_size
	if project != null and project.has_default_font_size():
		base = project.default_font_size
	var font: Font = ThemeDB.fallback_font
	if project != null and project.has_default_font():
		font = project.default_font
	var bold := FontVariation.new()
	bold.base_font = font
	bold.variation_embolden = 0.6
	return neutral_with(base, _project_color("font_color", "Label"), bold, _project_stylebox("panel", "PanelContainer"))


## The neutral theme from explicit inputs (`bold` null: titles keep the body face).
static func neutral_with(base_size: int, text: Color, bold: Font, panel: StyleBox) -> Theme:
	var t := Theme.new()
	t.set_meta(STOCK_META, true)
	for v in VARIATIONS:
		t.set_type_variation(v, VARIATIONS[v])
	var card := panel.duplicate() as StyleBox if panel != null else StyleBoxFlat.new()
	card.set_content_margin_all(roundi(base_size * 1.5))
	t.set_stylebox("panel", "PKeyCard", card)
	var strip := card.duplicate() as StyleBox
	strip.set_content_margin_all(roundi(base_size * 0.625))
	t.set_stylebox("panel", "PKeyBanner", strip)
	t.set_font_size("font_size", "PKeyTitle", roundi(base_size * 1.5))
	t.set_font_size("font_size", "PKeyCode", roundi(base_size * 2.25))
	t.set_font_size("font_size", "PKeyMuted", roundi(base_size * 0.875))
	t.set_font_size("font_size", "PKeyBadge", roundi(base_size * 0.8))
	var muted := text
	muted.a *= 0.72
	t.set_color("font_color", "PKeyMuted", muted)
	# Dark text means a light ground, which needs the darker red for 4.5:1.
	t.set_color("font_color", "PKeyError", NEUTRAL_ERROR if text.get_luminance() > 0.5 else NEUTRAL_ERROR_ON_LIGHT)
	t.set_color("font_color", "PKeyBadge", text)
	var tint := text
	tint.a = 0.1
	var edge := text
	edge.a = 0.35
	var chip := _box(tint, edge, 1, RADIUS_FULL, 3)
	chip.content_margin_left = roundi(base_size * 0.6)
	chip.content_margin_right = roundi(base_size * 0.6)
	t.set_stylebox("normal", "PKeyBadge", chip)
	if bold != null:
		t.set_font("font", "PKeyTitle", bold)
		t.set_font("font", "PKeyCode", bold)
		t.set_font("font", "PKeyPrimary", bold)
	t.set_color("dark", "PKeyQrRect", Color.BLACK)
	t.set_color("light", "PKeyQrRect", Color.WHITE)
	return t


## The committed neutral theme: built over the engine's default theme, without a derived bold
## face (a FontVariation of the engine's built-in font cannot be saved).
static func neutral_default() -> Theme:
	var d := ThemeDB.get_default_theme()
	return neutral_with(ThemeDB.fallback_font_size, d.get_color("font_color", "Label"), null, d.get_stylebox("panel", "PanelContainer"))


static func _project_color(item: StringName, type: StringName) -> Color:
	var project := ThemeDB.get_project_theme()
	if project != null and project.has_color(item, type):
		return project.get_color(item, type)
	return ThemeDB.get_default_theme().get_color(item, type)


static func _project_stylebox(item: StringName, type: StringName) -> StyleBox:
	var project := ThemeDB.get_project_theme()
	if project != null and project.has_stylebox(item, type):
		return project.get_stylebox(item, type)
	return ThemeDB.get_default_theme().get_stylebox(item, type)


# ── Polaris Key ──────────────────────────────────────────────────────────────────────────

## The brand theme with the bundled Rubik. `p_accent` (alpha 0: the platform violet) colours the
## primary button, the chips and the hover border; give it a colour with at least 3:1 against the
## theme's surfaces. `regular` / `bold` replace Rubik.
static func build(dark := true, p_accent := Color(0, 0, 0, 0), regular: Font = null, bold: Font = null) -> Theme:
	return build_with(dark, p_accent, regular if regular != null else load(REGULAR_PATH) as Font, bold if bold != null else load(BOLD_PATH) as Font)


## `build()` with exactly these fonts: null keeps the engine's default font for that role.
static func build_with(dark: bool, p_accent: Color, regular: Font, bold: Font) -> Theme:
	var p := palette(dark)
	if p_accent.a > 0.0:
		p["accent"] = p_accent
		p["accent_fg"] = p_accent
		p["accent_hover"] = p_accent.lightened(0.15) if dark else p_accent.darkened(0.15)
		p["accent_pressed"] = p_accent.darkened(0.2) if dark else p_accent.darkened(0.3)
		p["on_accent"] = _on(p_accent)
	var t := Theme.new()
	t.set_meta(STOCK_META, true)
	t.default_font_size = 18
	if regular != null:
		t.default_font = regular

	# Surfaces: the page ground, raised cards and banners.
	t.set_stylebox("panel", "PanelContainer", _box(p.page, p.page, 0, 0, 24))
	for v in VARIATIONS:
		t.set_type_variation(v, VARIATIONS[v])
	t.set_stylebox("panel", "PKeyCard", _box(p.raised, p.border, 1, RADIUS_CARD, 28))
	t.set_stylebox("panel", "PKeyBanner", _box(p.raised, p.border, 1, RADIUS_CARD, 10))

	# Text.
	t.set_color("font_color", "Label", p.text)
	t.set_font_size("font_size", "PKeyTitle", 28)
	t.set_color("font_color", "PKeyTitle", p.strong)
	t.set_color("font_color", "PKeyMuted", p.muted)
	t.set_font_size("font_size", "PKeyMuted", 16)
	t.set_font_size("font_size", "PKeyCode", 40)
	t.set_color("font_color", "PKeyCode", p.strong)
	t.set_color("font_color", "PKeyError", p.danger)
	if bold != null:
		t.set_font("font", "PKeyTitle", bold)
		t.set_font("font", "PKeyCode", bold)
	# The entitlement chip: the accent's text on its tint, never gold (BRAND.md §1.2).
	t.set_color("font_color", "PKeyBadge", p.accent_fg)
	t.set_font_size("font_size", "PKeyBadge", 14)
	var chip := _box(p.accent_subtle, p.accent, 1, RADIUS_FULL, 4)
	chip.content_margin_left = 10
	chip.content_margin_right = 10
	t.set_stylebox("normal", "PKeyBadge", chip)

	# Controls.
	var focus := _ring(p.focus)
	for type in ["Button", "CheckButton", "CheckBox", "OptionButton", "LineEdit", "TextEdit"]:
		t.set_stylebox("focus", type, focus)
	for type in ["Button", "OptionButton"]:
		t.set_stylebox("normal", type, _box(p.overlay, p.border_strong, 1, RADIUS_CONTROL, 10))
		t.set_stylebox("hover", type, _box(p.overlay, p.accent, 1, RADIUS_CONTROL, 10))
		t.set_stylebox("pressed", type, _box(p.sunken, p.accent, 1, RADIUS_CONTROL, 10))
		t.set_stylebox("disabled", type, _box(p.raised, p.border, 1, RADIUS_CONTROL, 10))
		t.set_color("font_color", type, p.text)
		t.set_color("font_hover_color", type, p.strong)
		t.set_color("font_focus_color", type, p.strong)
		t.set_color("font_pressed_color", type, p.strong)
		t.set_color("font_disabled_color", type, p.subtle)
	t.set_stylebox("normal", "PKeyPrimary", _box(p.accent, p.accent, 1, RADIUS_CONTROL, 10))
	t.set_stylebox("hover", "PKeyPrimary", _box(p.accent_hover, p.accent_hover, 1, RADIUS_CONTROL, 10))
	t.set_stylebox("pressed", "PKeyPrimary", _box(p.accent_pressed, p.accent_pressed, 1, RADIUS_CONTROL, 10))
	for c in ["font_color", "font_hover_color", "font_focus_color", "font_pressed_color"]:
		t.set_color(c, "PKeyPrimary", p.on_accent)
	for type in ["LineEdit", "TextEdit"]:
		t.set_stylebox("normal", type, _box(p.sunken, p.border_strong, 1, RADIUS_CONTROL, 10))
		t.set_stylebox("read_only", type, _box(p.raised, p.border, 1, RADIUS_CONTROL, 10))
		t.set_color("font_color", type, p.text)
		t.set_color("font_placeholder_color", type, p.subtle)
		t.set_color("caret_color", type, p.focus)
		t.set_color("selection_color", type, p.accent_subtle)
	for type in ["CheckButton", "CheckBox"]:
		t.set_color("font_color", type, p.text)
		t.set_color("font_hover_color", type, p.strong)
		t.set_color("font_focus_color", type, p.strong)
		t.set_color("font_pressed_color", type, p.text)
		t.set_color("font_disabled_color", type, p.subtle)
	# OptionButton's list.
	t.set_stylebox("panel", "PopupMenu", _box(p.overlay, p.border_strong, 1, RADIUS_CONTROL, 6))
	t.set_stylebox("hover", "PopupMenu", _box(p.accent_subtle, p.accent_subtle, 0, RADIUS_CONTROL, 4))
	t.set_color("font_color", "PopupMenu", p.text)
	t.set_color("font_hover_color", "PopupMenu", p.strong)
	t.set_color("font_disabled_color", "PopupMenu", p.subtle)
	# Progress: neutral, never the mark (BRAND.md §7.5).
	t.set_stylebox("background", "ProgressBar", _box(p.sunken, p.border, 1, RADIUS_FULL, 0))
	t.set_stylebox("fill", "ProgressBar", _box(p.subtle, p.subtle, 0, RADIUS_FULL, 0))
	t.set_color("font_color", "ProgressBar", p.text)
	# A QR code stays black on white whatever the theme: scanners need the contrast.
	t.set_color("dark", "PKeyQrRect", Color.BLACK)
	t.set_color("light", "PKeyQrRect", Color.WHITE)
	return t


## The semantic colours the brand theme uses, for one theme, from PKeyBrand.
static func palette(dark: bool) -> Dictionary:
	if dark:
		return {
			"page": PKeyBrand.Dark.SURFACE_PAGE, "raised": PKeyBrand.Dark.SURFACE_RAISED,
			"overlay": PKeyBrand.Dark.SURFACE_OVERLAY, "sunken": PKeyBrand.Dark.SURFACE_SUNKEN,
			"strong": PKeyBrand.Dark.TEXT_STRONG, "text": PKeyBrand.Dark.TEXT_DEFAULT,
			"muted": PKeyBrand.Dark.TEXT_MUTED, "subtle": PKeyBrand.Dark.TEXT_SUBTLE,
			"border": PKeyBrand.Dark.BORDER_SUBTLE, "border_strong": PKeyBrand.Dark.BORDER_STRONG,
			"focus": PKeyBrand.Dark.FOCUS, "danger": PKeyBrand.Dark.DANGER,
			"accent": PKeyBrand.Dark.SERVICE_CORE, "accent_fg": PKeyBrand.Dark.SERVICE_CORE_FG,
			"accent_subtle": PKeyBrand.Dark.SERVICE_CORE_SUBTLE, "on_accent": PKeyBrand.Dark.SERVICE_CORE_ON,
			"accent_hover": PKeyBrand.Dark.SERVICE_CORE.lightened(0.15),
			"accent_pressed": PKeyBrand.Dark.SERVICE_CORE.darkened(0.2),
		}
	return {
		"page": PKeyBrand.Light.SURFACE_PAGE, "raised": PKeyBrand.Light.SURFACE_RAISED,
		"overlay": PKeyBrand.Light.SURFACE_OVERLAY, "sunken": PKeyBrand.Light.SURFACE_SUNKEN,
		"strong": PKeyBrand.Light.TEXT_STRONG, "text": PKeyBrand.Light.TEXT_DEFAULT,
		"muted": PKeyBrand.Light.TEXT_MUTED, "subtle": PKeyBrand.Light.TEXT_SUBTLE,
		"border": PKeyBrand.Light.BORDER_SUBTLE, "border_strong": PKeyBrand.Light.BORDER_STRONG,
		"focus": PKeyBrand.Light.FOCUS, "danger": PKeyBrand.Light.DANGER,
		"accent": PKeyBrand.Light.SERVICE_CORE, "accent_fg": PKeyBrand.Light.SERVICE_CORE_FG,
		"accent_subtle": PKeyBrand.Light.SERVICE_CORE_SUBTLE, "on_accent": PKeyBrand.Light.SERVICE_CORE_ON,
		"accent_hover": PKeyBrand.Light.SERVICE_CORE.darkened(0.15),
		"accent_pressed": PKeyBrand.Light.SERVICE_CORE.darkened(0.3),
	}


# ── Marks ────────────────────────────────────────────────────────────────────────────────

## The Pinned K (display cut, no terminal bit) for a dark or light ground, rasterised for `px`
## logical pixels at 2x. Null when the engine cannot rasterise SVG.
static func mark_texture(dark: bool, px := MARK_SIZE) -> Texture2D:
	return _svg("mark-%s-%d" % [dark, px], PKeyBrandMarks.PINNED_K_DARK if dark else PKeyBrandMarks.PINNED_K_LIGHT, 2.0 * px / 96.0)


## The compact "Powered by Polaris Key" badge (the kit's transparent treatment) for a dark or
## light ground, rasterised at 2x its minimum. Show it at powered_by_size("compact") or larger.
static func powered_by_texture(dark: bool) -> Texture2D:
	return _svg("powered-%s" % dark, PKeyBrandMarks.POWERED_BY_COMPACT_DARK if dark else PKeyBrandMarks.POWERED_BY_COMPACT_LIGHT, 2.0 * PKeyBrand.BADGE_MIN_COMPACT.x / PKeyBrandMarks.POWERED_BY_COMPACT_WIDTH)


static func _svg(key: String, svg: String, scale: float) -> Texture2D:
	if _textures.has(key):
		return _textures[key]
	var img := Image.new()
	var tex: Texture2D = null
	if img.load_svg_from_string(svg, scale) == OK:
		tex = ImageTexture.create_from_image(img)
	_textures[key] = tex
	return tex


## The size a "Powered by Polaris Key" badge is shown at: `requested`, raised to the kit minimum
## for its layout ("compact" for app UI, "horizontal" for credits, "stacked" for square spots),
## keeping the badge's proportions. Never crop the badge or show it smaller (BRAND.md §1.5).
static func powered_by_size(layout: String, requested := Vector2.ZERO) -> Vector2:
	var minimum: Vector2 = {
		"horizontal": Vector2(PKeyBrand.BADGE_MIN_HORIZONTAL),
		"stacked": Vector2(PKeyBrand.BADGE_MIN_STACKED),
	}.get(layout, Vector2(PKeyBrand.BADGE_MIN_COMPACT))
	var k := maxf(1.0, maxf(requested.x / minimum.x, requested.y / minimum.y))
	return minimum * k


# ── Helpers ──────────────────────────────────────────────────────────────────────────────

## The text colour for an integrator's accent fill: the page ink or white, whichever contrasts more.
static func _on(fill: Color) -> Color:
	var a: Color = PKeyBrand.Dark.TEXT_ON_ACCENT
	var b: Color = PKeyBrand.Light.TEXT_ON_ACCENT
	return a if _contrast(fill, a) >= _contrast(fill, b) else b


static func _contrast(x: Color, y: Color) -> float:
	var lx := x.srgb_to_linear().get_luminance()
	var ly := y.srgb_to_linear().get_luminance()
	return (maxf(lx, ly) + 0.05) / (minf(lx, ly) + 0.05)


static func _box(bg: Color, border: Color, width: int, radius: int, pad: int) -> StyleBoxFlat:
	var s := StyleBoxFlat.new()
	s.bg_color = bg
	s.border_color = border
	s.set_border_width_all(width)
	s.set_corner_radius_all(radius)
	s.set_content_margin_all(pad)
	return s


## The focus ring: no fill, `RING_WIDTH` px of `color`, `RING_OFFSET` px outside the control so
## the gap shows the surface behind it and the ring never hides the control's own border.
static func _ring(color: Color) -> StyleBoxFlat:
	var s := StyleBoxFlat.new()
	s.draw_center = false
	s.border_color = color
	s.set_border_width_all(RING_WIDTH)
	s.set_corner_radius_all(RADIUS_CONTROL + RING_OFFSET + RING_WIDTH)
	s.set_expand_margin_all(RING_OFFSET + RING_WIDTH)
	return s
