"""Regenerate res://tests/qr/fixtures.json from a reference encoder (Nayuki's qrcodegen, pinned).

    uv run --with qrcodegen==1.8.0 python sdks/godot/tests/qr/gen_fixtures.py

Every case is byte mode, error-correction level M. Cases without `forcedMask` let the reference
choose the mask (the Godot encoder must reach the same symbol on its own, including the mask its
penalty scoring picks); `forcedVersion` / `forcedMask` pin the version floor and the mask, so
every mask and the version range's edges are covered. The committed JSON is the fixture; this
script is how it was made. qrcodegen is a development-time reference only: nothing in the addon
depends on it.

Why not segno: segno 1.6.6 appends a whole 0x00 codeword of "padding bits" when the bit stream
already ends on a codeword boundary (ISO/IEC 18004 §7.4.10 adds padding bits only when it does
not), which byte mode always does after the terminator. Its symbols decode, but they are not the
standard's, so every byte-mode symbol with pad codewords differs from a conforming encoder's.
"""

import json
import pathlib

from qrcodegen import QrCode, QrSegment

REFERENCE = "qrcodegen 1.8.0"

URLS = [
    "https://key.plrs.im/djdl/identity/auth/device?user_code=WDJB-MJHT",
    "https://key.plrs.im/djdl/identity/auth/device?user_code=VZBV-DJKF",
    "https://key.plrs.im/diceroll/identity/auth/device?user_code=BCDF-GHJK",
    "https://key.plrs.im/a/identity/auth/device",
    "HTTPS://K.EX/D?U=XXXX",
    "https://key.plrs.im/a-very-long-product-slug-for-testing/identity/auth/device?user_code=QRST-VWXZ&x=1",
    # Exactly 120 characters, the brief's upper bound.
    ("https://key.plrs.im/longer-product-name/identity/auth/device?user_code=MNPQ-RSTV&ref="
     + "q" * 120)[:120],
]


def case(text, version=None, mask=None):
    seg = QrSegment.make_bytes(text.encode("utf-8"))
    q = QrCode.encode_segments([seg], QrCode.Ecc.MEDIUM, version or 1, 10, -1 if mask is None else mask, False)
    assert q.get_error_correction_level() == QrCode.Ecc.MEDIUM
    n = q.get_size()
    rows = ["".join("1" if q.get_module(x, y) else "0" for x in range(n)) for y in range(n)]
    return {
        "text": text,
        "bytes": len(text.encode("utf-8")),
        "forcedVersion": version,
        "forcedMask": mask,
        "version": q.get_version(),
        "mask": q.get_mask(),
        "rows": rows,
    }


def main():
    cases = [case(u) for u in URLS]
    # Every mask on one URL, and the version range's edges.
    cases += [case(URLS[0], mask=m) for m in range(8)]
    cases += [case("HTTPS://K.EX/D", version=1)]  # 14 bytes, the most version 1 holds
    cases += [case(URLS[0], version=7)]  # version information blocks
    cases += [case(URLS[1], version=10)]  # the largest version, 16-bit count
    cases += [case("x" * 213)]  # the most version 10 holds at level M
    out = {
        "$comment": "GENERATED by sdks/godot/tests/qr/gen_fixtures.py from "
        + REFERENCE
        + " (byte mode, level M). Do not edit; regenerate.",
        "reference": REFERENCE,
        "cases": cases,
    }
    path = pathlib.Path(__file__).with_name("fixtures.json")
    path.write_text(json.dumps(out, indent=1) + "\n")
    print(f"wrote {path} ({len(cases)} cases)")


if __name__ == "__main__":
    main()
