// GENERATED by `pkey sdk --lang swift --write` from
// https://key.plrs.im/acme/.well-known/polaris.json. Do not edit: run the command again to refresh.
// The trust pins came from discovery; compare each fingerprint with the console before
// you ship (pkey sdk prints them). Release keys match release.releaseKeyFingerprints.

import PolarisKey

/// Polaris Key configuration for acme:
///
///     let client = try PolarisKeyClient(options: PolarisConfig.clientOptions(version: appVersion))
public enum PolarisConfig {
    public static let productSlug = "acme"
    public static let baseUrl = "https://key.plrs.im"
    public static let pinnedKeys: TrustSet = [
        "pkey-test-prod-2026": "kDJF6Deuexo91hFZ9TAPr2SmjUEuTXdia67UogTEpkI",
    ]
    /// For `UpdateClientOptions(pinnedReleaseKeys:)` (PolarisKeyUpdate, PolarisKeyPacks).
    public static let pinnedReleaseKeys: TrustSet = [
        "acme-release-2026": "Z6FCkd1K7Om4lxUk4og_J0m73saH4BrrLk8igXzwcJM",
    ]
    public static let expectedServices: [ServiceSlug] = [.license, .config, .release, .update]

    /// Every option the client needs; `version` is the app's own.
    public static func clientOptions(version: String, channel: String? = nil) -> PolarisKeyClientOptions {
        PolarisKeyClientOptions(
            productSlug: productSlug, baseUrl: baseUrl, version: version, channel: channel,
            pinnedKeys: pinnedKeys, expectedServices: expectedServices)
    }
}
