// GENERATED FILE — do not edit by hand.
//
// Written by `pnpm gen:constants` (tools/gen-sdk-constants.ts) from conformance/parity/
// copy.en.json, checked against errors.json and enums.json (licenseStatus, activationResult).
// `pnpm gen:constants -- --check` fails the green gate on any difference. To change a string,
// edit copy.en.json and regenerate.
// The core copy (core.copy): a title and message per error code, gate status (licenseStatus) and activation result (activationResult). A code missing from COPY_CODES shows COPY_FALLBACK with {code} filled in, never the raw body.

/// One piece of core copy.
public struct CopyEntry: Sendable, Equatable {
    public let title: String
    public let message: String

    public init(title: String, message: String) {
        self.title = title
        self.message = message
    }
}

public let COPY_VERSION = 1
public let COPY_LOCALE = "en"
/// The only placeholders a copy string may hold, each written `{name}`.
public let COPY_PLACEHOLDERS: [String] = ["code", "detail", "limit", "deviceCount", "retryAfterSeconds", "product"]
/// Shown for a code this table does not know, with {code} filled in.
public let COPY_FALLBACK = CopyEntry(title: "Something went wrong", message: "Something went wrong ({code}). Try again.")

/// Per error code (errors.json order).
public let COPY_CODES: [String: CopyEntry] = [
    "unauthorized": CopyEntry(title: "Not signed in", message: "This device isn't signed in, or its license is no longer valid. Sign in or activate again."),
    "not_found": CopyEntry(title: "Not found", message: "That wasn't found. It may have been removed."),
    "bad_request": CopyEntry(title: "Request refused", message: "The request wasn't valid. Update the app, then try again."),
    "forbidden": CopyEntry(title: "Not allowed", message: "You don't have permission to do that."),
    "attestation_required": CopyEntry(title: "Device check needed", message: "This needs a verified device. Let the app check this device, then try again."),
    "attestation_rejected": CopyEntry(title: "Device check failed", message: "This device couldn't be verified. Try again."),
    "attestation_unavailable": CopyEntry(title: "Device check unavailable", message: "Device verification isn't available for this app right now. Try again in a few minutes."),
    "rate_limited": CopyEntry(title: "Too many attempts", message: "Too many attempts. Wait a moment and try again."),
    "body_too_large": CopyEntry(title: "Too large", message: "That is too large to send."),
    "method_not_allowed": CopyEntry(title: "Request refused", message: "The request wasn't valid. Update the app, then try again."),
    "misconfigured": CopyEntry(title: "Service not set up", message: "This service isn't set up correctly. Contact the developer."),
    "registration_closed": CopyEntry(title: "Registration closed", message: "New devices can't register right now. Activate with a license key or sign in."),
    "value_not_representable": CopyEntry(title: "Value not accepted", message: "A value couldn't be saved. Change it and try again."),
    "document_not_representable": CopyEntry(title: "Service problem", message: "The service couldn't prepare your settings. Contact the developer."),
    "device_limit": CopyEntry(title: "Device limit reached", message: "This license is already on all its devices. Replace a device to use it here."),
    "license_disabled": CopyEntry(title: "License disabled", message: "This license has been disabled. Contact the developer."),
    "license_expired": CopyEntry(title: "License expired", message: "This license has expired. Renew it to continue."),
    "not_entitled": CopyEntry(title: "Not included", message: "Your license doesn't include this."),
    "version_blocked": CopyEntry(title: "Update required", message: "This version can't be used with your license. Update the app to continue."),
    "channel_not_allowed": CopyEntry(title: "Channel not included", message: "Your license doesn't include this release channel."),
    "hardware_mismatch": CopyEntry(title: "Device changed", message: "This device's hardware changed. Activate again to use your license here."),
    "fingerprint_required": CopyEntry(title: "Device check failed", message: "This license needs a hardware fingerprint, which couldn't be read on this device."),
    "enroll_disabled": CopyEntry(title: "No free license", message: "This app doesn't offer a free license. Enter a license key or sign in."),
    "enroll_claimed": CopyEntry(title: "Sign in to continue", message: "This device's free license belongs to an account now. Sign in to use it."),
    "enroll_failed": CopyEntry(title: "Couldn't get a free license", message: "A free license couldn't be issued. Try again in a few minutes."),
    "managed_by_admin": CopyEntry(title: "Set by your organization", message: "This setting is managed by your organization and can't be changed here."),
    "catalog_unavailable": CopyEntry(title: "Settings unavailable", message: "Settings can't be loaded right now. Try again in a few minutes."),
    "license_unusable": CopyEntry(title: "License no longer valid", message: "Your license is no longer valid, so settings can't be loaded. Sign in or activate again."),
    "disabled": CopyEntry(title: "Sign-in unavailable", message: "Sign-in isn't turned on for this app."),
    "oidc_error": CopyEntry(title: "Sign-in failed", message: "Sign-in didn't finish. Try again."),
    "unavailable": CopyEntry(title: "Sign-in unavailable", message: "Sign-in isn't available right now. Try again in a few minutes."),
    "auth_method_disabled": CopyEntry(title: "Sign-in method unavailable", message: "That sign-in method is turned off. Choose another one."),
    "email_not_configured": CopyEntry(title: "Email sign-in unavailable", message: "Email sign-in isn't available right now. Choose another sign-in method."),
    "license_owned": CopyEntry(title: "License in another account", message: "This {product} license is already in another Polaris Key account. A license never moves by its key."),
    "email_mismatch": CopyEntry(title: "Email not verified", message: "This license belongs to an email address your account hasn't verified. Add and verify that email, then try again."),
    "link_conflict": CopyEntry(title: "Already linked", message: "That sign-in method belongs to another Polaris Key account. Sign in to that account, or join the two accounts."),
    "last_link": CopyEntry(title: "Can't remove", message: "This is your account's only sign-in method. Add another one before removing it."),
    "step_up_required": CopyEntry(title: "Confirm it's you", message: "For your security, sign in again to continue."),
    "not_eligible": CopyEntry(title: "Offer unavailable", message: "This offer isn't available to your account anymore. Refresh and try again."),
    "download_auth_required": CopyEntry(title: "Sign in to download", message: "Sign in or activate a license to download this."),
    "delivery_gate_missing": CopyEntry(title: "Download unavailable", message: "This download isn't set up yet. Contact the developer."),
    "upstream_rate_limited": CopyEntry(title: "Download busy", message: "Downloads are busy right now. Try again in a few minutes."),
    "server_misconfigured": CopyEntry(title: "Service not set up", message: "This service isn't set up correctly. Contact the developer."),
    "internal_error": CopyEntry(title: "Download failed", message: "The download server had a problem. Try again in a few minutes."),
    "release_record_rejected": CopyEntry(title: "Release refused", message: "The release wasn't published because a check failed. The publish log names the check."),
    "release_tag_is_pack_release": CopyEntry(title: "Release skipped", message: "A release was skipped because its tag matches a content pack release. Rename the tag."),
    "asset_unreachable": CopyEntry(title: "Image not updated", message: "An image could not be fetched from its source. The previous copy is still shown, and it will be retried automatically."),
    "feed_not_composable": CopyEntry(title: "Update check unavailable", message: "Updates can't be checked right now. Try again in a few minutes."),
    "service-unavailable": CopyEntry(title: "Not available", message: "This app doesn't use this service."),
    "service-disabled": CopyEntry(title: "Not available", message: "This service is turned off for this app."),
    "local-only": CopyEntry(title: "Offline mode", message: "This app is running offline, so it didn't connect."),
    "insecure-base-url": CopyEntry(title: "Insecure connection", message: "The app refused an insecure connection. Contact the developer."),
    "bundle-jws-rejected": CopyEntry(title: "Activation file not valid", message: "The activation file's signature isn't valid."),
    "bundle-claims-rejected": CopyEntry(title: "Activation file not valid", message: "The activation file is for another product or device, or it has expired."),
    "bundle-trust-rejected": CopyEntry(title: "Activation file not trusted", message: "The activation file is signed by a key this app doesn't trust."),
    "inner-doc-rejected": CopyEntry(title: "Activation file not valid", message: "The license inside the activation file isn't valid."),
    "bundle": CopyEntry(title: "Activation file not valid", message: "The activation file couldn't be read."),
    "transport": CopyEntry(title: "Connection problem", message: "Check your connection and try again."),
    "network": CopyEntry(title: "Can't connect", message: "Can't reach Polaris Key. Check your connection and try again."),
    "refresh-failed": CopyEntry(title: "Couldn't refresh", message: "Your license and settings couldn't be refreshed. Check your connection and try again."),
    "sync-failed": CopyEntry(title: "Couldn't check your license", message: "Your license couldn't be checked, so the app can't start. Check your connection and try again."),
    "fetch-failed": CopyEntry(title: "Content missing", message: "Required content couldn't be downloaded, so the app can't start. Check your connection and try again."),
    "bridge-missing": CopyEntry(title: "App problem", message: "The app's licensing bridge is missing. Reinstall the app or contact the developer."),
    "unknown": CopyEntry(title: "Something went wrong", message: "Something went wrong. Try again."),
    "release-refused": CopyEntry(title: "Not included", message: "Your license doesn't include this release."),
    "bundle-rejected": CopyEntry(title: "Activation file not valid", message: "The activation file was refused."),
    "bundle-import-unsupported": CopyEntry(title: "Not available here", message: "Offline activation isn't available here."),
    "report-unsupported": CopyEntry(title: "Not available here", message: "Device reports aren't available here."),
    "device-management-unsupported": CopyEntry(title: "Not available here", message: "Devices can't be managed from here. Manage them in your account."),
    "device_list_failed": CopyEntry(title: "Couldn't load devices", message: "Your devices couldn't be loaded. Check your connection and try again."),
    "device_rename_failed": CopyEntry(title: "Couldn't rename", message: "The device couldn't be renamed. Try again."),
    "device_deauthorize_failed": CopyEntry(title: "Couldn't remove device", message: "The device couldn't be removed. Try again."),
    "key-entry-unsupported": CopyEntry(title: "Not available here", message: "License keys can't be entered here. Sign in instead."),
    "sign-in-failed": CopyEntry(title: "Sign-in failed", message: "Sign-in didn't finish. Try again."),
    "sign-out-failed": CopyEntry(title: "Sign-out failed", message: "Sign-out didn't finish. Try again."),
    "bad_response": CopyEntry(title: "Unexpected answer", message: "The service sent an answer the app couldn't use. Try again."),
    "network-error": CopyEntry(title: "Can't connect", message: "Can't reach Polaris Key. Check your connection and try again."),
    "server-error": CopyEntry(title: "Service problem", message: "The service had a problem. Try again in a few minutes."),
    "cancelled": CopyEntry(title: "Sign-in cancelled", message: "Sign-in was cancelled."),
    "sign-in-expired": CopyEntry(title: "Code expired", message: "The code expired before sign-in finished. Start again."),
    "sign-in-denied": CopyEntry(title: "Sign-in declined", message: "Sign-in was declined. Start again."),
    "sign-in-unavailable": CopyEntry(title: "Sign-in unavailable", message: "Sign-in isn't available right now. Try again in a few minutes."),
    "invalid-options": CopyEntry(title: "App not set up", message: "The app's licensing isn't set up correctly. Contact the developer."),
    "not-configured": CopyEntry(title: "App not set up", message: "The app's licensing isn't set up yet. Contact the developer."),
    "unsupported": CopyEntry(title: "Not available here", message: "This isn't available here."),
    "timeout": CopyEntry(title: "Timed out", message: "The service took too long to answer. Check your connection and try again."),
    "response-too-large": CopyEntry(title: "Unexpected answer", message: "The service sent an answer the app couldn't use. Try again."),
    "too-many-redirects": CopyEntry(title: "Connection problem", message: "The connection was redirected too many times. Try again."),
    "insecure-redirect": CopyEntry(title: "Insecure connection", message: "The app refused an insecure redirect."),
    "http-error": CopyEntry(title: "Service problem", message: "The service answered with an error. Try again."),
    "invalid-response": CopyEntry(title: "Unexpected answer", message: "The service sent an answer the app couldn't use. Try again."),
    "store-failed": CopyEntry(title: "Storage problem", message: "The app couldn't read or save its license on this device. Check that the app can write its data folder."),
    "platform-error": CopyEntry(title: "Platform problem", message: "The platform reported an error. Try again."),
    "no-token": CopyEntry(title: "Not activated", message: "This device isn't activated yet. Activate it or sign in."),
    "mint-unavailable": CopyEntry(title: "Not available", message: "This isn't available for this app."),
    "feed-rejected": CopyEntry(title: "Update check failed", message: "The update information couldn't be verified, so nothing was installed."),
    "feed-rollback": CopyEntry(title: "Update check failed", message: "The update information was older than what this device already has, so it was refused."),
    "record-rejected": CopyEntry(title: "Update not verified", message: "The update couldn't be verified, so it wasn't installed."),
    "record-mismatch": CopyEntry(title: "Update not verified", message: "The update didn't match what was published, so it wasn't installed."),
    "payload-mismatch": CopyEntry(title: "Download corrupted", message: "The update didn't download correctly, so it wasn't installed. Try again."),
    "swap-refused": CopyEntry(title: "Can't update here", message: "This installation can't update itself. Update it the way you installed it."),
    "swap-failed": CopyEntry(title: "Update not finished", message: "The update couldn't be applied. It will be tried again next launch."),
    "files-index-invalid": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "files-unsafe-path": CopyEntry(title: "Content refused", message: "Some content was refused because it contains an unsafe file path."),
    "files-duplicate-path": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "files-case-collision": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "files-path-conflict": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "files-layout-mismatch": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "content-stamp-invalid": CopyEntry(title: "App build problem", message: "This build's content information isn't valid. Reinstall the app or contact the developer."),
    "full-corrupt": CopyEntry(title: "Download corrupted", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "delta-artifact-mismatch": CopyEntry(title: "Download corrupted", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "delta-base-mismatch": CopyEntry(title: "Content changed", message: "Installed content changed on this device, so a full download is needed."),
    "delta-apply-failed": CopyEntry(title: "Update not applied", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "file-corrupt": CopyEntry(title: "Download corrupted", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "file-source-missing": CopyEntry(title: "Content missing", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "payload-hash-mismatch": CopyEntry(title: "Download corrupted", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-ref-mismatch": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-bad-length": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-bad-magic": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-unsupported-version": CopyEntry(title: "Content not supported", message: "This content needs a newer version of the app. Update the app."),
    "chunks-bad-record-size": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-bad-flags": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-reserved-nonzero": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-zero-length": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-bad-clen": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-bad-bundle-ref": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-bad-bundle-range": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-size-mismatch": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunks-payload-mismatch": CopyEntry(title: "Content not valid", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "chunk-bundle-truncated": CopyEntry(title: "Download interrupted", message: "A download was cut short. Check your connection and try again."),
    "chunk-corrupt": CopyEntry(title: "Download corrupted", message: "Some content couldn't be installed. It will be downloaded again next time."),
    "plan-transport-unsupported": CopyEntry(title: "Can't download here", message: "This content can't be downloaded on this platform."),
    "plan-insufficient-disk": CopyEntry(title: "Not enough space", message: "There isn't enough free space for this content. Free up some space and try again."),
    "plan-no-strategy": CopyEntry(title: "Can't install content", message: "This content can't be installed on this device."),
    "pack-no-variant": CopyEntry(title: "Content not available", message: "This content isn't available for this device."),
    "pack-type-unsupported": CopyEntry(title: "Content not supported", message: "This content needs a newer version of the app. Update the app."),
    "pack-type-check-failed": CopyEntry(title: "Content not valid", message: "Some content failed its check and wasn't installed."),
    "pack-not-pinned": CopyEntry(title: "Content not available", message: "This content isn't part of this version of the app."),
    "pack-not-entitled": CopyEntry(title: "Not included", message: "Your license doesn't include this content."),
    "pack-state-unreadable": CopyEntry(title: "Storage problem", message: "Installed content couldn't be read, so nothing new was installed. Restart the app."),
    "pck-directory-refused": CopyEntry(title: "Content refused", message: "Some content was refused because it contains files a content pack may not hold."),
    "pck-engine-mismatch": CopyEntry(title: "Content not supported", message: "This content needs a different version of the game. Update the game."),
    "pack-rolled-back": CopyEntry(title: "Content restored", message: "The last content update didn't start, so the previous version was restored."),
    "pack-revoked": CopyEntry(title: "Content withdrawn", message: "This content was withdrawn by its developer and can't be used."),
    "pack-not-data-only": CopyEntry(title: "Content refused", message: "Some content was refused because it contains files a data pack may not hold."),
    "marker-rejected": CopyEntry(title: "App build problem", message: "This build's built-in content isn't valid. Reinstall the app or contact the developer."),
]

/// Per licenseStatus.
public let COPY_GATE: [String: CopyEntry] = [
    "ok": CopyEntry(title: "License active", message: "Your license is active."),
    "grace": CopyEntry(title: "Offline grace", message: "The licensing service can't be reached. You can keep using the app until the grace period ends."),
    "expired": CopyEntry(title: "License expired", message: "Your license has expired. Connect to the internet or renew it to continue."),
    "revoked": CopyEntry(title: "Signed out", message: "This device was signed out. Sign in or activate again to continue."),
    "needs-activation": CopyEntry(title: "Activate", message: "Enter a license key or sign in to continue."),
    "version-too-old": CopyEntry(title: "Update required", message: "This version is no longer supported. Update the app to continue."),
    "version-too-new": CopyEntry(title: "Not available on this license", message: "This build is newer than your license allows."),
    "channel-not-entitled": CopyEntry(title: "Channel not included", message: "Your license doesn't include this release channel."),
    "not-applicable": CopyEntry(title: "No license needed", message: "This app doesn't need a license."),
]

/// Per activationResult.
public let COPY_ACTIVATION: [String: CopyEntry] = [
    "ok": CopyEntry(title: "Activated", message: "Your license is active on this device."),
    "device-limit": CopyEntry(title: "Device limit reached", message: "This license is already on all its devices. Replace a device to use it here."),
    "fingerprint-required": CopyEntry(title: "Device check failed", message: "This license needs a hardware fingerprint, which couldn't be read on this device."),
    "hardware-mismatch": CopyEntry(title: "Device changed", message: "This device's hardware changed. Activate again to use your license here."),
    "enroll-claimed": CopyEntry(title: "Sign in to continue", message: "This device's free license belongs to an account now. Sign in to use it."),
    "license-disabled": CopyEntry(title: "License disabled", message: "This license has been disabled. Contact the developer."),
    "license-expired": CopyEntry(title: "License expired", message: "This license has expired. Renew it to continue."),
    "attestation-required": CopyEntry(title: "Device check needed", message: "This license needs a verified device. Let the app check this device, then try again."),
    "rate-limited": CopyEntry(title: "Too many attempts", message: "Too many attempts. Wait a moment and try again."),
    "unauthorized": CopyEntry(title: "Key not accepted", message: "That license key wasn't accepted. Check it and try again."),
    "enroll-disabled": CopyEntry(title: "No free license", message: "This app doesn't offer a free license. Enter a license key or sign in."),
    "refused": CopyEntry(title: "Activation refused", message: "Activation was refused ({code})."),
    "error": CopyEntry(title: "Activation failed", message: "Activation didn't finish. Check your connection and try again."),
]
