// GENERATED by packages/worker/scripts/gen-storefront-ci.ts from
// packages/worker/src/core/storefront/ciPlane.ts and the CI-plane storefront adapters. DO NOT EDIT.
// Regenerate: pnpm gen:storefront-ci
// Freshness: pnpm gen:storefront-ci -- --check (and the worker suite's ciPlaneGenerated test)

import type { CiPlaneDeclaration } from "./types.js";

export const CI_PLANE: CiPlaneDeclaration = {
  stores: [
    {
      store: "itch",
      label: "itch.io",
      outletKinds: ["itch"],
      list: {
        tool: "butler",
        commands: {
          push: {
            argv: [
              "push",
              {
                param: "dir",
                pattern:
                  "(?!-)(?!.*(?:^|[\\\\/])\\.\\.(?:[\\\\/]|$))[A-Za-z0-9 ._/\\\\:+-]{1,512}",
              },
              {
                param: "target",
                pattern:
                  "[A-Za-z0-9_-]{1,64}/[A-Za-z0-9_-]{1,64}:(?:windows|linux|mac|osx|android)(?:-[a-z0-9]{1,32}){0,3}",
                identity: {
                  field: "target",
                  match: "prefix",
                  separator: ":",
                },
              },
              "--userversion",
              {
                param: "version",
                pattern: "[0-9A-Za-z][0-9A-Za-z.+_-]{0,63}",
              },
            ],
            confirm: "plain",
            why: "a build to one channel of the outlet's own game; the channel name tags its platform",
          },
        },
      },
      never: [
        ["login"],
        ["logout"],
        ["upgrade"],
        ["fetch", "vlad/dice:windows", "out"],
        ["push", "build", "vlad/dice:windows"],
        [
          "push",
          "build",
          "vlad/dice:windows",
          "--userversion",
          "1.0.0",
          "--fix-permissions",
        ],
      ],
      neverTokens: ["delete", "collection", "login", "logout", "fetch"],
    },
    {
      store: "snap",
      label: "Snap Store",
      outletKinds: ["snap"],
      list: {
        tool: "snapcraft",
        commands: {
          upload: {
            argv: [
              "upload",
              {
                param: "snap",
                pattern:
                  "(?!-)(?!.*(?:^|[\\\\/])\\.\\.(?:[\\\\/]|$))[A-Za-z0-9 ._/\\\\:+-]{1,512}\\.snap",
              },
              {
                param: "release",
                pattern:
                  "(?:[a-z0-9][a-z0-9.-]{0,63}/)?(?:stable|candidate|beta|edge)(?:/[a-z0-9][a-z0-9-]{0,63})?(?:,(?:[a-z0-9][a-z0-9.-]{0,63}/)?(?:stable|candidate|beta|edge)(?:/[a-z0-9][a-z0-9-]{0,63})?){0,7}",
                prefix: "--release=",
                identity: {
                  field: "channels",
                  match: "each",
                  separator: ",",
                },
              },
            ],
            confirm: "plain",
            why: "upload a revision and release it only to channels the outlet's identity declares",
          },
          "upload-metadata": {
            argv: [
              "upload-metadata",
              {
                param: "snap",
                pattern:
                  "(?!-)(?!.*(?:^|[\\\\/])\\.\\.(?:[\\\\/]|$))[A-Za-z0-9 ._/\\\\:+-]{1,512}\\.snap",
              },
            ],
            confirm: "plain",
            why: "the summary, description and icon the snap carries (written from the listing model by pkey storefront snap metadata)",
          },
        },
      },
      never: [
        ["close", "dice", "beta"],
        ["collaborate", "dice", "someone"],
        ["release", "dice", "12", "stable"],
        ["register", "dice"],
        ["promote", "dice", "--from-channel", "beta", "--to-channel", "stable"],
        ["set-default-track", "dice", "2.0"],
        [
          "export-login",
          "--snaps",
          "dice",
          "--acls",
          "package_manage",
          "creds.txt",
        ],
        ["upload", "dice_1.0_amd64.snap"],
        ["upload", "dice_1.0_amd64.snap", "--release=stable", "--force"],
      ],
      neverTokens: [
        "close",
        "collaborat",
        "package_manage",
        "register",
        "promote",
        "export-login",
        "progressive",
      ],
    },
    {
      store: "steam",
      label: "Steam",
      outletKinds: ["steam"],
      list: {
        tool: "steamcmd",
        commands: {
          "run-app-build": {
            argv: [
              "+login",
              {
                param: "account",
                pattern: "[A-Za-z0-9_]{1,64}",
              },
              "+run_app_build",
              {
                param: "script",
                pattern:
                  "(?!-)(?!.*(?:^|[\\\\/])\\.\\.(?:[\\\\/]|$))[A-Za-z0-9 ._/\\\\:+-]{1,512}\\.vdf",
              },
              "+quit",
            ],
            confirm: "plain",
            why: "a SteamPipe build; the script's setlive, if any, names a branch other than default and public (owner decision 5)",
            fileChecks: [
              {
                param: "script",
                check: "steam-vdf-setlive-named",
              },
            ],
          },
        },
      },
      never: [
        ["+login", "builder", "+app_set_config", "480", "+quit"],
        [
          "+login",
          "builder",
          "+run_app_build",
          "app.vdf",
          "+setlive",
          "public",
        ],
        ["+login", "builder", "+app_uninstall", "480", "+quit"],
        ["+login", "builder", "builder-password", "+run_app_build", "app.vdf"],
      ],
      neverTokens: ["delete", "setlive", "+app_set_config", "+app_uninstall"],
    },
    {
      store: "msstore",
      label: "Microsoft Store",
      outletKinds: ["ms-store"],
      list: {
        tool: "msstore",
        commands: {
          publish: {
            argv: [
              "publish",
              {
                param: "package",
                pattern:
                  "(?!-)(?!.*(?:^|[\\\\/])\\.\\.(?:[\\\\/]|$))[A-Za-z0-9 ._/\\\\:+-]{1,512}",
              },
              "--appId",
              {
                param: "productId",
                pattern: "[A-Za-z0-9]{12}",
                identity: {
                  field: "productId",
                  match: "equal",
                },
              },
            ],
            confirm: "plain",
            why: "a package submission from CI, never over a draft the Worker staged (A-18f): the CLI would replace it",
            unlessWorkerStaged: {
              opens: ["submission.create"],
              closes: ["submission.commit"],
            },
          },
        },
      },
      never: [
        ["submission", "delete", "9NBLGGH4R315"],
        ["submission", "rollout", "halt", "9NBLGGH4R315"],
        ["submission", "rollout", "finalize", "9NBLGGH4R315"],
        ["apps", "list"],
      ],
      neverTokens: ["delete", "rollout", "halt", "finalize"],
    },
    {
      store: "epic",
      label: "Epic Games Store",
      outletKinds: [],
      list: {
        tool: "BuildPatchTool",
        commands: {
          "upload-binary": {
            argv: [
              "-mode=UploadBinary",
              {
                param: "organization",
                pattern: "[A-Za-z0-9][A-Za-z0-9-]{0,63}",
                prefix: "-OrganizationId=",
              },
              {
                param: "product",
                pattern: "[A-Za-z0-9][A-Za-z0-9-]{0,63}",
                prefix: "-ProductId=",
              },
              {
                param: "artifact",
                pattern: "[A-Za-z0-9][A-Za-z0-9-]{0,63}",
                prefix: "-ArtifactId=",
              },
              {
                param: "client",
                pattern: "[A-Za-z0-9][A-Za-z0-9-]{0,63}",
                prefix: "-ClientId=",
              },
              {
                param: "secretEnv",
                pattern: "[A-Z_][A-Z0-9_]{0,63}",
                prefix: "-ClientSecretEnvVar=",
              },
              {
                param: "buildRoot",
                pattern:
                  "(?!-)(?!.*(?:^|[\\\\/])\\.\\.(?:[\\\\/]|$))[A-Za-z0-9 ._/\\\\:+-]{1,512}",
                prefix: "-BuildRoot=",
              },
              {
                param: "cloudDir",
                pattern:
                  "(?!-)(?!.*(?:^|[\\\\/])\\.\\.(?:[\\\\/]|$))[A-Za-z0-9 ._/\\\\:+-]{1,512}",
                prefix: "-CloudDir=",
              },
              {
                param: "buildVersion",
                pattern: "[0-9A-Za-z][0-9A-Za-z.+_-]{0,63}",
                prefix: "-BuildVersion=",
              },
              {
                param: "appLaunch",
                pattern:
                  "(?!-)(?!.*(?:^|[\\\\/])\\.\\.(?:[\\\\/]|$))[A-Za-z0-9 ._/\\\\:+-]{1,512}",
                prefix: "-AppLaunch=",
              },
              {
                param: "appArgs",
                pattern: "[A-Za-z0-9 ._=-]{0,256}",
                prefix: "-AppArgs=",
              },
            ],
            confirm: "plain",
            why: "upload a binary only; labelling it live stays in the Developer Portal, and the secret is read from an environment variable, never argv",
          },
        },
      },
      never: [
        ["-mode=DeleteBinary", "-BuildVersion=1.0.0"],
        ["-mode=UnlabelBinary", "-BuildVersion=1.0.0", "-Label=Live"],
        ["-mode=LabelBinary", "-BuildVersion=1.0.0", "-Label=Live"],
        ["-mode=UploadBinary", "-ClientSecret=hunter2"],
      ],
      neverTokens: ["deletebinary", "labelbinary", "-clientsecret="],
    },
  ],
  adapters: [
    {
      id: "itch",
      label: "itch.io",
      outletKinds: ["itch"],
      ciOps: {
        uploadBuild: ["push"],
      },
    },
    {
      id: "snap",
      label: "Snap Store",
      outletKinds: ["snap"],
      ciOps: {
        writeListingText: ["upload-metadata"],
        uploadBuild: ["upload"],
        release: ["upload"],
      },
    },
  ],
};
