// @polaris-key/client-core — the isomorphic client substrate shared by every JS Polaris Key SDK.
//
// WebCrypto only, zero Node APIs, no I/O: everything here is a pure function over bytes,
// claims, and clocks, so the identical implementation runs in @polaris-key/node, in @polaris-key/react's
// browser bundle, and in a Worker. Transport, storage, and keyrings belong to the hosts.
//
// Subpath exports mirror these modules one-for-one (`@polaris-key/client-core/gate`, …) for hosts
// that want a single concern without pulling the barrel.

export {
  CLOCK_SKEW_SECONDS,
  MAX_GRACE_SECONDS,
  NO_NON_WIRE_INTEGERS,
  REFRESH_MARGIN_SECONDS,
  isWireInteger,
} from "./claims.js";

export {
  compareVersions,
  parseVersion,
  type ParsedVersion,
} from "./version.js";

export {
  boundChannels,
  commitFeed,
  feedClaims,
  feedContent,
  feedFloor,
  reloadFeeds,
  verifyFeed,
  withFeedContent,
  type CommittedFeed,
  type FeedClaimsOptions,
  type FeedClaimsRefusal,
  type FeedFloor,
  type FeedRefusal,
  type ReloadedFeeds,
  type VerifyFeedOptions,
  type VerifyFeedResult,
} from "./feed.js";

export {
  coversPack,
  delegatedKid,
  delegationHashOf,
  delegationOf,
  recordRevoked,
  verifyDelegation,
  type DelegationBody,
  type RecordDelegation,
  type VerifiedDelegation,
  type VerifyDelegationOptions,
  type VerifyDelegationResult,
  newerRevocation,
  recordHash,
  releaseRecordClaims,
  reloadReleaseRecords,
  revocationOf,
  verifyReleaseRecord,
  verifyRevocation,
  type RevocationBody,
  type RevocationStep,
  type VerifiedRevocation,
  type VerifyRevocationOptions,
  type VerifyRevocationResult,
  type ReleaseRecordClaimsOptions,
  type ReleaseRecordPin,
  type ReleaseRecordStep,
  type VerifyReleaseRecordOptions,
  type VerifyReleaseRecordResult,
} from "./record.js";

export {
  checkPaths,
  contentClaims,
  frameWindow,
  holdsOf,
  isPackId,
  objectRef,
  packSetId,
  parseContentStamp,
  dataOnlyExtension,
  dataOnlyFileRefusal,
  dataOnlyPathRefusal,
  dataOnlyRefusal,
  dataOnlyTextRefusal,
  dataOnlyTreeSink,
  DATA_ONLY_SCRIPT_MARKERS,
  DATA_ONLY_TEXT_EXTENSIONS,
  type DataOnlyRefusalSeen,
  type DataOnlyRule,
  MAX_STORED_REVOCATIONS,
  stampHolds,
  type RevocationsDoc,
  type RevocationsSnapshot,
  type StoredRevocation,
  parseFilesIndex,
  treeDigest,
  variantKey,
  windowAllowed,
  windowLogMax,
  type CheckPathsResult,
  type ContentClaimsOptions,
  type FilesErrorCode,
  type FilesIndexRef,
  type PackSetEntry,
  type ParseContentStampResult,
  type ParseFilesIndexOptions,
  type ParseFilesIndexResult,
  type ZstdDecode,
  // P4-10: the chunk index (`pkey-chunks/1`).
  parseChunkIndex,
  parseChunkIndexBytes,
  type ChunkIndexErrorCode,
  type ChunkIndexRef,
  type ParseChunkIndexOptions,
  type ParseChunkIndexResult,
  type PlanChunkIndex,
  // P4-06: the appliers, planner, selection, marker, install state and pipeline.
  FILES_TREE_HANDLER,
  // P4-16: the v3 pack-type handlers.
  DataJsonHandler,
  L10nTableHandler,
  MlModelHandler,
  bcp47Canonical,
  parseL10nFile,
  type DataJsonHandlerOptions,
  type L10nMessage,
  type L10nTable,
  type L10nTableHandlerOptions,
  type MlModel,
  type MlModelHandlerOptions,
  type ModelDescriptor,
  type PackCheckRefusal,
  type PackPayloadAccess,
  type StagedPack,
  PACK_STATE_VERSION,
  PLAN_STRATEGIES,
  PackEngine,
  PackError,
  READ_CHUNK,
  abandonInstall,
  applyDelta,
  applyFile,
  applyFull,
  beginInstall,
  bootPackOptions,
  runBootFetch,
  applyChunk,
  chunkRangeFetch,
  chunkRuns,
  seedMap,
  type ApplyChunkOptions,
  type ApplyChunkPorts,
  type ChunkApplyErrorCode,
  type ChunkApplyFailure,
  type ChunkOutput,
  type ChunkRangeFetch,
  type ChunkRangeResponse,
  type ChunkRun,
  type ChunkSeed,
  type ChunkVerdict,
  type ChunkVerdictOk,
  checkpoint,
  commitInstall,
  confirmBoot,
  emptyPackState,
  gcRoots,
  hashSource,
  indexReadable,
  indexRebuildable,
  matchEmbedded,
  memoryPackStateStore,
  memoryPackStorage,
  memorySource,
  openObject,
  parsePackState,
  parsePatch,
  plan,
  planTarget,
  readAll,
  reloadPackState,
  rollbackInstall,
  selectVariant,
  serializePackState,
  sha256Of,
  sliceSource,
  usableCodec,
  variantUsable,
  verifyMarker,
  webCryptoSha256,
  withFeedDeltas,
  type ApplyCounters,
  type ApplyDeltaOptions,
  type ApplyErrorCode,
  type ApplyFailure,
  type ApplyPorts,
  type ApplyResult,
  type ApplyVerdict,
  type ByteSink,
  type ByteSource,
  type ChunkIndexStore,
  type ContainerVerdict,
  type EmbeddedBaseline,
  type EmbeddedPayload,
  type InstalledFile,
  type InstalledPayload,
  type JournalObject,
  type MarkerStep,
  type MemoryPackStorage,
  type MemoryPayload,
  type NativePayloadPort,
  type NativePayloadRequest,
  type NativePayloadResult,
  type ObjectFetch,
  type ObjectPort,
  type ObjectResponse,
  type PackEngineOptions,
  type PackEstimate,
  type PackGcRoots,
  type PackHandler,
  type PackInstall,
  type PackInstallReport,
  type PackJournal,
  type PackProgress,
  type PacksSnapshot,
  type PackStateDoc,
  type PackStateStore,
  type PackStateVerifier,
  type PackStorage,
  type PlanCandidate,
  type PlanCaps,
  type PlanDelta,
  type PlanError,
  type PlanInput,
  type PlanInstalled,
  type PlanResult,
  type PlanStrategy,
  type PlanTarget,
  type RecordFetch,
  type RunBootFetchOptions,
  type Sha256Hasher,
  type Sha256Port,
  type StagedObject,
  type TreeSink,
  type TreeVerdict,
  type VariantPrefs,
  type VerifyMarkerOptions,
  type VerifyMarkerResult,
  type ZstdPort,
  // P4-20: save compatibility (`isAvailable`, `packFor`).
  CONTENT_ID_PATTERN,
  MAX_PROVIDES,
  providesFacts,
  providesOf,
  verifiedPayloadOf,
  type PackProvider,
  type ProvidesFacts,
} from "./packs/index.js";

export {
  OUTLET_CAPABILITY_DEFAULTS,
  PLATFORM_NARROWING,
  SUBKIND_NARROWING,
  bootDecision,
  decideUpdate,
  effectiveCapabilities,
  feedTarget,
  isUndismissable,
  isValidHostOutlet,
  outletEntry,
  resolveUpdateOutlet,
  rolloutBucket,
  selectPackRows,
  type DetectedOutlet,
  type EffectiveCapabilitiesOptions,
  type HostOutlet,
  type OutletStamp,
  type ResolvedOutlet,
} from "./decide.js";

export {
  OUTLET_PLATFORM_DATA,
  OUTLET_SIGNALS,
  UNKNOWN_DETECTION,
  WEB_DETECTION_STAMP,
  detectOutlet,
  detectionStamp,
  type DetectionStamp,
  type OutletIds,
  type OutletSignalSpec,
  type OutletSignals,
} from "./outlet.js";

export {
  runUpdateCheck,
  type FetchOutcome,
  type RunUpdateCheckOptions,
  type RunUpdateCheckResult,
  type UpdateCheckContent,
  type UpdateCheckError,
} from "./check.js";

export {
  CONFIG_DOC,
  LICENSE_DOC,
  verifyConfigDoc,
  verifyDoc,
  verifyLicenseDoc,
  type DocTypeSpec,
  type VerifyOptions,
} from "./verify.js";

export {
  mergeTrust,
  verifyTrustManifest,
  type TrustManifestOptions,
  type TrustManifestResult,
} from "./trust.js";

export {
  MAX_BUNDLE_BYTES,
  inspectBundle,
  verifyBundle,
  type BundleInspection,
  type BundleOptions,
  type BundleRefusalReason,
  type VerifiedBundle,
  type VerifiedBundleDoc,
} from "./bundle.js";

export {
  isUsable,
  licenseState,
  type BlockedState,
  type GateInput,
  type LicenseState,
} from "./gate.js";

export {
  listUserEntries,
  resolveSource,
  resolveValue,
  type ConfigSource,
  type ResolveContext,
  type UserConfigEntry,
} from "./config.js";

export { canonicalArch, canonicalPlatform } from "./headers.js";
// WIRE-CONTRACT-V4 §12.7.1 (PX-W13): the device label every SDK sends as `deviceName`.
export { normalizeDeviceLabel } from "./deviceLabel.js";

export {
  channelForVersion,
  compareSemver,
  isDevBuild,
  parseSemver,
} from "./semver.js";

export { effectiveNow, highWaterMark, type DatedArtifact } from "./clock.js";

export { PolarisError, type PolarisErrorDetails } from "./errors.js";

export {
  UNSUPPORTED_CODE,
  UnsupportedError,
  detectorKey,
  detectorProblems,
  evaluateSupport,
  supportedFeatures,
  type CapabilityContext,
  type CapabilityDetector,
  type CapabilityDetectors,
  type CapabilityNaLike,
  type CapabilityRowLike,
  type Support,
  type Supported,
  type Unsupported,
  type UnsupportedReason,
} from "./caps.js";

export {
  CACHE_VERSION,
  STORE_BACKENDS,
  STORE_DEGRADED_REASONS,
  type CacheRecordV3,
  type Store,
  type StoreBackend,
  type StoreDegradedReason,
  type StoreStatus,
} from "./store.js";

export {
  BOOT_CONFIRMATIONS,
  BOOT_DECISIONS,
  BOOT_OK_SECONDS,
  bootConfirmation,
  type BootConfirmation,
  BOOT_EMIT_TYPES,
  BOOT_EVENT_TYPES,
  BOOT_GUARD_ACTIONS,
  BOOT_OUTCOMES,
  BOOT_STAGES,
  MAX_FAILED_BOOTS,
  bootGuardAction,
  bootTransition,
  initialBootState,
  type BootBlockedReason,
  type BootDecision,
  type BootEmit,
  type BootEmitType,
  type BootEvent,
  type BootEventType,
  type BootFetchResult,
  type BootGuardAction,
  type BootGuardResult,
  type BootOptions,
  type BootOutcome,
  type BootStage,
  type BootState,
  type BootSyncResult,
  type BootTransition,
} from "./stages.js";

export {
  MANAGE_URL_MAX_LENGTH,
  isManageUrl,
  manageFormEncode,
  readManageUrl,
  withManageKey,
  withManageReturn,
} from "./manage.js";
