# GENERATED by `pkey sdk --lang python --write` from
# https://key.plrs.im/acme/.well-known/polaris.json. Do not edit: run the command again to refresh.
# The trust pins came from discovery; compare each fingerprint with the console before
# you ship (pkey sdk prints them). Release keys match release.releaseKeyFingerprints.
"""Polaris Key configuration for acme.

    from polaris_key import PolarisKeyClient
    import polaris_config

    client = PolarisKeyClient.create(**polaris_config.CONFIG, version=__version__)
"""

from typing import Any, Dict, List

from polaris_key import UpdateClientOptions

PRODUCT_SLUG = "acme"
BASE_URL = "https://key.plrs.im"
PINNED_KEYS: Dict[str, str] = {
    "pkey-test-prod-2026": "kDJF6Deuexo91hFZ9TAPr2SmjUEuTXdia67UogTEpkI",
}
PINNED_RELEASE_KEYS: Dict[str, str] = {
    "acme-release-2026": "Z6FCkd1K7Om4lxUk4og_J0m73saH4BrrLk8igXzwcJM",
}
EXPECTED_SERVICES: List[str] = ["license", "config", "release", "update"]

#: Every `PolarisKeyClient` keyword except `version`.
CONFIG: Dict[str, Any] = {
    "product_slug": PRODUCT_SLUG,
    "base_url": BASE_URL,
    "trust": dict(PINNED_KEYS),
    "expected_services": list(EXPECTED_SERVICES),
    "update": UpdateClientOptions(pinned_release_keys=dict(PINNED_RELEASE_KEYS)),
}
