#!/bin/bash
# Copies the prototype's verifier, vectors and content core into project/ (all git-ignored), so the
# wrapper exports without touching the prototype's own project or presets.
# usage: ./sync.sh [small|large|both]   (default: both; the Web preset only ships vectors/small)
set -euo pipefail
L=$(cd "$(dirname "$0")" && pwd)
P=$(cd "$L/.." && pwd)
SETS=${1:-both}
D=$L/project
rm -rf "$D/addons" "$D/vectors" "$D/lib"
mkdir -p "$D/addons" "$D/vectors" "$D/lib"
cp -R "$P/addons/polaris_key" "$D/addons/"
find "$D/addons" -name '*.uid' -delete
for f in ed25519.json sha512.json corpus_jws.json corpus_sigs.json; do
  [ -f "$P/vectors/$f" ] || { echo "missing $P/vectors/$f: run 'node vectors/gen_corpus.mjs' in ../" >&2; exit 1; }
  cp "$P/vectors/$f" "$D/vectors/"
done
node "$L/gen_bench_vectors.mjs" "$P/vectors/corpus_sigs.json" "$D/vectors/ed25519_bench.json"
case "$SETS" in
  small) S="small" ;; large) S="large" ;; both) S="small large" ;; *) echo "bad set $SETS" >&2; exit 2 ;;
esac
for s in $S; do
  [ -f "$P/content/vectors/$s/cases.json" ] || { echo "missing content vectors/$s: see ../content/README.md step 2" >&2; exit 1; }
  cp -R "$P/content/vectors/$s" "$D/vectors/$s"
done
# The content core: ContentRunner minus its SceneTree entry points (best/bench/_init are the tail of the file).
SRC=$P/content/runners/godot/content_runner.gd
CUT=$(grep -n '^func best(' "$SRC" | cut -d: -f1)
[ -n "$CUT" ] || { echo "content_runner.gd changed: no 'func best(' to cut at" >&2; exit 1; }
{
  echo "# GENERATED by lowend/sync.sh from content/runners/godot/content_runner.gd (lines 1-$((CUT - 1))). Do not edit."
  head -n $((CUT - 1)) "$SRC" | sed -e 's/^class_name ContentRunner$/class_name PKLowendContent/' -e 's/^extends SceneTree$/extends RefCounted/'
} > "$D/lib/content_core.gd"
grep -q '^class_name PKLowendContent$' "$D/lib/content_core.gd" && grep -q '^extends RefCounted$' "$D/lib/content_core.gd" \
  || { echo "content core header rewrite failed" >&2; exit 1; }
echo "synced into $D: addons, vectors ($S), lib/content_core.gd"
