/**
 * `pkey sdk --lang <lang> [--write] [--out <path>]` (SDK parity pass §3.19, SP-02): fetch a
 * product's discovery document and write a typed configuration module for one SDK, so an
 * integration starts from generated product facts instead of pasted ones.
 *
 * The module holds the product slug, the base URL, the trust pins (`trust.pinnedKeys` from
 * discovery), the pinned release keys and the services the product runs (each SDK's D-21
 * `expectedServices` fallback). Release keys are not served by any public route: they come from
 * the product's own `.pkey/release` `releaseKeys` (or `--release-key kid=key`), and every one of
 * them must match discovery's `release.releaseKeyFingerprints` (SHA-256 of the raw key), both
 * ways. A mismatch refuses: the module would otherwise pin a key the server does not advertise,
 * or leave out one it does.
 *
 * Trust pins are compiled in, never learned at runtime. Fetching them here is a build-time
 * convenience over HTTPS, so the command prints each pin's fingerprint for comparison with the
 * console, and `--kid`/`--public-key` (the `pkey trust` pair) makes it refuse unless discovery
 * serves exactly that pin.
 *
 * Nothing here changes the wire: discovery and the fingerprints are what the Worker already
 * serves (`/<product>/.well-known/polaris.json`).
 */

import { createHash } from "node:crypto";
import { PROTOCOL_VERSION } from "@polaris-key/protocol/core";
import { SERVICE_SLUGS, type ServiceSlug } from "@polaris-key/manifest";

export const SDK_LANGS = [
  "node",
  "react",
  "python",
  "swift",
  "kotlin",
  "godot",
] as const;
export type SdkLang = (typeof SDK_LANGS)[number];

export const SDK_CONFIG_USAGE =
  "Usage: pkey sdk --lang node|react|python|swift|kotlin|godot --product <slug> [--base-url <url>]\n" +
  "                [--write] [--out <path>] [--force] [--kid <kid> --public-key <key>]\n" +
  "                [--release-key <kid>=<key> ...] [--package <kotlin package>]";

/** The marker every generated module starts with; `--write` only overwrites a file carrying it. */
export const SDK_CONFIG_MARKER = "GENERATED by `pkey sdk";

/** Where `--write` puts each language's module when `--out` is not given. */
export const SDK_CONFIG_DEFAULT_OUT: Record<SdkLang, string> = {
  node: "polaris.config.ts",
  react: "polaris.config.ts",
  python: "polaris_config.py",
  swift: "PolarisConfig.swift",
  kotlin: "PolarisConfig.kt",
  godot: "polaris_key_config.gd",
};

/** The product facts a generated module carries. */
export interface SdkConfigFacts {
  product: string;
  baseUrl: string;
  /** The discovery URL the facts came from (named in the banner). */
  discoveryUrl: string;
  pinnedKeys: Record<string, string>;
  pinnedReleaseKeys: Record<string, string>;
  /** The enabled services, in canonical order. */
  services: ServiceSlug[];
}

export interface DeclaredReleaseKey {
  kid: string;
  publicKey: string;
}

const PRODUCT_RE = /^[a-z0-9][a-z0-9_-]*$/;
// Narrow on purpose: every value is emitted inside a string literal in six languages (Kotlin
// interpolates `$`, Swift `\(`), so anything outside these alphabets is refused, not escaped.
const KID_RE = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const KEY_RE = /^[A-Za-z0-9_-]{43}$/;
const URL_CHARS_RE = /^[A-Za-z0-9:/._~%-]+$/;
const KOTLIN_PACKAGE_RE = /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*$/;

/** Lowercase hex SHA-256 of a raw key: what discovery's `releaseKeyFingerprints` lists. */
function fingerprint(publicKey: string): string {
  return createHash("sha256")
    .update(Buffer.from(publicKey, "base64url"))
    .digest("hex");
}

/** `https:` (or loopback `http:`), no query or fragment, no trailing slash. */
export function normalizeBaseUrl(raw: string): string {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    throw new Error(`--base-url ${raw} is not a URL.`);
  }
  const loopback =
    url.hostname === "localhost" ||
    url.hostname === "127.0.0.1" ||
    url.hostname === "[::1]";
  if (url.protocol !== "https:" && !(url.protocol === "http:" && loopback))
    throw new Error(
      `--base-url must be https: (http: only for localhost); got ${raw}.`,
    );
  if (url.search || url.hash || url.username || url.password)
    throw new Error(
      `--base-url must not carry credentials, a query or a fragment.`,
    );
  const out = `${url.origin}${url.pathname}`.replace(/\/+$/, "");
  if (!URL_CHARS_RE.test(out))
    throw new Error(`--base-url ${raw} has characters pkey sdk cannot emit.`);
  return out;
}

/** `--release-key kid=key` values. */
export function parseReleaseKeyFlags(values: string[]): DeclaredReleaseKey[] {
  return values.map((v) => {
    const eq = v.indexOf("=");
    if (eq <= 0) throw new Error(`--release-key takes <kid>=<key>; got ${v}.`);
    return { kid: v.slice(0, eq), publicKey: v.slice(eq + 1) };
  });
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/**
 * Fetch discovery and resolve the facts. Throws, writing nothing, on any refusal: a product or
 * protocol mismatch, a malformed pin, an expected pin discovery does not serve, or release keys
 * that do not match `releaseKeyFingerprints`.
 */
export async function resolveSdkFacts(opts: {
  product: string;
  baseUrl: string;
  /** Declared release keys (`.pkey/release` plus `--release-key`). */
  releaseKeys: readonly DeclaredReleaseKey[];
  /** The `pkey trust` pair the caller expects discovery to serve. */
  expectPin?: { kid: string; publicKey: string };
  fetchImpl?: typeof fetch;
}): Promise<SdkConfigFacts> {
  if (!PRODUCT_RE.test(opts.product))
    throw new Error(
      `--product must be a lower-case slug; got ${opts.product}.`,
    );
  const baseUrl = normalizeBaseUrl(opts.baseUrl);
  const discoveryUrl = `${baseUrl}/${opts.product}/.well-known/polaris.json`;
  const doFetch = opts.fetchImpl ?? fetch;
  let res: Response;
  try {
    res = await doFetch(discoveryUrl, {
      headers: { accept: "application/json" },
    });
  } catch (e) {
    throw new Error(`Could not reach ${discoveryUrl}: ${(e as Error).message}`);
  }
  if (!res.ok)
    throw new Error(
      `${discoveryUrl} answered ${res.status}; is the product registered and the base URL right?`,
    );
  let doc: unknown;
  try {
    doc = await res.json();
  } catch {
    throw new Error(`${discoveryUrl} did not answer JSON.`);
  }
  if (!isRecord(doc)) throw new Error(`${discoveryUrl} is not an object.`);
  if (doc.product !== opts.product)
    throw new Error(
      `Discovery names product ${JSON.stringify(doc.product)}, not ${opts.product}.`,
    );
  if (doc.protocolVersion !== PROTOCOL_VERSION)
    throw new Error(
      `Discovery speaks protocol ${String(doc.protocolVersion)}; this pkey speaks ${PROTOCOL_VERSION}. Update pkey or the server.`,
    );

  // Trust pins.
  const trust = isRecord(doc.trust) ? doc.trust : {};
  const pins = isRecord(trust.pinnedKeys) ? trust.pinnedKeys : {};
  const pinnedKeys: Record<string, string> = {};
  for (const kid of Object.keys(pins).sort()) {
    const key = pins[kid];
    if (!KID_RE.test(kid) || typeof key !== "string" || !KEY_RE.test(key))
      throw new Error(
        `Discovery's trust.pinnedKeys has a malformed entry (${kid}).`,
      );
    pinnedKeys[kid] = key;
  }
  if (Object.keys(pinnedKeys).length === 0)
    throw new Error(`Discovery lists no trust.pinnedKeys.`);
  if (opts.expectPin) {
    const { kid, publicKey } = opts.expectPin;
    if (pinnedKeys[kid] !== publicKey)
      throw new Error(
        `Discovery does not pin ${kid} with the key you gave (--kid/--public-key); nothing was written. ` +
          `Compare the console's signing keys with ${discoveryUrl}.`,
      );
  }

  // Services, in canonical order.
  const services = isRecord(doc.services) ? doc.services : {};
  const enabled = SERVICE_SLUGS.filter((slug) => {
    const s = services[slug];
    return isRecord(s) && s.enabled === true;
  });

  // Release keys, matched against releaseKeyFingerprints both ways.
  const release = isRecord(services.release) ? services.release : {};
  const advertised = Array.isArray(release.releaseKeyFingerprints)
    ? release.releaseKeyFingerprints.filter(
        (f): f is string => typeof f === "string",
      )
    : [];
  const pinnedReleaseKeys: Record<string, string> = {};
  for (const k of opts.releaseKeys) {
    if (!KID_RE.test(k.kid) || !KEY_RE.test(k.publicKey))
      throw new Error(`Release key ${k.kid} is malformed.`);
    if (
      pinnedReleaseKeys[k.kid] !== undefined &&
      pinnedReleaseKeys[k.kid] !== k.publicKey
    )
      throw new Error(
        `Release key ${k.kid} is declared twice with different keys.`,
      );
    if (Object.values(pinnedKeys).includes(k.publicKey))
      throw new Error(
        `Release key ${k.kid} is also a trust pin; a release key is never a product signing key.`,
      );
    pinnedReleaseKeys[k.kid] = k.publicKey;
  }
  const declaredPrints = new Map(
    Object.entries(pinnedReleaseKeys).map(([kid, key]) => [
      fingerprint(key),
      kid,
    ]),
  );
  const notAdvertised = [...declaredPrints]
    .filter(([fp]) => !advertised.includes(fp))
    .map(([, kid]) => kid);
  if (notAdvertised.length > 0)
    throw new Error(
      `Discovery does not advertise release key${notAdvertised.length === 1 ? "" : "s"} ${notAdvertised.join(", ")} ` +
        `(release.releaseKeyFingerprints). Push .pkey/release and resync the product, then run pkey sdk again.`,
    );
  const undeclared = advertised.filter((fp) => !declaredPrints.has(fp));
  if (undeclared.length > 0)
    throw new Error(
      `Discovery advertises ${undeclared.length} release key${undeclared.length === 1 ? "" : "s"} you did not declare ` +
        `(fingerprint ${undeclared.join(", ")}). Run pkey sdk in the product repo (it reads .pkey/release), ` +
        `or pass each key with --release-key <kid>=<key>.`,
    );

  return {
    product: opts.product,
    baseUrl,
    discoveryUrl,
    pinnedKeys,
    pinnedReleaseKeys: Object.fromEntries(
      Object.entries(pinnedReleaseKeys).sort(([a], [b]) => a.localeCompare(b)),
    ),
    services: enabled,
  };
}

/** What `pkey sdk` prints after resolving: each pin's fingerprint, to compare with the console. */
export function factsSummary(facts: SdkConfigFacts): string {
  const lines = [
    `Product ${facts.product} at ${facts.baseUrl}`,
    `Services: ${facts.services.join(", ") || "(none)"}`,
    "Trust pins (compare each fingerprint with the console before you ship):",
    ...Object.entries(facts.pinnedKeys).map(
      ([kid, key]) => `  ${kid}  sha256:${fingerprint(key)}`,
    ),
  ];
  const rk = Object.entries(facts.pinnedReleaseKeys);
  lines.push(
    rk.length === 0
      ? "Release keys: none"
      : "Release keys (matched against discovery's releaseKeyFingerprints):",
    ...rk.map(([kid, key]) => `  ${kid}  sha256:${fingerprint(key)}`),
  );
  return lines.join("\n");
}

// ── Renderers ────────────────────────────────────────────────────────────────────────────────

function banner(lang: SdkLang, facts: SdkConfigFacts, comment: string): string {
  return [
    `${comment} ${SDK_CONFIG_MARKER} --lang ${lang} --write\` from`,
    `${comment} ${facts.discoveryUrl}. Do not edit: run the command again to refresh.`,
    `${comment} The trust pins came from discovery; compare each fingerprint with the console before`,
    `${comment} you ship (pkey sdk prints them). Release keys match release.releaseKeyFingerprints.`,
  ].join("\n");
}

const q = (s: string): string => JSON.stringify(s);

function tsMap(map: Record<string, string>, indent: string): string {
  const rows = Object.entries(map);
  if (rows.length === 0) return "{}";
  return `{\n${rows.map(([k, v]) => `${indent}  ${q(k)}: ${q(v)},`).join("\n")}\n${indent}}`;
}

function renderNode(facts: SdkConfigFacts, js: boolean): string {
  const hasRelease = Object.keys(facts.pinnedReleaseKeys).length > 0;
  const body = [
    `  productSlug: ${q(facts.product)},`,
    `  baseUrl: ${q(facts.baseUrl)},`,
    `  trust: {\n    pinnedKeys: ${tsMap(facts.pinnedKeys, "    ")},\n  },`,
    `  expectedServices: [${facts.services.map(q).join(", ")}],`,
    ...(hasRelease
      ? [
          `  update: {\n    pinnedReleaseKeys: ${tsMap(facts.pinnedReleaseKeys, "    ")},\n  },`,
        ]
      : []),
  ].join("\n");
  const doc = `/**
 * Everything \`PolarisKeyClient.create()\` needs except the app's \`version\`:
 *
 *   const client = await PolarisKeyClient.create({ ...polarisConfig, version: "1.2.3" });
 */`;
  if (js)
    return `${banner("node", facts, "//")}

${doc}
/** @satisfies {Omit<import("@polaris-key/node").PolarisKeyClientOptions, "version">} */
export const polarisConfig = {
${body}
};

export default polarisConfig;
`;
  return `${banner("node", facts, "//")}
import type { PolarisKeyClientOptions } from "@polaris-key/node";

${doc}
export const polarisConfig = {
${body}
} satisfies Omit<PolarisKeyClientOptions, "version">;

export default polarisConfig;
`;
}

function renderReact(facts: SdkConfigFacts, js: boolean): string {
  const props = [
    `  productSlug: ${q(facts.product)},`,
    `  baseUrl: ${q(facts.baseUrl)},`,
    `  expectServices: [${facts.services.map(q).join(", ")}],`,
  ].join("\n");
  const pins = `/** The trust pins, for the desktop host's \`@polaris-key/node\` client (the bridge's main
 *  process verifies; the renderer never does). */
export const pinnedKeys = ${tsMap(facts.pinnedKeys, "")};

/** The pinned release keys, for the same host (\`update.pinnedReleaseKeys\`). */
export const pinnedReleaseKeys = ${tsMap(facts.pinnedReleaseKeys, "")};
`;
  const doc = `/**
 * The provider's product facts:
 *
 *   <PolarisKeyProvider {...polarisConfig} version={APP_VERSION}>…</PolarisKeyProvider>
 */`;
  if (js)
    return `${banner("react", facts, "//")}

${doc}
/** @satisfies {Partial<import("@polaris-key/react").PolarisKeyProviderProps>} */
export const polarisConfig = {
${props}
};

${pins}
export default polarisConfig;
`;
  return `${banner("react", facts, "//")}
import type { PolarisKeyProviderProps } from "@polaris-key/react";

${doc}
export const polarisConfig = {
${props}
} satisfies Partial<PolarisKeyProviderProps>;

${pins}
export default polarisConfig;
`;
}

function pyMap(map: Record<string, string>): string {
  const rows = Object.entries(map);
  if (rows.length === 0) return "{}";
  return `{\n${rows.map(([k, v]) => `    ${q(k)}: ${q(v)},`).join("\n")}\n}`;
}

function renderPython(facts: SdkConfigFacts): string {
  const hasRelease = Object.keys(facts.pinnedReleaseKeys).length > 0;
  return `${banner("python", facts, "#")}
"""Polaris Key configuration for ${facts.product}.

    from polaris_key import PolarisKeyClient
    import polaris_config

    client = PolarisKeyClient.create(**polaris_config.CONFIG, version=__version__)
"""

from typing import Any, Dict, List

${hasRelease ? "from polaris_key import UpdateClientOptions\n\n" : ""}PRODUCT_SLUG = ${q(facts.product)}
BASE_URL = ${q(facts.baseUrl)}
PINNED_KEYS: Dict[str, str] = ${pyMap(facts.pinnedKeys)}
PINNED_RELEASE_KEYS: Dict[str, str] = ${pyMap(facts.pinnedReleaseKeys)}
EXPECTED_SERVICES: List[str] = [${facts.services.map(q).join(", ")}]

#: Every \`PolarisKeyClient\` keyword except \`version\`.
CONFIG: Dict[str, Any] = {
    "product_slug": PRODUCT_SLUG,
    "base_url": BASE_URL,
    "trust": dict(PINNED_KEYS),
    "expected_services": list(EXPECTED_SERVICES),
${hasRelease ? `    "update": UpdateClientOptions(pinned_release_keys=dict(PINNED_RELEASE_KEYS)),\n` : ""}}
`;
}

function swiftMap(map: Record<string, string>): string {
  const rows = Object.entries(map);
  if (rows.length === 0) return "[:]";
  return `[\n${rows.map(([k, v]) => `        ${q(k)}: ${q(v)},`).join("\n")}\n    ]`;
}

function renderSwift(facts: SdkConfigFacts): string {
  return `${banner("swift", facts, "//")}

import PolarisKey

/// Polaris Key configuration for ${facts.product}:
///
///     let client = try PolarisKeyClient(options: PolarisConfig.clientOptions(version: appVersion))
public enum PolarisConfig {
    public static let productSlug = ${q(facts.product)}
    public static let baseUrl = ${q(facts.baseUrl)}
    public static let pinnedKeys: TrustSet = ${swiftMap(facts.pinnedKeys)}
    /// For \`UpdateClientOptions(pinnedReleaseKeys:)\` (PolarisKeyUpdate, PolarisKeyPacks).
    public static let pinnedReleaseKeys: TrustSet = ${swiftMap(facts.pinnedReleaseKeys)}
    public static let expectedServices: [ServiceSlug] = [${facts.services.map((s) => `.${s}`).join(", ")}]

    /// Every option the client needs; \`version\` is the app's own.
    public static func clientOptions(version: String, channel: String? = nil) -> PolarisKeyClientOptions {
        PolarisKeyClientOptions(
            productSlug: productSlug, baseUrl: baseUrl, version: version, channel: channel,
            pinnedKeys: pinnedKeys, expectedServices: expectedServices)
    }
}
`;
}

function ktMap(map: Record<string, string>): string {
  const rows = Object.entries(map);
  if (rows.length === 0) return "emptyMap()";
  return `mapOf(\n${rows.map(([k, v]) => `        ${q(k)} to ${q(v)},`).join("\n")}\n    )`;
}

function renderKotlin(facts: SdkConfigFacts, pkg: string): string {
  return `${banner("kotlin", facts, "//")}

package ${pkg}

import im.plrs.key.core.CoreOptions
import im.plrs.key.core.ServiceSlug
import im.plrs.key.core.TrustSet
import im.plrs.key.sdk.PolarisKeyClientOptions
import im.plrs.key.update.UpdateClientOptions

/**
 * Polaris Key configuration for ${facts.product}:
 *
 *     val client = PolarisKeyClient.create(PolarisConfig.clientOptions(version = BuildConfig.VERSION_NAME))
 */
public object PolarisConfig {
    public const val PRODUCT_SLUG: String = ${q(facts.product)}
    public const val BASE_URL: String = ${q(facts.baseUrl)}
    public val pinnedKeys: TrustSet = ${ktMap(facts.pinnedKeys)}
    public val pinnedReleaseKeys: TrustSet = ${ktMap(facts.pinnedReleaseKeys)}
    public val expectedServices: List<ServiceSlug> = listOf(${facts.services.map((s) => `ServiceSlug.${s}`).join(", ")})

    /** Core's options; [version] is the app's own. */
    public fun coreOptions(version: String, channel: String? = null): CoreOptions = CoreOptions(
        productSlug = PRODUCT_SLUG,
        baseUrl = BASE_URL,
        version = version,
        channel = channel,
        pinnedKeys = pinnedKeys,
        expectedServices = expectedServices,
    )

    /** The client's options, with the update client configured when release keys are pinned. */
    public fun clientOptions(version: String, channel: String? = null): PolarisKeyClientOptions =
        PolarisKeyClientOptions(
            core = coreOptions(version, channel),
            update = if (pinnedReleaseKeys.isEmpty()) null else UpdateClientOptions(pinnedReleaseKeys = pinnedReleaseKeys),
        )
}
`;
}

function gdMap(map: Record<string, string>): string {
  const rows = Object.entries(map);
  if (rows.length === 0) return "{}";
  return `{\n${rows.map(([k, v]) => `\t${q(k)}: ${q(v)},`).join("\n")}\n}`;
}

function renderGodot(facts: SdkConfigFacts): string {
  return `${banner("godot", facts, "#")}
extends RefCounted
## Polaris Key configuration for ${facts.product}. Keep it outside addons/:
##
##     const PolarisConfig := preload("res://polaris_key_config.gd")
##     PolarisKey.configure(PolarisConfig.options())

const PRODUCT := ${q(facts.product)}
const BASE_URL := ${q(facts.baseUrl)}
const PINNED_TRUST_KEYS := ${gdMap(facts.pinnedKeys)}
const PINNED_RELEASE_KEYS := ${gdMap(facts.pinnedReleaseKeys)}
const EXPECTED_SERVICES := [${facts.services.map(q).join(", ")}]


## Writes the product facts into [param opts] and returns it; every other field is left alone.
static func apply(opts: PKeyOptions) -> PKeyOptions:
\topts.product = PRODUCT
\topts.base_url = BASE_URL
\topts.pinned_trust_keys = PINNED_TRUST_KEYS.duplicate()
\topts.pinned_release_keys = PINNED_RELEASE_KEYS.duplicate()
\topts.expected_services = PackedStringArray(EXPECTED_SERVICES)
\treturn opts


## A new [PKeyOptions] carrying the product facts.
static func options() -> PKeyOptions:
\treturn apply(PKeyOptions.new())
`;
}

/** Render one language's module. `out` picks `.js`/`.mjs` for Node and React. */
export function renderSdkConfig(
  lang: SdkLang,
  facts: SdkConfigFacts,
  opts: { out?: string; kotlinPackage?: string } = {},
): string {
  const js = /\.(m?js|cjs)$/.test(opts.out ?? "");
  switch (lang) {
    case "node":
      return renderNode(facts, js);
    case "react":
      return renderReact(facts, js);
    case "python":
      return renderPython(facts);
    case "swift":
      return renderSwift(facts);
    case "kotlin": {
      const pkg = opts.kotlinPackage ?? "polaris.generated";
      if (!KOTLIN_PACKAGE_RE.test(pkg))
        throw new Error(`--package must be a Kotlin package name; got ${pkg}.`);
      return renderKotlin(facts, pkg);
    }
    case "godot":
      return renderGodot(facts);
  }
}

export function isSdkLang(v: string): v is SdkLang {
  return (SDK_LANGS as readonly string[]).includes(v);
}
