// GENERATED by `pkey sdk --lang node --write` from
// https://key.plrs.im/acme/.well-known/polaris.json. Do not edit: run the command again to refresh.
// The trust pins came from discovery; compare each fingerprint with the console before
// you ship (pkey sdk prints them). Release keys match release.releaseKeyFingerprints.
import type { PolarisKeyClientOptions } from "@polaris-key/node";

/**
 * Everything `PolarisKeyClient.create()` needs except the app's `version`:
 *
 *   const client = await PolarisKeyClient.create({ ...polarisConfig, version: "1.2.3" });
 */
export const polarisConfig = {
  productSlug: "acme",
  baseUrl: "https://key.plrs.im",
  trust: {
    pinnedKeys: {
      "pkey-test-prod-2026": "kDJF6Deuexo91hFZ9TAPr2SmjUEuTXdia67UogTEpkI",
    },
  },
  expectedServices: ["license", "config", "release", "update"],
  update: {
    pinnedReleaseKeys: {
      "acme-release-2026": "Z6FCkd1K7Om4lxUk4og_J0m73saH4BrrLk8igXzwcJM",
    },
  },
} satisfies Omit<PolarisKeyClientOptions, "version">;

export default polarisConfig;
