/**
 * Every App Store Connect write operation the gate REFUSES, with the reason (A-17a; notes/S-14
 * §7.5). The gate itself is deny-by-default (`writeGate.ts`): this table changes nothing at run
 * time. It exists so that every write operation of the pinned OpenAPI document is classified on
 * purpose, and `test/ascWriteGate.test.ts` requires each operation in
 * `test/fixtures/asc/openapi-writes.json` to appear EITHER in `ASC_WRITE_ALLOW` OR here, exactly
 * once, and no entry here to be missing from the spec. A spec bump therefore fails CI until each
 * new operation is placed (here, or, after review, in the allow table).
 *
 * Moving an entry from here to the allow table is a THREAT-MODEL §9 review trigger.
 */

/** Why each group is refused. */
export const ASC_DENY_REASONS = {
  teamMembership:
    "Team membership. An Admin key could invite or promote a user, a takeover that outlives revoking the key (owner decision: never users).",
  delete:
    "No DELETE, ever (owner decision 2026-10-04): identifiers, builds, groups, testers, IAPs and relationships are removed by hand in the portal.",
  signingIdentity:
    "Signing identity and identifiers: certificates, profiles, devices, merchant and pass type ids, and changes to an existing bundle id or capability (owner decision: never certificates, devices or profiles).",
  reviewContactData:
    "App Review contact details and demo accounts: personal data and a password, which Polaris Key never stores or sends.",
  subscriptions:
    "Subscriptions and promoted purchases: outside the approved surface (non-consumable IAPs only, matching P6-01).",
  gameCenter: "Game Center: outside the approved surface.",
  alternativeDistribution:
    "Alternative distribution and marketplaces: outside the approved surface.",
  tooling:
    "Xcode Cloud, analytics report requests and sandbox testers: outside the approved surface.",
  uploads:
    "Uploads (builds, assets, screenshots, previews, images, documents): Polaris Key never uploads to App Store Connect (P5-02 README decision 7).",
  inAppPurchasesOutsideSurface:
    "IAP operations beyond creating a non-consumable with its version, v2 localizations, price schedule and availability: offer codes, the v1 localization API, the portal-only first submission, changes to an existing IAP.",
  testFlightOutsideSurface:
    "TestFlight operations beyond groups, testers, builds to groups, What to Test and beta review: App Clips, app-level beta metadata, license agreements, recruitment, notifications, individual testers.",
  webhooksOutsideSurface:
    "Webhook changes beyond P5-02's create and ping (redelivery, editing an existing webhook's URL or secret).",
  versionsOutsideSurface:
    "Version operations beyond create, settings, build, release notes, phased release, submission and release: experiments, keywords, promotions, App Clip experiences, resolving submission items.",
  listingOutsideSurface:
    "Store listing and app metadata (app info, age rating, custom product pages, events, App Clips, EULA, routing coverage, encryption declarations, pre-orders, territory changes, review responses, nominations): outside the approved surface.",
} as const;

export type AscDenyGroup = keyof typeof ASC_DENY_REASONS;

/** `"<METHOD> <path template>"` per group, as the spec spells it. */
export const ASC_WRITE_DENIED: Readonly<
  Record<AscDenyGroup, readonly string[]>
> = {
  teamMembership: [
    "POST /v1/userInvitations",
    "DELETE /v1/userInvitations/{id}",
    "DELETE /v1/users/{id}",
    "PATCH /v1/users/{id}",
    "DELETE /v1/users/{id}/relationships/visibleApps",
    "PATCH /v1/users/{id}/relationships/visibleApps",
    "POST /v1/users/{id}/relationships/visibleApps",
  ],
  delete: [
    "DELETE /v1/accessibilityDeclarations/{id}",
    "DELETE /v1/alternativeDistributionDomains/{id}",
    "DELETE /v1/alternativeDistributionKeys/{id}",
    "DELETE /v1/analyticsReportRequests/{id}",
    "DELETE /v1/androidToIosAppMappingDetails/{id}",
    "DELETE /v1/appClipDefaultExperienceLocalizations/{id}",
    "DELETE /v1/appClipDefaultExperiences/{id}",
    "DELETE /v1/appClipHeaderImages/{id}",
    "DELETE /v1/appCustomProductPageLocalizations/{id}",
    "DELETE /v1/appCustomProductPageLocalizations/{id}/relationships/searchKeywords",
    "DELETE /v1/appCustomProductPages/{id}",
    "DELETE /v1/appEventLocalizations/{id}",
    "DELETE /v1/appEvents/{id}",
    "DELETE /v1/appEventScreenshots/{id}",
    "DELETE /v1/appEventVideoClips/{id}",
    "DELETE /v1/appInfoLocalizations/{id}",
    "DELETE /v1/appPreviews/{id}",
    "DELETE /v1/appPreviewSets/{id}",
    "DELETE /v1/apps/{id}/relationships/betaTesters",
    "DELETE /v1/appScreenshots/{id}",
    "DELETE /v1/appScreenshotSets/{id}",
    "DELETE /v1/appStoreReviewAttachments/{id}",
    "DELETE /v1/appStoreVersionExperiments/{id}",
    "DELETE /v1/appStoreVersionExperimentTreatmentLocalizations/{id}",
    "DELETE /v1/appStoreVersionExperimentTreatments/{id}",
    "DELETE /v1/appStoreVersionLocalizations/{id}",
    "DELETE /v1/appStoreVersionLocalizations/{id}/relationships/searchKeywords",
    "DELETE /v1/appStoreVersionPhasedReleases/{id}",
    "DELETE /v1/appStoreVersions/{id}",
    "DELETE /v1/appStoreVersionSubmissions/{id}",
    "DELETE /v1/betaAppClipInvocationLocalizations/{id}",
    "DELETE /v1/betaAppClipInvocations/{id}",
    "DELETE /v1/betaAppLocalizations/{id}",
    "DELETE /v1/betaBuildLocalizations/{id}",
    "DELETE /v1/betaFeedbackCrashSubmissions/{id}",
    "DELETE /v1/betaFeedbackScreenshotSubmissions/{id}",
    "DELETE /v1/betaGroups/{id}",
    "DELETE /v1/betaGroups/{id}/relationships/betaTesters",
    "DELETE /v1/betaGroups/{id}/relationships/builds",
    "DELETE /v1/betaRecruitmentCriteria/{id}",
    "DELETE /v1/betaTesters/{id}",
    "DELETE /v1/betaTesters/{id}/relationships/apps",
    "DELETE /v1/betaTesters/{id}/relationships/betaGroups",
    "DELETE /v1/betaTesters/{id}/relationships/builds",
    "DELETE /v1/builds/{id}/relationships/betaGroups",
    "DELETE /v1/builds/{id}/relationships/individualTesters",
    "DELETE /v1/buildUploads/{id}",
    "DELETE /v1/bundleIdCapabilities/{id}",
    "DELETE /v1/bundleIds/{id}",
    "DELETE /v1/certificates/{id}",
    "DELETE /v1/ciProducts/{id}",
    "DELETE /v1/ciWorkflows/{id}",
    "DELETE /v1/customerReviewResponses/{id}",
    "DELETE /v1/endUserLicenseAgreements/{id}",
    "DELETE /v1/gameCenterAchievementImages/{id}",
    "DELETE /v1/gameCenterAchievementLocalizations/{id}",
    "DELETE /v1/gameCenterAchievementReleases/{id}",
    "DELETE /v1/gameCenterAchievements/{id}",
    "DELETE /v1/gameCenterActivities/{id}",
    "DELETE /v1/gameCenterActivities/{id}/relationships/achievements",
    "DELETE /v1/gameCenterActivities/{id}/relationships/achievementsV2",
    "DELETE /v1/gameCenterActivities/{id}/relationships/leaderboards",
    "DELETE /v1/gameCenterActivities/{id}/relationships/leaderboardsV2",
    "DELETE /v1/gameCenterActivityImages/{id}",
    "DELETE /v1/gameCenterActivityLocalizations/{id}",
    "DELETE /v1/gameCenterActivityVersionReleases/{id}",
    "DELETE /v1/gameCenterAppVersions/{id}/relationships/compatibilityVersions",
    "DELETE /v1/gameCenterChallengeImages/{id}",
    "DELETE /v1/gameCenterChallengeLocalizations/{id}",
    "DELETE /v1/gameCenterChallenges/{id}",
    "DELETE /v1/gameCenterChallengeVersionReleases/{id}",
    "DELETE /v1/gameCenterEnabledVersions/{id}/relationships/compatibleVersions",
    "DELETE /v1/gameCenterGroups/{id}",
    "DELETE /v1/gameCenterLeaderboardImages/{id}",
    "DELETE /v1/gameCenterLeaderboardLocalizations/{id}",
    "DELETE /v1/gameCenterLeaderboardReleases/{id}",
    "DELETE /v1/gameCenterLeaderboards/{id}",
    "DELETE /v1/gameCenterLeaderboardSetImages/{id}",
    "DELETE /v1/gameCenterLeaderboardSetLocalizations/{id}",
    "DELETE /v1/gameCenterLeaderboardSetMemberLocalizations/{id}",
    "DELETE /v1/gameCenterLeaderboardSetReleases/{id}",
    "DELETE /v1/gameCenterLeaderboardSets/{id}",
    "DELETE /v1/gameCenterLeaderboardSets/{id}/relationships/gameCenterLeaderboards",
    "DELETE /v1/gameCenterMatchmakingQueues/{id}",
    "DELETE /v1/gameCenterMatchmakingRules/{id}",
    "DELETE /v1/gameCenterMatchmakingRuleSets/{id}",
    "DELETE /v1/gameCenterMatchmakingTeams/{id}",
    "DELETE /v1/inAppPurchaseAppStoreReviewScreenshots/{id}",
    "DELETE /v1/inAppPurchaseImages/{id}",
    "DELETE /v1/inAppPurchaseLocalizations/{id}",
    "DELETE /v1/marketplaceSearchDetails/{id}",
    "DELETE /v1/marketplaceWebhooks/{id}",
    "DELETE /v1/merchantIds/{id}",
    "DELETE /v1/nominations/{id}",
    "DELETE /v1/passTypeIds/{id}",
    "DELETE /v1/profiles/{id}",
    "DELETE /v1/promotedPurchases/{id}",
    "DELETE /v1/reviewSubmissionItems/{id}",
    "DELETE /v1/routingAppCoverages/{id}",
    "DELETE /v1/subscriptionAppStoreReviewScreenshots/{id}",
    "DELETE /v1/subscriptionGroupLocalizations/{id}",
    "DELETE /v1/subscriptionGroups/{id}",
    "DELETE /v1/subscriptionImages/{id}",
    "DELETE /v1/subscriptionIntroductoryOffers/{id}",
    "DELETE /v1/subscriptionLocalizations/{id}",
    "DELETE /v1/subscriptionPrices/{id}",
    "DELETE /v1/subscriptionPromotionalOffers/{id}",
    "DELETE /v1/subscriptions/{id}",
    "DELETE /v1/subscriptions/{id}/relationships/introductoryOffers",
    "DELETE /v1/subscriptions/{id}/relationships/prices",
    "DELETE /v1/webhooks/{id}",
    "DELETE /v1/winBackOffers/{id}",
    "DELETE /v2/appStoreVersionExperiments/{id}",
    "DELETE /v2/gameCenterAchievementImages/{id}",
    "DELETE /v2/gameCenterAchievementLocalizations/{id}",
    "DELETE /v2/gameCenterAchievements/{id}",
    "DELETE /v2/gameCenterLeaderboardImages/{id}",
    "DELETE /v2/gameCenterLeaderboardLocalizations/{id}",
    "DELETE /v2/gameCenterLeaderboards/{id}",
    "DELETE /v2/gameCenterLeaderboardSetImages/{id}",
    "DELETE /v2/gameCenterLeaderboardSetLocalizations/{id}",
    "DELETE /v2/gameCenterLeaderboardSets/{id}",
    "DELETE /v2/gameCenterLeaderboardSets/{id}/relationships/gameCenterLeaderboards",
    "DELETE /v2/inAppPurchaseImages/{id}",
    "DELETE /v2/inAppPurchaseLocalizations/{id}",
    "DELETE /v2/inAppPurchases/{id}",
    "DELETE /v2/subscriptionGroupLocalizations/{id}",
    "DELETE /v2/subscriptionImages/{id}",
    "DELETE /v2/subscriptionLocalizations/{id}",
  ],
  signingIdentity: [
    "PATCH /v1/bundleIdCapabilities/{id}",
    "PATCH /v1/bundleIds/{id}",
    "POST /v1/certificates",
    "PATCH /v1/certificates/{id}",
    "POST /v1/devices",
    "PATCH /v1/devices/{id}",
    "POST /v1/merchantIds",
    "PATCH /v1/merchantIds/{id}",
    "POST /v1/passTypeIds",
    "PATCH /v1/passTypeIds/{id}",
    "POST /v1/profiles",
  ],
  reviewContactData: [
    "POST /v1/appClipAppStoreReviewDetails",
    "PATCH /v1/appClipAppStoreReviewDetails/{id}",
    "POST /v1/appStoreReviewAttachments",
    "PATCH /v1/appStoreReviewAttachments/{id}",
    "POST /v1/appStoreReviewDetails",
    "PATCH /v1/appStoreReviewDetails/{id}",
    "PATCH /v1/betaAppReviewDetails/{id}",
  ],
  subscriptions: [
    "PATCH /v1/apps/{id}/relationships/promotedPurchases",
    "POST /v1/promotedPurchases",
    "PATCH /v1/promotedPurchases/{id}",
    "POST /v1/subscriptionAppStoreReviewScreenshots",
    "PATCH /v1/subscriptionAppStoreReviewScreenshots/{id}",
    "POST /v1/subscriptionAvailabilities",
    "PATCH /v1/subscriptionGracePeriods/{id}",
    "POST /v1/subscriptionGroupLocalizations",
    "PATCH /v1/subscriptionGroupLocalizations/{id}",
    "POST /v1/subscriptionGroups",
    "PATCH /v1/subscriptionGroups/{id}",
    "POST /v1/subscriptionGroupSubmissions",
    "POST /v1/subscriptionGroupVersions",
    "POST /v1/subscriptionImages",
    "PATCH /v1/subscriptionImages/{id}",
    "POST /v1/subscriptionIntroductoryOffers",
    "PATCH /v1/subscriptionIntroductoryOffers/{id}",
    "POST /v1/subscriptionLocalizations",
    "PATCH /v1/subscriptionLocalizations/{id}",
    "POST /v1/subscriptionOfferCodeCustomCodes",
    "PATCH /v1/subscriptionOfferCodeCustomCodes/{id}",
    "POST /v1/subscriptionOfferCodeOneTimeUseCodes",
    "PATCH /v1/subscriptionOfferCodeOneTimeUseCodes/{id}",
    "POST /v1/subscriptionOfferCodes",
    "PATCH /v1/subscriptionOfferCodes/{id}",
    "POST /v1/subscriptionPlanAvailabilities",
    "PATCH /v1/subscriptionPlanAvailabilities/{id}",
    "PATCH /v1/subscriptionPlanAvailabilities/{id}/relationships/availableTerritories",
    "POST /v1/subscriptionPrices",
    "POST /v1/subscriptionPromotionalOffers",
    "PATCH /v1/subscriptionPromotionalOffers/{id}",
    "POST /v1/subscriptions",
    "PATCH /v1/subscriptions/{id}",
    "POST /v1/subscriptionSubmissions",
    "POST /v1/subscriptionVersions",
    "POST /v1/winBackOffers",
    "PATCH /v1/winBackOffers/{id}",
    "POST /v2/subscriptionGroupLocalizations",
    "PATCH /v2/subscriptionGroupLocalizations/{id}",
    "POST /v2/subscriptionImages",
    "PATCH /v2/subscriptionImages/{id}",
    "POST /v2/subscriptionLocalizations",
    "PATCH /v2/subscriptionLocalizations/{id}",
  ],
  gameCenter: [
    "POST /v1/gameCenterAchievementImages",
    "PATCH /v1/gameCenterAchievementImages/{id}",
    "POST /v1/gameCenterAchievementLocalizations",
    "PATCH /v1/gameCenterAchievementLocalizations/{id}",
    "POST /v1/gameCenterAchievementReleases",
    "POST /v1/gameCenterAchievements",
    "PATCH /v1/gameCenterAchievements/{id}",
    "PATCH /v1/gameCenterAchievements/{id}/relationships/activity",
    "PATCH /v1/gameCenterAchievements/{id}/relationships/groupAchievement",
    "POST /v1/gameCenterActivities",
    "PATCH /v1/gameCenterActivities/{id}",
    "POST /v1/gameCenterActivities/{id}/relationships/achievements",
    "POST /v1/gameCenterActivities/{id}/relationships/achievementsV2",
    "POST /v1/gameCenterActivities/{id}/relationships/leaderboards",
    "POST /v1/gameCenterActivities/{id}/relationships/leaderboardsV2",
    "POST /v1/gameCenterActivityImages",
    "PATCH /v1/gameCenterActivityImages/{id}",
    "POST /v1/gameCenterActivityLocalizations",
    "PATCH /v1/gameCenterActivityLocalizations/{id}",
    "POST /v1/gameCenterActivityVersionReleases",
    "POST /v1/gameCenterActivityVersions",
    "PATCH /v1/gameCenterActivityVersions/{id}",
    "POST /v1/gameCenterAppVersions",
    "PATCH /v1/gameCenterAppVersions/{id}",
    "POST /v1/gameCenterAppVersions/{id}/relationships/compatibilityVersions",
    "POST /v1/gameCenterChallengeImages",
    "PATCH /v1/gameCenterChallengeImages/{id}",
    "POST /v1/gameCenterChallengeLocalizations",
    "PATCH /v1/gameCenterChallengeLocalizations/{id}",
    "POST /v1/gameCenterChallenges",
    "PATCH /v1/gameCenterChallenges/{id}",
    "PATCH /v1/gameCenterChallenges/{id}/relationships/leaderboard",
    "PATCH /v1/gameCenterChallenges/{id}/relationships/leaderboardV2",
    "POST /v1/gameCenterChallengeVersionReleases",
    "POST /v1/gameCenterChallengeVersions",
    "PATCH /v1/gameCenterDetailPlayers/{id}",
    "POST /v1/gameCenterDetails",
    "PATCH /v1/gameCenterDetails/{id}",
    "PATCH /v1/gameCenterDetails/{id}/relationships/challengesMinimumPlatformVersions",
    "PATCH /v1/gameCenterDetails/{id}/relationships/gameCenterAchievements",
    "PATCH /v1/gameCenterDetails/{id}/relationships/gameCenterAchievementsV2",
    "PATCH /v1/gameCenterDetails/{id}/relationships/gameCenterLeaderboards",
    "PATCH /v1/gameCenterDetails/{id}/relationships/gameCenterLeaderboardSets",
    "PATCH /v1/gameCenterDetails/{id}/relationships/gameCenterLeaderboardSetsV2",
    "PATCH /v1/gameCenterDetails/{id}/relationships/gameCenterLeaderboardsV2",
    "PATCH /v1/gameCenterEnabledVersions/{id}/relationships/compatibleVersions",
    "POST /v1/gameCenterEnabledVersions/{id}/relationships/compatibleVersions",
    "POST /v1/gameCenterGroups",
    "PATCH /v1/gameCenterGroups/{id}",
    "PATCH /v1/gameCenterGroups/{id}/relationships/gameCenterAchievements",
    "PATCH /v1/gameCenterGroups/{id}/relationships/gameCenterAchievementsV2",
    "PATCH /v1/gameCenterGroups/{id}/relationships/gameCenterLeaderboards",
    "PATCH /v1/gameCenterGroups/{id}/relationships/gameCenterLeaderboardSets",
    "PATCH /v1/gameCenterGroups/{id}/relationships/gameCenterLeaderboardSetsV2",
    "PATCH /v1/gameCenterGroups/{id}/relationships/gameCenterLeaderboardsV2",
    "POST /v1/gameCenterLeaderboardEntrySubmissions",
    "POST /v1/gameCenterLeaderboardImages",
    "PATCH /v1/gameCenterLeaderboardImages/{id}",
    "POST /v1/gameCenterLeaderboardLocalizations",
    "PATCH /v1/gameCenterLeaderboardLocalizations/{id}",
    "POST /v1/gameCenterLeaderboardReleases",
    "POST /v1/gameCenterLeaderboards",
    "PATCH /v1/gameCenterLeaderboards/{id}",
    "PATCH /v1/gameCenterLeaderboards/{id}/relationships/activity",
    "PATCH /v1/gameCenterLeaderboards/{id}/relationships/challenge",
    "PATCH /v1/gameCenterLeaderboards/{id}/relationships/groupLeaderboard",
    "POST /v1/gameCenterLeaderboardSetImages",
    "PATCH /v1/gameCenterLeaderboardSetImages/{id}",
    "POST /v1/gameCenterLeaderboardSetLocalizations",
    "PATCH /v1/gameCenterLeaderboardSetLocalizations/{id}",
    "POST /v1/gameCenterLeaderboardSetMemberLocalizations",
    "PATCH /v1/gameCenterLeaderboardSetMemberLocalizations/{id}",
    "POST /v1/gameCenterLeaderboardSetReleases",
    "POST /v1/gameCenterLeaderboardSets",
    "PATCH /v1/gameCenterLeaderboardSets/{id}",
    "PATCH /v1/gameCenterLeaderboardSets/{id}/relationships/gameCenterLeaderboards",
    "POST /v1/gameCenterLeaderboardSets/{id}/relationships/gameCenterLeaderboards",
    "PATCH /v1/gameCenterLeaderboardSets/{id}/relationships/groupLeaderboardSet",
    "POST /v1/gameCenterMatchmakingQueues",
    "PATCH /v1/gameCenterMatchmakingQueues/{id}",
    "POST /v1/gameCenterMatchmakingRules",
    "PATCH /v1/gameCenterMatchmakingRules/{id}",
    "POST /v1/gameCenterMatchmakingRuleSets",
    "PATCH /v1/gameCenterMatchmakingRuleSets/{id}",
    "POST /v1/gameCenterMatchmakingRuleSetTests",
    "POST /v1/gameCenterMatchmakingTeams",
    "PATCH /v1/gameCenterMatchmakingTeams/{id}",
    "POST /v1/gameCenterPlayerAchievementSubmissions",
    "PATCH /v1/gameCenterScoreModerations/{id}",
    "POST /v2/gameCenterAchievementImages",
    "PATCH /v2/gameCenterAchievementImages/{id}",
    "POST /v2/gameCenterAchievementLocalizations",
    "PATCH /v2/gameCenterAchievementLocalizations/{id}",
    "POST /v2/gameCenterAchievements",
    "PATCH /v2/gameCenterAchievements/{id}",
    "PATCH /v2/gameCenterAchievements/{id}/relationships/activity",
    "POST /v2/gameCenterAchievementVersions",
    "POST /v2/gameCenterLeaderboardImages",
    "PATCH /v2/gameCenterLeaderboardImages/{id}",
    "POST /v2/gameCenterLeaderboardLocalizations",
    "PATCH /v2/gameCenterLeaderboardLocalizations/{id}",
    "POST /v2/gameCenterLeaderboards",
    "PATCH /v2/gameCenterLeaderboards/{id}",
    "PATCH /v2/gameCenterLeaderboards/{id}/relationships/activity",
    "PATCH /v2/gameCenterLeaderboards/{id}/relationships/challenge",
    "POST /v2/gameCenterLeaderboardSetImages",
    "PATCH /v2/gameCenterLeaderboardSetImages/{id}",
    "POST /v2/gameCenterLeaderboardSetLocalizations",
    "PATCH /v2/gameCenterLeaderboardSetLocalizations/{id}",
    "POST /v2/gameCenterLeaderboardSets",
    "PATCH /v2/gameCenterLeaderboardSets/{id}",
    "PATCH /v2/gameCenterLeaderboardSets/{id}/relationships/gameCenterLeaderboards",
    "POST /v2/gameCenterLeaderboardSets/{id}/relationships/gameCenterLeaderboards",
    "POST /v2/gameCenterLeaderboardSetVersions",
    "POST /v2/gameCenterLeaderboardVersions",
  ],
  alternativeDistribution: [
    "POST /v1/alternativeDistributionDomains",
    "POST /v1/alternativeDistributionKeys",
    "POST /v1/alternativeDistributionPackages",
    "POST /v1/marketplaceSearchDetails",
    "PATCH /v1/marketplaceSearchDetails/{id}",
    "POST /v1/marketplaceWebhooks",
    "PATCH /v1/marketplaceWebhooks/{id}",
  ],
  tooling: [
    "POST /v1/analyticsReportRequests",
    "POST /v1/ciBuildRuns",
    "POST /v1/ciWorkflows",
    "PATCH /v1/ciWorkflows/{id}",
    "PATCH /v2/sandboxTesters/{id}",
    "POST /v2/sandboxTestersClearPurchaseHistoryRequest",
  ],
  uploads: [
    "POST /v1/appClipAdvancedExperienceImages",
    "PATCH /v1/appClipAdvancedExperienceImages/{id}",
    "POST /v1/appClipHeaderImages",
    "PATCH /v1/appClipHeaderImages/{id}",
    "POST /v1/appEncryptionDeclarationDocuments",
    "PATCH /v1/appEncryptionDeclarationDocuments/{id}",
    "POST /v1/appEventScreenshots",
    "PATCH /v1/appEventScreenshots/{id}",
    "POST /v1/appEventVideoClips",
    "PATCH /v1/appEventVideoClips/{id}",
    "POST /v1/appPreviews",
    "PATCH /v1/appPreviews/{id}",
    "POST /v1/appPreviewSets",
    "PATCH /v1/appPreviewSets/{id}/relationships/appPreviews",
    "POST /v1/appScreenshots",
    "PATCH /v1/appScreenshots/{id}",
    "POST /v1/appScreenshotSets",
    "PATCH /v1/appScreenshotSets/{id}/relationships/appScreenshots",
    "POST /v1/backgroundAssets",
    "PATCH /v1/backgroundAssets/{id}",
    "POST /v1/backgroundAssetUploadFiles",
    "PATCH /v1/backgroundAssetUploadFiles/{id}",
    "POST /v1/backgroundAssetVersions",
    "POST /v1/buildUploadFiles",
    "PATCH /v1/buildUploadFiles/{id}",
    "POST /v1/buildUploads",
    "POST /v1/inAppPurchaseAppStoreReviewScreenshots",
    "PATCH /v1/inAppPurchaseAppStoreReviewScreenshots/{id}",
    "POST /v1/inAppPurchaseImages",
    "PATCH /v1/inAppPurchaseImages/{id}",
    "POST /v2/inAppPurchaseImages",
    "PATCH /v2/inAppPurchaseImages/{id}",
  ],
  inAppPurchasesOutsideSurface: [
    "POST /v1/inAppPurchaseLocalizations",
    "PATCH /v1/inAppPurchaseLocalizations/{id}",
    "POST /v1/inAppPurchaseOfferCodeCustomCodes",
    "PATCH /v1/inAppPurchaseOfferCodeCustomCodes/{id}",
    "POST /v1/inAppPurchaseOfferCodeOneTimeUseCodes",
    "PATCH /v1/inAppPurchaseOfferCodeOneTimeUseCodes/{id}",
    "POST /v1/inAppPurchaseOfferCodes",
    "PATCH /v1/inAppPurchaseOfferCodes/{id}",
    "POST /v1/inAppPurchaseSubmissions",
    "PATCH /v2/inAppPurchases/{id}",
  ],
  testFlightOutsideSurface: [
    "POST /v1/betaAppClipInvocationLocalizations",
    "PATCH /v1/betaAppClipInvocationLocalizations/{id}",
    "POST /v1/betaAppClipInvocations",
    "PATCH /v1/betaAppClipInvocations/{id}",
    "POST /v1/betaAppLocalizations",
    "PATCH /v1/betaAppLocalizations/{id}",
    "PATCH /v1/betaLicenseAgreements/{id}",
    "POST /v1/betaRecruitmentCriteria",
    "PATCH /v1/betaRecruitmentCriteria/{id}",
    "POST /v1/betaTesterInvitations",
    "POST /v1/betaTesters/{id}/relationships/betaGroups",
    "POST /v1/betaTesters/{id}/relationships/builds",
    "PATCH /v1/buildBetaDetails/{id}",
    "POST /v1/buildBetaNotifications",
    "PATCH /v1/builds/{id}/relationships/appEncryptionDeclaration",
    "POST /v1/builds/{id}/relationships/betaGroups",
    "POST /v1/builds/{id}/relationships/individualTesters",
  ],
  webhooksOutsideSurface: [
    "POST /v1/webhookDeliveries",
    "PATCH /v1/webhooks/{id}",
  ],
  versionsOutsideSurface: [
    "POST /v1/appStoreVersionExperiments",
    "PATCH /v1/appStoreVersionExperiments/{id}",
    "POST /v1/appStoreVersionExperimentTreatmentLocalizations",
    "POST /v1/appStoreVersionExperimentTreatments",
    "PATCH /v1/appStoreVersionExperimentTreatments/{id}",
    "POST /v1/appStoreVersionLocalizations/{id}/relationships/searchKeywords",
    "POST /v1/appStoreVersionPromotions",
    "PATCH /v1/appStoreVersions/{id}/relationships/appClipDefaultExperience",
    "PATCH /v1/reviewSubmissionItems/{id}",
    "POST /v2/appStoreVersionExperiments",
    "PATCH /v2/appStoreVersionExperiments/{id}",
  ],
  listingOutsideSurface: [
    "POST /v1/accessibilityDeclarations",
    "PATCH /v1/accessibilityDeclarations/{id}",
    "PATCH /v1/ageRatingDeclarations/{id}",
    "POST /v1/androidToIosAppMappingDetails",
    "PATCH /v1/androidToIosAppMappingDetails/{id}",
    "POST /v1/appClipAdvancedExperiences",
    "PATCH /v1/appClipAdvancedExperiences/{id}",
    "POST /v1/appClipDefaultExperienceLocalizations",
    "PATCH /v1/appClipDefaultExperienceLocalizations/{id}",
    "POST /v1/appClipDefaultExperiences",
    "PATCH /v1/appClipDefaultExperiences/{id}",
    "PATCH /v1/appClipDefaultExperiences/{id}/relationships/releaseWithAppStoreVersion",
    "POST /v1/appCustomProductPageLocalizations",
    "PATCH /v1/appCustomProductPageLocalizations/{id}",
    "POST /v1/appCustomProductPageLocalizations/{id}/relationships/searchKeywords",
    "POST /v1/appCustomProductPages",
    "PATCH /v1/appCustomProductPages/{id}",
    "POST /v1/appCustomProductPageVersions",
    "PATCH /v1/appCustomProductPageVersions/{id}",
    "POST /v1/appEncryptionDeclarations",
    "POST /v1/appEncryptionDeclarations/{id}/relationships/builds",
    "POST /v1/appEventLocalizations",
    "PATCH /v1/appEventLocalizations/{id}",
    "POST /v1/appEvents",
    "PATCH /v1/appEvents/{id}",
    "POST /v1/appInfoLocalizations",
    "PATCH /v1/appInfoLocalizations/{id}",
    "PATCH /v1/appInfos/{id}",
    "PATCH /v1/appTags/{id}",
    "POST /v1/customerReviewResponses",
    "POST /v1/endAppAvailabilityPreOrders",
    "POST /v1/endUserLicenseAgreements",
    "PATCH /v1/endUserLicenseAgreements/{id}",
    "POST /v1/nominations",
    "PATCH /v1/nominations/{id}",
    "POST /v1/routingAppCoverages",
    "PATCH /v1/routingAppCoverages/{id}",
    "PATCH /v1/territoryAvailabilities/{id}",
  ],
};
