# @generated by tools/gen-mirrors.ts — do not edit. Run `pnpm gen:mirrors`.
# Typed mirror of a Polaris Key product catalog, for the Godot SDK. Load it and hand it over:
#
#   PolarisKey.config.set_compiled_catalog(preload("res://catalog_generated.gd"))
#
# DEFAULTS holds each config key's catalog default: PolarisKey.config.get_value(key) returns it
# when nothing else resolves and the caller passed no fallback. A secret's default is omitted
# everywhere: anything compiled into a game can be extracted from it.
extends RefCounted

const CATALOG_VERSION := 3

const KEYS := [
	"dice.animSpeed",
	"audio.musicVolume",
	"ui.theme",
	"game.killSwitch",
	"difficulty.tuning",
	"leaderboard.apiKey",
	"extras.diceSkins",
]

const ENTRIES := [
	{
		"accessor": "dice.animSpeed",
		"category": "Dice",
		"default": 1.25,
		"description": "How fast the dice roll.",
		"key": "dice.animSpeed",
		"kind": "config",
		"label": "Animation speed",
		"managementDefault": "default",
		"schema": {
			"maximum": 4,
			"minimum": 0.25,
			"type": "number",
		},
		"ui": {
			"order": 1,
			"unit": "\u00D7",
			"widget": "stepper",
		},
	},
	{
		"accessor": "audio.music_volume",
		"category": "Audio",
		"default": 80,
		"description": "Line one.\nLine two, with a back\\slash and a tab\there.",
		"key": "audio.musicVolume",
		"kind": "config",
		"label": "M\u00FAsica \"principal\"",
		"schema": {
			"maximum": 100,
			"minimum": 0,
			"type": "integer",
		},
		"ui": {
			"advanced": true,
			"order": 2,
		},
	},
	{
		"accessor": "ui.theme",
		"category": "Interface",
		"default": "dark",
		"description": "Dashboard colour theme.",
		"key": "ui.theme",
		"kind": "config",
		"label": "Theme \U01F3B2",
		"schema": {
			"enum": [
				"dark",
				"light",
			],
			"type": "string",
		},
		"ui": {
			"optionLabels": {
				"dark": "Dunkel \u263E",
				"light": "Hell",
			},
			"widget": "select",
		},
	},
	{
		"category": "Operations",
		"default": false,
		"dependsOn": {
			"equals": "dark",
			"key": "ui.theme",
		},
		"description": "Turns online play off.",
		"key": "game.killSwitch",
		"kind": "config",
		"label": "Kill switch",
		"managementDefault": "enforced",
		"schema": {
			"type": "boolean",
		},
	},
	{
		"category": "Balance",
		"default": {
			"easy": 0.5,
			"hard": [
				1,
				2.5,
				3,
			],
			"none": null,
		},
		"description": "Per-difficulty multipliers.",
		"key": "difficulty.tuning",
		"kind": "config",
		"label": "Tuning",
		"managementDefault": "hidden",
		"schema": {
			"type": "object",
		},
	},
	{
		"category": "Online",
		"delivery": "edgeMint",
		"description": "Minted at the edge.",
		"key": "leaderboard.apiKey",
		"kind": "secret",
		"label": "Leaderboard token",
		"schema": {
			"type": "string",
		},
	},
	{
		"category": "Extras",
		"default": true,
		"description": "Unlocks the skin picker.",
		"grantLabel": "Dice skins",
		"key": "extras.diceSkins",
		"kind": "flag",
		"label": "Dice skins",
		"schema": {
			"type": "boolean",
		},
		"userGrant": true,
	},
]

const DEFAULTS := {
	"audio.musicVolume": 80,
	"dice.animSpeed": 1.25,
	"difficulty.tuning": {
		"easy": 0.5,
		"hard": [
			1,
			2.5,
			3,
		],
		"none": null,
	},
	"game.killSwitch": false,
	"ui.theme": "dark",
}


## The entry for `key` (read-only), or an empty Dictionary.
static func entry_by_key(key: String) -> Dictionary:
	for e in ENTRIES:
		if e["key"] == key:
			return e
	return {}


## Every entry of one kind ("config", "secret" or "flag"), in catalog order.
static func entries_by_kind(kind: String) -> Array:
	return ENTRIES.filter(func(e): return e["kind"] == kind)
