/**
 * The App Store Connect write gate's rule table (A-17a; notes/S-14 §7.5, owner decision 1 of
 * 2026-10-04), moved unchanged by A-18a into the store-agnostic gate (`../gate.ts`, the engine;
 * `../match/jsonapi.ts`, the body matcher). This file is the first adapter's rule set.
 *
 * The Worker holds the team's **Admin** App Store Connect key (`PLATFORM_ASC_API_KEY`, A-16). An
 * Admin key can invite users, create and revoke certificates and delete apps' identifiers; the
 * owner declined a narrower App Manager key, so THIS TABLE is the only barrier between a console
 * session (or a compromised Worker path) and those powers. It is deny-by-default:
 *
 *   - `AscClient.request` calls `checkAscRequest` **before the token thunk runs**. A request this
 *     module refuses throws `AscWriteDenied`: no token is minted and nothing is sent.
 *   - A write (`POST`, `PATCH`, `PUT`, `DELETE`) passes only when an `ASC_WRITE_ALLOW` rule matches
 *     its method and path template exactly AND its JSON:API body: the resource type, every
 *     attribute key, every relationship name and the type of every identifier it names, the
 *     `included` resource types, and the rule's own value checks. Anything else is refused.
 *   - No rule allows a `DELETE` (owner decision: never delete anything), and none touches users,
 *     certificates, devices or profiles.
 *   - Reads are free except personal data and team membership (`/v1/users*`,
 *     `/v1/userInvitations*`), refused outright.
 *   - Release, submit-for-review and price changes need a **typed confirmation**: the handler
 *     compares what the operator typed (the app's name) and only then passes
 *     `{ typedConfirmation: true }`. A rule with `confirm: "typed"` refuses a request without it,
 *     so a handler that forgets the check cannot send the write.
 *
 * `test/ascWriteGate.test.ts` classifies EVERY write operation of a pinned copy of Apple's OpenAPI
 * document (`test/fixtures/asc/openapi-writes.json`, generated by `scripts/asc-spec-writes.mjs`
 * from the spec whose SHA-256 is `ASC_SPEC_PIN`) as allowed here or denied, with a reason, in
 * `appStoreDenied.ts`. An unclassified operation, or an allow rule the spec does not have, fails
 * CI; so does a spec bump until each new write is classified. A change to `ASC_WRITE_ALLOW` is a
 * THREAT-MODEL §9 review trigger (any `core/storefront/rules/*` table).
 *
 * Messages never carry a body value: an `AscWriteDenied` names the method, the path template (or
 * the path when nothing matched) and a fixed reason.
 */

import type { SpecPin } from "../../adapters/contract.js";
import {
  compileGate,
  isOwnHookUrl,
  oneOf,
  PATH_SEGMENT,
  type Confirm,
  type DenyReason,
  type GateContext,
  type GateMethod,
  type GateRuleSet,
} from "../gate.js";
import { StoreWriteDenied } from "../errors.js";
import {
  attrs,
  matchJsonApi,
  type JsonApiRule,
} from "../match/jsonapi.js";
import { ASC_DENY_REASONS, ASC_WRITE_DENIED } from "./appStoreDenied.js";

/** The App Store Connect OpenAPI document the gate is classified against (S-14 §13). */
export const ASC_SPEC_PIN = {
  title: "App Store Connect API",
  version: "4.5",
  sha256: "1e8ef250d6a41bab0f5670b669abf3f06298ef129c8455ba258149fda86927b2",
} as const satisfies SpecPin;

// The engine's types under the names A-17 knows them by (`../gate.ts` documents each).
export type AscMethod = GateMethod;
export type AscGateContext = GateContext;
export type AscConfirm = Confirm;
export type AscDenyReason = DenyReason;
export type AscAllowRule = JsonApiRule;

/** A request the App Store Connect gate refused. Thrown before any token is minted or request sent. */
export class AscWriteDenied extends StoreWriteDenied {
  constructor(method: string, target: string, reason: AscDenyReason) {
    super(
      "app-store",
      method,
      target,
      reason,
      `App Store Connect write gate refused ${method} ${target}: ${reason}`,
    );
    this.name = "AscWriteDenied";
  }
}

// ── Value checks ─────────────────────────────────────────────────────────────────────────────

/**
 * Capability types the gate lets a bundle id gain. A-17b's wizard offers a subset; anything a
 * game on Polaris Key plausibly needs, nothing that reaches payments or device management.
 * App Attest is not here because it is not a capability (A-17h: no `APP_ATTEST` type exists; the
 * entitlement goes in the export preset).
 */
export const GATE_CAPABILITY_TYPES: readonly string[] = [
  "IN_APP_PURCHASE",
  "PUSH_NOTIFICATIONS",
  "GAME_CENTER",
  "ICLOUD",
  "APP_GROUPS",
  "ASSOCIATED_DOMAINS",
  "APPLE_ID_AUTH",
  "DATA_PROTECTION",
];

const ASN_SUFFIX = "distribution/hooks/app-store";
const WEBHOOK_SUFFIX = "distribution/hooks/asc";

// ── The allow table ──────────────────────────────────────────────────────────────────────────

/**
 * The approved write surface (owner decision 2, 2026-10-04). Everything not here is refused.
 * Keep rules exact: one method, one template, the narrowest attribute set the flow needs.
 */
export const ASC_WRITE_ALLOW: readonly AscAllowRule[] = [
  // ── Team provisioning (A-17b) ──
  {
    method: "POST",
    path: "/v1/bundleIds",
    type: "bundleIds",
    attributes: ["identifier", "name", "platform"],
    relationships: {},
    confirm: "plain",
    check: (d) =>
      oneOf(attrs(d).platform, ["IOS", "MAC_OS", "UNIVERSAL"])
        ? null
        : "value_not_allowed",
    why: "register a bundle id so the app record can be created in the portal (S-14 §5.1)",
  },
  {
    method: "POST",
    path: "/v1/bundleIdCapabilities",
    type: "bundleIdCapabilities",
    attributes: ["capabilityType", "settings"],
    relationships: { bundleId: "bundleIds" },
    confirm: "plain",
    check: (d) =>
      oneOf(attrs(d).capabilityType, GATE_CAPABILITY_TYPES)
        ? null
        : "value_not_allowed",
    why: "enable a capability on a bundle id (idempotent at Apple, A-17h)",
  },
  // ── Product app setup (A-17c) ──
  {
    method: "PATCH",
    path: "/v1/apps/{id}",
    type: "apps",
    attributes: [
      "subscriptionStatusUrl",
      "subscriptionStatusUrlVersion",
      "subscriptionStatusUrlForSandbox",
      "subscriptionStatusUrlVersionForSandbox",
    ],
    relationships: {},
    confirm: "plain",
    check: (d, ctx) => {
      const a = attrs(d);
      for (const k of [
        "subscriptionStatusUrl",
        "subscriptionStatusUrlForSandbox",
      ])
        if (
          k in a &&
          a[k] !== null &&
          !isOwnHookUrl(a[k], ASN_SUFFIX, ctx.hookOrigin)
        )
          return "value_not_allowed";
      for (const k of [
        "subscriptionStatusUrlVersion",
        "subscriptionStatusUrlVersionForSandbox",
      ])
        if (k in a && !oneOf(a[k], ["V1", "V2"], true))
          return "value_not_allowed";
      return null;
    },
    why: "point App Store Server Notifications at the product's own hook (A-17h: not persisted by Apple; the console falls back to a deep link and a verification read)",
  },
  {
    method: "POST",
    path: "/v2/appAvailabilities",
    type: "appAvailabilities",
    attributes: ["availableInNewTerritories"],
    relationships: {
      app: "apps",
      territoryAvailabilities: "territoryAvailabilities",
    },
    included: ["territoryAvailabilities"],
    confirm: "initial",
    why: "the default availability of a new app, only while none exists (a change could take the app off sale)",
  },
  {
    method: "POST",
    path: "/v1/appPriceSchedules",
    type: "appPriceSchedules",
    attributes: [],
    relationships: {
      app: "apps",
      baseTerritory: "territories",
      manualPrices: "appPrices",
    },
    included: ["appPrices", "territories"],
    confirm: "typed-or-initial",
    why: "the free price default of a new app; a later change is a price change (typed)",
  },
  // ── TestFlight (A-17c, A-17d) ──
  {
    method: "POST",
    path: "/v1/betaGroups",
    type: "betaGroups",
    attributes: [
      "name",
      "isInternalGroup",
      "hasAccessToAllBuilds",
      "publicLinkEnabled",
      "publicLinkLimitEnabled",
      "publicLinkLimit",
      "feedbackEnabled",
    ],
    relationships: {
      app: "apps",
      builds: "builds",
      betaTesters: "betaTesters",
    },
    confirm: "plain",
    why: "create an internal or external TestFlight group",
  },
  {
    method: "PATCH",
    path: "/v1/betaGroups/{id}",
    type: "betaGroups",
    // `isInternalGroup` cannot change after creation: Apple's update body has no such key.
    attributes: [
      "name",
      "publicLinkEnabled",
      "publicLinkLimitEnabled",
      "publicLinkLimit",
      "feedbackEnabled",
      "iosBuildsAvailableForAppleSiliconMac",
      "iosBuildsAvailableForAppleVision",
    ],
    relationships: {},
    confirm: "plain",
    why: "group settings, including P5-02's public-link control",
  },
  {
    method: "POST",
    path: "/v1/betaTesters",
    type: "betaTesters",
    attributes: ["email", "firstName", "lastName"],
    relationships: { betaGroups: "betaGroups", builds: "builds" },
    confirm: "plain",
    why: "invite a tester to a group (emails are never stored by Polaris Key)",
  },
  {
    method: "POST",
    path: "/v1/betaGroups/{id}/relationships/builds",
    type: "builds",
    attributes: [],
    relationships: {},
    confirm: "plain",
    why: "add a build to a group",
  },
  {
    method: "POST",
    path: "/v1/betaGroups/{id}/relationships/betaTesters",
    type: "betaTesters",
    attributes: [],
    relationships: {},
    confirm: "plain",
    why: "add existing testers to a group",
  },
  {
    method: "POST",
    path: "/v1/betaBuildLocalizations",
    type: "betaBuildLocalizations",
    attributes: ["locale", "whatsNew"],
    relationships: { build: "builds" },
    confirm: "plain",
    why: "TestFlight 'What to Test'",
  },
  {
    method: "PATCH",
    path: "/v1/betaBuildLocalizations/{id}",
    type: "betaBuildLocalizations",
    attributes: ["whatsNew"],
    relationships: {},
    confirm: "plain",
    why: "TestFlight 'What to Test'",
  },
  {
    method: "PATCH",
    path: "/v1/builds/{id}",
    type: "builds",
    // Never `expired`: expiring a build is irreversible (S-14 §7.5 denies it).
    attributes: ["usesNonExemptEncryption"],
    relationships: {},
    confirm: "plain",
    check: (d) =>
      typeof attrs(d).usesNonExemptEncryption === "boolean"
        ? null
        : "value_not_allowed",
    why: "answer export compliance once, so the build can enter review",
  },
  {
    method: "POST",
    path: "/v1/betaAppReviewSubmissions",
    type: "betaAppReviewSubmissions",
    attributes: [],
    relationships: { build: "builds" },
    confirm: "plain",
    why: "submit a build for external TestFlight review",
  },
  // ── Versions, submission, release (A-17d) ──
  {
    method: "POST",
    path: "/v1/appStoreVersions",
    type: "appStoreVersions",
    attributes: [
      "platform",
      "versionString",
      "copyright",
      "releaseType",
      "earliestReleaseDate",
      "reviewType",
    ],
    relationships: { app: "apps", build: "builds" },
    confirm: "plain",
    why: "create the App Store version a release ships as",
  },
  {
    method: "PATCH",
    path: "/v1/appStoreVersions/{id}",
    type: "appStoreVersions",
    // Not `downloadable` (that withdraws the version) and not the App Clip relationship.
    attributes: [
      "versionString",
      "copyright",
      "releaseType",
      "earliestReleaseDate",
      "reviewType",
    ],
    relationships: { build: "builds" },
    confirm: "plain",
    why: "version settings and its build",
  },
  {
    method: "PATCH",
    path: "/v1/appStoreVersions/{id}/relationships/build",
    type: "builds",
    attributes: [],
    relationships: {},
    confirm: "plain",
    why: "attach the release's build to the version",
  },
  {
    method: "POST",
    path: "/v1/appStoreVersionLocalizations",
    type: "appStoreVersionLocalizations",
    attributes: ["locale", "whatsNew", "promotionalText"],
    relationships: { appStoreVersion: "appStoreVersions" },
    confirm: "plain",
    why: "release notes (not the listing's description or keywords)",
  },
  {
    method: "PATCH",
    path: "/v1/appStoreVersionLocalizations/{id}",
    type: "appStoreVersionLocalizations",
    attributes: ["whatsNew", "promotionalText"],
    relationships: {},
    confirm: "plain",
    why: "release notes",
  },
  {
    method: "POST",
    path: "/v1/appStoreVersionPhasedReleases",
    type: "appStoreVersionPhasedReleases",
    attributes: ["phasedReleaseState"],
    relationships: { appStoreVersion: "appStoreVersions" },
    confirm: "plain",
    check: (d) =>
      oneOf(attrs(d).phasedReleaseState, ["INACTIVE", "ACTIVE"], true) ||
      !("phasedReleaseState" in attrs(d))
        ? null
        : "value_not_allowed",
    why: "choose a phased release for a version before it ships",
  },
  {
    method: "PATCH",
    path: "/v1/appStoreVersionPhasedReleases/{id}",
    type: "appStoreVersionPhasedReleases",
    attributes: ["phasedReleaseState"],
    relationships: {},
    confirm: "plain",
    check: (d, ctx) => {
      const state = attrs(d).phasedReleaseState;
      if (!oneOf(state, ["PAUSED", "ACTIVE", "COMPLETE"]))
        return "value_not_allowed";
      // Completing releases the version to every user at once: it is a release, so it is typed
      // (owner decision (b), 2026-10-04). Pausing and resuming stay a plain confirm.
      if (state === "COMPLETE" && ctx.typedConfirmation !== true)
        return "typed_confirmation_required";
      return null;
    },
    why: "P5-02's pause and resume controls, and complete (typed: it releases to everyone)",
  },
  {
    method: "POST",
    path: "/v1/reviewSubmissions",
    type: "reviewSubmissions",
    attributes: ["platform"],
    relationships: { app: "apps" },
    confirm: "plain",
    why: "open a review submission (one open per platform at Apple)",
  },
  {
    method: "POST",
    path: "/v1/reviewSubmissionItems",
    type: "reviewSubmissionItems",
    attributes: [],
    // A version, a non-consumable IAP version, or a Background Asset version: nothing else on
    // the approved surface rides a submission.
    relationships: {
      reviewSubmission: "reviewSubmissions",
      appStoreVersion: "appStoreVersions",
      inAppPurchaseVersion: "inAppPurchaseVersions",
      backgroundAssetVersion: "backgroundAssetVersions",
    },
    confirm: "plain",
    why: "add an item to the open review submission",
  },
  {
    method: "PATCH",
    path: "/v1/reviewSubmissions/{id}",
    type: "reviewSubmissions",
    attributes: ["submitted", "canceled"],
    relationships: {},
    confirm: "plain",
    check: (d, ctx) => {
      const a = attrs(d);
      const keys = Object.keys(a);
      if (keys.length !== 1 || a[keys[0]!] !== true) return "value_not_allowed";
      // Submitting for review is typed; cancelling is a plain confirm.
      if (keys[0] === "submitted" && ctx.typedConfirmation !== true)
        return "typed_confirmation_required";
      return null;
    },
    why: "submit for App Store review (typed) or cancel a submission",
  },
  {
    method: "POST",
    path: "/v1/appStoreVersionReleaseRequests",
    type: "appStoreVersionReleaseRequests",
    attributes: [],
    relationships: { appStoreVersion: "appStoreVersions" },
    confirm: "typed",
    why: "release a version held in PENDING_DEVELOPER_RELEASE (P5-02's release control)",
  },
  // ── Non-consumable IAPs (A-17e) ──
  {
    method: "POST",
    path: "/v2/inAppPurchases",
    type: "inAppPurchases",
    attributes: [
      "name",
      "productId",
      "inAppPurchaseType",
      "reviewNote",
      "familySharable",
    ],
    relationships: { app: "apps" },
    confirm: "plain",
    check: (d) =>
      attrs(d).inAppPurchaseType === "NON_CONSUMABLE"
        ? null
        : "value_not_allowed",
    why: "create a non-consumable IAP from a commerce mapping (matching P6-01)",
  },
  {
    method: "POST",
    path: "/v1/inAppPurchaseVersions",
    type: "inAppPurchaseVersions",
    attributes: [],
    relationships: { inAppPurchase: "inAppPurchases" },
    confirm: "plain",
    why: "an IAP version to submit",
  },
  {
    method: "POST",
    path: "/v2/inAppPurchaseLocalizations",
    type: "inAppPurchaseLocalizations",
    attributes: ["name", "locale", "description"],
    relationships: { version: "inAppPurchaseVersions" },
    confirm: "plain",
    why: "an IAP's display name and description",
  },
  {
    method: "PATCH",
    path: "/v2/inAppPurchaseLocalizations/{id}",
    type: "inAppPurchaseLocalizations",
    attributes: ["name", "description"],
    relationships: {},
    confirm: "plain",
    why: "an IAP's display name and description",
  },
  {
    method: "POST",
    path: "/v1/inAppPurchasePriceSchedules",
    type: "inAppPurchasePriceSchedules",
    attributes: [],
    relationships: {
      inAppPurchase: "inAppPurchases",
      baseTerritory: "territories",
      manualPrices: "inAppPurchasePrices",
    },
    included: ["inAppPurchasePrices", "territories"],
    confirm: "typed-or-initial",
    why: "an IAP's first price; a later change is a price change (typed)",
  },
  {
    method: "POST",
    path: "/v1/inAppPurchaseAvailabilities",
    type: "inAppPurchaseAvailabilities",
    attributes: ["availableInNewTerritories"],
    relationships: {
      inAppPurchase: "inAppPurchases",
      availableTerritories: "territories",
    },
    // Every availability write is typed (owner decision (c), 2026-10-04): it decides where the IAP
    // is sold, and an empty territory list takes it off sale everywhere.
    confirm: "typed",
    why: "where an IAP is sold (typed: an empty list takes it off sale)",
  },
  // ── P5-02's webhook (unchanged) ──
  {
    method: "POST",
    path: "/v1/webhooks",
    type: "webhooks",
    attributes: ["enabled", "eventTypes", "name", "secret", "url"],
    relationships: { app: "apps" },
    confirm: "plain",
    check: (d, ctx) =>
      isOwnHookUrl(attrs(d).url, WEBHOOK_SUFFIX, ctx.hookOrigin)
        ? null
        : "value_not_allowed",
    why: "P5-02's webhook registration, to the product's own hook",
  },
  {
    method: "POST",
    path: "/v1/webhookPings",
    type: "webhookPings",
    attributes: [],
    relationships: { webhook: "webhooks" },
    confirm: "plain",
    why: "P5-02's webhook ping",
  },
];

// ── Matching ─────────────────────────────────────────────────────────────────────────────────

/** Personal data and team membership: refused for every method, reads included. */
function isPersonalData(path: string): boolean {
  // Case-insensitive: a `/v1/Users` spelling is refused too, whatever Apple would answer.
  return /^\/v1\/(users|userinvitations)(\/|$)/i.test(path);
}

/** The App Store's rule set, as the store-agnostic engine takes it. */
export const APP_STORE_GATE: GateRuleSet<AscAllowRule> = {
  store: "app-store",
  specPin: ASC_SPEC_PIN,
  allow: ASC_WRITE_ALLOW,
  denied: ASC_WRITE_DENIED,
  denyReasons: ASC_DENY_REASONS,
  validPath: (path) =>
    /^\/v[12]\//.test(path) &&
    path
      .slice(4)
      .split("/")
      .every((s) => PATH_SEGMENT.test(s)),
  forbidden: isPersonalData,
  match: matchJsonApi,
  deny: (method, target, reason) => new AscWriteDenied(method, target, reason),
};

const GATE = compileGate(APP_STORE_GATE);

/** The allow rule for one method and request path, or null. */
export function findAllowRule(
  method: string,
  path: string,
): AscAllowRule | null {
  return GATE.find(method, path);
}

/**
 * Admit or refuse one App Store Connect request. Throws `AscWriteDenied`; returns the matched
 * rule for a write (null for an admitted read). Pure: no I/O, no token.
 */
export function checkAscRequest(
  method: string,
  path: string,
  body: unknown,
  ctx: AscGateContext = {},
): AscAllowRule | null {
  return GATE.check(method, path, body, ctx);
}
