/**
 * The Google Play write gate's rule table (A-18e; notes/S-15 §4.1, §6.2, owner decisions 2, 4 and 6
 * of 2026-10-04), on the store-agnostic engine (`../gate.ts`).
 *
 * The Worker holds a Play service account (A-16's `google-play.service-account`, or a product's own
 * `google-service-account`). Its one OAuth scope, `androidpublisher`, reaches every method of the
 * API; the Play Console permissions (S-15 decision 4: "Manage store presence", "Manage testing
 * tracks and edit tester lists" and the release permissions, never Admin, no "Manage policy
 * declarations") are the vendor-side control, and "Manage store presence" also covers PRICES. So
 * THIS TABLE is what keeps a console session (or a compromised Worker path) to the approved surface:
 *
 *   - `GoogleApiClient` (`connectors/play/client.ts`) calls `checkPlayRequest` **before its token
 *     thunk runs** for every Android Publisher request a gated client sends. A refusal throws
 *     `PlayWriteDenied`: no token is minted and nothing is sent.
 *   - A write passes only when a `PLAY_WRITE_ALLOW` rule matches its method and its path template
 *     (the discovery document's `flatPath`) exactly, AND its query parameters, AND its body: a
 *     JSON body's every key (`json`), an upload's content type and size (`upload`, from the blob
 *     store's record; the bytes are never seen here), or no body at all (`none`).
 *   - No rule allows a `DELETE` (owner rule: never delete; the engine refuses one at compile time),
 *     a user or grant, a signing key or app recovery, a refund or any other payment action, or a
 *     binary upload (CI only, decision 2).
 *   - Reads are free, except the Permissions API (`/developers/…`), refused for every method.
 *   - TYPED CONFIRMATION (S-15 §6.4): an `edits.commit` whose edit touches production or changes a
 *     release status, a production release `completed` or at a `userFraction` of 1.0, and any
 *     one-time product price after the initial one. The handler compares what the operator typed
 *     (Play's default-language title, `confirm.ts`) and only then asserts `typedConfirmation`.
 *     Since a commit has no body, the handler tells the gate what its edit holds through
 *     `resourceState` (`PLAY_EDIT_SCOPE`): a missing scope is treated as the most dangerous one.
 *     P5-03's rollout controls (fraction, halt, resume, complete, priority, and the vitals
 *     auto-halt) keep their own confirmations (`confirmRollback`) and assert
 *     `PLAY_EDIT_SCOPE.rolloutControl`, the one scope that is not typed here; making the
 *     production `complete` typed too is a proposed follow-up, not this table's change.
 *
 * `test/storefront/conformance.test.ts` classifies EVERY write method of the pinned discovery
 * document (`test/fixtures/play/discovery-writes.json`, generated by `scripts/play-spec-writes.mjs`
 * from the revision and canonical SHA-256 in `PLAY_SPEC_PIN`) as allowed here or denied, with a
 * reason, in `googlePlayDenied.ts`. A revision bump fails CI until each new write is classified. A
 * change to `PLAY_WRITE_ALLOW` is a THREAT-MODEL §9 review trigger.
 *
 * Messages never carry a body value: a `PlayWriteDenied` names the method, the template (or the
 * path when nothing matched) and a fixed reason.
 */

import type { SpecPin } from "../../adapters/contract.js";
import {
  checkConfirm,
  compileGate,
  isPlainObject,
  onlyKeys,
  type DenyReason,
  type GateContext,
  type GateRule,
  type GateRuleSet,
} from "../gate.js";
import { StoreWriteDenied } from "../errors.js";
import { matchJson, type JsonShape } from "../match/json.js";
import { matchUpload, type UploadDescriptor } from "../match/multipart.js";
import { PLAY_DENY_REASONS, PLAY_WRITE_DENIED } from "./googlePlayDenied.js";

/**
 * The discovery document the gate is classified against (S-15 §3). Google serves one revision with
 * its keys in a different order on each fetch, so the hash is over CANONICAL JSON (keys sorted, no
 * whitespace; `scripts/play-spec-writes.mjs`), not the raw bytes S-15 hashed.
 */
export const PLAY_SPEC_PIN = {
  title: "Google Play Android Developer API",
  version: "20261001",
  sha256: "b8a7f31d74baff7eb4a407b28b649975a769dbfba30d6a408cc3220bc6605ec4",
} as const satisfies SpecPin;

/** A request the Play gate refused. Thrown before any token is minted or request sent. */
export class PlayWriteDenied extends StoreWriteDenied {
  constructor(method: string, target: string, reason: DenyReason) {
    super(
      "google-play",
      method,
      target,
      reason,
      `Google Play write gate refused ${method} ${target}: ${reason}`,
    );
    this.name = "PlayWriteDenied";
  }
}

// ── What a gated request carries ─────────────────────────────────────────────────────────────

/**
 * The gate's view of one Play request (the engine's `body`): its query parameters, and either a
 * JSON body or an upload's descriptor. The client builds it from what it is about to send.
 */
export interface PlayGateRequest {
  query?: Record<string, string>;
  json?: unknown;
  upload?: UploadDescriptor;
}

/**
 * What a handler asserts about an edit it commits, or a track it patches (`ctx.resourceState`).
 * A commit carries no body, so this is the only way the gate learns what the edit holds.
 */
export const PLAY_EDIT_SCOPE = {
  /** Listing text, images, closed tracks, testers, release notes and releases on testing tracks
   *  only: no production track and no release-status change. Plain. */
  testing: "play-edit:testing",
  /** One of P5-03's rollout controls (`connectors/play/controls.ts`), with their own
   *  confirmations. Plain here (see the file comment). */
  rolloutControl: "play-edit:rollout-control",
  /** Production, or a release-status change: typed. Also what a missing scope means. */
  production: "play-edit:production",
} as const;

/** A query parameter's allowed values. */
interface QueryShape {
  values?: readonly string[];
  pattern?: RegExp;
}

export interface PlayRule extends GateRule {
  /** What the request carries besides its query. */
  carries: "none" | "json" | "upload";
  /** The query parameters it may carry; any other is refused. */
  query?: Readonly<Record<string, QueryShape>>;
  /** Query parameters it must carry. */
  requiredQuery?: readonly string[];
  /** `json`: the body's shape (`match/json.ts`). */
  json?: Readonly<Record<string, JsonShape>>;
  /** `upload`: the accepted media types and the byte cap (`match/multipart.ts`). */
  contentTypes?: readonly string[];
  maxBytes?: number;
  /** Value checks after the shape, with the request path (its `{placeholders}` filled). */
  check?: (
    req: PlayGateRequest,
    path: string,
    ctx: GateContext,
  ) => DenyReason | null;
}

// ── Shapes and value checks ──────────────────────────────────────────────────────────────────

const A = "/androidpublisher/v3/applications/{packageName}";
const E = `${A}/edits/{editId}`;

/** The 8 image types `edits.images.upload` takes (the enum minus `appImageTypeUnspecified`). */
export const PLAY_IMAGE_TYPES = [
  "phoneScreenshots",
  "sevenInchScreenshots",
  "tenInchScreenshots",
  "tvScreenshots",
  "wearScreenshots",
  "icon",
  "featureGraphic",
  "tvBanner",
] as const;
export type PlayImageType = (typeof PLAY_IMAGE_TYPES)[number];

/** `images.upload`'s cap (the discovery document's `mediaUpload.maxSize`: 15 MiB). */
export const PLAY_IMAGE_MAX_BYTES = 15 * 1024 * 1024;

/** The tracks every app has; a closed track created here may not take one of these names. */
export const PLAY_STANDARD_TRACKS = [
  "production",
  "beta",
  "alpha",
  "internal",
] as const;

/** A track id is production for the default form factor or any other (`wear:production`). */
export function isProductionTrack(track: string): boolean {
  return track === "production" || track.endsWith(":production");
}

const LOCALE = /^[a-z]{2,3}(-[A-Za-z0-9]{2,8}){0,2}$/;
const EMAIL = /^[^@\s]{1,64}@[^@\s]{1,189}$/;
const PRODUCT_ID = /^[a-z0-9][a-z0-9._]{0,138}$/;

const str = (max: number, values?: readonly string[]): JsonShape => ({
  kind: "string",
  max,
  ...(values ? { values } : {}),
});
const MONEY: JsonShape = {
  kind: "object",
  keys: {
    currencyCode: str(3),
    units: str(13),
    nanos: { kind: "number", min: 0, max: 999_999_999 },
  },
};
const RELEASE_STATUSES = ["draft", "inProgress", "halted", "completed"];
const TRACK_RELEASE: JsonShape = {
  kind: "object",
  keys: {
    name: str(50),
    versionCodes: { kind: "array", items: str(20), max: 50 },
    status: str(20, RELEASE_STATUSES),
    userFraction: { kind: "number", min: 0, max: 1 },
    inAppUpdatePriority: { kind: "number", min: 0, max: 5 },
    releaseNotes: {
      kind: "array",
      max: 100,
      items: {
        kind: "object",
        keys: { language: str(16), text: str(500) },
      },
    },
    countryTargeting: {
      kind: "object",
      keys: {
        countries: { kind: "array", items: str(2), max: 250 },
        includeRestOfWorld: { kind: "boolean" },
      },
    },
  },
};

/** The last segment of a request path (the gate sees paths unencoded). */
function lastSegment(path: string): string {
  return path.slice(path.lastIndexOf("/") + 1);
}

/** A segment of a request path by its index in the template's segments. */
function segmentAt(path: string, index: number): string {
  return path.split("/")[index] ?? "";
}

function isHttpsUrl(v: unknown, hosts?: readonly string[]): boolean {
  if (typeof v !== "string" || v.length > 2048) return false;
  try {
    const u = new URL(v);
    return (
      u.protocol === "https:" &&
      u.username === "" &&
      u.password === "" &&
      (!hosts || hosts.includes(u.hostname))
    );
  } catch {
    return false;
  }
}

const YOUTUBE = ["www.youtube.com", "youtube.com", "youtu.be", "m.youtube.com"];

/** Typed for a production touch, unless the handler asserted a plain scope. */
function editScopeConfirm(ctx: GateContext): DenyReason | null {
  if (
    ctx.resourceState === PLAY_EDIT_SCOPE.testing ||
    ctx.resourceState === PLAY_EDIT_SCOPE.rolloutControl
  )
    return null;
  return checkConfirm("typed", ctx);
}

// ── The allow table ──────────────────────────────────────────────────────────────────────────

/**
 * The approved write surface. Everything not here is refused. Keep rules exact: one method, one
 * template, the narrowest body and query the flow needs.
 */
export const PLAY_WRITE_ALLOW: readonly PlayRule[] = [
  // ── Edits ──
  {
    method: "POST",
    path: `${A}/edits`,
    carries: "json",
    json: {},
    confirm: "plain",
    why: "open an edit (every Play read and write is one), under the package's edit lease (S-15 §5.3)",
  },
  {
    method: "POST",
    path: `${E}:validate`,
    carries: "none",
    confirm: "plain",
    why: "check an edit before committing it (nothing changes)",
  },
  {
    method: "POST",
    path: `${E}:commit`,
    carries: "none",
    query: {
      changesInReviewBehavior: { values: ["ERROR_IF_IN_REVIEW"] },
      changesNotSentForReview: { values: ["true", "false"] },
    },
    requiredQuery: ["changesInReviewBehavior"],
    confirm: "plain",
    // Typed unless the handler asserts a testing-only edit or a P5-03 rollout control.
    check: (_req, _path, ctx) => editScopeConfirm(ctx),
    why: "commit an edit: never cancelling a review in flight (ERROR_IF_IN_REVIEW), optionally staged without sending for review; typed when production or a release status is touched",
  },
  // ── Listing (writeListingText) ──
  {
    method: "PATCH",
    path: `${E}/details`,
    carries: "json",
    json: {
      defaultLanguage: str(16),
      contactEmail: str(254),
      contactWebsite: str(2048),
    },
    confirm: "plain",
    check: (req) => {
      const j = req.json as Record<string, unknown>;
      if (
        j.defaultLanguage !== undefined &&
        !LOCALE.test(String(j.defaultLanguage))
      )
        return "value_not_allowed";
      if (j.contactEmail !== undefined && !EMAIL.test(String(j.contactEmail)))
        return "value_not_allowed";
      if (j.contactWebsite !== undefined && !isHttpsUrl(j.contactWebsite))
        return "value_not_allowed";
      return null;
    },
    why: "the app's default language, public contact email and website (no phone number)",
  },
  ...(["PATCH", "PUT"] as const).map(
    (method): PlayRule => ({
      method,
      path: `${E}/listings/{language}`,
      carries: "json",
      json: {
        language: str(16),
        title: str(30),
        shortDescription: str(80),
        fullDescription: str(4000),
        video: str(2048),
      },
      confirm: "plain",
      check: (req, path) => {
        const j = req.json as Record<string, unknown>;
        const language = lastSegment(path);
        if (!LOCALE.test(language)) return "value_not_allowed";
        if (j.language !== undefined && j.language !== language)
          return "value_not_allowed";
        if (
          j.video !== undefined &&
          j.video !== "" &&
          !isHttpsUrl(j.video, YOUTUBE)
        )
          return "value_not_allowed";
        return null;
      },
      why: "a language's title, short and full description and YouTube video, from the shared listing model (A-18b)",
    }),
  ),
  // ── Listing assets (writeListingAssets, decision 2: listing images from the blob store) ──
  {
    method: "POST",
    path: `${E}/listings/{language}/{imageType}`,
    carries: "upload",
    contentTypes: ["image/png", "image/jpeg"],
    maxBytes: PLAY_IMAGE_MAX_BYTES,
    query: {
      uploadType: { values: ["media"] },
      aiGeneratedState: {
        values: [
          "aiGeneratedStateNotAiGenerated",
          "aiGeneratedStateAiGeneratedDeveloperAttested",
        ],
      },
    },
    confirm: "plain",
    check: (_req, path) => {
      const parts = path.split("/");
      const imageType = parts[parts.length - 1]!;
      const language = parts[parts.length - 2]!;
      return LOCALE.test(language) &&
        (PLAY_IMAGE_TYPES as readonly string[]).includes(imageType)
        ? null
        : "value_not_allowed";
    },
    why: "upload one listing image (PNG or JPEG, at most 15 MiB) from the blob store; old images are removed by hand in the Console (decision 6)",
  },
  // ── Testing (testers) ──
  {
    method: "POST",
    path: `${E}/tracks`,
    carries: "json",
    json: {
      track: str(100),
      type: str(20, ["CLOSED_TESTING"]),
      formFactor: str(20, ["DEFAULT", "WEAR", "AUTOMOTIVE"]),
    },
    confirm: "plain",
    check: (req) => {
      const j = req.json as Record<string, unknown>;
      if (j.type !== "CLOSED_TESTING" || typeof j.track !== "string")
        return "value_not_allowed";
      if (
        !/^[A-Za-z0-9][A-Za-z0-9 ._-]{0,99}$/.test(j.track) ||
        (PLAY_STANDARD_TRACKS as readonly string[]).includes(
          j.track.toLowerCase(),
        )
      )
        return "value_not_allowed";
      return null;
    },
    why: "create a closed-testing track (the only type the API creates)",
  },
  {
    method: "PATCH",
    path: `${E}/testers/{track}`,
    carries: "json",
    json: {
      googleGroups: { kind: "array", items: str(254), max: 200 },
    },
    confirm: "plain",
    check: (req, path) => {
      if (isProductionTrack(lastSegment(path))) return "value_not_allowed";
      const groups = (req.json as { googleGroups?: unknown[] }).googleGroups;
      return (groups ?? []).every((g) => EMAIL.test(String(g)))
        ? null
        : "value_not_allowed";
    },
    why: "a testing track's Google Groups (the API takes no email lists; those stay in the Console)",
  },
  // ── Releases on tracks (release notes, testing releases, P5-03's rollout controls) ──
  {
    method: "PATCH",
    path: `${E}/tracks/{track}`,
    carries: "json",
    json: {
      track: str(100),
      releases: { kind: "array", items: TRACK_RELEASE, max: 20 },
    },
    confirm: "plain",
    check: (req, path, ctx) => {
      const track = lastSegment(path);
      const j = req.json as { track?: unknown; releases?: unknown[] };
      if (j.track !== track) return "value_not_allowed";
      if (ctx.resourceState === PLAY_EDIT_SCOPE.rolloutControl) return null;
      // A release on production that is (or reaches) everyone is a release: typed.
      const releasesToAll = (j.releases ?? []).some((r) => {
        const rel = r as { status?: unknown; userFraction?: unknown };
        return (
          rel.status === "completed" ||
          (typeof rel.userFraction === "number" && rel.userFraction >= 1)
        );
      });
      return isProductionTrack(track) && releasesToAll
        ? checkConfirm("typed", ctx)
        : null;
    },
    why: "a track's releases: release notes per language, testing releases, P5-03's rollout controls; a completed production release is typed",
  },
  // ── One-time products and prices (iap, pricing) ──
  {
    method: "PATCH",
    path: `${A}/onetimeproducts/{productId}`,
    carries: "json",
    query: {
      allowMissing: { values: ["true", "false"] },
      "regionsVersion.version": { pattern: /^[0-9A-Za-z._/-]{1,32}$/ },
      updateMask: {
        pattern:
          /^(listings|purchaseOptions|offerTags)(,(listings|purchaseOptions|offerTags)){0,2}$/,
      },
      latencyTolerance: {
        values: [
          "PRODUCT_UPDATE_LATENCY_TOLERANCE_LATENCY_SENSITIVE",
          "PRODUCT_UPDATE_LATENCY_TOLERANCE_LATENCY_TOLERANT",
        ],
      },
    },
    requiredQuery: ["regionsVersion.version"],
    json: {
      packageName: str(255),
      productId: str(139),
      listings: {
        kind: "array",
        max: 100,
        items: {
          kind: "object",
          keys: {
            languageCode: str(16),
            title: str(55),
            description: str(200),
          },
        },
      },
      purchaseOptions: {
        kind: "array",
        max: 1,
        items: {
          kind: "object",
          keys: {
            purchaseOptionId: str(63),
            buyOption: {
              kind: "object",
              keys: {
                legacyCompatible: { kind: "boolean" },
                multiQuantityEnabled: { kind: "boolean" },
              },
            },
            regionalPricingAndAvailabilityConfigs: {
              kind: "array",
              max: 250,
              items: {
                kind: "object",
                keys: {
                  regionCode: str(2),
                  price: MONEY,
                  availability: str(30, [
                    "AVAILABLE",
                    "NO_LONGER_AVAILABLE",
                    "AVAILABLE_IF_RELEASED",
                  ]),
                },
              },
            },
            newRegionsConfig: {
              kind: "object",
              keys: {
                usdPrice: MONEY,
                eurPrice: MONEY,
                availability: str(30, ["AVAILABLE", "NO_LONGER_AVAILABLE"]),
              },
            },
          },
        },
      },
      regionsVersion: { kind: "object", keys: { version: str(32) } },
    },
    confirm: "plain",
    check: (req, path, ctx) => {
      const j = req.json as Record<string, unknown>;
      const productId = lastSegment(path);
      if (!PRODUCT_ID.test(productId) || j.productId !== productId)
        return "value_not_allowed";
      if (j.packageName !== undefined && j.packageName !== segmentAt(path, 4))
        return "value_not_allowed";
      // Prices ride on the purchase options: the first set is `initial` (the pre-read found no
      // product), any later one is typed (S-15 §6.4).
      return j.purchaseOptions !== undefined
        ? checkConfirm("typed-or-initial", ctx)
        : null;
    },
    why: "create (allowMissing) or update a one-time product from dist_store_products (store play); a price after the initial one is typed",
  },
  {
    method: "POST",
    path: `${A}/pricing:convertRegionPrices`,
    carries: "json",
    json: { price: MONEY, productTaxCategoryCode: str(64) },
    confirm: "plain",
    why: "convert one price into every region's (a computation; nothing changes)",
  },
];

// ── Matching ─────────────────────────────────────────────────────────────────────────────────

/** The Play matcher: query, then the body by what the rule carries, then the rule's check. */
export function matchPlay(
  rule: PlayRule,
  path: string,
  body: unknown,
  ctx: GateContext,
): DenyReason | null {
  if (!isPlainObject(body) || !onlyKeys(body, ["query", "json", "upload"]))
    return "invalid_body";
  const req = body as PlayGateRequest;
  const query = req.query ?? {};
  if (!isPlainObject(query)) return "invalid_body";
  for (const [k, v] of Object.entries(query)) {
    if (!rule.query || !Object.hasOwn(rule.query, k))
      return "attribute_not_allowed";
    const shape = rule.query[k]!;
    if (typeof v !== "string" || v.length > 512) return "invalid_body";
    if (shape.values && !shape.values.includes(v)) return "value_not_allowed";
    if (shape.pattern && !shape.pattern.test(v)) return "value_not_allowed";
  }
  for (const k of rule.requiredQuery ?? [])
    if (!Object.hasOwn(query, k)) return "invalid_body";
  switch (rule.carries) {
    case "none":
      if (req.json !== undefined || req.upload !== undefined)
        return "invalid_body";
      break;
    case "json": {
      if (req.upload !== undefined) return "invalid_body";
      // The shape only: the rule's own check runs below, with the whole request.
      const r = matchJson(
        {
          method: rule.method,
          path: rule.path,
          confirm: "plain",
          why: rule.why,
          body: rule.json ?? {},
        },
        path,
        req.json,
        ctx,
      );
      if (r) return r;
      break;
    }
    case "upload": {
      if (req.json !== undefined) return "invalid_body";
      const r = matchUpload(
        {
          method: rule.method,
          path: rule.path,
          confirm: "plain",
          why: rule.why,
          contentTypes: rule.contentTypes ?? [],
          maxBytes: rule.maxBytes ?? 0,
        },
        path,
        req.upload,
        ctx,
      );
      if (r) return r;
      break;
    }
  }
  return rule.check ? rule.check(req, path, ctx) : null;
}

/** The Permissions API (`users`, `grants`): refused for every method, reads included. */
function isPermissionsPath(path: string): boolean {
  return /^\/androidpublisher\/v3\/developers(\/|$)/i.test(path);
}

/** One request-path segment: a package name, an edit id, a language, a track id (`wear:beta`). */
const PLAY_PLACEHOLDER = "[A-Za-z0-9][A-Za-z0-9 ._:+=-]{0,199}";
const PLAY_SEGMENT = new RegExp(`^${PLAY_PLACEHOLDER}$`);

/** The Play rule set, as the store-agnostic engine takes it. */
export const GOOGLE_PLAY_GATE: GateRuleSet<PlayRule> = {
  store: "google-play",
  specPin: PLAY_SPEC_PIN,
  allow: PLAY_WRITE_ALLOW,
  denied: PLAY_WRITE_DENIED,
  denyReasons: PLAY_DENY_REASONS,
  validPath: (path) =>
    path.startsWith("/androidpublisher/v3/") &&
    path
      .slice("/androidpublisher/v3/".length)
      .split("/")
      .every((s) => PLAY_SEGMENT.test(s)),
  forbidden: isPermissionsPath,
  placeholder: PLAY_PLACEHOLDER,
  match: matchPlay,
  deny: (method, target, reason) => new PlayWriteDenied(method, target, reason),
};

/** The compiled Play gate: what `GoogleApiClient` and the Play adapter consult. */
export const GOOGLE_PLAY_COMPILED_GATE = compileGate(GOOGLE_PLAY_GATE);

/**
 * Admit or refuse one Android Publisher request (the full path, `/androidpublisher/v3/…`, its
 * segments unencoded). Throws `PlayWriteDenied`; returns the matched rule for a write (null for an
 * admitted read). Pure: no I/O, no token.
 */
export function checkPlayRequest(
  method: string,
  path: string,
  req: PlayGateRequest | undefined,
  ctx: GateContext = {},
): PlayRule | null {
  return GOOGLE_PLAY_COMPILED_GATE.check(method, path, req, ctx);
}
