/**
 * Every Google Play Developer API write method the Play gate REFUSES, with the reason (A-18e;
 * notes/S-15 §4.1). The gate itself is deny-by-default (`googlePlay.ts`, on the engine
 * `../gate.ts`): this table changes nothing at run time. It exists so that every write method of
 * the pinned androidpublisher v3 discovery document is classified on purpose:
 * `test/storefront/conformance.test.ts` (item 1) requires each method in
 * `test/fixtures/play/discovery-writes.json` (generated by `scripts/play-spec-writes.mjs`) to
 * appear EITHER in `PLAY_WRITE_ALLOW` OR here, exactly once, and no entry here to be missing from
 * the document. A revision bump therefore fails CI until each new method is placed.
 *
 * Moving an entry from here to the allow table is a THREAT-MODEL §9 review trigger.
 */

const A = "/androidpublisher/v3/applications/{packageName}";
const E = `${A}/edits/{editId}`;
const SUBS = `${A}/subscriptions`;
const OTP = `${A}/oneTimeProducts/{productId}`;
const DEV = "/androidpublisher/v3/developers/{developersId}";
const STORE = "/androidpublisher/v3/appstore/{appStorePackageName}";

/** Why each group is refused. */
export const PLAY_DENY_REASONS = {
  delete:
    "No DELETE, ever (owner rule, 2026-10-04): listings, images, products, subscriptions, offers, users and grants are removed by hand in the Play Console. Replacing a screenshot set uploads the new images and links to the Console to remove the old ones (S-15 decision 6). Discarding a throwaway edit is `edits.delete`; P5-03's poll and controls send it outside this gate (the client's `discardEdit`), and no rule here may ever allow it.",
  users:
    "Console users and per-app grants (the Permissions API): a service account that could grant itself Admin outlives revoking the key (owner rule: never users or permissions).",
  signingKeys:
    "Play App Signing enrolment and key rotation, and remote app recovery: irreversible signing and device-reaching actions (owner rule: never signing keys).",
  payments:
    "Refunds, cancellations, deferrals, revocations, consumption and external transactions: payment actions (owner rule: never payments). P6-01 reads purchases and acknowledges them; it never refunds.",
  commerceRuntime:
    "Purchase acknowledgement is P6-01's, on its own purchase client (`commerce/play.ts`), never the storefront adapter's: it answers a player's purchase, not a provisioning step.",
  binaries:
    "Binaries (APKs, bundles, expansion and deobfuscation files, internal app sharing, system APKs): uploaded by the release workflow in CI, never by the Worker (S-15 decision 2, README decision 7).",
  policyDeclarations:
    "Data safety and policy declarations: a legal declaration the operator makes in the Play Console (S-15 decision 4; the service account holds no 'Manage policy declarations').",
  subscriptions:
    "Subscriptions, base plans and offers: outside the approved surface (one-time products only, matching P6-01).",
  oneTimeProductsOutsideSurface:
    "One-time product operations beyond `onetimeproducts.patch` with `allowMissing` (batch writes, purchase-option and offer state changes, offer reads by POST) and the legacy `inappproducts` API: outside the approved surface.",
  editsOutsideSurface:
    "Edit methods the surface does not need: the whole-resource `update` (PUT) of details, tracks and testers, where `patch` suffices and changes less.",
  outsideSurface:
    "Device tier configurations, review replies and the alternative-app-store review API: not on the provisioning surface (S-15 §4.1).",
} as const;

export type PlayDenyGroup = keyof typeof PLAY_DENY_REASONS;

/** `"<METHOD> <path template>"` per group, as the discovery document's `flatPath` spells it. */
export const PLAY_WRITE_DENIED: Readonly<
  Record<PlayDenyGroup, readonly string[]>
> = {
  delete: [
    `DELETE ${E}`,
    `DELETE ${E}/listings`,
    `DELETE ${E}/listings/{language}`,
    `DELETE ${E}/listings/{language}/{imageType}`,
    `DELETE ${E}/listings/{language}/{imageType}/{imageId}`,
    `DELETE ${A}/inappproducts/{sku}`,
    `DELETE ${OTP}`,
    `DELETE ${SUBS}/{productId}`,
    `DELETE ${SUBS}/{productId}/basePlans/{basePlanId}`,
    `DELETE ${SUBS}/{productId}/basePlans/{basePlanId}/offers/{offerId}`,
    `DELETE ${DEV}/users/{usersId}`,
    `DELETE ${DEV}/users/{usersId}/grants/{grantsId}`,
  ],
  users: [
    `POST ${DEV}/users`,
    `PATCH ${DEV}/users/{usersId}`,
    `POST ${DEV}/users/{usersId}/grants`,
    `PATCH ${DEV}/users/{usersId}/grants/{grantsId}`,
  ],
  signingKeys: [
    "POST /androidpublisher/v3/applications/{name}/appSigning:enrollApp",
    "POST /androidpublisher/v3/applications/{name}/appSigning:rotateAppSigningKey",
    `POST ${A}/appRecoveries`,
    `POST ${A}/appRecoveries/{appRecoveryId}:addTargeting`,
    `POST ${A}/appRecoveries/{appRecoveryId}:cancel`,
    `POST ${A}/appRecoveries/{appRecoveryId}:deploy`,
  ],
  payments: [
    `POST ${A}/orders/{orderId}:refund`,
    `POST ${A}/orders/{orderId}:reviewrefund`,
    `POST ${A}/purchases/products/{productId}/tokens/{token}:consume`,
    `POST ${A}/purchases/subscriptions/{subscriptionId}/tokens/{token}:cancel`,
    `POST ${A}/purchases/subscriptions/{subscriptionId}/tokens/{token}:defer`,
    `POST ${A}/purchases/subscriptionsv2/tokens/{token}:cancel`,
    `POST ${A}/purchases/subscriptionsv2/tokens/{token}:defer`,
    `POST ${A}/purchases/subscriptionsv2/tokens/{token}:revoke`,
    "POST /androidpublisher/v3/applications/{applicationsId}/externalTransactions",
    "POST /androidpublisher/v3/applications/{applicationsId}/externalTransactions/{externalTransactionsId}:refund",
  ],
  commerceRuntime: [
    `POST ${A}/purchases/products/{productId}/tokens/{token}:acknowledge`,
    `POST ${A}/purchases/subscriptions/{subscriptionId}/tokens/{token}:acknowledge`,
  ],
  binaries: [
    `POST ${E}/apks`,
    `POST ${E}/apks/externallyHosted`,
    `POST ${E}/apks/{apkVersionCode}/deobfuscationFiles/{deobfuscationFileType}`,
    `PATCH ${E}/apks/{apkVersionCode}/expansionFiles/{expansionFileType}`,
    `POST ${E}/apks/{apkVersionCode}/expansionFiles/{expansionFileType}`,
    `PUT ${E}/apks/{apkVersionCode}/expansionFiles/{expansionFileType}`,
    `POST ${E}/bundles`,
    `POST ${A}/systemApks/{versionCode}/variants`,
    "POST /androidpublisher/v3/applications/internalappsharing/{packageName}/artifacts/apk",
    "POST /androidpublisher/v3/applications/internalappsharing/{packageName}/artifacts/bundle",
    `POST ${STORE}/apps/{packageName}/apks:upload`,
  ],
  policyDeclarations: [
    `POST ${A}/dataSafety`,
    `POST ${STORE}/apps/{packageName}/policyDeclarationFiles:upload`,
  ],
  subscriptions: [
    `POST ${SUBS}`,
    `POST ${SUBS}:batchUpdate`,
    `PATCH ${SUBS}/{productId}`,
    `POST ${SUBS}/{productId}:archive`,
    `POST ${SUBS}/{productId}/basePlans:batchMigratePrices`,
    `POST ${SUBS}/{productId}/basePlans:batchUpdateStates`,
    `POST ${SUBS}/{productId}/basePlans/{basePlanId}:activate`,
    `POST ${SUBS}/{productId}/basePlans/{basePlanId}:deactivate`,
    `POST ${SUBS}/{productId}/basePlans/{basePlanId}:migratePrices`,
    `POST ${SUBS}/{productId}/basePlans/{basePlanId}/offers`,
    `POST ${SUBS}/{productId}/basePlans/{basePlanId}/offers:batchGet`,
    `POST ${SUBS}/{productId}/basePlans/{basePlanId}/offers:batchUpdate`,
    `POST ${SUBS}/{productId}/basePlans/{basePlanId}/offers:batchUpdateStates`,
    `PATCH ${SUBS}/{productId}/basePlans/{basePlanId}/offers/{offerId}`,
    `POST ${SUBS}/{productId}/basePlans/{basePlanId}/offers/{offerId}:activate`,
    `POST ${SUBS}/{productId}/basePlans/{basePlanId}/offers/{offerId}:deactivate`,
  ],
  oneTimeProductsOutsideSurface: [
    `POST ${A}/oneTimeProducts:batchDelete`,
    `POST ${A}/oneTimeProducts:batchUpdate`,
    `POST ${OTP}/purchaseOptions:batchDelete`,
    `POST ${OTP}/purchaseOptions:batchUpdateStates`,
    `POST ${OTP}/purchaseOptions/{purchaseOptionId}/offers:batchDelete`,
    `POST ${OTP}/purchaseOptions/{purchaseOptionId}/offers:batchGet`,
    `POST ${OTP}/purchaseOptions/{purchaseOptionId}/offers:batchUpdate`,
    `POST ${OTP}/purchaseOptions/{purchaseOptionId}/offers:batchUpdateStates`,
    `POST ${OTP}/purchaseOptions/{purchaseOptionId}/offers/{offerId}:activate`,
    `POST ${OTP}/purchaseOptions/{purchaseOptionId}/offers/{offerId}:cancel`,
    `POST ${OTP}/purchaseOptions/{purchaseOptionId}/offers/{offerId}:deactivate`,
    `POST ${A}/inappproducts`,
    `POST ${A}/inappproducts:batchDelete`,
    `POST ${A}/inappproducts:batchUpdate`,
    `PATCH ${A}/inappproducts/{sku}`,
    `PUT ${A}/inappproducts/{sku}`,
  ],
  editsOutsideSurface: [
    `PUT ${E}/details`,
    `PUT ${E}/testers/{track}`,
    `PUT ${E}/tracks/{track}`,
  ],
  outsideSurface: [
    `POST ${A}/deviceTierConfigs`,
    `POST ${A}/reviews/{reviewId}:reply`,
    `POST ${STORE}/apps:create`,
    `POST ${STORE}/apps:update`,
    `POST ${STORE}/apps/{packageName}:updateAppStoreHostedAppPublishStatus`,
    `POST ${STORE}/apps/{packageName}/images:upload`,
  ],
};
