// @polaris-key/protocol — the Polaris Key wire-contract types ONLY (no runtime, no crypto).
// Organized by service since wire contract v3. There is exactly ONE identifier set: this
// barrel re-exports core's values verbatim (`ISSUER` = `key.plrs.im`, the `X-PKey-*` headers),
// so an import from here and an import from `@polaris-key/protocol/core` can never disagree.
// Prefer the service subpaths (`/core`, `/license`, `/config`, `/release`, `/update`, `/trust`,
// `/distribution`, `/packs`)
// in new code; the barrel exists for consumers that want one import.

export {
  ISSUER,
  HEADER_DEVICE,
  HEADER_VERSION,
  HEADER_CHANNEL,
  HEADER_SDK_NAME,
  HEADER_SDK_VERSION,
  HEADER_PLATFORM,
  HEADER_ARCH,
  PROTOCOL_VERSION,
  MAX_WIRE_INTEGER,
  MAX_JSON_DEPTH,
  MAX_RECORD_JWS_BYTES,
  REVOCATION_REASON_MAX_BYTES,
  MAX_DELEGATION_TTL_SECONDS,
  MAX_DELEGATION_TYPES,
  DATA_ONLY_HEAD_BYTES,
  DATA_ONLY_TAIL_BYTES,
  MAX_DELEGATIONS_PER_CHECK,
  MAX_BUNDLE_BYTES,
  FINGERPRINT_COMPONENTS,
  FINGERPRINT_ANCHOR,
  FINGERPRINT_HASH_PREFIX,
  FINGERPRINT_COMPONENT_LENGTH,
  FINGERPRINT_HWID_LENGTH,
  FINGERPRINT_TOLERANCE,
  MAX_DEVICE_PROBES,
  DOC_EXPIRY_SECONDS,
  SECONDS_PER_DAY,
  CHANNEL_STABLE,
  CHANNEL_BETA,
  CHANNEL_PR,
  CHANNEL_DEV,
  CHANNEL_ALIASES,
  CHANNEL_NAME_PATTERN,
  PR_CHANNEL_PATTERN,
  PR_NUMBER_MAX_DIGITS,
  PLATFORM_SPELLINGS,
  ARCH_SPELLINGS,
  MAX_PACK_VARIANTS,
  MAX_VARIANT_DELTAS,
  MAX_CONTENT_PINS,
  MAX_BUILD_EMBEDS,
  MAX_INDEX_FILES,
  MAX_FILES_INDEX_BYTES,
  MAX_PACK_PATH_BYTES,
  FILES_FORMAT,
  PATCH_FORMAT,
  MARKER_FORMAT,
  CONTENT_STAMP_FORMAT,
  CHUNKS_FORMAT,
  MAX_CHUNK_INDEX_BYTES,
  MAX_CHUNK_BYTES,
} from "./core.js";
export type {
  JSONValue,
  ManagementState,
  ManagedEntry,
  DocClaims,
  BundleDoc,
  RegistrationPolicy,
  DeviceMetadata,
  FingerprintComponent,
  HardwareFingerprint,
  FingerprintMode,
  DeviceProbeResult,
  DeviceFacts,
  PolarisErrorCode,
  PolarisErrorBody,
  BuildChannel,
  ClientPlatform,
  ClientArch,
} from "./core.js";

export type {
  DocProfile,
  LicenseDoc,
  LicenseStatus,
  BlockReason,
  AllowedRange,
  ActivationSource,
} from "./license.js";

export type { ConfigDoc, SecretDelivery } from "./config.js";

export {
  DEFAULT_RELEASE_ACCESS,
  BUILD_ID_PATTERN,
  RECORD_KINDS,
  RESERVED_RECORD_KINDS,
  DELEGATED_KID_PATTERN,
} from "./release.js";
export type {
  ReleaseAccess,
  ReleaseAccessPolicy,
  ReleaseRecordDoc,
  ReleaseRecordBuild,
  ReleaseRecordArtifact,
  RevocationRecordDoc,
  RevocationReplacement,
  DelegationRecordDoc,
} from "./release.js";

export {
  FEED_VERSION_SCHEMES,
  FEED_TTL_SECONDS,
  MAX_FEED_TTL_SECONDS,
  ROLLOUT_BUCKETS,
  FEED_PLATFORM_PATTERN,
  UPDATE_ACTIONS,
  NONE_REASONS,
  BLOCKED_REASONS,
  BINARY_METHODS,
  MAX_FEED_REVOCATIONS,
} from "./update.js";
export type {
  UpdateArch,
  FeedVersionScheme,
  ReleasePin,
  FeedRollout,
  FeedOutletEntry,
  FeedTarget,
  FeedApp,
  FeedSelector,
  ChannelFeedDoc,
  UpdateAction,
  UpdateNoneReason,
  UpdateBlockedReason,
  BinaryMethod,
  UpdateOutlet,
  InstalledBuild,
  StagedUpdate,
  UpdateDecisionInput,
  DecisionRelease,
  UpdateDecision,
  UpdateCheck,
  FeedPackRelease,
  FeedPackRow,
  FeedPackGate,
  FeedPackOutlet,
  FeedPackSets,
  FeedPackFloor,
  FeedRevocation,
  FeedContent,
  ContentBlock,
  ContentRevocationInput,
  UpdateContentInput,
  PackTarget,
  PacksDecision,
} from "./update.js";

export {
  OUTLET_KINDS,
  OUTLET_ID_PATTERN,
  OUTLET_UNKNOWN,
  BINARY_UPDATES_ORDER,
  OUTLET_CAPABILITY_DEFAULTS,
  OUTLET_PLATFORMS,
  PLATFORM_NARROWING,
  OUTLET_SUBKINDS,
  SUBKIND_NARROWING,
  LISTING_URL_PREFIXES,
  OUTLET_CONFIDENCES,
} from "./distribution.js";
export type {
  OutletKind,
  BinaryUpdates,
  OutletCapabilities,
  CapabilityNarrowing,
  OutletSubkind,
  OutletConfidence,
} from "./distribution.js";

export {
  PACK_TYPE_PATTERN,
  VOCAB_TOKEN_PATTERN,
  OBJECT_FORMAT_PATTERN,
  HANDLER_PREFIX_PATTERN,
  ENTITLEMENT_PATTERN,
  VARIANT_AXIS_PATTERN,
  VARIANT_VALUE_PATTERN,
  ENGINE_PATTERN,
  PACK_TYPES,
  DELEGABLE_PACK_TYPES,
  DATA_ONLY_EXTENSIONS,
  FILES_LAYOUTS,
  CONTENT_CODECS,
  PATCH_METHODS,
  RESERVED_PATCH_METHODS,
  PATCH_SCOPES,
  PACK_DELIVERIES,
  PACK_ACTIVATIONS,
  VARIANT_AXES,
  ZSTD_DICTIONARY_MAGIC,
  MARKER_SUFFIX,
  TREE_MARKER_PATH,
  CONTENT_STAMP_FILE,
} from "./packs.js";
export type {
  PackType,
  DelegablePackType,
  DataOnlyExtension,
  FilesLayout,
  ContentCodec,
  PatchMethod,
  PatchScope,
  PackDelivery,
  PackActivation,
  VariantAxis,
  ObjectRef,
  FilesRef,
  PayloadDelta,
  FilesDelta,
  PackVariant,
  ChunkParams,
  ChunksRef,
  ChunkRecord,
  ChunkIndexDoc,
  PackRecordDoc,
  ContentPin,
  ContentHold,
  ContentExpect,
  AppContent,
  FilesIndexEntry,
  FilesIndexDoc,
  PatchEntry,
  PatchDoc,
  MarkerDoc,
  ContentStampDoc,
} from "./packs.js";

export type {
  SigningKeyStatus,
  TrustManifestKey,
  TrustManifestDoc,
} from "./trust.js";
