// @pkey-feature config.mirror
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, it, expect } from "vitest";
import type { ConfigEntry, ProductCatalog } from "@polaris-key/catalog";
import {
  gdStr,
  gdValue,
  renderGdscript,
  renderPython,
  renderSwift,
  renderTs,
} from "./gen-mirrors.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
/** The Godot runner loads this pair (sdks/godot/tests/config/): the sample must be exactly what
 *  the renderer writes for the fixture catalog, so the runner is testing today's renderer. */
const GODOT_FIXTURE = join(ROOT, "sdks/godot/tests/config/catalog.json");
const GODOT_SAMPLE = join(ROOT, "sdks/godot/tests/config/catalog_generated.gd");

const CATALOG: ProductCatalog = {
  schemaVersion: 2,
  entries: [
    {
      key: "run.concurrency",
      kind: "config",
      category: "Run",
      label: "Parallel",
      description: "How many.",
      accessor: "run.concurrency",
      schema: { type: "integer", minimum: 1, maximum: 8 },
      managementDefault: "default",
      ui: { widget: "stepper" },
    },
    {
      key: "polarisVpn",
      kind: "flag",
      category: "VPN",
      label: "VPN",
      description: "Master switch.",
      schema: { type: "boolean" },
      userGrant: true,
      grantLabel: "Polaris VPN",
    },
  ],
};

const [RUN, VPN] = CATALOG.entries as [ConfigEntry, ConfigEntry];

describe("gen-mirrors", () => {
  it("TS mirror has version, key union, and data", () => {
    const out = renderTs(CATALOG);
    expect(out).toContain("CATALOG_VERSION = 2");
    expect(out).toContain('"run.concurrency" | "polarisVpn"');
    expect(out).toContain('"key": "run.concurrency"');
    expect(out).toContain("export const entryByKey");
  });

  it("Python mirror has dataclass, Literal keys, and entries", () => {
    const out = renderPython(CATALOG);
    expect(out).toContain("CATALOG_VERSION = 2");
    expect(out).toContain('Literal["run.concurrency", "polarisVpn"]');
    expect(out).toContain('ConfigEntry(key="run.concurrency"');
    expect(out).toContain("user_grant=True");
    expect(out).toContain("def entry_by_key");
  });

  it("Swift mirror has struct, enum, and entries", () => {
    const out = renderSwift(CATALOG);
    expect(out).toContain("struct ConfigSchemaEntry");
    expect(out).toContain("enum ProductCatalog");
    expect(out).toContain("static let version = 2");
    expect(out).toContain(
      'ConfigSchemaEntry(key: "run.concurrency", kind: .config',
    );
    expect(out).toContain("kind: .flag");
  });

  it("Swift mirror escapes the `default` reserved word in the enum + member access", () => {
    const out = renderSwift(CATALOG);
    // The enum case is backtick-escaped.
    expect(out).toContain(
      "enum ManagementState: String { case `default`, enforced, hidden }",
    );
    // A managementDefault of "default" emits an escaped member access, not `.default`.
    expect(out).toContain("managementDefault: .`default`");
    expect(out).not.toContain("managementDefault: .default");
  });

  describe("GDScript mirror", () => {
    it("has the version, the keys, the entries and entry_by_key", () => {
      const out = renderGdscript(CATALOG);
      expect(out).toContain("const CATALOG_VERSION := 2\n");
      expect(out).toContain(
        'const KEYS := [\n\t"run.concurrency",\n\t"polarisVpn",\n]',
      );
      expect(out).toContain("const ENTRIES := [");
      expect(out).toContain('\t\t"key": "run.concurrency",');
      expect(out).toContain('\t\t"kind": "flag",');
      expect(out).toContain(
        "static func entry_by_key(key: String) -> Dictionary:",
      );
      expect(out).toContain(
        "static func entries_by_kind(kind: String) -> Array:",
      );
      // No global class name: a game may mirror more than one product.
      expect(out).not.toContain("class_name");
      expect(out.startsWith("# @generated by tools/gen-mirrors.ts")).toBe(true);
    });

    it("sorts object keys and keeps the entry order", () => {
      const out = renderGdscript(CATALOG);
      const entry = out.slice(out.indexOf("const ENTRIES"));
      const order = ["accessor", "category", "description", "key", "kind"].map(
        (k) => entry.indexOf(`"${k}":`),
      );
      expect([...order].sort((a, b) => a - b)).toEqual(order);
      expect(entry.indexOf('"run.concurrency"')).toBeLessThan(
        entry.indexOf('"polarisVpn"'),
      );
      // Reordering the source object's keys changes nothing.
      const shuffled: ProductCatalog = {
        schemaVersion: 2,
        entries: CATALOG.entries.map(
          (e) =>
            Object.fromEntries(
              Object.entries(e).reverse(),
            ) as unknown as (typeof CATALOG.entries)[number],
        ),
      };
      expect(renderGdscript(shuffled)).toBe(out);
    });

    it("emits DEFAULTS for config keys only, sorted, never a secret's", () => {
      const out = renderGdscript({
        schemaVersion: 1,
        entries: [
          { ...RUN, key: "z.last", default: 3 },
          {
            ...RUN,
            key: "a.first",
            default: { b: [1, 2.5], a: null },
          },
          { ...VPN, default: true },
          {
            ...RUN,
            key: "api.key",
            kind: "secret",
            default: "hunter2",
            delivery: "edgeMint",
          },
        ],
      });
      const defaults = out.slice(out.indexOf("const DEFAULTS"));
      expect(defaults).toContain(
        'const DEFAULTS := {\n\t"a.first": {\n\t\t"a": null,\n\t\t"b": [\n\t\t\t1,\n\t\t\t2.5,\n\t\t],\n\t},\n\t"z.last": 3,\n}',
      );
      expect(defaults).not.toContain("polarisVpn");
      expect(out).not.toContain("hunter2");
      expect(out).toContain('"delivery": "edgeMint"');
    });

    it("escapes quotes, backslashes, control characters and non-ASCII labels", () => {
      expect(gdStr('say "hi"')).toBe('"say \\"hi\\""');
      expect(gdStr("a\\b")).toBe('"a\\\\b"');
      expect(gdStr("one\ntwo\tthree\r")).toBe('"one\\ntwo\\tthree\\r"');
      expect(gdStr("bell\u0007 del\u007f")).toBe('"bell\\u0007 del\\u007F"');
      expect(gdStr("Música ×")).toBe('"M\\u00FAsica \\u00D7"');
      expect(gdStr("dice 🎲")).toBe('"dice \\U01F3B2"');
      // ASCII only on output, whatever the input.
      const out = renderGdscript({
        schemaVersion: 1,
        entries: [{ ...RUN, label: 'Música "principal" 🎲 \\ ☾' }],
      });
      // eslint-disable-next-line no-control-regex
      expect(/^[\x00-\x7f]*$/.test(out.slice(out.indexOf("\n")))).toBe(true);
      expect(out).toContain(
        '"label": "M\\u00FAsica \\"principal\\" \\U01F3B2 \\\\ \\u263E",',
      );
    });

    it("writes numbers GDScript parses with the right type", () => {
      expect(gdValue(3)).toBe("3");
      expect(gdValue(-0)).toBe("0");
      expect(gdValue(1.5)).toBe("1.5");
      expect(gdValue(1e-7)).toBe("1e-7");
      expect(gdValue(1e21)).toBe("1e+21");
      // Beyond 2^53 an integer is written as a float literal, never an int64 overflow.
      expect(gdValue(2 ** 60)).toBe("1152921504606847000.0");
      expect(gdValue([])).toBe("[]");
      expect(gdValue({})).toBe("{}");
      expect(gdValue(null)).toBe("null");
    });

    it("the Godot runner's sample is today's output for its fixture", () => {
      const catalog = JSON.parse(
        readFileSync(GODOT_FIXTURE, "utf8"),
      ) as ProductCatalog;
      expect(readFileSync(GODOT_SAMPLE, "utf8")).toBe(renderGdscript(catalog));
    });
  });
});
