// Generalized schema-mirror generator (the multi-language successor to djdl's
// scripts/gen-config-schema.ts). Given a product catalog JSON (the `/<product>/schema`
// shape), it emits self-contained typed mirrors for products that want compile-time
// config types: TypeScript, Python (dataclasses), and Swift. Products that stay purely
// data-driven skip this and read the catalog at runtime.
//
//   tsx tools/gen-mirrors.ts --catalog <path> --out-dir <dir> --lang ts,python,swift
//   tsx tools/gen-mirrors.ts ... --check     # CI drift guard (exit 1 if stale)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ConfigEntry, ProductCatalog } from "@polaris-key/catalog";

const BANNER =
  "// @generated by tools/gen-mirrors.ts — do not edit. Run `pnpm gen:mirrors`.";
const PY_BANNER =
  "# @generated by tools/gen-mirrors.ts — do not edit. Run `pnpm gen:mirrors`.";

// ── TypeScript mirror ────────────────────────────────────────────────────────
export function renderTs(catalog: ProductCatalog): string {
  const keys = catalog.entries.map((e) => JSON.stringify(e.key)).join(" | ");
  return `${BANNER}
// Typed mirror of a Polaris Key product catalog.

export const CATALOG_VERSION = ${catalog.schemaVersion};

export type ConfigKind = "config" | "secret" | "flag";
export type ManagementState = "default" | "enforced" | "hidden";
export type JsonSchema = Record<string, unknown>;

export interface ConfigEntry {
  key: string;
  kind: ConfigKind;
  category: string;
  label: string;
  description: string;
  schema: JsonSchema;
  examples?: unknown[];
  default?: unknown;
  secret?: boolean;
  managementDefault?: ManagementState;
  userGrant?: boolean;
  grantLabel?: string;
  ui?: Record<string, unknown>;
  dependsOn?: { key: string; equals: unknown };
  accessor?: string;
}

/** Every declared key in this catalog. */
export type ConfigKey = ${keys || "never"};

export const CATALOG: readonly ConfigEntry[] = ${JSON.stringify(catalog.entries, null, 2)};

const BY_KEY = new Map(CATALOG.map((e) => [e.key, e]));
export const entryByKey = (key: ConfigKey | string): ConfigEntry | undefined => BY_KEY.get(key);
export const entriesByKind = (kind: ConfigKind): ConfigEntry[] =>
  CATALOG.filter((e) => e.kind === kind);
`;
}

// ── Python mirror ────────────────────────────────────────────────────────────
function jsonToPython(value: unknown): string {
  if (value === null) return "None";
  if (value === true) return "True";
  if (value === false) return "False";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(jsonToPython).join(", ")}]`;
  if (typeof value === "object") {
    const rows = Object.entries(value as Record<string, unknown>).map(
      ([k, v]) => `${JSON.stringify(k)}: ${jsonToPython(v)}`,
    );
    return `{${rows.join(", ")}}`;
  }
  return "None";
}

function pyEntry(e: ConfigEntry): string {
  const parts = [
    `key=${JSON.stringify(e.key)}`,
    `kind=${JSON.stringify(e.kind)}`,
    `category=${JSON.stringify(e.category)}`,
    `label=${JSON.stringify(e.label)}`,
    `description=${JSON.stringify(e.description)}`,
    `schema=${jsonToPython(e.schema)}`,
  ];
  if (e.secret) parts.push("secret=True");
  if (e.managementDefault)
    parts.push(`management_default=${JSON.stringify(e.managementDefault)}`);
  if (e.userGrant) parts.push("user_grant=True");
  if (e.grantLabel) parts.push(`grant_label=${JSON.stringify(e.grantLabel)}`);
  if (e.accessor) parts.push(`accessor=${JSON.stringify(e.accessor)}`);
  if (e.dependsOn)
    parts.push(`depends_on_key=${JSON.stringify(e.dependsOn.key)}`);
  return `    ConfigEntry(${parts.join(", ")})`;
}

export function renderPython(catalog: ProductCatalog): string {
  const keys = catalog.entries.map((e) => JSON.stringify(e.key)).join(", ");
  const rows = catalog.entries.map(pyEntry).join(",\n");
  return `${PY_BANNER}
"""Typed mirror of a Polaris Key product catalog."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal, Optional

CATALOG_VERSION = ${catalog.schemaVersion}

ConfigKey = Literal[${keys}]


@dataclass(frozen=True)
class ConfigEntry:
    key: str
    kind: str
    category: str
    label: str
    description: str
    schema: dict[str, Any]
    secret: bool = False
    management_default: Optional[str] = None
    user_grant: bool = False
    grant_label: Optional[str] = None
    accessor: Optional[str] = None
    depends_on_key: Optional[str] = None


CATALOG: list[ConfigEntry] = [
${rows}
]

_BY_KEY = {e.key: e for e in CATALOG}


def entry_by_key(key: str) -> Optional[ConfigEntry]:
    return _BY_KEY.get(key)


def entries_by_kind(kind: str) -> list[ConfigEntry]:
    return [e for e in CATALOG if e.kind == kind]
`;
}

// ── Swift mirror (ported from djdl scripts/gen-config-schema.ts) ──────────────
function swiftStr(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
function swiftOptStr(s: string | undefined): string {
  return s === undefined ? "nil" : swiftStr(s);
}
function swiftOptInt(n: number | undefined): string {
  return typeof n === "number" && Number.isFinite(n) ? String(n) : "nil";
}
function swiftStringArray(values: string[] | undefined): string {
  if (!values || values.length === 0) return "[]";
  return `[${values.map(swiftStr).join(", ")}]`;
}
function swiftStringDict(values: Record<string, string> | undefined): string {
  if (!values || Object.keys(values).length === 0) return "[:]";
  return `[${Object.entries(values)
    .map(([k, v]) => `${swiftStr(k)}: ${swiftStr(v)}`)
    .join(", ")}]`;
}
function swiftDependsOnEquals(value: unknown): string {
  if (value === undefined) return "nil";
  if (typeof value === "string") return swiftStr(value);
  if (typeof value === "number" || typeof value === "boolean")
    return swiftStr(String(value));
  return swiftStr(JSON.stringify(value));
}

export function renderSwift(catalog: ProductCatalog): string {
  const rows = catalog.entries
    .map((e: ConfigEntry) => {
      const ui = (e.ui ?? {}) as Record<string, unknown>;
      const dep = e.dependsOn ? swiftStr(e.dependsOn.key) : "nil";
      const depEquals = e.dependsOn
        ? swiftDependsOnEquals(e.dependsOn.equals)
        : "nil";
      // `default` is a Swift reserved word — the enum case is escaped with backticks, so the
      // member access must be escaped too: `.`default`` (not `.default`).
      const mgmt = e.managementDefault
        ? `.${e.managementDefault === "default" ? "`default`" : e.managementDefault}`
        : "nil";
      const grantLabel = e.grantLabel ? swiftStr(e.grantLabel) : "nil";
      return (
        `    ConfigSchemaEntry(key: ${swiftStr(e.key)}, kind: .${e.kind}, ` +
        `category: ${swiftStr(e.category)}, label: ${swiftStr(e.label)}, ` +
        `description: ${swiftStr(e.description)}, widget: ${swiftOptStr(ui.widget as string | undefined)}, ` +
        `help: ${swiftOptStr(ui.help as string | undefined)}, placeholder: ${swiftOptStr(ui.placeholder as string | undefined)}, ` +
        `order: ${swiftOptInt(ui.order as number | undefined)}, scopes: ${swiftStringArray(ui.scopes as string[] | undefined)}, ` +
        `advanced: ${ui.advanced ? "true" : "false"}, unit: ${swiftOptStr(ui.unit as string | undefined)}, ` +
        `optionLabels: ${swiftStringDict(ui.optionLabels as Record<string, string> | undefined)}, adminSection: ${swiftOptStr(ui.adminSection as string | undefined)}, ` +
        `isSecret: ${e.kind === "secret" ? "true" : "false"}, ` +
        `managementDefault: ${mgmt}, userGrant: ${e.userGrant ? "true" : "false"}, ` +
        `grantLabel: ${grantLabel}, dependsOnKey: ${dep}, dependsOnEquals: ${depEquals})`
      );
    })
    .join(",\n");

  return `${BANNER}
// Typed mirror of a Polaris Key product catalog, for the Swift SDK.

import Foundation

enum ConfigKind: String { case config, secret, flag }
enum ManagementState: String { case \`default\`, enforced, hidden }

struct ConfigSchemaEntry: Identifiable, Sendable {
    let key: String
    let kind: ConfigKind
    let category: String
    let label: String
    let description: String
    let widget: String?
    let help: String?
    let placeholder: String?
    let order: Int?
    let scopes: [String]
    let advanced: Bool
    let unit: String?
    let optionLabels: [String: String]
    let adminSection: String?
    let isSecret: Bool
    let managementDefault: ManagementState?
    let userGrant: Bool
    let grantLabel: String?
    let dependsOnKey: String?
    let dependsOnEquals: String?
    var id: String { key }
}

enum ProductCatalog {
    static let version = ${catalog.schemaVersion}
    static let entries: [ConfigSchemaEntry] = [
${rows}
    ]
    static func entry(for key: String) -> ConfigSchemaEntry? {
        entries.first { $0.key == key }
    }
}
`;
}

// ── CLI ──────────────────────────────────────────────────────────────────────
type Lang = "ts" | "python" | "swift";
const FILENAME: Record<Lang, string> = {
  ts: "catalog.generated.ts",
  python: "catalog_generated.py",
  swift: "ConfigSchema.generated.swift",
};
const RENDER: Record<Lang, (c: ProductCatalog) => string> = {
  ts: renderTs,
  python: renderPython,
  swift: renderSwift,
};

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

function writeIfNeeded(path: string, content: string, check: boolean): boolean {
  let current: string | undefined;
  try {
    current = readFileSync(path, "utf8");
  } catch {
    current = undefined;
  }
  if (current === content) return false;
  if (check) {
    console.error(`stale: ${path} — run \`pnpm gen:mirrors\``);
    return true;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`wrote ${path}`);
  return false;
}

async function main(): Promise<void> {
  const catalogPath = arg("--catalog");
  const outDir = arg("--out-dir");
  const langs = (arg("--lang") ?? "ts,python,swift").split(",") as Lang[];
  const check = process.argv.includes("--check");
  if (!catalogPath || !outDir) {
    console.error(
      "usage: gen-mirrors --catalog <path> --out-dir <dir> [--lang ts,python,swift] [--check]",
    );
    process.exit(2);
  }
  const catalog = JSON.parse(
    readFileSync(catalogPath, "utf8"),
  ) as ProductCatalog;
  let stale = 0;
  for (const lang of langs) {
    const render = RENDER[lang];
    if (!render) {
      console.error(`unknown lang: ${lang}`);
      process.exit(2);
    }
    stale += Number(
      writeIfNeeded(join(outDir, FILENAME[lang]), render(catalog), check),
    );
  }
  if (check && stale > 0) process.exit(1);
}

const invokedDirectly =
  process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url) === process.argv[1];
if (invokedDirectly) await main();
