// Renders the generator registry (tools/generators.ts) as two committed documents:
//
//   packages/docs/src/content/docs/reference/generators.mdx   the reference page
//   AGENTS.md                                                 the table between the
//                                                             `generators:start` / `generators:end` markers
//
//   pnpm gen registry-docs            # write both
//   pnpm gen registry-docs --check    # exit 1 when either is stale

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as prettier from "prettier";
import { GENERATORS, type Cmd, type Generator } from "./generators.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const PAGE_PATH =
  "packages/docs/src/content/docs/reference/generators.mdx";
export const AGENTS_PATH = "AGENTS.md";
export const START =
  "<!-- generators:start (generated by `pnpm gen registry-docs`; do not edit) -->";
export const END = "<!-- generators:end -->";

const sorted = (): Generator[] =>
  [...GENERATORS].sort((a, b) => a.order - b.order);

function shell(c: Cmd): string {
  const env = Object.entries(c.env ?? {}).map(([k, v]) => `${k}=${v}`);
  const cwd = c.cwd ? `(cd ${c.cwd} && ` : "";
  return `${cwd}${[...env, ...c.argv].join(" ")}${c.cwd ? ")" : ""}`;
}

/** The command a person types to regenerate (or check) a family. */
export function command(g: Generator, check = false): string {
  if (g.checkOnly) return `pnpm gen ${g.id}`;
  return `pnpm gen ${g.id}${check ? " --check" : ""}`;
}

function list(globs: string[]): string {
  return globs.length === 0
    ? "none (a checker)"
    : globs.map((x) => `\`${x}\``).join(", ");
}

function mode(g: Generator): string {
  if (g.manual) return "named run only";
  if (g.via) return `runs with \`${g.via}\``;
  if (g.checkOnly) return "check only";
  return g.fast ? "default, pre-commit" : "default";
}

export function agentsTable(): string {
  const rows = sorted().map(
    (g) =>
      `| \`${g.id}\` | \`${command(g)}\` | ${list(g.inputs)} | ${list(g.outputs)} |`,
  );
  return [
    START,
    "",
    "| Family | Regenerate | Reads | Writes |",
    "| --- | --- | --- | --- |",
    ...rows,
    "",
    END,
  ].join("\n");
}

export function pageSource(): string {
  const parts: string[] = [
    "---",
    'title: "Generators"',
    'description: "Every generator the repository runs, what each reads and writes, and the one command that regenerates or checks them all."',
    "---",
    "",
    "{/* GENERATED PAGE — do not edit. Regenerate with `pnpm gen registry-docs`.",
    "    Source of truth: tools/generators.ts; emitter: tools/gen-generators-doc.ts. */}",
    "",
    "Generated files are committed, never hand-edited. `tools/generators.ts` declares every generator once; `pnpm gen` runs them.",
    "",
    "| Command | Does |",
    "| --- | --- |",
    "| `pnpm gen` | Regenerates every default family in order. |",
    "| `pnpm gen --check` | Fails when any default family is stale. Writes nothing. CI and the green gate run this. |",
    "| `pnpm gen --changed` | Only the families whose inputs or outputs changed on this branch. Add `--check` to verify. |",
    "| `pnpm gen --fast --check` | Only the cheap families. The pre-commit hook runs this. |",
    "| `pnpm gen <family> ...` | The named families. Extra `--flag value` pairs go to a single named family. |",
    "| `pnpm gen --list` | One line per family. |",
    "",
    "A new generator is one entry in `tools/generators.ts`. A test fails when a file carries a GENERATED banner that no entry claims.",
    "",
    "## Families",
    "",
  ];
  for (const g of sorted()) {
    parts.push(`### ${g.id}`, "", g.title + ".", "");
    parts.push(`- Run: ${mode(g)}.`);
    if (!g.checkOnly) parts.push(`- Regenerate: \`${command(g)}\`.`);
    parts.push(`- Check: \`${command(g, true)}\`.`);
    const steps = g.manual && !g.write ? [] : (g.write ?? []);
    if (steps.length > 0)
      parts.push(
        `- Underlying: ${steps.map((s) => `\`${shell(s)}\``).join(", then ")}.`,
      );
    if (g.manual) parts.push(`- Why not default: ${g.manual}.`);
    if (g.needsBuild) parts.push("- Needs `pnpm build` first.");
    parts.push(
      `- Reads: ${list(g.inputs)}.`,
      `- Writes: ${list(g.outputs)}.`,
      "",
    );
  }
  return parts.join("\n");
}

async function fmt(text: string, file: string): Promise<string> {
  const cfg = (await prettier.resolveConfig(join(ROOT, file))) ?? {};
  return prettier.format(text, { ...cfg, filepath: join(ROOT, file) });
}

export async function render(root = ROOT): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  out.set(PAGE_PATH, await fmt(pageSource(), PAGE_PATH));
  const agents = readFileSync(join(root, AGENTS_PATH), "utf8");
  const s = agents.indexOf(START);
  const e = agents.indexOf(END);
  if (s < 0 || e < s)
    throw new Error(`${AGENTS_PATH} lacks the ${START} ... ${END} markers`);
  const table = agentsTable();
  const next = agents.slice(0, s) + table + agents.slice(e + END.length);
  out.set(AGENTS_PATH, await fmt(next, AGENTS_PATH));
  return out;
}

async function main(): Promise<number> {
  const check = process.argv.includes("--check");
  const files = await render();
  let stale = 0;
  for (const [path, text] of files) {
    let current = "";
    try {
      current = readFileSync(join(ROOT, path), "utf8");
    } catch {
      /* missing: stale */
    }
    if (current === text) continue;
    stale++;
    if (check) console.error(`stale: ${path}`);
    else {
      writeFileSync(join(ROOT, path), text);
      console.log(`wrote ${path}`);
    }
  }
  if (check && stale > 0) {
    console.error(
      "gen registry-docs --check: run `pnpm gen registry-docs` and commit the result",
    );
    return 1;
  }
  return 0;
}

const isMain =
  process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) process.exit(await main());
