// Generalized schema-mirror generator (the multi-language successor to djdl's
// scripts/gen-config-schema.ts). Given a product catalog JSON (the `/<product>/config/schema`
// shape), it emits self-contained typed mirrors for products that want compile-time
// config types: TypeScript, Python (dataclasses), Swift, GDScript and Kotlin. Products that stay
// purely data-driven skip this and read the catalog at runtime.
//
//   tsx tools/gen-mirrors.ts --catalog <path> --out-dir <dir> --lang ts,python,swift,gdscript,kotlin
//                            [--kotlin-package com.example.catalog]
//   tsx tools/gen-mirrors.ts ... --check     # CI drift guard (exit 1 if stale)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { ConfigEntry, ProductCatalog } from "@polaris-key/catalog";

const BANNER =
  "// @generated by tools/gen-mirrors.ts — do not edit. Run `pnpm gen:mirrors`.";
const PY_BANNER =
  "# @generated by tools/gen-mirrors.ts — do not edit. Run `pnpm gen:mirrors`.";

// ── TypeScript mirror ────────────────────────────────────────────────────────
export function renderTs(catalog: ProductCatalog): string {
  const keys = catalog.entries.map((e) => JSON.stringify(e.key)).join(" | ");
  return `${BANNER}
// Typed mirror of a Polaris Key product catalog.

export const CATALOG_VERSION = ${catalog.schemaVersion};

export type ConfigKind = "config" | "secret" | "flag";
export type ManagementState = "default" | "enforced" | "hidden";
export type JsonSchema = Record<string, unknown>;

export interface ConfigEntry {
  key: string;
  kind: ConfigKind;
  category: string;
  label: string;
  description: string;
  schema: JsonSchema;
  examples?: unknown[];
  default?: unknown;
  secret?: boolean;
  managementDefault?: ManagementState;
  userGrant?: boolean;
  grantLabel?: string;
  ui?: Record<string, unknown>;
  dependsOn?: { key: string; equals: unknown };
  accessor?: string;
}

/** Every declared key in this catalog. */
export type ConfigKey = ${keys || "never"};

export const CATALOG: readonly ConfigEntry[] = ${JSON.stringify(catalog.entries, null, 2)};

const BY_KEY = new Map(CATALOG.map((e) => [e.key, e]));
export const entryByKey = (key: ConfigKey | string): ConfigEntry | undefined => BY_KEY.get(key);
export const entriesByKind = (kind: ConfigKind): ConfigEntry[] =>
  CATALOG.filter((e) => e.kind === kind);
`;
}

// ── Python mirror ────────────────────────────────────────────────────────────
function jsonToPython(value: unknown): string {
  if (value === null) return "None";
  if (value === true) return "True";
  if (value === false) return "False";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(jsonToPython).join(", ")}]`;
  if (typeof value === "object") {
    const rows = Object.entries(value as Record<string, unknown>).map(
      ([k, v]) => `${JSON.stringify(k)}: ${jsonToPython(v)}`,
    );
    return `{${rows.join(", ")}}`;
  }
  return "None";
}

function pyEntry(e: ConfigEntry): string {
  const parts = [
    `key=${JSON.stringify(e.key)}`,
    `kind=${JSON.stringify(e.kind)}`,
    `category=${JSON.stringify(e.category)}`,
    `label=${JSON.stringify(e.label)}`,
    `description=${JSON.stringify(e.description)}`,
    `schema=${jsonToPython(e.schema)}`,
  ];
  if (e.secret) parts.push("secret=True");
  if (e.managementDefault)
    parts.push(`management_default=${JSON.stringify(e.managementDefault)}`);
  if (e.userGrant) parts.push("user_grant=True");
  if (e.grantLabel) parts.push(`grant_label=${JSON.stringify(e.grantLabel)}`);
  if (e.accessor) parts.push(`accessor=${JSON.stringify(e.accessor)}`);
  if (e.dependsOn)
    parts.push(`depends_on_key=${JSON.stringify(e.dependsOn.key)}`);
  return `    ConfigEntry(${parts.join(", ")})`;
}

export function renderPython(catalog: ProductCatalog): string {
  const keys = catalog.entries.map((e) => JSON.stringify(e.key)).join(", ");
  const rows = catalog.entries.map(pyEntry).join(",\n");
  return `${PY_BANNER}
"""Typed mirror of a Polaris Key product catalog."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal, Optional

CATALOG_VERSION = ${catalog.schemaVersion}

ConfigKey = Literal[${keys}]


@dataclass(frozen=True)
class ConfigEntry:
    key: str
    kind: str
    category: str
    label: str
    description: str
    schema: dict[str, Any]
    secret: bool = False
    management_default: Optional[str] = None
    user_grant: bool = False
    grant_label: Optional[str] = None
    accessor: Optional[str] = None
    depends_on_key: Optional[str] = None


CATALOG: list[ConfigEntry] = [
${rows}
]

_BY_KEY = {e.key: e for e in CATALOG}


def entry_by_key(key: str) -> Optional[ConfigEntry]:
    return _BY_KEY.get(key)


def entries_by_kind(kind: str) -> list[ConfigEntry]:
    return [e for e in CATALOG if e.kind == kind]
`;
}

// ── Swift mirror (ported from djdl scripts/gen-config-schema.ts) ──────────────
function swiftStr(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
function swiftOptStr(s: string | undefined): string {
  return s === undefined ? "nil" : swiftStr(s);
}
function swiftOptInt(n: number | undefined): string {
  return typeof n === "number" && Number.isFinite(n) ? String(n) : "nil";
}
function swiftStringArray(values: string[] | undefined): string {
  if (!values || values.length === 0) return "[]";
  return `[${values.map(swiftStr).join(", ")}]`;
}
function swiftStringDict(values: Record<string, string> | undefined): string {
  if (!values || Object.keys(values).length === 0) return "[:]";
  return `[${Object.entries(values)
    .map(([k, v]) => `${swiftStr(k)}: ${swiftStr(v)}`)
    .join(", ")}]`;
}
function swiftDependsOnEquals(value: unknown): string {
  if (value === undefined) return "nil";
  if (typeof value === "string") return swiftStr(value);
  if (typeof value === "number" || typeof value === "boolean")
    return swiftStr(String(value));
  return swiftStr(JSON.stringify(value));
}

export function renderSwift(catalog: ProductCatalog): string {
  const rows = catalog.entries
    .map((e: ConfigEntry) => {
      const ui = (e.ui ?? {}) as Record<string, unknown>;
      const dep = e.dependsOn ? swiftStr(e.dependsOn.key) : "nil";
      const depEquals = e.dependsOn
        ? swiftDependsOnEquals(e.dependsOn.equals)
        : "nil";
      // `default` is a Swift reserved word — the enum case is escaped with backticks, so the
      // member access must be escaped too: `.`default`` (not `.default`).
      const mgmt = e.managementDefault
        ? `.${e.managementDefault === "default" ? "`default`" : e.managementDefault}`
        : "nil";
      const grantLabel = e.grantLabel ? swiftStr(e.grantLabel) : "nil";
      return (
        `    ConfigSchemaEntry(key: ${swiftStr(e.key)}, kind: .${e.kind}, ` +
        `category: ${swiftStr(e.category)}, label: ${swiftStr(e.label)}, ` +
        `description: ${swiftStr(e.description)}, widget: ${swiftOptStr(ui.widget as string | undefined)}, ` +
        `help: ${swiftOptStr(ui.help as string | undefined)}, placeholder: ${swiftOptStr(ui.placeholder as string | undefined)}, ` +
        `order: ${swiftOptInt(ui.order as number | undefined)}, scopes: ${swiftStringArray(ui.scopes as string[] | undefined)}, ` +
        `advanced: ${ui.advanced ? "true" : "false"}, unit: ${swiftOptStr(ui.unit as string | undefined)}, ` +
        `optionLabels: ${swiftStringDict(ui.optionLabels as Record<string, string> | undefined)}, adminSection: ${swiftOptStr(ui.adminSection as string | undefined)}, ` +
        `isSecret: ${e.kind === "secret" ? "true" : "false"}, ` +
        `managementDefault: ${mgmt}, userGrant: ${e.userGrant ? "true" : "false"}, ` +
        `grantLabel: ${grantLabel}, dependsOnKey: ${dep}, dependsOnEquals: ${depEquals})`
      );
    })
    .join(",\n");

  return `${BANNER}
// Typed mirror of a Polaris Key product catalog, for the Swift SDK.

import Foundation

enum ConfigKind: String { case config, secret, flag }
enum ManagementState: String { case \`default\`, enforced, hidden }

struct ConfigSchemaEntry: Identifiable, Sendable {
    let key: String
    let kind: ConfigKind
    let category: String
    let label: String
    let description: String
    let widget: String?
    let help: String?
    let placeholder: String?
    let order: Int?
    let scopes: [String]
    let advanced: Bool
    let unit: String?
    let optionLabels: [String: String]
    let adminSection: String?
    let isSecret: Bool
    let managementDefault: ManagementState?
    let userGrant: Bool
    let grantLabel: String?
    let dependsOnKey: String?
    let dependsOnEquals: String?
    var id: String { key }
}

enum ProductCatalog {
    static let version = ${catalog.schemaVersion}
    static let entries: [ConfigSchemaEntry] = [
${rows}
    ]
    static func entry(for key: String) -> ConfigSchemaEntry? {
        entries.first { $0.key == key }
    }
}
`;
}

// ── GDScript mirror (the Godot SDK, P1-04) ────────────────────────────────────
//
// A script of constants with no `class_name` (a game may mirror more than one product, and a
// global name would collide), loaded with `preload` and handed to
// `PolarisKey.config.set_compiled_catalog(script)`. It must parse on Godot 4.4, the SDK's
// floor, so it uses nothing newer than untyped `const` literals and static functions.
//
// Deterministic like the other renderers: entries keep the catalog's order (it is data), every
// object's keys are SORTED, and `DEFAULTS` is sorted by key. Strings are ASCII-only on output:
// quotes, backslashes and control characters are escaped, and every non-ASCII code point is
// written as `\uXXXX` (BMP) or `\UXXXXXX` (astral), so the file survives any editor or
// checkout encoding.

/** A GDScript string literal: ASCII only, every special character escaped. */
export function gdStr(s: string): string {
  let out = '"';
  for (const ch of s) {
    const cp = ch.codePointAt(0) as number;
    if (ch === "\\") out += "\\\\";
    else if (ch === '"') out += '\\"';
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (ch === "\t") out += "\\t";
    else if (cp < 0x20 || (cp >= 0x7f && cp <= 0xffff))
      out += `\\u${cp.toString(16).toUpperCase().padStart(4, "0")}`;
    else if (cp > 0xffff)
      out += `\\U${cp.toString(16).toUpperCase().padStart(6, "0")}`;
    else out += ch;
  }
  return `${out}"`;
}

/** A GDScript number literal. JSON integers within 2^53 stay `int`; anything else is a `float`
 *  literal (an integer beyond int64 written without a decimal point would not parse). */
function gdNumber(n: number): string {
  if (!Number.isFinite(n)) throw new Error(`non-finite number ${n} in catalog`);
  if (Number.isInteger(n) && Math.abs(n) <= Number.MAX_SAFE_INTEGER)
    return String(n === 0 ? 0 : n);
  const s = String(n);
  return /[.e]/.test(s) ? s : `${s}.0`;
}

/** A JSON value as a GDScript constant expression, tab-indented, object keys sorted. */
export function gdValue(value: unknown, depth = 0): string {
  if (value === null || value === undefined) return "null";
  if (value === true) return "true";
  if (value === false) return "false";
  if (typeof value === "number") return gdNumber(value);
  if (typeof value === "string") return gdStr(value);
  const pad = "\t".repeat(depth + 1);
  const end = "\t".repeat(depth);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return `[\n${value.map((v) => `${pad}${gdValue(v, depth + 1)},\n`).join("")}${end}]`;
  }
  if (typeof value === "object") {
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj)
      .filter((k) => obj[k] !== undefined)
      .sort();
    if (keys.length === 0) return "{}";
    const rows = keys.map(
      (k) => `${pad}${gdStr(k)}: ${gdValue(obj[k], depth + 1)},\n`,
    );
    return `{\n${rows.join("")}${end}}`;
  }
  throw new Error(`unsupported value in catalog: ${typeof value}`);
}

export function renderGdscript(catalog: ProductCatalog): string {
  const defaults: Record<string, unknown> = {};
  for (const e of catalog.entries)
    if (e.kind === "config" && e.default !== undefined)
      defaults[e.key] = e.default;
  // A game binary is extractable: a secret's catalog default is never compiled into one.
  const entries = catalog.entries.map((e) =>
    e.kind === "secret" ? { ...e, default: undefined } : e,
  );
  return `${PY_BANNER}
# Typed mirror of a Polaris Key product catalog, for the Godot SDK. Load it and hand it over:
#
#   PolarisKey.config.set_compiled_catalog(preload("res://catalog_generated.gd"))
#
# DEFAULTS holds each config key's catalog default: PolarisKey.config.get_value(key) returns it
# when nothing else resolves and the caller passed no fallback. A secret's default is omitted
# everywhere: anything compiled into a game can be extracted from it.
extends RefCounted

const CATALOG_VERSION := ${gdNumber(catalog.schemaVersion)}

const KEYS := ${gdValue(catalog.entries.map((e) => e.key))}

const ENTRIES := ${gdValue(entries)}

const DEFAULTS := ${gdValue(defaults)}


## The entry for \`key\` (read-only), or an empty Dictionary.
static func entry_by_key(key: String) -> Dictionary:
\tfor e in ENTRIES:
\t\tif e["key"] == key:
\t\t\treturn e
\treturn {}


## Every entry of one kind ("config", "secret" or "flag"), in catalog order.
static func entries_by_kind(kind: String) -> Array:
\treturn ENTRIES.filter(func(e): return e["kind"] == kind)
`;
}

// ── Kotlin mirror (the Kotlin SDK, P6-07) ────────────────────────────────────
//
// One file in the caller's package (`--kotlin-package`, default `DEFAULT_KOTLIN_PACKAGE`), with no
// dependency on the SDK, so it compiles in any Kotlin/JVM or Android module. It carries the Swift
// mirror's fields plus the entry's `accessor`, its JSON `schema` and its catalog `default` as JSON
// text (a secret's default is never compiled in: anything in a binary can be extracted). Every
// declaration is `public`, so it also compiles under explicit-API mode.
//
// Deterministic like the other renderers: entries keep the catalog's order, JSON text has its
// object keys sorted, and string literals are ASCII only: quotes, backslashes, `$` (a template in
// Kotlin), control characters and every non-ASCII UTF-16 unit are escaped.

/** The package a Kotlin mirror is written in when the caller names none. */
export const DEFAULT_KOTLIN_PACKAGE = "im.plrs.key.catalog";

/** A Kotlin string literal: ASCII only, every special character (including `$`) escaped. */
export function ktStr(s: string): string {
  let out = '"';
  for (let i = 0; i < s.length; i++) {
    const ch = s[i] as string;
    const cu = s.charCodeAt(i);
    if (ch === "\\") out += "\\\\";
    else if (ch === '"') out += '\\"';
    else if (ch === "$") out += "\\$";
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (ch === "\t") out += "\\t";
    else if (cu < 0x20 || cu >= 0x7f)
      out += `\\u${cu.toString(16).toUpperCase().padStart(4, "0")}`;
    else out += ch;
  }
  return `${out}"`;
}

function ktOptStr(s: unknown): string {
  return typeof s === "string" ? ktStr(s) : "null";
}

/** JSON text with every object's keys sorted (arrays keep their order). */
export function sortedJson(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(sortedJson).join(",")}]`;
  const obj = value as Record<string, unknown>;
  const keys = Object.keys(obj)
    .filter((k) => obj[k] !== undefined)
    .sort();
  return `{${keys.map((k) => `${JSON.stringify(k)}:${sortedJson(obj[k])}`).join(",")}}`;
}

function ktStringList(values: unknown): string {
  if (!Array.isArray(values) || values.length === 0) return "emptyList()";
  return `listOf(${values.map((v) => ktStr(String(v))).join(", ")})`;
}

function ktStringMap(values: unknown): string {
  if (!values || typeof values !== "object") return "emptyMap()";
  const entries = Object.entries(values as Record<string, unknown>).sort(
    ([a], [b]) => (a < b ? -1 : a > b ? 1 : 0),
  );
  if (entries.length === 0) return "emptyMap()";
  return `mapOf(${entries.map(([k, v]) => `${ktStr(k)} to ${ktStr(String(v))}`).join(", ")})`;
}

export function renderKotlin(
  catalog: ProductCatalog,
  pkg: string = DEFAULT_KOTLIN_PACKAGE,
): string {
  if (!/^[a-z_][A-Za-z0-9_]*(\.[a-z_][A-Za-z0-9_]*)*$/.test(pkg))
    throw new Error(`not a Kotlin package name: ${pkg}`);
  const rows = catalog.entries
    .map((e: ConfigEntry) => {
      const ui = (e.ui ?? {}) as Record<string, unknown>;
      const order =
        typeof ui.order === "number" && Number.isInteger(ui.order)
          ? String(ui.order)
          : "null";
      const dependsOnEquals =
        e.dependsOn === undefined
          ? "null"
          : typeof e.dependsOn.equals === "string"
            ? ktStr(e.dependsOn.equals)
            : ktStr(JSON.stringify(e.dependsOn.equals));
      const defaultJson =
        e.kind === "secret" || e.default === undefined
          ? "null"
          : ktStr(sortedJson(e.default));
      return [
        `        ConfigSchemaEntry(`,
        `            key = ${ktStr(e.key)},`,
        `            kind = ConfigKind.${e.kind},`,
        `            category = ${ktStr(e.category)},`,
        `            label = ${ktStr(e.label)},`,
        `            description = ${ktStr(e.description)},`,
        `            widget = ${ktOptStr(ui.widget)},`,
        `            help = ${ktOptStr(ui.help)},`,
        `            placeholder = ${ktOptStr(ui.placeholder)},`,
        `            order = ${order},`,
        `            scopes = ${ktStringList(ui.scopes)},`,
        `            advanced = ${ui.advanced ? "true" : "false"},`,
        `            unit = ${ktOptStr(ui.unit)},`,
        `            optionLabels = ${ktStringMap(ui.optionLabels)},`,
        `            adminSection = ${ktOptStr(ui.adminSection)},`,
        `            isSecret = ${e.kind === "secret" ? "true" : "false"},`,
        `            managementDefault = ${e.managementDefault ? `ManagementState.${e.managementDefault}` : "null"},`,
        `            userGrant = ${e.userGrant ? "true" : "false"},`,
        `            grantLabel = ${ktOptStr(e.grantLabel)},`,
        `            dependsOnKey = ${e.dependsOn ? ktStr(e.dependsOn.key) : "null"},`,
        `            dependsOnEquals = ${dependsOnEquals},`,
        `            accessor = ${ktOptStr(e.accessor)},`,
        `            schemaJson = ${ktStr(sortedJson(e.schema))},`,
        `            defaultJson = ${defaultJson},`,
        `        ),`,
      ].join("\n");
    })
    .join("\n");

  return `${BANNER}
// Typed mirror of a Polaris Key product catalog, for the Kotlin SDK. It depends on nothing, so it
// compiles in any Kotlin/JVM or Android module. A secret's catalog default is never compiled in.

package ${pkg}

public enum class ConfigKind(public val wire: String) {
    config("config"),
    secret("secret"),
    flag("flag"),
}

public enum class ManagementState(public val wire: String) {
    default("default"),
    enforced("enforced"),
    hidden("hidden"),
}

public data class ConfigSchemaEntry(
    val key: String,
    val kind: ConfigKind,
    val category: String,
    val label: String,
    val description: String,
    val widget: String?,
    val help: String?,
    val placeholder: String?,
    val order: Int?,
    val scopes: List<String>,
    val advanced: Boolean,
    val unit: String?,
    val optionLabels: Map<String, String>,
    val adminSection: String?,
    val isSecret: Boolean,
    val managementDefault: ManagementState?,
    val userGrant: Boolean,
    val grantLabel: String?,
    val dependsOnKey: String?,
    val dependsOnEquals: String?,
    val accessor: String?,
    /** The entry's JSON Schema fragment, as JSON text with sorted keys. */
    val schemaJson: String,
    /** The catalog default as JSON text with sorted keys; null when absent, and always for a secret. */
    val defaultJson: String?,
)

public object ProductCatalog {
    public const val VERSION: Int = ${catalog.schemaVersion}

    public val entries: List<ConfigSchemaEntry> = listOf(
${rows}
    )

    /** Every declared key, in catalog order. */
    public val keys: List<String> = entries.map { it.key }

    public fun entry(key: String): ConfigSchemaEntry? = entries.firstOrNull { it.key == key }

    public fun entriesByKind(kind: ConfigKind): List<ConfigSchemaEntry> = entries.filter { it.kind == kind }
}
`;
}

// ── CLI ──────────────────────────────────────────────────────────────────────
type Lang = "ts" | "python" | "swift" | "gdscript" | "kotlin";
const FILENAME: Record<Lang, string> = {
  ts: "catalog.generated.ts",
  python: "catalog_generated.py",
  swift: "ConfigSchema.generated.swift",
  gdscript: "catalog_generated.gd",
  kotlin: "ConfigSchema.generated.kt",
};
const RENDER: Record<Lang, (c: ProductCatalog) => string> = {
  ts: renderTs,
  python: renderPython,
  swift: renderSwift,
  gdscript: renderGdscript,
  kotlin: (c) =>
    renderKotlin(c, arg("--kotlin-package") ?? DEFAULT_KOTLIN_PACKAGE),
};

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

function writeIfNeeded(path: string, content: string, check: boolean): boolean {
  let current: string | undefined;
  try {
    current = readFileSync(path, "utf8");
  } catch {
    current = undefined;
  }
  if (current === content) return false;
  if (check) {
    console.error(`stale: ${path} — run \`pnpm gen:mirrors\``);
    return true;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.log(`wrote ${path}`);
  return false;
}

async function main(): Promise<void> {
  const catalogPath = arg("--catalog");
  const outDir = arg("--out-dir");
  const langs = (arg("--lang") ?? "ts,python,swift").split(",") as Lang[];
  const check = process.argv.includes("--check");
  if (!catalogPath || !outDir) {
    console.error(
      "usage: gen-mirrors --catalog <path> --out-dir <dir> [--lang ts,python,swift,gdscript,kotlin] [--kotlin-package <pkg>] [--check]",
    );
    process.exit(2);
  }
  const catalog = JSON.parse(
    readFileSync(catalogPath, "utf8"),
  ) as ProductCatalog;
  let stale = 0;
  for (const lang of langs) {
    const render = RENDER[lang];
    if (!render) {
      console.error(`unknown lang: ${lang}`);
      process.exit(2);
    }
    stale += Number(
      writeIfNeeded(join(outDir, FILENAME[lang]), render(catalog), check),
    );
  }
  if (check && stale > 0) process.exit(1);
}

const invokedDirectly =
  process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url) === process.argv[1];
if (invokedDirectly) await main();
