/**
 * A-17a — the App Store Connect write gate (notes/S-14 §7.5; owner decision 1, 2026-10-04: the
 * Worker holds an ADMIN key and this gate is the only barrier). A REQUIRED check:
 *
 *   1. every write operation of the pinned OpenAPI document (`fixtures/asc/openapi-writes.json`,
 *      generated by `scripts/asc-spec-writes.mjs`) is classified exactly once, allowed
 *      (`ASC_WRITE_ALLOW`) or denied with a reason (`ASC_WRITE_DENIED`); nothing classified is
 *      missing from the spec; a spec bump fails here until each new write is placed;
 *   2. every allow rule is a subset of the spec's own request body (type, attributes,
 *      relationships, `included`);
 *   3. at run time, every denied operation is refused, an invented one is refused (deny by
 *      default), and the body checks hold;
 *   4. a refused request mints no token and sends nothing.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it, vi } from "vitest";
import {
  ASC_SPEC_PIN,
  ASC_WRITE_ALLOW,
  AscWriteDenied,
  checkAscRequest,
  checkAscUpload,
  GATE_CAPABILITY_TYPES,
  type AscGateContext,
} from "../src/core/storefront/rules/appStore.js";
import {
  ASC_DENY_REASONS,
  ASC_WRITE_DENIED,
} from "../src/core/storefront/rules/appStoreDenied.js";
import {
  AscClient,
  AscError,
  ascPath,
  ascPathV,
} from "../src/core/asc/client.js";

const HERE = dirname(fileURLToPath(import.meta.url));

interface SpecOp {
  method: string;
  path: string;
  operationId: string | null;
  requestSchema: string | null;
  type: string | null;
  attributes: string[];
  relationships: string[];
  linkage: boolean;
  included: boolean;
}

const SPEC = JSON.parse(
  readFileSync(join(HERE, "fixtures", "asc", "openapi-writes.json"), "utf8"),
) as {
  source: { title: string; version: string; sha256: string };
  operations: SpecOp[];
};

const key = (method: string, path: string) => `${method} ${path}`;
const SPEC_BY_KEY = new Map(
  SPEC.operations.map((o) => [key(o.method, o.path), o]),
);
const ALLOWED = ASC_WRITE_ALLOW.map((r) => key(r.method, r.path));
const DENIED = Object.values(ASC_WRITE_DENIED).flat();

/** A concrete path for a template. */
const concrete = (template: string, id = "X1") =>
  template.replace(/\{id\}/g, id);

function denial(
  method: string,
  path: string,
  body?: unknown,
  ctx?: AscGateContext,
): string | null {
  try {
    checkAscRequest(method, path, body, ctx);
    return null;
  } catch (e) {
    if (e instanceof AscWriteDenied) return e.reason;
    throw e;
  }
}

describe("the pinned spec", () => {
  it("is the spec the gate is classified against", () => {
    expect(SPEC.source.sha256).toBe(ASC_SPEC_PIN.sha256);
    expect(SPEC.source.version).toBe(ASC_SPEC_PIN.version);
    expect(SPEC.source.title).toBe(ASC_SPEC_PIN.title);
    // 4.5: 176 POST, 160 PATCH, 132 DELETE (S-14 §5.5's 336 POST+PATCH).
    expect(SPEC.operations.length).toBe(468);
  });
});

describe("every write operation is classified", () => {
  it("each spec write is allowed or denied — exactly once", () => {
    const unclassified: string[] = [];
    const twice: string[] = [];
    for (const o of SPEC.operations) {
      const k = key(o.method, o.path);
      const n =
        ALLOWED.filter((a) => a === k).length +
        DENIED.filter((d) => d === k).length;
      if (n === 0) unclassified.push(k);
      if (n > 1) twice.push(k);
    }
    expect(
      unclassified,
      "classify these in rules/appStore.ts or rules/appStoreDenied.ts",
    ).toEqual([]);
    expect(twice).toEqual([]);
  });

  it("nothing classified is missing from the spec (no stale or misspelt entry)", () => {
    const stale = [...ALLOWED, ...DENIED].filter((k) => !SPEC_BY_KEY.has(k));
    expect(stale).toEqual([]);
  });

  it("every deny group has a reason, and every reason a group", () => {
    expect(Object.keys(ASC_WRITE_DENIED).sort()).toEqual(
      Object.keys(ASC_DENY_REASONS).sort(),
    );
    for (const ops of Object.values(ASC_WRITE_DENIED))
      expect(ops.length).toBeGreaterThan(0);
  });
});

describe("the owner's never-list", () => {
  it("no allow rule is a DELETE", () => {
    expect(
      ASC_WRITE_ALLOW.filter((r) => (r.method as string) === "DELETE"),
    ).toEqual([]);
    expect(
      SPEC.operations
        .filter((o) => o.method === "DELETE")
        .every((o) => DENIED.includes(key(o.method, o.path))),
    ).toBe(true);
  });

  it("no allow rule touches users, invitations, certificates, devices or profiles", () => {
    const forbidden =
      /^\/v1\/(users|userInvitations|certificates|devices|profiles|merchantIds|passTypeIds)(\/|$)/;
    expect(ASC_WRITE_ALLOW.filter((r) => forbidden.test(r.path))).toEqual([]);
    for (const o of SPEC.operations.filter((o) => forbidden.test(o.path)))
      expect(denial(o.method, concrete(o.path), { data: {} })).not.toBeNull();
  });

  it("existing bundle ids and capabilities cannot be changed", () => {
    for (const p of ["/v1/bundleIds/X1", "/v1/bundleIdCapabilities/X1"])
      expect(denial("PATCH", p, { data: {} })).toBe("not_allowed");
  });
});

describe("allow rules are a subset of the spec's own request bodies", () => {
  for (const rule of ASC_WRITE_ALLOW) {
    it(`${rule.method} ${rule.path}`, () => {
      const op = SPEC_BY_KEY.get(key(rule.method, rule.path))!;
      expect(op, "not in the spec").toBeDefined();
      expect(rule.type).toBe(op.type);
      expect(rule.path.includes("/relationships/")).toBe(op.linkage);
      for (const a of rule.attributes) expect(op.attributes).toContain(a);
      for (const r of Object.keys(rule.relationships))
        expect(op.relationships).toContain(r);
      if (rule.included) expect(op.included).toBe(true);
      expect(rule.why.length).toBeGreaterThan(10);
    });
  }
});

describe("deny by default at run time", () => {
  it("every denied spec operation is refused, whatever the body", () => {
    const admitted: string[] = [];
    for (const k of DENIED) {
      const [method, template] = k.split(" ") as [string, string];
      const op = SPEC_BY_KEY.get(k)!;
      // The most plausible body: the spec's own type with no attributes.
      const body = op.linkage
        ? { data: [{ type: op.type, id: "X2" }] }
        : method === "DELETE"
          ? undefined
          : {
              data: {
                type: op.type,
                ...(method === "PATCH" ? { id: "X1" } : {}),
              },
            };
      const reason = denial(method, concrete(template), body, {
        typedConfirmation: true,
        initial: true,
      });
      if (reason === null) admitted.push(k);
    }
    expect(admitted).toEqual([]);
  });

  it("an operation the spec does not have is refused", () => {
    expect(denial("POST", "/v1/fooBars", { data: { type: "fooBars" } })).toBe(
      "not_allowed",
    );
    expect(denial("PUT", "/v1/apps/1", { data: {} })).toBe("not_allowed");
    expect(denial("DELETE", "/v1/betaGroups/g1")).toBe("not_allowed");
    expect(denial("POST", "/v3/bundleIds", {})).toBe("invalid_path");
    expect(denial("GET", "/v1/apps/../users")).toBe("invalid_path");
    expect(denial("GET", "/v1/apps/%2e%2e")).toBe("invalid_path");
  });

  it("user records are refused even to read; other reads pass", () => {
    for (const p of [
      "/v1/users",
      "/v1/users/U1",
      "/v1/users/U1/visibleApps",
      "/v1/userInvitations",
      // Case-insensitive: another spelling is refused too, whatever Apple would answer.
      "/v1/Users",
      "/v1/USERS/U1",
      "/v1/UserInvitations",
    ])
      expect(denial("GET", p)).toBe("personal_data");
    expect(denial("GET", "/v1/apps")).toBeNull();
    expect(denial("GET", "/v2/inAppPurchases/I1")).toBeNull();
    expect(
      denial("GET", "/v1/bundleIdCapabilities/HPA5436NK7_IN_APP_PURCHASE"),
    ).toBeNull();
  });
});

describe("body checks", () => {
  const bundleId = (attributes: Record<string, unknown>) => ({
    data: { type: "bundleIds", attributes },
  });

  it("admits the documented bundle id registration", () => {
    expect(
      denial(
        "POST",
        "/v1/bundleIds",
        bundleId({ identifier: "gg.acme.djdl", name: "djdl", platform: "IOS" }),
      ),
    ).toBeNull();
  });

  it("refuses an attribute outside the rule, a wrong type, a body id on create", () => {
    expect(
      denial(
        "POST",
        "/v1/bundleIds",
        bundleId({ identifier: "x", platform: "IOS", seedId: "T" }),
      ),
    ).toBe("attribute_not_allowed");
    expect(
      denial("POST", "/v1/bundleIds", {
        data: { type: "apps", attributes: {} },
      }),
    ).toBe("wrong_type");
    expect(
      denial("POST", "/v1/bundleIds", {
        data: { type: "bundleIds", id: "B1", attributes: { platform: "IOS" } },
      }),
    ).toBe("invalid_body");
    expect(
      denial("POST", "/v1/bundleIds", bundleId({ platform: "TVOS" })),
    ).toBe("value_not_allowed");
    expect(
      denial("POST", "/v1/bundleIds", { data: { type: "bundleIds" }, meta: 1 }),
    ).toBe("included_not_allowed");
    expect(denial("POST", "/v1/bundleIds", "nope")).toBe("invalid_body");
  });

  it("a PATCH body must name the path's object", () => {
    const body = (id: string) => ({
      data: { type: "betaGroups", id, attributes: { name: "QA" } },
    });
    expect(denial("PATCH", "/v1/betaGroups/g1", body("g1"))).toBeNull();
    expect(denial("PATCH", "/v1/betaGroups/g1", body("g2"))).toBe(
      "invalid_body",
    );
  });

  it("relationships: only the rule's names, only the right identifier types", () => {
    const cap = (rel: unknown, capabilityType = "IN_APP_PURCHASE") => ({
      data: {
        type: "bundleIdCapabilities",
        attributes: { capabilityType },
        relationships: rel,
      },
    });
    expect(
      denial(
        "POST",
        "/v1/bundleIdCapabilities",
        cap({ bundleId: { data: { type: "bundleIds", id: "B1" } } }),
      ),
    ).toBeNull();
    expect(
      denial(
        "POST",
        "/v1/bundleIdCapabilities",
        cap({ bundleId: { data: { type: "apps", id: "B1" } } }),
      ),
    ).toBe("wrong_type");
    expect(
      denial(
        "POST",
        "/v1/bundleIdCapabilities",
        cap({ app: { data: { type: "apps", id: "1" } } }),
      ),
    ).toBe("relationship_not_allowed");
    expect(
      denial(
        "POST",
        "/v1/bundleIdCapabilities",
        cap(
          { bundleId: { data: { type: "bundleIds", id: "B1" } } },
          "USER_MANAGEMENT",
        ),
      ),
    ).toBe("value_not_allowed");
    expect(GATE_CAPABILITY_TYPES).not.toContain("APP_ATTEST");
  });

  it("the app record: only the four notification URL attributes, only to an own hook", () => {
    const app = (attributes: Record<string, unknown>) => ({
      data: { type: "apps", id: "1234567890", attributes },
    });
    const ok = "https://key.plrs.im/djdl/distribution/hooks/app-store";
    const own = { hookOrigin: "https://key.plrs.im" };
    expect(
      denial(
        "PATCH",
        "/v1/apps/1234567890",
        app({ subscriptionStatusUrl: ok, subscriptionStatusUrlVersion: "V2" }),
        own,
      ),
    ).toBeNull();
    // Without the handler's own origin, no callback URL is admitted at all.
    expect(
      denial(
        "PATCH",
        "/v1/apps/1234567890",
        app({ subscriptionStatusUrl: ok }),
      ),
    ).toBe("value_not_allowed");
    expect(
      denial(
        "PATCH",
        "/v1/apps/1234567890",
        app({
          subscriptionStatusUrl: null,
          subscriptionStatusUrlVersion: null,
        }),
      ),
    ).toBeNull();
    for (const bad of [
      "http://key.plrs.im/djdl/distribution/hooks/app-store",
      "https://evil.example/djdl/distribution/hooks/app-store?x=1",
      // A clean URL of the right shape on another host (A-17a fix round 1).
      "https://evil.example/djdl/distribution/hooks/app-store",
      "https://key.plrs.im.evil.example/djdl/distribution/hooks/app-store",
      "https://user:pw@key.plrs.im/djdl/distribution/hooks/app-store",
      "https://key.plrs.im:8443/djdl/distribution/hooks/app-store",
      "https://key.plrs.im/djdl/distribution/hooks/asc",
      "https://key.plrs.im/a/b/distribution/hooks/app-store",
    ])
      expect(
        denial(
          "PATCH",
          "/v1/apps/1234567890",
          app({ subscriptionStatusUrl: bad }),
          own,
        ),
      ).toBe("value_not_allowed");
    expect(denial("PATCH", "/v1/apps/1234567890", app({ bundleId: "x" }))).toBe(
      "attribute_not_allowed",
    );
    expect(
      denial("PATCH", "/v1/apps/1234567890", app({ primaryLocale: "en-US" })),
    ).toBe("attribute_not_allowed");
    expect(
      denial(
        "PATCH",
        "/v1/apps/1234567890",
        app({ subscriptionStatusUrlVersion: "V3" }),
      ),
    ).toBe("value_not_allowed");
  });

  it("builds: export compliance only, never expired", () => {
    const build = (attributes: Record<string, unknown>) => ({
      data: { type: "builds", id: "b1", attributes },
    });
    expect(
      denial(
        "PATCH",
        "/v1/builds/b1",
        build({ usesNonExemptEncryption: false }),
      ),
    ).toBeNull();
    expect(denial("PATCH", "/v1/builds/b1", build({ expired: true }))).toBe(
      "attribute_not_allowed",
    );
    expect(
      denial(
        "PATCH",
        "/v1/builds/b1",
        build({ usesNonExemptEncryption: "no" }),
      ),
    ).toBe("value_not_allowed");
  });

  it("IAPs: non-consumable only", () => {
    const iap = (inAppPurchaseType: string) => ({
      data: {
        type: "inAppPurchases",
        attributes: {
          name: "Full game",
          productId: "gg.acme.full",
          inAppPurchaseType,
        },
        relationships: { app: { data: { type: "apps", id: "1" } } },
      },
    });
    expect(
      denial("POST", "/v2/inAppPurchases", iap("NON_CONSUMABLE")),
    ).toBeNull();
    expect(denial("POST", "/v2/inAppPurchases", iap("CONSUMABLE"))).toBe(
      "value_not_allowed",
    );
    expect(
      denial("PATCH", "/v2/inAppPurchases/I1", {
        data: { type: "inAppPurchases", id: "I1" },
      }),
    ).toBe("not_allowed");
  });

  it("the webhook goes to the product's own hook only", () => {
    const hook = (url: string) => ({
      data: {
        type: "webhooks",
        attributes: {
          enabled: true,
          eventTypes: [],
          name: "n",
          secret: "s",
          url,
        },
        relationships: { app: { data: { type: "apps", id: "1" } } },
      },
    });
    const own = { hookOrigin: "https://key.plrs.im" };
    expect(
      denial(
        "POST",
        "/v1/webhooks",
        hook("https://key.plrs.im/djdl/distribution/hooks/asc"),
        own,
      ),
    ).toBeNull();
    for (const [url, ctx] of [
      ["https://attacker.example/collect", own],
      ["https://attacker.example/djdl/distribution/hooks/asc", own],
      ["https://key.plrs.im/djdl/distribution/hooks/asc", undefined],
      ["https://key.plrs.im/djdl/distribution/hooks/asc", { hookOrigin: "" }],
    ] as const)
      expect(denial("POST", "/v1/webhooks", hook(url), ctx), url).toBe(
        "value_not_allowed",
      );
  });

  it("linkage bodies: identifiers of the rule's type, at least one", () => {
    const p = "/v1/betaGroups/g1/relationships/builds";
    expect(
      denial("POST", p, { data: [{ type: "builds", id: "b1" }] }),
    ).toBeNull();
    expect(
      denial("POST", p, { data: [{ type: "betaTesters", id: "t1" }] }),
    ).toBe("wrong_type");
    expect(denial("POST", p, { data: [] })).toBe("invalid_body");
    expect(
      denial("POST", p, { data: [{ type: "builds", id: "b1", extra: 1 }] }),
    ).toBe("wrong_type");
    expect(denial("DELETE", p, { data: [{ type: "builds", id: "b1" }] })).toBe(
      "not_allowed",
    );
  });

  it("included resources: only on inline creates, only the rule's types", () => {
    const schedule = (included: unknown[]) => ({
      data: {
        type: "appPriceSchedules",
        relationships: {
          app: { data: { type: "apps", id: "1" } },
          baseTerritory: { data: { type: "territories", id: "USA" } },
          manualPrices: { data: [{ type: "appPrices", id: "${price1}" }] },
        },
      },
      included,
    });
    expect(
      denial(
        "POST",
        "/v1/appPriceSchedules",
        schedule([{ type: "appPrices", id: "${price1}" }]),
        {
          initial: true,
        },
      ),
    ).toBeNull();
    expect(
      denial(
        "POST",
        "/v1/appPriceSchedules",
        schedule([{ type: "users", id: "u" }]),
        {
          initial: true,
        },
      ),
    ).toBe("included_not_allowed");
    expect(
      denial("POST", "/v1/bundleIds", {
        ...bundleId({ platform: "IOS" }),
        included: [],
      }),
    ).toBe("included_not_allowed");
  });
});

describe("confirmation levels", () => {
  const release = {
    data: {
      type: "appStoreVersionReleaseRequests",
      relationships: {
        appStoreVersion: { data: { type: "appStoreVersions", id: "v1" } },
      },
    },
  };
  const submission = (attributes: Record<string, unknown>) => ({
    data: { type: "reviewSubmissions", id: "rs1", attributes },
  });

  it("release needs the typed confirmation", () => {
    expect(denial("POST", "/v1/appStoreVersionReleaseRequests", release)).toBe(
      "typed_confirmation_required",
    );
    expect(
      denial("POST", "/v1/appStoreVersionReleaseRequests", release, {
        initial: true,
      }),
    ).toBe("typed_confirmation_required");
    expect(
      denial("POST", "/v1/appStoreVersionReleaseRequests", release, {
        typedConfirmation: true,
      }),
    ).toBeNull();
  });

  it("submitting for review is typed; cancelling is not; one flag at a time", () => {
    const p = "/v1/reviewSubmissions/rs1";
    expect(denial("PATCH", p, submission({ submitted: true }))).toBe(
      "typed_confirmation_required",
    );
    expect(
      denial("PATCH", p, submission({ submitted: true }), {
        typedConfirmation: true,
      }),
    ).toBeNull();
    expect(denial("PATCH", p, submission({ canceled: true }))).toBeNull();
    expect(
      denial("PATCH", p, submission({ submitted: true, canceled: true }), {
        typedConfirmation: true,
      }),
    ).toBe("value_not_allowed");
    expect(denial("PATCH", p, submission({ submitted: false }))).toBe(
      "value_not_allowed",
    );
    expect(denial("PATCH", p, submission({ platform: "IOS" }))).toBe(
      "attribute_not_allowed",
    );
  });

  it("price schedules: a first schedule, or a typed price change", () => {
    const iapSchedule = {
      data: {
        type: "inAppPurchasePriceSchedules",
        relationships: {
          inAppPurchase: { data: { type: "inAppPurchases", id: "I1" } },
          baseTerritory: { data: { type: "territories", id: "USA" } },
          manualPrices: {
            data: [{ type: "inAppPurchasePrices", id: "${p1}" }],
          },
        },
      },
      included: [{ type: "inAppPurchasePrices", id: "${p1}" }],
    };
    const p = "/v1/inAppPurchasePriceSchedules";
    expect(denial("POST", p, iapSchedule)).toBe("typed_confirmation_required");
    expect(denial("POST", p, iapSchedule, { initial: true })).toBeNull();
    expect(
      denial("POST", p, iapSchedule, { typedConfirmation: true }),
    ).toBeNull();
  });

  it("completing a phased release is typed; pausing and resuming are not (owner decision (b))", () => {
    const p = "/v1/appStoreVersionPhasedReleases/phr1";
    const phased = (phasedReleaseState: string) => ({
      data: {
        type: "appStoreVersionPhasedReleases",
        id: "phr1",
        attributes: { phasedReleaseState },
      },
    });
    expect(denial("PATCH", p, phased("COMPLETE"))).toBe(
      "typed_confirmation_required",
    );
    expect(denial("PATCH", p, phased("COMPLETE"), { initial: true })).toBe(
      "typed_confirmation_required",
    );
    expect(
      denial("PATCH", p, phased("COMPLETE"), { typedConfirmation: true }),
    ).toBeNull();
    expect(denial("PATCH", p, phased("PAUSED"))).toBeNull();
    expect(denial("PATCH", p, phased("ACTIVE"))).toBeNull();
    expect(
      denial("PATCH", p, phased("INACTIVE"), { typedConfirmation: true }),
    ).toBe("value_not_allowed");
  });

  it("creating a phased release ACTIVE is typed; INACTIVE or unset is not (A-18a)", () => {
    const p = "/v1/appStoreVersionPhasedReleases";
    const create = (attributes: Record<string, unknown>) => ({
      data: {
        type: "appStoreVersionPhasedReleases",
        attributes,
        relationships: {
          appStoreVersion: { data: { type: "appStoreVersions", id: "V1" } },
        },
      },
    });
    expect(denial("POST", p, create({ phasedReleaseState: "ACTIVE" }))).toBe(
      "typed_confirmation_required",
    );
    expect(
      denial("POST", p, create({ phasedReleaseState: "ACTIVE" }), {
        initial: true,
      }),
    ).toBe("typed_confirmation_required");
    expect(
      denial("POST", p, create({ phasedReleaseState: "ACTIVE" }), {
        typedConfirmation: true,
      }),
    ).toBeNull();
    expect(
      denial("POST", p, create({ phasedReleaseState: "INACTIVE" })),
    ).toBeNull();
    expect(denial("POST", p, create({ phasedReleaseState: null }))).toBeNull();
    expect(denial("POST", p, create({}))).toBeNull();
    expect(
      denial("POST", p, create({ phasedReleaseState: "COMPLETE" }), {
        typedConfirmation: true,
      }),
    ).toBe("value_not_allowed");
  });

  it("a release type that auto-releases is typed once the version is in or after review (A-18a)", () => {
    const p = "/v1/appStoreVersions/V1";
    const patch = (attributes: Record<string, unknown>) => ({
      data: { type: "appStoreVersions", id: "V1", attributes },
    });
    const auto = [
      { releaseType: "AFTER_APPROVAL" },
      { releaseType: "SCHEDULED", earliestReleaseDate: "2026-11-01T10:00:00Z" },
      { earliestReleaseDate: "2026-11-01T10:00:00Z" },
      { releaseType: "SOMETHING_NEW" },
    ];
    for (const state of [
      "WAITING_FOR_REVIEW",
      "IN_REVIEW",
      "PENDING_DEVELOPER_RELEASE",
      "READY_FOR_SALE",
      undefined, // no state asserted: treated as in review
    ])
      for (const attributes of auto) {
        const ctx = state === undefined ? {} : { resourceState: state };
        expect(denial("PATCH", p, patch(attributes), ctx)).toBe(
          "typed_confirmation_required",
        );
        expect(
          denial("PATCH", p, patch(attributes), {
            ...ctx,
            typedConfirmation: true,
          }),
        ).toBeNull();
      }
    // Before review it is a setting: plain.
    for (const state of [
      "PREPARE_FOR_SUBMISSION",
      "READY_FOR_REVIEW",
      "DEVELOPER_REJECTED",
      "REJECTED",
      "METADATA_REJECTED",
      "INVALID_BINARY",
    ])
      for (const attributes of auto)
        expect(
          denial("PATCH", p, patch(attributes), { resourceState: state }),
        ).toBeNull();
    // MANUAL, and edits that carry no release type, stay plain in any state.
    for (const attributes of [
      { releaseType: "MANUAL" },
      { releaseType: "MANUAL", earliestReleaseDate: null },
      { copyright: "2026 Acme" },
    ])
      expect(
        denial("PATCH", p, patch(attributes), { resourceState: "IN_REVIEW" }),
      ).toBeNull();
  });

  it("every IAP availability write is typed, an empty territory list included (owner decision (c))", () => {
    const p = "/v1/inAppPurchaseAvailabilities";
    const avail = (territories: string[]) => ({
      data: {
        type: "inAppPurchaseAvailabilities",
        attributes: { availableInNewTerritories: false },
        relationships: {
          inAppPurchase: { data: { type: "inAppPurchases", id: "I1" } },
          availableTerritories: {
            data: territories.map((id) => ({ type: "territories", id })),
          },
        },
      },
    });
    for (const list of [["USA", "GBR"], []]) {
      expect(denial("POST", p, avail(list))).toBe(
        "typed_confirmation_required",
      );
      expect(denial("POST", p, avail(list), { initial: true })).toBe(
        "typed_confirmation_required",
      );
      expect(
        denial("POST", p, avail(list), { typedConfirmation: true }),
      ).toBeNull();
    }
  });

  it("app availability is a first-time set only", () => {
    const avail = {
      data: {
        type: "appAvailabilities",
        attributes: { availableInNewTerritories: true },
        relationships: { app: { data: { type: "apps", id: "1" } } },
      },
    };
    expect(denial("POST", "/v2/appAvailabilities", avail)).toBe("initial_only");
    expect(
      denial("POST", "/v2/appAvailabilities", avail, {
        typedConfirmation: true,
      }),
    ).toBe("initial_only");
    expect(
      denial("POST", "/v2/appAvailabilities", avail, { initial: true }),
    ).toBeNull();
  });
});

describe("the client consults the gate before the token", () => {
  function client() {
    const token = vi.fn(async () => "bearer");
    const fetchImpl = vi.fn(
      async () =>
        new Response(JSON.stringify({ data: { type: "x", id: "1" } }), {
          status: 201,
        }),
    );
    return { c: new AscClient({ token, fetchImpl }), token, fetchImpl };
  }

  it("a refused write mints no token and sends nothing", async () => {
    const { c, token, fetchImpl } = client();
    await expect(
      c.post(ascPath("certificates"), {
        data: {
          type: "certificates",
          attributes: { certificateType: "DEVELOPER_ID_APPLICATION" },
        },
      }),
    ).rejects.toBeInstanceOf(AscWriteDenied);
    await expect(
      c.request("DELETE", ascPath("bundleIds", "B1")),
    ).rejects.toBeInstanceOf(AscWriteDenied);
    await expect(c.get(ascPath("users"))).rejects.toBeInstanceOf(
      AscWriteDenied,
    );
    await expect(
      c.post(ascPath("appStoreVersionReleaseRequests"), {
        data: {
          type: "appStoreVersionReleaseRequests",
          relationships: {
            appStoreVersion: { data: { type: "appStoreVersions", id: "v" } },
          },
        },
      }),
    ).rejects.toThrow("typed_confirmation_required");
    expect(token).not.toHaveBeenCalled();
    expect(fetchImpl).not.toHaveBeenCalled();
    expect(c.calls).toBe(0);
  });

  it("an admitted write is sent once, with the handler's assertion never on the wire", async () => {
    const { c, token, fetchImpl } = client();
    await c.post(
      ascPath("appStoreVersionReleaseRequests"),
      {
        data: {
          type: "appStoreVersionReleaseRequests",
          relationships: {
            appStoreVersion: { data: { type: "appStoreVersions", id: "v" } },
          },
        },
      },
      { typedConfirmation: true },
    );
    await c.post(ascPathV("v2", "inAppPurchases"), {
      data: {
        type: "inAppPurchases",
        attributes: {
          name: "n",
          productId: "p",
          inAppPurchaseType: "NON_CONSUMABLE",
        },
        relationships: { app: { data: { type: "apps", id: "1" } } },
      },
    });
    expect(token).toHaveBeenCalledTimes(1);
    expect(fetchImpl).toHaveBeenCalledTimes(2);
    const calls = fetchImpl.mock.calls as unknown as [string, RequestInit][];
    expect(calls[1]![0]).toBe(
      "https://api.appstoreconnect.apple.com/v2/inAppPurchases",
    );
    expect(String(calls[0]![1].body)).not.toContain("typedConfirmation");
  });

  it("gates the exact bytes it sends: a toJSON cannot swap the body after the check", async () => {
    const { c, token, fetchImpl } = client();
    // An object that looks harmless to a property read but serialises to a certificate request.
    const sneaky = {
      data: {
        type: "bundleIds",
        attributes: { identifier: "gg.a.b", name: "b", platform: "IOS" },
      },
      toJSON: () => ({
        data: {
          type: "certificates",
          attributes: { certificateType: "DEVELOPER_ID_APPLICATION" },
        },
      }),
    };
    await expect(c.post(ascPath("bundleIds"), sneaky)).rejects.toBeInstanceOf(
      AscWriteDenied,
    );
    // A body that does not serialise to JSON at all is refused, not sent bodiless.
    await expect(
      c.post(ascPath("bundleIds"), (() => undefined) as unknown as object),
    ).rejects.toThrow("invalid_body");
    expect(token).not.toHaveBeenCalled();
    expect(fetchImpl).not.toHaveBeenCalled();
    // And what is admitted is sent byte for byte as checked.
    const plain = {
      data: {
        type: "bundleIds",
        attributes: { identifier: "gg.a.b", name: "b", platform: "IOS" },
      },
    };
    await c.post(ascPath("bundleIds"), plain);
    const calls = fetchImpl.mock.calls as unknown as [string, RequestInit][];
    expect(calls[0]![1].body).toBe(JSON.stringify(plain));
  });
});

describe("Apple's error code token (A-17h)", () => {
  const failing = (status: number, body: string) =>
    new AscClient({
      token: async () => "bearer",
      fetchImpl: async () => new Response(body, { status }),
      sleep: async () => undefined,
    });
  const register = (c: AscClient) =>
    c
      .post(ascPath("bundleIds"), {
        data: {
          type: "bundleIds",
          attributes: {
            identifier: "gg.acme.djdl",
            name: "djdl",
            platform: "IOS",
          },
        },
      })
      .catch((e: unknown) => e);

  it("keeps errors[0].code, never the title or detail", async () => {
    const e = (await register(
      failing(
        409,
        JSON.stringify({
          errors: [
            {
              code: "ENTITY_ERROR.ATTRIBUTE.INVALID",
              title: "secret-ish title",
              detail: "An attribute value is not available",
            },
          ],
        }),
      ),
    )) as AscError;
    expect(e).toBeInstanceOf(AscError);
    expect(e.status).toBe(409);
    expect(e.code).toBe("ENTITY_ERROR.ATTRIBUTE.INVALID");
    expect(e.message).toBe("App Store Connect POST /v1/bundleIds: HTTP 409");
  });

  it("drops a code that is not a token, and survives a body that is not JSON", async () => {
    const free = (await register(
      failing(422, JSON.stringify({ errors: [{ code: "not a token <b>" }] })),
    )) as AscError;
    expect(free.code).toBeNull();
    const html = (await register(
      failing(500, "<html>oops</html>"),
    )) as AscError;
    expect(html.status).toBe(500);
    expect(html.code).toBeNull();
  });
});

describe("A-18m: the listing's text and screenshots (owner decision 1)", () => {
  const vloc = (attributes: Record<string, unknown>, id?: string) => ({
    data: {
      type: "appStoreVersionLocalizations",
      ...(id ? { id } : {}),
      attributes,
      ...(id
        ? {}
        : {
            relationships: {
              appStoreVersion: { data: { type: "appStoreVersions", id: "V1" } },
            },
          }),
    },
  });

  it("adds exactly the listed allows, all plain, none a DELETE", () => {
    const listing = [
      "POST /v1/appInfoLocalizations",
      "PATCH /v1/appInfoLocalizations/{id}",
      "POST /v1/appScreenshotSets",
      "POST /v1/appScreenshots",
      "PATCH /v1/appScreenshots/{id}",
    ];
    for (const k of listing) {
      expect(ALLOWED).toContain(k);
      const rule = ASC_WRITE_ALLOW.find((r) => key(r.method, r.path) === k)!;
      expect(rule.confirm).toBe("plain");
    }
    // Removal and reordering stay denied: every screenshot DELETE and the set's membership PATCH.
    for (const k of [
      "DELETE /v1/appScreenshots/{id}",
      "DELETE /v1/appScreenshotSets/{id}",
      "DELETE /v1/appInfoLocalizations/{id}",
      "DELETE /v1/appStoreVersionLocalizations/{id}",
      "PATCH /v1/appScreenshotSets/{id}/relationships/appScreenshots",
    ])
      expect(DENIED).toContain(k);
    expect(
      denial("PATCH", "/v1/appScreenshotSets/S1/relationships/appScreenshots", {
        data: [{ type: "appScreenshots", id: "X1" }],
      }),
    ).toBe("not_allowed");
  });

  it("version localizations take the listing text and http(s) URLs only", () => {
    expect(
      denial(
        "POST",
        "/v1/appStoreVersionLocalizations",
        vloc({
          locale: "en-US",
          description: "A game.",
          keywords: "a,b",
          marketingUrl: "https://acme.example/",
          supportUrl: "https://acme.example/help",
        }),
      ),
    ).toBeNull();
    expect(
      denial(
        "PATCH",
        "/v1/appStoreVersionLocalizations/L1",
        vloc({ description: "x", supportUrl: null }, "L1"),
      ),
    ).toBeNull();
    for (const bad of [
      "javascript:alert(1)",
      "ftp://acme.example/",
      "https://user:pw@acme.example/",
      `https://acme.example/${"a".repeat(2050)}`,
      42,
    ])
      expect(
        denial(
          "PATCH",
          "/v1/appStoreVersionLocalizations/L1",
          vloc({ supportUrl: bad }, "L1"),
        ),
      ).toBe("value_not_allowed");
  });

  it("app info localizations: name, subtitle and privacy URL; never the privacy text or choices", () => {
    const body = (attributes: Record<string, unknown>) => ({
      data: {
        type: "appInfoLocalizations",
        attributes,
        relationships: { appInfo: { data: { type: "appInfos", id: "I1" } } },
      },
    });
    expect(
      denial(
        "POST",
        "/v1/appInfoLocalizations",
        body({
          locale: "de-DE",
          name: "Spiel",
          subtitle: "Ein Spiel",
          privacyPolicyUrl: "https://acme.example/privacy",
        }),
      ),
    ).toBeNull();
    for (const k of ["privacyPolicyText", "privacyChoicesUrl"])
      expect(
        denial("POST", "/v1/appInfoLocalizations", body({ [k]: "x" })),
      ).toBe("attribute_not_allowed");
    expect(
      denial("PATCH", "/v1/appInfoLocalizations/L1", {
        data: {
          type: "appInfoLocalizations",
          id: "L1",
          attributes: { privacyPolicyUrl: "data:text/html,x" },
        },
      }),
    ).toBe("value_not_allowed");
  });

  it("screenshot sets: a version localization's, of the three display types only", () => {
    const set = (
      type: unknown,
      rel: string = "appStoreVersionLocalization",
    ) => ({
      data: {
        type: "appScreenshotSets",
        attributes: { screenshotDisplayType: type },
        relationships: {
          [rel]: {
            data: {
              type:
                rel === "appStoreVersionLocalization"
                  ? "appStoreVersionLocalizations"
                  : "appCustomProductPageLocalizations",
              id: "L1",
            },
          },
        },
      },
    });
    for (const t of ["APP_IPHONE_67", "APP_IPAD_PRO_3GEN_129", "APP_DESKTOP"])
      expect(denial("POST", "/v1/appScreenshotSets", set(t))).toBeNull();
    expect(
      denial("POST", "/v1/appScreenshotSets", set("APP_WATCH_ULTRA")),
    ).toBe("value_not_allowed");
    expect(
      denial(
        "POST",
        "/v1/appScreenshotSets",
        set("APP_IPHONE_67", "appCustomProductPageLocalization"),
      ),
    ).toBe("relationship_not_allowed");
    expect(
      denial("POST", "/v1/appScreenshotSets", {
        data: {
          type: "appScreenshotSets",
          attributes: { screenshotDisplayType: "APP_IPHONE_67" },
        },
      }),
    ).toBe("value_not_allowed");
  });

  it("screenshots: a reserve of an image file within the cap, then only the commit", () => {
    const reserve = (attributes: Record<string, unknown>) => ({
      data: {
        type: "appScreenshots",
        attributes,
        relationships: {
          appScreenshotSet: { data: { type: "appScreenshotSets", id: "S1" } },
        },
      },
    });
    expect(
      denial(
        "POST",
        "/v1/appScreenshots",
        reserve({ fileName: "ab12.png", fileSize: 1000 }),
      ),
    ).toBeNull();
    for (const a of [
      { fileName: "a.ipa", fileSize: 1000 },
      { fileName: "../a.png", fileSize: 1000 },
      { fileName: "a.png", fileSize: 0 },
      { fileName: "a.png", fileSize: 33 * 1024 * 1024 },
      { fileName: "a.png", fileSize: 1.5 },
    ])
      expect(denial("POST", "/v1/appScreenshots", reserve(a))).toBe(
        "value_not_allowed",
      );
    const commit = (attributes: Record<string, unknown>) => ({
      data: { type: "appScreenshots", id: "X1", attributes },
    });
    expect(
      denial(
        "PATCH",
        "/v1/appScreenshots/X1",
        commit({ uploaded: true, sourceFileChecksum: "0".repeat(32) }),
      ),
    ).toBeNull();
    expect(
      denial("PATCH", "/v1/appScreenshots/X1", commit({ uploaded: false })),
    ).toBe("value_not_allowed");
    expect(
      denial(
        "PATCH",
        "/v1/appScreenshots/X1",
        commit({ uploaded: true, sourceFileChecksum: "nope" }),
      ),
    ).toBe("value_not_allowed");
  });

  it("the upload operation: PUT only, https on apple.com only, an image within the cap", () => {
    const png = { contentType: "image/png", size: 1000 };
    const ok = "https://store-032.blobstore.apple.com/itms/a?sig=1";
    expect(() => checkAscUpload("PUT", ok, png)).not.toThrow();
    const reason = (m: string, u: string, d: typeof png) => {
      try {
        checkAscUpload(m, u, d);
        return null;
      } catch (e) {
        expect(e).toBeInstanceOf(AscWriteDenied);
        // The presigned URL never reaches a message.
        expect((e as Error).message).not.toContain("sig=1");
        return (e as AscWriteDenied).reason;
      }
    };
    expect(reason("POST", ok, png)).toBe("not_allowed");
    expect(reason("DELETE", ok, png)).toBe("not_allowed");
    for (const u of [
      "http://store-032.blobstore.apple.com/a?sig=1",
      "https://apple.com.evil.example/a?sig=1",
      "https://evilapple.com/a?sig=1",
      "https://u:p@store.apple.com/a?sig=1",
      "https://store.apple.com:8443/a?sig=1",
      "https://169.254.169.254/a?sig=1",
    ])
      expect(reason("PUT", u, png), u).toBe("invalid_path");
    expect(
      reason("PUT", ok, { contentType: "application/octet-stream", size: 1 }),
    ).toBe("content_type_not_allowed");
    expect(
      reason("PUT", ok, { contentType: "image/png", size: 33 * 1024 * 1024 }),
    ).toBe("too_large");
  });
});
