/**
 * Outlet-credential custody (P5-01): `core/outletCredentials.ts` and the Core admin API beside
 * `secrets`.
 *
 * Every key here is generated by the test. No real store credential exists in this repository,
 * and none may: the value shapes are what App Store Connect, Google and Partner Center issue,
 * filled with throwaway material.
 */

import { generateKeyPairSync } from "node:crypto";
import { beforeEach, describe, expect, it } from "vitest";
import { makeTestDb } from "./helpers.js";
import { KvMock } from "./kvMock.js";
import { makeEnv, NOW, seedProduct, TEST_KEK } from "./seed.js";
import type { Env } from "../src/env.js";
import type { Db } from "../src/db/types.js";
import { handleAdmin } from "../src/admin/index.js";
import {
  ADMIN_COOKIE,
  CSRF_HEADER,
  issueSession,
} from "../src/admin/session.js";
import { listAudit } from "../src/repo.js";
import { open } from "../src/keyvault.js";
import {
  GOOGLE_TOKEN_URI,
  listOutletCredentials,
  openOutletCredential,
  OUTLET_CREDENTIAL_ACTOR,
  putOutletCredential,
  recordOutletCredentialResult,
  validateOutletCredential,
  type OutletCredentialKind,
} from "../src/core/outletCredentials.js";

const pem = (k: { export(o: object): string | Buffer }, type: string) =>
  (k.export({ type, format: "pem" }) as string).trim();

const P8 = pem(
  generateKeyPairSync("ec", { namedCurve: "P-256" }).privateKey,
  "pkcs8",
);
const P384 = pem(
  generateKeyPairSync("ec", { namedCurve: "P-384" }).privateKey,
  "pkcs8",
);
const RSA = pem(
  generateKeyPairSync("rsa", { modulusLength: 2048 }).privateKey,
  "pkcs8",
);

/** The shape of a Google service-account key file, with a throwaway key. */
const GOOGLE_KEY = {
  type: "service_account",
  project_id: "test-project",
  private_key_id: "0123abcd",
  private_key: RSA,
  client_email: "play-publisher@test-project.iam.gserviceaccount.com",
  client_id: "1234567890",
  auth_uri: "https://accounts.google.com/o/oauth2/auth",
  token_uri: GOOGLE_TOKEN_URI,
};

const VALUES: Record<OutletCredentialKind, Record<string, unknown>> = {
  "asc-api-key": {
    keyId: "ABC123DEFG",
    issuerId: "69a6de7f-0000-47e3-e053-5b8c7c11a4d1",
    p8: P8,
  },
  "asc-webhook-secret": { secret: "whsec-test-only-0000" },
  "google-service-account": GOOGLE_KEY,
  "ms-partner-center": {
    tenantId: "contoso.onmicrosoft.com",
    clientId: "00000000-0000-0000-0000-000000000001",
    clientSecret: "test-client-secret~000",
    sellerId: "12345678",
  },
};

/** The secret part of each value: none of it may ever appear in metadata or a response. */
const SECRET_PARTS: Record<OutletCredentialKind, string[]> = {
  "asc-api-key": [P8.split("\n")[1]!],
  "asc-webhook-secret": ["whsec-test-only-0000"],
  "google-service-account": [RSA.split("\n")[1]!],
  "ms-partner-center": ["test-client-secret~000"],
};

const ADMIN_SECRET = "test-admin-session-secret";
const PLATFORM_GROUP = "platform-admins";

function adminEnv(kv = new KvMock()): Env {
  const env = makeEnv(kv, ["djdl"]);
  env.ADMIN_SESSION_SECRET = ADMIN_SECRET;
  env.PLATFORM_ADMIN_GROUP = PLATFORM_GROUP;
  return env;
}

async function call(
  env: Env,
  db: Db,
  method: string,
  path: string,
  body?: unknown,
  groups: string[] = [PLATFORM_GROUP],
): Promise<{ status: number; body: Record<string, unknown>; raw: string }> {
  const { token, session } = await issueSession(
    env,
    { sub: "admin-1", email: "admin@example.com", groups },
    NOW,
  );
  const headers: Record<string, string> = {
    cookie: `${ADMIN_COOKIE}=${token}`,
    [CSRF_HEADER]: session.csrf,
  };
  const init: RequestInit = { method, headers };
  if (body !== undefined) {
    headers["content-type"] = "application/json";
    init.body = JSON.stringify(body);
  }
  const res = await handleAdmin(
    new Request(
      `https://key.plrs.im/manage${path}`,
      init,
    ) as unknown as Request,
    env,
    db,
    path,
    { now: NOW },
  );
  const raw = await res.text();
  return {
    status: res.status,
    raw,
    body: raw ? (JSON.parse(raw) as Record<string, unknown>) : {},
  };
}

const BASE = "/api/products/djdl/outlet-credentials";

describe("outlet credentials: per-kind validation", () => {
  it("accepts each kind's real shape and projects non-secret metadata only", async () => {
    for (const kind of Object.keys(VALUES) as OutletCredentialKind[]) {
      const v = await validateOutletCredential(kind, VALUES[kind]);
      expect(v.ok, kind).toBe(true);
      if (!v.ok) continue;
      const meta = JSON.stringify(v.meta);
      for (const part of SECRET_PARTS[kind]) expect(meta).not.toContain(part);
      expect(meta).not.toMatch(/p8|private_key|clientSecret|secret/);
    }
  });

  it("keeps only client_email, private_key and token_uri of a Google key file", async () => {
    const v = await validateOutletCredential(
      "google-service-account",
      GOOGLE_KEY,
    );
    expect(v.ok && Object.keys(v.value).sort()).toEqual([
      "client_email",
      "private_key",
      "token_uri",
    ]);
  });

  it("rejects a .p8 that is not P-256 PKCS#8", async () => {
    for (const p8 of [
      P384,
      RSA,
      "-----BEGIN PRIVATE KEY-----\nAAAA\n-----END PRIVATE KEY-----",
      "not a pem",
    ]) {
      const v = await validateOutletCredential("asc-api-key", {
        ...VALUES["asc-api-key"],
        p8,
      });
      expect(v).toMatchObject({ ok: false, field: "p8" });
    }
  });

  it("rejects a Google key that is not RSA or names another token endpoint", async () => {
    expect(
      await validateOutletCredential("google-service-account", {
        ...GOOGLE_KEY,
        private_key: P8,
      }),
    ).toMatchObject({ ok: false, field: "private_key" });
    expect(
      await validateOutletCredential("google-service-account", {
        ...GOOGLE_KEY,
        token_uri: "https://attacker.example/token",
      }),
    ).toMatchObject({ ok: false, field: "token_uri" });
  });

  it("rejects missing fields for every kind", async () => {
    expect(
      await validateOutletCredential("ms-partner-center", {
        ...VALUES["ms-partner-center"],
        clientSecret: "",
      }),
    ).toMatchObject({ ok: false, field: "clientSecret" });
    expect(
      await validateOutletCredential("asc-webhook-secret", {}),
    ).toMatchObject({ ok: false, field: "secret" });
    expect(await validateOutletCredential("asc-api-key", [])).toMatchObject({
      ok: false,
      field: "value",
    });
  });
});

describe("outlet credentials: the admin API", () => {
  let db: Db;
  let env: Env;
  beforeEach(async () => {
    db = makeTestDb();
    env = adminEnv();
    await seedProduct(db, "djdl");
  });

  it("PUT is write-only: echoes the id only, and GET lists metadata and health, never values", async () => {
    for (const kind of Object.keys(VALUES) as OutletCredentialKind[]) {
      const put = await call(env, db, "PUT", `${BASE}/${kind}-1`, {
        kind,
        outletId: "app-store",
        value: VALUES[kind],
      });
      expect(put.status, kind).toBe(200);
      expect(put.body).toEqual({ ok: true, id: `${kind}-1` });
    }
    const list = await call(env, db, "GET", BASE);
    expect(list.status).toBe(200);
    for (const part of Object.values(SECRET_PARTS).flat())
      expect(list.raw).not.toContain(part);
    const creds = list.body.credentials as Array<Record<string, unknown>>;
    expect(creds.map((c) => c.id)).toEqual([
      "asc-api-key-1",
      "asc-webhook-secret-1",
      "google-service-account-1",
      "ms-partner-center-1",
    ]);
    expect(creds[0]).toMatchObject({
      kind: "asc-api-key",
      outletId: "app-store",
      meta: { keyId: "ABC123DEFG" },
      status: "active",
      createdAt: NOW,
      createdBy: "admin-1",
      lastUsedAt: null,
      lastOkAt: null,
      lastError: null,
    });
    expect(Object.keys(creds[0]!)).not.toContain("value");
  });

  it("stores the value sealed under the outlet-credential AAD and meta_json without secrets", async () => {
    await call(env, db, "PUT", `${BASE}/asc`, {
      kind: "asc-api-key",
      value: VALUES["asc-api-key"],
    });
    const row = await db.first<{ enc_value_json: string; meta_json: string }>(
      "SELECT enc_value_json, meta_json FROM outlet_credentials WHERE product = 'djdl' AND credential_id = 'asc'",
    );
    expect(row!.enc_value_json).not.toContain(SECRET_PARTS["asc-api-key"][0]);
    expect(JSON.parse(row!.meta_json)).toEqual({
      keyId: "ABC123DEFG",
      issuerId: VALUES["asc-api-key"].issuerId,
    });
    const plain = await open(env, row!.enc_value_json, {
      product: "djdl",
      kind: "outlet-credential",
      id: "asc",
    });
    expect(JSON.parse(plain)).toEqual(VALUES["asc-api-key"]);
  });

  it("refuses a bad value at write with the failing field, and stores nothing", async () => {
    const res = await call(env, db, "PUT", `${BASE}/asc`, {
      kind: "asc-api-key",
      value: { ...VALUES["asc-api-key"], p8: P384 },
    });
    expect(res.status).toBe(422);
    expect(res.body.fields).toEqual(["value.p8"]);
    expect(res.raw).not.toContain(P384.split("\n")[1]);
    expect(await listOutletCredentials(db, "djdl")).toEqual([]);
  });

  it("refuses an unknown kind, a bad id, a bad outlet id and a non-integer expiry", async () => {
    expect(
      (await call(env, db, "PUT", `${BASE}/x`, { kind: "aws", value: {} }))
        .status,
    ).toBe(422);
    expect(
      (
        await call(env, db, "PUT", `${BASE}/Bad:Id`, {
          kind: "asc-webhook-secret",
          value: VALUES["asc-webhook-secret"],
        })
      ).status,
    ).toBe(404);
    expect(
      (
        await call(env, db, "PUT", `${BASE}/x`, {
          kind: "asc-webhook-secret",
          outletId: "Not An Id",
          value: VALUES["asc-webhook-secret"],
        })
      ).status,
    ).toBe(422);
    expect(
      (
        await call(env, db, "PUT", `${BASE}/x`, {
          kind: "asc-webhook-secret",
          expiresAt: "soon",
          value: VALUES["asc-webhook-secret"],
        })
      ).status,
    ).toBe(422);
  });

  it("accepts a Google key pasted as its JSON file", async () => {
    const res = await call(env, db, "PUT", `${BASE}/play`, {
      kind: "google-service-account",
      value: JSON.stringify(GOOGLE_KEY),
    });
    expect(res.status).toBe(200);
  });

  it("re-PUT of the same kind rotates in place and clears health; another kind is refused", async () => {
    await call(env, db, "PUT", `${BASE}/asc`, {
      kind: "asc-api-key",
      value: VALUES["asc-api-key"],
    });
    await recordOutletCredentialResult(
      db,
      "djdl",
      "asc",
      { ok: false, error: "401 from ASC" },
      NOW,
    );
    const rotated = await call(env, db, "PUT", `${BASE}/asc`, {
      kind: "asc-api-key",
      value: VALUES["asc-api-key"],
    });
    expect(rotated.status).toBe(200);
    const [info] = await listOutletCredentials(db, "djdl");
    expect(info).toMatchObject({
      rotatedAt: NOW,
      lastError: null,
      createdBy: "admin-1",
    });
    const other = await call(env, db, "PUT", `${BASE}/asc`, {
      kind: "asc-webhook-secret",
      value: VALUES["asc-webhook-secret"],
    });
    expect(other.status).toBe(409);
  });

  it("DELETE removes the row, 404s an unknown id, and both writes are audited with the session actor", async () => {
    await call(env, db, "PUT", `${BASE}/asc`, {
      kind: "asc-api-key",
      value: VALUES["asc-api-key"],
    });
    const del = await call(env, db, "DELETE", `${BASE}/asc`);
    expect(del.body).toEqual({ ok: true, id: "asc" });
    expect(await listOutletCredentials(db, "djdl")).toEqual([]);
    expect((await call(env, db, "DELETE", `${BASE}/asc`)).status).toBe(404);

    const audits = await listAudit(db, "djdl", {});
    const mine = audits.filter((a) =>
      a.action.startsWith("outlet_credential."),
    );
    expect(
      mine.map((a) => [a.action, a.actor_sub, a.target_id]).sort(),
    ).toEqual([
      ["outlet_credential.delete", "admin-1", "asc"],
      ["outlet_credential.set", "admin-1", "asc"],
    ]);
    for (const a of mine)
      expect(a.summary ?? "").not.toContain(SECRET_PARTS["asc-api-key"][0]);
  });

  it("is refused to a session that is not a platform admin", async () => {
    const res = await call(
      env,
      db,
      "PUT",
      `${BASE}/asc`,
      { kind: "asc-api-key", value: VALUES["asc-api-key"] },
      ["someone-else"],
    );
    expect(res.status).toBe(403);
    expect(await listOutletCredentials(db, "djdl")).toEqual([]);
  });

  it("refuses methods it does not serve", async () => {
    expect((await call(env, db, "POST", BASE)).status).toBe(405);
    expect((await call(env, db, "GET", `${BASE}/asc`)).status).toBe(405);
  });

  it("deleting a product deletes its outlet credentials", async () => {
    await seedProduct(db, "acme");
    await call(env, db, "PUT", `${BASE}/asc`, {
      kind: "asc-api-key",
      value: VALUES["asc-api-key"],
    });
    await call(env, db, "PUT", "/api/products/acme/outlet-credentials/asc", {
      kind: "asc-api-key",
      value: VALUES["asc-api-key"],
    });
    const res = await call(env, db, "DELETE", "/api/products/djdl", {
      confirmSlug: "djdl",
    });
    expect(res.status).toBe(200);
    expect(await listOutletCredentials(db, "djdl")).toEqual([]);
    expect(await listOutletCredentials(db, "acme")).toHaveLength(1);
  });
});

describe("outlet credentials: openOutletCredential", () => {
  let db: Db;
  let env: Env;
  beforeEach(async () => {
    db = makeTestDb();
    env = makeEnv(new KvMock(), ["djdl"]);
    await seedProduct(db, "djdl");
    for (const kind of Object.keys(VALUES) as OutletCredentialKind[]) {
      const r = await putOutletCredential(env, db, {
        product: "djdl",
        credentialId: kind,
        kind,
        outletId: null,
        value: VALUES[kind],
        expiresAt: null,
        actor: "admin-1",
        now: NOW,
      });
      expect(r.ok).toBe(true);
    }
  });

  const useRows = async () =>
    (await listAudit(db, "djdl", {})).filter(
      (a) => a.action === "outlet_credential.use",
    );

  it("returns the parsed, kind-typed value and audits the open as system:distribution", async () => {
    const cred = await openOutletCredential(
      env,
      db,
      "djdl",
      "asc-api-key",
      "asc:poll",
      {
        kind: "asc-api-key",
        now: NOW + 5,
      },
    );
    expect(cred).toEqual({
      product: "djdl",
      credentialId: "asc-api-key",
      kind: "asc-api-key",
      outletId: null,
      value: VALUES["asc-api-key"],
    });
    const rows = await useRows();
    expect(rows).toHaveLength(1);
    expect(rows[0]).toMatchObject({
      actor_sub: OUTLET_CREDENTIAL_ACTOR,
      target_kind: "outlet_credential",
      target_id: "asc-api-key",
      at: NOW + 5,
    });
    expect(rows[0]!.summary).toBe("asc:poll: opened");
    const [info] = await listOutletCredentials(db, "djdl");
    expect(info!.lastUsedAt).toBe(NOW + 5);
  });

  it("audits EVERY open, including the unusable ones, and answers null for each", async () => {
    // Unknown id.
    expect(
      await openOutletCredential(env, db, "djdl", "nope", "asc:poll", {
        now: NOW,
      }),
    ).toBeNull();
    // Wrong kind.
    expect(
      await openOutletCredential(env, db, "djdl", "asc-api-key", "play:token", {
        kind: "google-service-account",
        now: NOW,
      }),
    ).toBeNull();
    // Invalid use string.
    expect(
      await openOutletCredential(env, db, "djdl", "asc-api-key", "Bad Use", {
        now: NOW,
      }),
    ).toBeNull();
    // A disabled row.
    await db.run(
      "UPDATE outlet_credentials SET status = 'disabled' WHERE credential_id = 'ms-partner-center'",
    );
    expect(
      await openOutletCredential(
        env,
        db,
        "djdl",
        "ms-partner-center",
        "ms:submit",
        { now: NOW },
      ),
    ).toBeNull();
    // A tampered blob.
    await db.run(
      "UPDATE outlet_credentials SET enc_value_json = (SELECT enc_value_json FROM outlet_credentials WHERE credential_id = 'asc-api-key') WHERE credential_id = 'asc-webhook-secret'",
    );
    expect(
      await openOutletCredential(
        env,
        db,
        "djdl",
        "asc-webhook-secret",
        "asc:webhook",
        { now: NOW },
      ),
    ).toBeNull();
    // A ring without the KEK the row was sealed under.
    const otherRing = { ...env, PLATFORM_KEK: btoa("\x01".repeat(32)) } as Env;
    expect(TEST_KEK).not.toBe(otherRing.PLATFORM_KEK);
    expect(
      await openOutletCredential(
        otherRing,
        db,
        "djdl",
        "google-service-account",
        "play:token",
        { now: NOW },
      ),
    ).toBeNull();

    const rows = await useRows();
    expect(rows).toHaveLength(6);
    expect(rows.every((r) => r.summary!.endsWith("unusable credential"))).toBe(
      true,
    );
    expect(rows.every((r) => r.actor_sub === OUTLET_CREDENTIAL_ACTOR)).toBe(
      true,
    );
  });

  it("is product-scoped: another product's id never opens", async () => {
    await seedProduct(db, "acme");
    expect(
      await openOutletCredential(env, db, "acme", "asc-api-key", "asc:poll", {
        now: NOW,
      }),
    ).toBeNull();
  });

  it("records connector health: ok stamps last_ok_at, an error stores a truncated status line", async () => {
    await recordOutletCredentialResult(
      db,
      "djdl",
      "asc-api-key",
      { ok: false, error: "x".repeat(500) },
      NOW,
    );
    let info = (await listOutletCredentials(db, "djdl")).find(
      (c) => c.id === "asc-api-key",
    )!;
    expect(info.lastError).toHaveLength(200);
    await recordOutletCredentialResult(
      db,
      "djdl",
      "asc-api-key",
      { ok: true },
      NOW + 1,
    );
    info = (await listOutletCredentials(db, "djdl")).find(
      (c) => c.id === "asc-api-key",
    )!;
    expect(info).toMatchObject({ lastOkAt: NOW + 1, lastError: null });
  });
});

describe("outlet credentials: KEK rotation", () => {
  const KEK_NEW = btoa(String.fromCharCode(1).repeat(32));

  it("GET /kek counts the table and the re-seal sweep re-seals its rows, which still open", async () => {
    const db = makeTestDb();
    const kv = new KvMock();
    await seedProduct(db, "djdl");
    await putOutletCredential(makeEnv(kv, []), db, {
      product: "djdl",
      credentialId: "asc",
      kind: "asc-api-key",
      outletId: null,
      value: VALUES["asc-api-key"],
      expiresAt: null,
      actor: "admin-1",
      now: NOW,
    });

    // Promote a new KEK; the stored row is still under the legacy `default` kid.
    const base = adminEnv(kv) as unknown as Record<string, unknown>;
    delete base.PLATFORM_KEK;
    const env = Object.assign(base, {
      PLATFORM_KEK_KEYS: JSON.stringify({ default: TEST_KEK, k2: KEK_NEW }),
      PLATFORM_KEK_ACTIVE: "k2",
    }) as Env;

    const before = await call(env, db, "GET", "/api/products/kek");
    expect(before.status).toBe(200);
    expect(before.body).toMatchObject({
      counts: { outletCredentials: { default: 1 } },
    });

    const sweep = await call(env, db, "POST", "/api/products/kek", {
      limit: 200,
    });
    expect(sweep.body).toMatchObject({
      failed: 0,
      remaining: 0,
      counts: { outletCredentials: { k2: 1 } },
    });

    // The old KEK can now be retired, and the credential still opens under the same AAD.
    const retired = Object.assign({}, env, {
      PLATFORM_KEK_KEYS: JSON.stringify({ k2: KEK_NEW }),
    }) as Env;
    const cred = await openOutletCredential(
      retired,
      db,
      "djdl",
      "asc",
      "asc:poll",
      { kind: "asc-api-key", now: NOW },
    );
    expect(cred?.value).toEqual(VALUES["asc-api-key"]);
  });
});
