# GENERATED FILE — do not edit by hand.
#
# Written by `pnpm gen:constants` (tools/gen-sdk-constants.ts) from conformance/parity/
# copy.en.json, checked against errors.json and enums.json (licenseStatus, activationResult).
# `pnpm gen:constants -- --check` fails the green gate on any difference. To change a string,
# edit copy.en.json and regenerate.
class_name PKeyCoreCopy
extends RefCounted
## The core copy (core.copy): a title and message per error code, gate status (licenseStatus) and activation result (activationResult). A code missing from COPY_CODES shows COPY_FALLBACK with {code} filled in, never the raw body.
## Each entry is {"title": String, "message": String}.

const COPY_VERSION := 1
const COPY_LOCALE := "en"
## The only placeholders a copy string may hold, each written `{name}`.
const COPY_PLACEHOLDERS := ["code", "detail", "limit", "deviceCount", "retryAfterSeconds", "product"]
## Shown for a code this table does not know, with {code} filled in.
const COPY_FALLBACK := {"title": "Something went wrong", "message": "Something went wrong ({code}). Try again."}

## Per error code (errors.json order).
const COPY_CODES := {
	"unauthorized": {"title": "Not signed in", "message": "This device isn't signed in, or its license is no longer valid. Sign in or activate again."},
	"not_found": {"title": "Not found", "message": "That wasn't found. It may have been removed."},
	"bad_request": {"title": "Request refused", "message": "The request wasn't valid. Update the app, then try again."},
	"forbidden": {"title": "Not allowed", "message": "You don't have permission to do that."},
	"attestation_required": {"title": "Device check needed", "message": "This needs a verified device. Let the app check this device, then try again."},
	"attestation_rejected": {"title": "Device check failed", "message": "This device couldn't be verified. Try again."},
	"attestation_unavailable": {"title": "Device check unavailable", "message": "Device verification isn't available for this app right now. Try again in a few minutes."},
	"rate_limited": {"title": "Too many attempts", "message": "Too many attempts. Wait a moment and try again."},
	"body_too_large": {"title": "Too large", "message": "That is too large to send."},
	"method_not_allowed": {"title": "Request refused", "message": "The request wasn't valid. Update the app, then try again."},
	"misconfigured": {"title": "Service not set up", "message": "This service isn't set up correctly. Contact the developer."},
	"registration_closed": {"title": "Registration closed", "message": "New devices can't register right now. Activate with a license key or sign in."},
	"value_not_representable": {"title": "Value not accepted", "message": "A value couldn't be saved. Change it and try again."},
	"document_not_representable": {"title": "Service problem", "message": "The service couldn't prepare your settings. Contact the developer."},
	"device_limit": {"title": "Device limit reached", "message": "This license is already on all its devices. Replace a device to use it here."},
	"key_entry_limit": {"title": "No key entries left", "message": "This key has no entries left. Add it to your account and sign in instead."},
	"license_disabled": {"title": "License disabled", "message": "This license has been disabled. Contact the developer."},
	"license_expired": {"title": "License expired", "message": "This license has expired. Renew it to continue."},
	"not_entitled": {"title": "Not included", "message": "Your license doesn't include this."},
	"version_blocked": {"title": "Update required", "message": "This version can't be used with your license. Update the app to continue."},
	"channel_not_allowed": {"title": "Channel not included", "message": "Your license doesn't include this release channel."},
	"hardware_mismatch": {"title": "Device changed", "message": "This device's hardware changed. Activate again to use your license here."},
	"fingerprint_required": {"title": "Device check failed", "message": "This license needs a hardware fingerprint, which couldn't be read on this device."},
	"enroll_disabled": {"title": "No free license", "message": "This app doesn't offer a free license. Enter a license key or sign in."},
	"enroll_claimed": {"title": "Sign in to continue", "message": "This device's free license belongs to an account now. Sign in to use it."},
	"enroll_failed": {"title": "Couldn't get a free license", "message": "A free license couldn't be issued. Try again in a few minutes."},
	"managed_by_admin": {"title": "Set by your organization", "message": "This setting is managed by your organization and can't be changed here."},
	"catalog_unavailable": {"title": "Settings unavailable", "message": "Settings can't be loaded right now. Try again in a few minutes."},
	"license_unusable": {"title": "License no longer valid", "message": "Your license is no longer valid, so settings can't be loaded. Sign in or activate again."},
	"disabled": {"title": "Sign-in unavailable", "message": "Sign-in isn't turned on for this app."},
	"oidc_error": {"title": "Sign-in failed", "message": "Sign-in didn't finish. Try again."},
	"unavailable": {"title": "Sign-in unavailable", "message": "Sign-in isn't available right now. Try again in a few minutes."},
	"identity_disabled": {"title": "Sign-in unavailable", "message": "Sign-in through this app is turned off. Your installs and licenses keep working."},
	"auth_method_disabled": {"title": "Sign-in method unavailable", "message": "That sign-in method is turned off. Choose another one."},
	"email_unavailable": {"title": "Email sign-in unavailable", "message": "Email sign-in isn't available right now. Choose another sign-in method."},
	"turnstile_failed": {"title": "Check didn't pass", "message": "The security check didn't pass. Reload the page and try again."},
	"signin_expired": {"title": "Sign-in expired", "message": "This sign-in has expired. Start again."},
	"invalid_code": {"title": "Wrong code", "message": "That code isn't right. Check the email and try again."},
	"email_in_use": {"title": "Email already in use", "message": "Another Polaris Key account already uses this email. Join this sign-in to that account, or use a different email."},
	"terms_required": {"title": "Terms not accepted", "message": "Agree to the terms to continue."},
	"license_owned": {"title": "License in another account", "message": "This {product} license is already in another Polaris Key account. A license never moves by its key."},
	"email_mismatch": {"title": "Email not verified", "message": "This license belongs to an email address your account hasn't verified. Add and verify that email, then try again."},
	"link_conflict": {"title": "Already linked", "message": "That sign-in method belongs to another Polaris Key account. Sign in to that account, or join the two accounts."},
	"last_link": {"title": "Can't remove", "message": "This is your account's only sign-in method. Add another one before removing it."},
	"step_up_required": {"title": "Confirm it's you", "message": "For your security, sign in again to continue."},
	"not_eligible": {"title": "Offer unavailable", "message": "This offer isn't available to your account anymore. Refresh and try again."},
	"not_removable": {"title": "Can't remove", "message": "This license can't be added back with a key, so it stays in your library."},
	"download_auth_required": {"title": "Sign in to download", "message": "Sign in or activate a license to download this."},
	"delivery_gate_missing": {"title": "Download unavailable", "message": "This download isn't set up yet. Contact the developer."},
	"upstream_rate_limited": {"title": "Download busy", "message": "Downloads are busy right now. Try again in a few minutes."},
	"server_misconfigured": {"title": "Service not set up", "message": "This service isn't set up correctly. Contact the developer."},
	"internal_error": {"title": "Download failed", "message": "The download server had a problem. Try again in a few minutes."},
	"release_record_rejected": {"title": "Release refused", "message": "The release wasn't published because a check failed. The publish log names the check."},
	"release_tag_is_pack_release": {"title": "Release skipped", "message": "A release was skipped because its tag matches a content pack release. Rename the tag."},
	"asset_unreachable": {"title": "Image not updated", "message": "An image could not be fetched from its source. The previous copy is still shown, and it will be retried automatically."},
	"feed_not_composable": {"title": "Update check unavailable", "message": "Updates can't be checked right now. Try again in a few minutes."},
	"service-unavailable": {"title": "Not available", "message": "This app doesn't use this service."},
	"service-disabled": {"title": "Not available", "message": "This service is turned off for this app."},
	"local-only": {"title": "Offline mode", "message": "This app is running offline, so it didn't connect."},
	"insecure-base-url": {"title": "Insecure connection", "message": "The app refused an insecure connection. Contact the developer."},
	"bundle-jws-rejected": {"title": "Activation file not valid", "message": "The activation file's signature isn't valid."},
	"bundle-claims-rejected": {"title": "Activation file not valid", "message": "The activation file is for another product or device, or it has expired."},
	"bundle-trust-rejected": {"title": "Activation file not trusted", "message": "The activation file is signed by a key this app doesn't trust."},
	"inner-doc-rejected": {"title": "Activation file not valid", "message": "The license inside the activation file isn't valid."},
	"bundle": {"title": "Activation file not valid", "message": "The activation file couldn't be read."},
	"transport": {"title": "Connection problem", "message": "Check your connection and try again."},
	"network": {"title": "Can't connect", "message": "Can't reach Polaris Key. Check your connection and try again."},
	"refresh-failed": {"title": "Couldn't refresh", "message": "Your license and settings couldn't be refreshed. Check your connection and try again."},
	"sync-failed": {"title": "Couldn't check your license", "message": "Your license couldn't be checked, so the app can't start. Check your connection and try again."},
	"fetch-failed": {"title": "Content missing", "message": "Required content couldn't be downloaded, so the app can't start. Check your connection and try again."},
	"bridge-missing": {"title": "App problem", "message": "The app's licensing bridge is missing. Reinstall the app or contact the developer."},
	"unknown": {"title": "Something went wrong", "message": "Something went wrong. Try again."},
	"release-refused": {"title": "Not included", "message": "Your license doesn't include this release."},
	"bundle-rejected": {"title": "Activation file not valid", "message": "The activation file was refused."},
	"bundle-import-unsupported": {"title": "Not available here", "message": "Offline activation isn't available here."},
	"report-unsupported": {"title": "Not available here", "message": "Device reports aren't available here."},
	"device-management-unsupported": {"title": "Not available here", "message": "Devices can't be managed from here. Manage them in your account."},
	"device_list_failed": {"title": "Couldn't load devices", "message": "Your devices couldn't be loaded. Check your connection and try again."},
	"device_rename_failed": {"title": "Couldn't rename", "message": "The device couldn't be renamed. Try again."},
	"device_deauthorize_failed": {"title": "Couldn't remove device", "message": "The device couldn't be removed. Try again."},
	"key-entry-unsupported": {"title": "Not available here", "message": "License keys can't be entered here. Sign in instead."},
	"sign-in-failed": {"title": "Sign-in failed", "message": "Sign-in didn't finish. Try again."},
	"sign-out-failed": {"title": "Sign-out failed", "message": "Sign-out didn't finish. Try again."},
	"bad_response": {"title": "Unexpected answer", "message": "The service sent an answer the app couldn't use. Try again."},
	"network-error": {"title": "Can't connect", "message": "Can't reach Polaris Key. Check your connection and try again."},
	"server-error": {"title": "Service problem", "message": "The service had a problem. Try again in a few minutes."},
	"cancelled": {"title": "Sign-in cancelled", "message": "Sign-in was cancelled."},
	"sign-in-expired": {"title": "Code expired", "message": "The code expired before sign-in finished. Start again."},
	"sign-in-denied": {"title": "Sign-in declined", "message": "Sign-in was declined. Start again."},
	"sign-in-unavailable": {"title": "Sign-in unavailable", "message": "Sign-in isn't available right now. Try again in a few minutes."},
	"invalid-options": {"title": "App not set up", "message": "The app's licensing isn't set up correctly. Contact the developer."},
	"not-configured": {"title": "App not set up", "message": "The app's licensing isn't set up yet. Contact the developer."},
	"unsupported": {"title": "Not available here", "message": "This isn't available here."},
	"timeout": {"title": "Timed out", "message": "The service took too long to answer. Check your connection and try again."},
	"response-too-large": {"title": "Unexpected answer", "message": "The service sent an answer the app couldn't use. Try again."},
	"too-many-redirects": {"title": "Connection problem", "message": "The connection was redirected too many times. Try again."},
	"insecure-redirect": {"title": "Insecure connection", "message": "The app refused an insecure redirect."},
	"http-error": {"title": "Service problem", "message": "The service answered with an error. Try again."},
	"invalid-response": {"title": "Unexpected answer", "message": "The service sent an answer the app couldn't use. Try again."},
	"store-failed": {"title": "Storage problem", "message": "The app couldn't read or save its license on this device. Check that the app can write its data folder."},
	"platform-error": {"title": "Platform problem", "message": "The platform reported an error. Try again."},
	"no-token": {"title": "Not activated", "message": "This device isn't activated yet. Activate it or sign in."},
	"mint-unavailable": {"title": "Not available", "message": "This isn't available for this app."},
	"feed-rejected": {"title": "Update check failed", "message": "The update information couldn't be verified, so nothing was installed."},
	"feed-rollback": {"title": "Update check failed", "message": "The update information was older than what this device already has, so it was refused."},
	"record-rejected": {"title": "Update not verified", "message": "The update couldn't be verified, so it wasn't installed."},
	"record-mismatch": {"title": "Update not verified", "message": "The update didn't match what was published, so it wasn't installed."},
	"payload-mismatch": {"title": "Download corrupted", "message": "The update didn't download correctly, so it wasn't installed. Try again."},
	"swap-refused": {"title": "Can't update here", "message": "This installation can't update itself. Update it the way you installed it."},
	"swap-failed": {"title": "Update not finished", "message": "The update couldn't be applied. It will be tried again next launch."},
	"files-index-invalid": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"files-unsafe-path": {"title": "Content refused", "message": "Some content was refused because it contains an unsafe file path."},
	"files-duplicate-path": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"files-case-collision": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"files-path-conflict": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"files-layout-mismatch": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"content-stamp-invalid": {"title": "App build problem", "message": "This build's content information isn't valid. Reinstall the app or contact the developer."},
	"full-corrupt": {"title": "Download corrupted", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"delta-artifact-mismatch": {"title": "Download corrupted", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"delta-base-mismatch": {"title": "Content changed", "message": "Installed content changed on this device, so a full download is needed."},
	"delta-apply-failed": {"title": "Update not applied", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"file-corrupt": {"title": "Download corrupted", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"file-source-missing": {"title": "Content missing", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"payload-hash-mismatch": {"title": "Download corrupted", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunks-ref-mismatch": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunks-bad-length": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunks-bad-magic": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunks-unsupported-version": {"title": "Content not supported", "message": "This content needs a newer version of the app. Update the app."},
	"chunks-bad-record-size": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunks-bad-flags": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunks-reserved-nonzero": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunks-zero-length": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunks-bad-clen": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunks-bad-bundle-ref": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunks-bad-bundle-range": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunks-size-mismatch": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunks-payload-mismatch": {"title": "Content not valid", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"chunk-bundle-truncated": {"title": "Download interrupted", "message": "A download was cut short. Check your connection and try again."},
	"chunk-corrupt": {"title": "Download corrupted", "message": "Some content couldn't be installed. It will be downloaded again next time."},
	"plan-transport-unsupported": {"title": "Can't download here", "message": "This content can't be downloaded on this platform."},
	"plan-insufficient-disk": {"title": "Not enough space", "message": "There isn't enough free space for this content. Free up some space and try again."},
	"plan-no-strategy": {"title": "Can't install content", "message": "This content can't be installed on this device."},
	"pack-no-variant": {"title": "Content not available", "message": "This content isn't available for this device."},
	"pack-type-unsupported": {"title": "Content not supported", "message": "This content needs a newer version of the app. Update the app."},
	"pack-type-check-failed": {"title": "Content not valid", "message": "Some content failed its check and wasn't installed."},
	"pack-not-pinned": {"title": "Content not available", "message": "This content isn't part of this version of the app."},
	"pack-not-entitled": {"title": "Not included", "message": "Your license doesn't include this content."},
	"pack-state-unreadable": {"title": "Storage problem", "message": "Installed content couldn't be read, so nothing new was installed. Restart the app."},
	"pck-directory-refused": {"title": "Content refused", "message": "Some content was refused because it contains files a content pack may not hold."},
	"pck-engine-mismatch": {"title": "Content not supported", "message": "This content needs a different version of the game. Update the game."},
	"pack-rolled-back": {"title": "Content restored", "message": "The last content update didn't start, so the previous version was restored."},
	"pack-revoked": {"title": "Content withdrawn", "message": "This content was withdrawn by its developer and can't be used."},
	"pack-not-data-only": {"title": "Content refused", "message": "Some content was refused because it contains files a data pack may not hold."},
	"marker-rejected": {"title": "App build problem", "message": "This build's built-in content isn't valid. Reinstall the app or contact the developer."},
}

## Per licenseStatus.
const COPY_GATE := {
	"ok": {"title": "License active", "message": "Your license is active."},
	"grace": {"title": "Offline grace", "message": "The licensing service can't be reached. You can keep using the app until the grace period ends."},
	"expired": {"title": "License expired", "message": "Your license has expired. Connect to the internet or renew it to continue."},
	"revoked": {"title": "Signed out", "message": "This device was signed out. Sign in or activate again to continue."},
	"needs-activation": {"title": "Activate", "message": "Enter a license key or sign in to continue."},
	"version-too-old": {"title": "Update required", "message": "This version is no longer supported. Update the app to continue."},
	"version-too-new": {"title": "Not available on this license", "message": "This build is newer than your license allows."},
	"channel-not-entitled": {"title": "Channel not included", "message": "Your license doesn't include this release channel."},
	"not-applicable": {"title": "No license needed", "message": "This app doesn't need a license."},
}

## Per activationResult.
const COPY_ACTIVATION := {
	"ok": {"title": "Activated", "message": "Your license is active on this device."},
	"device-limit": {"title": "Device limit reached", "message": "This license is already on all its devices. Replace a device to use it here."},
	"fingerprint-required": {"title": "Device check failed", "message": "This license needs a hardware fingerprint, which couldn't be read on this device."},
	"hardware-mismatch": {"title": "Device changed", "message": "This device's hardware changed. Activate again to use your license here."},
	"enroll-claimed": {"title": "Sign in to continue", "message": "This device's free license belongs to an account now. Sign in to use it."},
	"license-disabled": {"title": "License disabled", "message": "This license has been disabled. Contact the developer."},
	"license-expired": {"title": "License expired", "message": "This license has expired. Renew it to continue."},
	"attestation-required": {"title": "Device check needed", "message": "This license needs a verified device. Let the app check this device, then try again."},
	"rate-limited": {"title": "Too many attempts", "message": "Too many attempts. Wait a moment and try again."},
	"unauthorized": {"title": "Key not accepted", "message": "That license key wasn't accepted. Check it and try again."},
	"enroll-disabled": {"title": "No free license", "message": "This app doesn't offer a free license. Enter a license key or sign in."},
	"key-entry-limit": {"title": "No key entries left", "message": "This key has no entries left. Add it to your account and sign in instead."},
	"refused": {"title": "Activation refused", "message": "Activation was refused ({code})."},
	"error": {"title": "Activation failed", "message": "Activation didn't finish. Check your connection and try again."},
}
