// GENERATED by `pkey sdk --lang react --write` from
// https://key.plrs.im/acme/.well-known/polaris.json. Do not edit: run the command again to refresh.
// The trust pins came from discovery; compare each fingerprint with the console before
// you ship (pkey sdk prints them). Release keys match release.releaseKeyFingerprints.
import type { PolarisKeyProviderProps } from "@polaris-key/react";

/** The trust pins. Bearer mode (a page on its own origin, or Tauri) verifies every document in
 *  the page against them; a desktop host's `@polaris-key/node` client pins the same keys. */
export const pinnedKeys = {
  "pkey-test-prod-2026": "kDJF6Deuexo91hFZ9TAPr2SmjUEuTXdia67UogTEpkI",
};

/** The pinned release keys, for a desktop host (`update.pinnedReleaseKeys`). */
export const pinnedReleaseKeys = {
  "acme-release-2026": "Z6FCkd1K7Om4lxUk4og_J0m73saH4BrrLk8igXzwcJM",
};

/**
 * The provider's product facts and trust pins:
 *
 *   <PolarisKeyProvider {...polarisConfig} version={APP_VERSION}>…</PolarisKeyProvider>
 */
export const polarisConfig = {
  productSlug: "acme",
  baseUrl: "https://key.plrs.im",
  trust: { pinnedKeys },
  expectServices: ["license", "config", "release", "update"],
} satisfies Partial<PolarisKeyProviderProps>;

export default polarisConfig;
